// src/components/ui/yayaw-table/components/forms/bulk-editor-fields.tsx
"use client";

import { Plus, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/src/components/ui/button";
import {
  Command,
  CommandEmpty,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/src/components/ui/command";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/src/components/ui/popover";
import { useTranslations } from "../../providers/table-provider";
import {
  type BulkEditorMessages,
  bulkConditionMessages,
} from "../../utils/bulk-editor";
import { FormBuilder } from "./form-builder";
import { formValuesEqual } from "./form-runtime";
import type { FormBuilderFormInstance } from "./hooks/use-form-builder";
import type {
  AnyFieldDefinition,
  FieldValues,
  FormConfigContext,
} from "./types";

const listFields = (names: string[]) => names.join(", ");

export function BulkEditorFields({
  fields,
  available,
  blocked = [],
  clearValues,
  context,
  form,
  messages,
  mixedOf,
  disabled,
  onAdd,
  onRemove,
}: {
  fields: AnyFieldDefinition[];
  available: AnyFieldDefinition[];
  /** Fields held back by a rule that reads values differing across the selection. */
  blocked?: { field: AnyFieldDefinition; mixed: string[] }[];
  /** Labels of the mixed values a field's rules read. */
  mixedOf?: (field: AnyFieldDefinition) => string[];
  clearValues: FieldValues;
  context: FormConfigContext;
  form: FormBuilderFormInstance<FieldValues>;
  messages: BulkEditorMessages;
  disabled: boolean;
  onAdd: (name: string) => void;
  onRemove: (name: string) => void;
}) {
  const { locale } = useTranslations();
  const conditionWords = bulkConditionMessages(locale);
  const [pickerOpen, setPickerOpen] = useState(false);
  const trigger = useRef<HTMLButtonElement>(null);
  const restoreFocus = useRef(false);
  useEffect(() => {
    // The picker may still be disabled until the removed field becomes available again.
    if (restoreFocus.current && available.length > 0 && !disabled) {
      restoreFocus.current = false;
      trigger.current?.focus();
    }
  }, [available.length, disabled]);
  return (
    <fieldset className="space-y-5" disabled={disabled}>
      {!fields.length && (
        <p className="py-3 text-muted-foreground text-sm">{messages.empty}</p>
      )}
      {fields.map((field) => (
        <div
          className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-x-2 gap-y-1"
          data-bulk-field={field.name}
          key={field.name}
        >
          <FormBuilder
            asFieldset
            context={context}
            disabled={disabled}
            fields={[field]}
            form={form}
            showFormErrors={false}
          />
          <Button
            aria-label={messages.removeField.replace("{field}", field.label)}
            className="mt-6"
            onClick={() => {
              restoreFocus.current = true;
              onRemove(field.name);
            }}
            size="icon-sm"
            type="button"
            variant="ghost"
          >
            <X aria-hidden="true" />
          </Button>
          {mixedOf?.(field).length ? (
            <p
              className="col-start-1 text-muted-foreground text-xs"
              data-bulk-mixed={field.name}
            >
              {conditionWords.mixedNote.replaceAll(
                "{fields}",
                listFields(mixedOf(field))
              )}
            </p>
          ) : null}
          {Object.hasOwn(clearValues, field.name) && (
            <Button
              className="col-start-1 w-fit px-0 text-muted-foreground"
              disabled={formValuesEqual(
                context.values?.[field.name],
                clearValues[field.name]
              )}
              onClick={() =>
                form.setFieldValue(field.name, clearValues[field.name])
              }
              size="sm"
              type="button"
              variant="link"
            >
              {messages.clearValue}
            </Button>
          )}
        </div>
      ))}
      <Popover onOpenChange={setPickerOpen} open={pickerOpen && !disabled}>
        <PopoverTrigger
          render={
            <Button
              disabled={disabled || !(available.length || blocked.length)}
              ref={trigger}
              type="button"
              variant="outline"
            >
              <Plus aria-hidden="true" />
              {messages.addField}
            </Button>
          }
        />
        <PopoverContent
          align="start"
          className="w-[min(18rem,calc(100vw-2rem))] gap-0 p-0"
        >
          <Command>
            <CommandInput
              aria-label={messages.searchFields}
              placeholder={messages.searchFields}
            />
            <CommandList className="max-h-[min(16rem,40dvh)]">
              <CommandEmpty>{messages.noFields}</CommandEmpty>
              {available.map((field) => (
                <CommandItem
                  className="min-h-11 md:min-h-8"
                  data-bulk-option={field.name}
                  key={field.name}
                  keywords={[field.label]}
                  onSelect={() => {
                    onAdd(field.name);
                    setPickerOpen(false);
                  }}
                  value={field.name}
                >
                  {field.label}
                </CommandItem>
              ))}
              {blocked.map(({ field, mixed }) => (
                <CommandItem
                  className="min-h-11 flex-col items-start gap-0.5 md:min-h-8"
                  data-bulk-blocked={field.name}
                  disabled
                  key={field.name}
                  keywords={[field.label]}
                  value={field.name}
                >
                  <span>{field.label}</span>
                  <span className="text-muted-foreground text-xs">
                    {conditionWords.mixedBlocked.replaceAll(
                      "{fields}",
                      listFields(mixed)
                    )}
                  </span>
                </CommandItem>
              ))}
            </CommandList>
          </Command>
        </PopoverContent>
      </Popover>
    </fieldset>
  );
}

// packages/yayaw-table-vue/src/components/forms/BulkEditorFields.vue
<script setup lang="ts">
import { computed, nextTick, ref } from "vue";
import { Plus, X } from "lucide-vue-next";
import { ListboxContent, ListboxFilter, ListboxItem, ListboxRoot, PopoverContent, PopoverRoot, PopoverTrigger } from "reka-ui";
import { type BulkEditorMessages, bulkConditionMessages } from "../../bulk-editor";
import { useTableContext } from "../../context";
import { formValuesEqual } from "../../form-runtime";
import type { FormFieldDefinition, TableRecord } from "../../types";

const props = defineProps<{
  fields: FormFieldDefinition[]; available: FormFieldDefinition[];
  clearValues: TableRecord; values: TableRecord; messages: BulkEditorMessages; disabled: boolean;
  /** Fields held back by a rule that reads values differing across the selection. */
  blocked?: { field: FormFieldDefinition; mixed: string[] }[];
  /** Labels of the mixed values a field's rules read. */
  mixedOf?: (field: FormFieldDefinition) => string[];
}>();
const table = useTableContext();
const conditionWords = computed(() => bulkConditionMessages(table.locale));
const blockedOptions = computed(() => (props.blocked ?? []).filter(({ field }) => field.label.toLocaleLowerCase().includes(search.value.trim().toLocaleLowerCase())));
const emit = defineEmits<{ add: [name: string]; remove: [name: string]; clear: [name: string, value: unknown] }>();
const open = ref(false);
const search = ref("");
const trigger = ref<HTMLButtonElement>();
const options = computed(() => props.available.filter(field => field.label.toLocaleLowerCase().includes(search.value.trim().toLocaleLowerCase())));
const add = (name: unknown): void => {
  if (props.disabled || typeof name !== "string" || !props.available.some(field => field.name === name)) return;
  emit("add", name);
  open.value = false;
};
const remove = async (name: string): Promise<void> => {
  emit("remove", name);
  await nextTick();
  trigger.value?.focus();
};
</script>

<template>
  <div class="yayaw-bulk-fields">
    <p v-if="!fields.length" class="yayaw-help yayaw-bulk-empty">{{ messages.empty }}</p>
    <div v-for="field in fields" :key="field.name" class="yayaw-bulk-field" :data-bulk-field="field.name">
      <slot name="field" :field="field" />
      <p v-if="mixedOf?.(field).length" class="yayaw-help yayaw-bulk-mixed" :data-bulk-mixed="field.name">{{ conditionWords.mixedNote.replaceAll("{fields}", mixedOf(field).join(", ")) }}</p>
      <button type="button" class="yayaw-icon-button yayaw-bulk-remove" :aria-label="messages.removeField.replace('{field}', field.label)" :disabled="disabled" @click="remove(field.name)"><X :size="16" aria-hidden="true" /></button>
      <button v-if="Object.hasOwn(clearValues, field.name)" type="button" class="yayaw-bulk-clear" :disabled="disabled || formValuesEqual(values[field.name], clearValues[field.name])" @click="emit('clear', field.name, clearValues[field.name])">{{ messages.clearValue }}</button>
    </div>
    <PopoverRoot :open="open && !disabled" @update:open="open = $event; search = ''">
      <PopoverTrigger as-child>
        <button ref="trigger" type="button" class="yayaw-button yayaw-button-outline" :disabled="disabled || !(available.length || blocked?.length)"><Plus :size="16" aria-hidden="true" />{{ messages.addField }}</button>
      </PopoverTrigger>
      <PopoverContent class="yayaw-bulk-picker" align="start" :side-offset="4" :collision-padding="16" :aria-label="messages.addField">
        <ListboxRoot @update:model-value="add">
          <ListboxFilter v-model="search" class="yayaw-input" :aria-label="messages.searchFields" :placeholder="messages.searchFields" auto-focus />
          <ListboxContent class="yayaw-bulk-picker-list" :aria-label="messages.addField">
            <ListboxItem v-for="field in options" :key="field.name" :value="field.name" :data-bulk-option="field.name" class="yayaw-bulk-picker-option">{{ field.label }}</ListboxItem>
            <ListboxItem v-for="item in blockedOptions" :key="item.field.name" :value="`blocked:${item.field.name}`" disabled :data-bulk-blocked="item.field.name" class="yayaw-bulk-picker-option yayaw-bulk-picker-blocked">
              <span>{{ item.field.label }}</span>
              <span class="yayaw-help">{{ conditionWords.mixedBlocked.replaceAll("{fields}", item.mixed.join(", ")) }}</span>
            </ListboxItem>
            <p v-if="!options.length && !blockedOptions.length" class="yayaw-help" role="status">{{ messages.noFields }}</p>
          </ListboxContent>
        </ListboxRoot>
      </PopoverContent>
    </PopoverRoot>
  </div>
</template>
