// packages/yayaw-table-vue/src/form/FormBuilderPreview.vue
<script setup lang="ts">
/**
 * The builder's center: the form as people will see it, in the language
 * being edited and the chosen layout. Answers are never sent; "Show as
 * closed" previews the closed message.
 */
import { SwitchRoot, SwitchThumb } from "reka-ui";
import { computed, nextTick, ref, useId, watch } from "vue";
import type { FormBuilderState } from "../form-builder";
import { formLanguageName } from "../form-text";
import type { FormColumn, FormLabelKey, FormTranslate } from "../form-view";
import YayawTableForm from "./YayawTableForm.vue";

const props = defineProps<{
  columns: readonly FormColumn[];
  state: FormBuilderState;
  headingId: string;
  translate?: FormTranslate;
  label: (key: FormLabelKey, params?: Record<string, string>) => string;
}>();

const id = `yayaw-form-builder-preview-${useId()}`;
const closed = ref(false);
const body = ref<HTMLElement>();
const layout = computed(() =>
  props.label(props.state.layout === "steps" ? "layoutSteps" : "layoutPage")
);
/** The preview answers without sending anything. */
const previewSubmit = () => ({ ok: true as const });

/** The rendered item of the selected entry, outlined and scrolled into view. */
const target = (container: HTMLElement): HTMLElement | null => {
  const selection = props.state.selection;
  switch (selection.kind) {
    case "question":
      return container.querySelector(`[data-form-question="${CSS.escape(selection.entry.id)}"]`);
    case "consent":
      return container.querySelector(`[data-form-consent="${CSS.escape(selection.entry.id)}"]`);
    case "section":
      return container.querySelector(`[data-form-section="${CSS.escape(selection.entry.id)}"]`);
    default:
      return null;
  }
};
let highlighted: HTMLElement | null = null;
watch(
  () => props.state,
  async () => {
    await nextTick();
    highlighted?.removeAttribute("data-builder-selected");
    highlighted = body.value ? target(body.value) : null;
    if (highlighted) {
      highlighted.setAttribute("data-builder-selected", "");
      highlighted.scrollIntoView?.({ block: "nearest" });
    }
  },
  { immediate: true, flush: "post" }
);
</script>

<template>
  <section class="yayaw-form-builder-preview" :aria-labelledby="headingId" data-form-builder-preview>
    <div class="yayaw-form-builder-pane-header yayaw-form-builder-preview-header">
      <h2 :id="headingId" class="yayaw-form-builder-pane-title">{{ label("builderPreview") }}</h2>
      <span class="yayaw-form-builder-subtitle" data-form-builder-preview-state>
        {{ formLanguageName(state.locale) }} · {{ layout }}
      </span>
      <div class="yayaw-form-builder-closed">
        <label :id="`${id}-closed-label`" class="yayaw-form-builder-subtitle" :for="`${id}-closed`">{{ label("builderShowClosed") }}</label>
        <SwitchRoot
          :id="`${id}-closed`"
          class="yayaw-switch-root"
          data-size="sm"
          :model-value="closed"
          :aria-labelledby="`${id}-closed-label`"
          @update:model-value="closed = $event === true"
        >
          <SwitchThumb class="yayaw-switch-thumb" />
        </SwitchRoot>
      </div>
    </div>
    <div ref="body" class="yayaw-form-builder-preview-body">
      <div class="yayaw-form-builder-preview-inner">
        <slot name="language" />
        <p class="yayaw-form-settings-note">{{ label("builderPreviewNote") }}</p>
        <YayawTableForm
          :columns="columns"
          :form="state.form"
          :locale="state.locale"
          :closed="closed"
          :translate="translate"
          :on-submit="previewSubmit"
        />
      </div>
    </div>
  </section>
</template>

// src/components/ui/yayaw-table/form/form-builder-preview.tsx
"use client";

import { type ReactNode, useEffect, useId, useRef, useState } from "react";
import { Switch } from "@/src/components/ui/switch";
import type { FormBuilderState } from "../utils/form-builder";
import { formLanguageName } from "../utils/form-text";
import type {
  FormColumn,
  FormLabelKey,
  FormTranslate,
} from "../utils/form-view";
import { YayawTableForm } from "./yayaw-table-form";

type Label = (key: FormLabelKey, params?: Record<string, string>) => string;

/** The preview answers without sending anything. */
const previewSubmit = () => ({ ok: true as const });

/** The rendered item of an outline entry, for highlighting the selection. */
function previewTarget(
  body: HTMLElement,
  state: FormBuilderState
): HTMLElement | null {
  const selection = state.selection;
  const escaped = (id: string) => CSS.escape(id);
  switch (selection.kind) {
    case "question":
      return body.querySelector(
        `[data-form-question="${escaped(selection.entry.id)}"]`
      );
    case "consent":
      return body.querySelector(
        `[data-form-consent="${escaped(selection.entry.id)}"]`
      );
    case "section":
      return body.querySelector(
        `[data-form-section="${escaped(selection.entry.id)}"]`
      );
    default:
      return null;
  }
}

/**
 * The builder's center: the form as people will see it, in the language
 * being edited and the chosen layout. Answers are never sent; "Show as
 * closed" previews the closed message.
 */
export function FormBuilderPreview({
  columns,
  headingId,
  label,
  languageBar,
  state,
  translate,
}: {
  columns: readonly FormColumn[];
  headingId: string;
  label: Label;
  /** The language switcher, above the preview on phones. */
  languageBar?: ReactNode;
  state: FormBuilderState;
  translate?: FormTranslate;
}) {
  const id = useId();
  const [closed, setClosed] = useState(false);
  const body = useRef<HTMLDivElement>(null);
  // The selected question, section or consent is outlined and scrolled into view.
  useEffect(() => {
    const container = body.current;
    const target = container ? previewTarget(container, state) : null;
    if (!target) {
      return;
    }
    target.setAttribute("data-builder-selected", "");
    target.scrollIntoView?.({ block: "nearest" });
    return () => target.removeAttribute("data-builder-selected");
  }, [state]);
  const layout = label(state.layout === "steps" ? "layoutSteps" : "layoutPage");
  return (
    <section
      aria-labelledby={headingId}
      className="flex min-h-0 min-w-0 flex-col bg-muted/40 dark:bg-muted/20"
      data-form-builder-preview
    >
      <div className="flex min-h-12 flex-wrap items-center gap-x-3 gap-y-1 border-b bg-background px-4 py-2">
        <h2 className="font-medium text-sm" id={headingId}>
          {label("builderPreview")}
        </h2>
        <span className="text-muted-foreground text-xs" data-form-builder-preview-state>
          {formLanguageName(state.locale)} · {layout}
        </span>
        <div className="ml-auto flex items-center gap-2">
          <label className="text-muted-foreground text-xs" htmlFor={`${id}-closed`}>
            {label("builderShowClosed")}
          </label>
          <Switch
            checked={closed}
            id={`${id}-closed`}
            onCheckedChange={(next) => setClosed(next)}
            size="sm"
          />
        </div>
      </div>
      <div
        className="min-h-0 flex-1 overflow-y-auto overscroll-contain px-3 py-5 sm:px-6 sm:py-8 [&_[data-builder-selected]]:rounded-md [&_[data-builder-selected]]:outline-2 [&_[data-builder-selected]]:outline-primary/60 [&_[data-builder-selected]]:outline-offset-4"
        ref={body}
      >
        <div className="mx-auto grid w-full max-w-[640px] gap-3">
          {languageBar}
          <p className="text-muted-foreground text-xs">{label("builderPreviewNote")}</p>
          <YayawTableForm
            closed={closed}
            columns={columns}
            form={state.form}
            locale={state.locale}
            onSubmit={previewSubmit}
            translate={translate}
          />
        </div>
      </div>
    </section>
  );
}
