// registry/default/ui/yayaw-table/components/details/record-details.tsx
"use client";

import { AlertDialog } from "@base-ui/react/alert-dialog";
import { Dialog } from "@base-ui/react/dialog";
import { Tabs } from "@base-ui/react/tabs";
import { Clock3, History, Pencil, Trash2, Undo2, X } from "lucide-react";
import { type ReactNode, type RefObject, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import type { ColumnDefinition } from "../../config/helpers";
import {
  type DetailActivity,
  type DetailField,
  type DetailLabels,
  type DetailRecord,
  type DetailRevertHandler,
  detailActivity,
  detailDate,
  detailLabels,
  detailSections,
  detailValue,
  type RecordDetailsConfig,
} from "../../utils/record-details";
import { DetailValue } from "./detail-value";
import { useActivityUndo } from "./use-activity-undo";
import "./record-details.css";

export interface RecordDetailsProps {
  row: DetailRecord;
  config: RecordDetailsConfig;
  columns?: ColumnDefinition[];
  locale?: string;
  onClose: () => void;
  onPlanning?: (row: DetailRecord) => void;
  onEdit?: (row: DetailRecord) => void;
  onDelete?: (
    row: DetailRecord
  ) =>
    | Promise<{ success: boolean; error?: string }>
    | { success: boolean; error?: string };
  onDeleted?: (row: DetailRecord) => void;
  onRevertActivity?: DetailRevertHandler;
  onReverted?: (entry: DetailActivity) => void;
  renderField?: (
    field: DetailField,
    value: unknown,
    row: DetailRecord
  ) => ReactNode;
}

function ActivityEntry({
  entry,
  fields,
  row,
  locale,
  labels,
  undoAction,
}: {
  entry: DetailActivity;
  fields: DetailField[];
  row: DetailRecord;
  locale: string;
  labels: DetailLabels;
  undoAction?: ReactNode;
}) {
  return (
    <li>
      <span aria-hidden="true" className="yayaw-detail-avatar">
        {entry.actor.name
          .split(" ")
          .map((part) => part[0])
          .slice(0, 2)
          .join("")}
      </span>
      <div className="yayaw-detail-event">
        <p>
          <strong>{entry.actor.name}</strong> {entry.action}
        </p>
        <time dateTime={entry.at}>{detailDate(entry.at, locale, true)}</time>
        {undoAction}
        {entry.changes?.map((change) => {
          const field = fields.find((item) => item.id === change.field);
          if (!field) {
            return null;
          }
          return (
            <div className="yayaw-detail-change" key={change.field}>
              <p>{field.label}</p>
              <div className="yayaw-detail-diff">
                <div>
                  <small>{labels.before}</small>
                  <DetailValue
                    field={field}
                    labels={labels}
                    locale={locale}
                    row={row}
                    value={change.before}
                  />
                </div>
                <span aria-hidden="true">→</span>
                <div>
                  <small>{labels.after}</small>
                  <DetailValue
                    field={field}
                    labels={labels}
                    locale={locale}
                    row={row}
                    value={change.after}
                  />
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </li>
  );
}

function ActivityUndoControl({
  entry,
  undo,
  labels,
  enabled,
  busy,
}: {
  entry: DetailActivity;
  undo: ReturnType<typeof useActivityUndo>;
  labels: DetailLabels;
  enabled: boolean;
  busy: boolean;
}) {
  const showUndo =
    enabled &&
    Boolean(entry.changes?.length) &&
    !entry.reverts &&
    entry.reversible !== false &&
    !undo.isUndone(entry);
  return (
    <>
      {undo.isUndone(entry) ? (
        <span className="yayaw-detail-undone">{labels.undone}</span>
      ) : null}
      {showUndo ? (
        <button
          className="yayaw-detail-undo"
          disabled={!undo.canUndo(entry) || Boolean(undo.pending) || busy}
          onClick={() => undo.undo(entry)}
          title={undo.canUndo(entry) ? labels.undo : labels.undoUnavailable}
          type="button"
        >
          <Undo2 aria-hidden="true" size={13} />
          {undo.pending === entry.id ? labels.undoing : labels.undo}
        </button>
      ) : null}
      {undo.error?.id === entry.id ? (
        <p role="alert">{undo.error.message}</p>
      ) : null}
    </>
  );
}

function DetailHeader({
  row,
  title,
  config,
  locale,
  labels,
  busy,
  onPlanning,
  onEdit,
  onDelete,
  onClose,
  deleteButton,
}: {
  row: DetailRecord;
  title: string;
  config: RecordDetailsConfig;
  locale: string;
  labels: DetailLabels;
  busy: boolean;
  onPlanning?: (row: DetailRecord) => void;
  onEdit?: (row: DetailRecord) => void;
  onDelete?: () => void;
  onClose: () => void;
  deleteButton: RefObject<HTMLButtonElement | null>;
}) {
  const updated = config.updatedAt?.(row);
  const updatedBy = config.updatedBy?.(row);
  const inline = config.presentation === "inline";
  return (
    <>
      <header className="yayaw-detail-header">
        <div className="yayaw-detail-heading">
          <p className="yayaw-detail-eyebrow">
            {labels.record} {row.id ? <span>/ {String(row.id)}</span> : null}
          </p>
          <h2>{title}</h2>
          {config.description ? (
            <p className="yayaw-detail-description">
              {config.description(row)}
            </p>
          ) : null}
        </div>
        <div className="yayaw-detail-actions">
          {onPlanning && (
            <button onClick={() => onPlanning(row)} type="button">
              {locale.startsWith("fr") ? "Planification" : "Planning"}
            </button>
          )}
          {onEdit ? (
            <Button
              disabled={busy}
              onClick={() => onEdit(row)}
              variant="outline"
            >
              <Pencil aria-hidden="true" size={15} />
              {labels.edit}
            </Button>
          ) : null}
          {onDelete ? (
            <Button
              className="yayaw-detail-delete"
              disabled={busy}
              onClick={onDelete}
              ref={deleteButton}
              variant="outline"
            >
              <Trash2 aria-hidden="true" size={15} />
              {labels.delete}
            </Button>
          ) : null}
          {inline ? (
            <Button
              aria-label={labels.close}
              disabled={busy}
              onClick={onClose}
              size="icon"
              variant="ghost"
            >
              <X size={16} />
            </Button>
          ) : null}
        </div>
      </header>
      {updated ? (
        <div className="yayaw-detail-meta">
          <Clock3 aria-hidden="true" size={14} />
          <span>
            {labels.updated}{" "}
            <time
              dateTime={
                updated instanceof Date ? updated.toISOString() : updated
              }
            >
              {detailDate(updated, locale, true)}
            </time>
            {updatedBy ? (
              <>
                {" "}
                · {labels.by} <strong>{updatedBy}</strong>
              </>
            ) : null}
          </span>
        </div>
      ) : null}
    </>
  );
}

/** Mount with a stable record key; the content works in a drawer, modal, or any page container. */
export function RecordDetails({
  row,
  config,
  columns = [],
  locale = "en",
  onClose,
  onPlanning,
  onEdit,
  onDelete,
  onDeleted,
  onRevertActivity,
  onReverted,
  renderField,
}: RecordDetailsProps) {
  const [confirming, setConfirming] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const deletionPending = useRef(false);
  const [error, setError] = useState("");
  const cancelButton = useRef<HTMLButtonElement>(null);
  const deleteButton = useRef<HTMLButtonElement>(null);
  const labels = detailLabels(locale, config.labels);
  const title =
    config.title?.(row) ??
    String(row.name ?? row.title ?? row.id ?? labels.record);
  const sections = detailSections(config, columns, row, labels.details);
  const fields = sections.flatMap((section) => section.fields);
  const activity = detailActivity(config, row);
  const undo = useActivityUndo({
    activity,
    row,
    config,
    labels,
    handler: onRevertActivity,
    onReverted,
  });
  const inline = config.presentation === "inline";
  const confirmDelete = async () => {
    if (!onDelete || deletionPending.current || undo.pending) {
      return;
    }
    deletionPending.current = true;
    setDeleting(true);
    setError("");
    try {
      const result = await onDelete(row);
      if (!result.success) {
        throw new Error(result.error ?? labels.deleteError);
      }
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : labels.deleteError);
      return;
    } finally {
      deletionPending.current = false;
      setDeleting(false);
    }
    // Refresh callbacks run outside mutation error handling, so a completed delete cannot be repeated.
    setConfirming(false);
    onClose();
    onDeleted?.(row);
  };
  const content = (
    <>
      <article
        aria-busy={deleting || Boolean(undo.pending)}
        aria-label={title}
        className="yayaw-detail"
      >
        <DetailHeader
          busy={confirming || deleting || Boolean(undo.pending)}
          config={config}
          deleteButton={deleteButton}
          labels={labels}
          locale={locale}
          onClose={onClose}
          onDelete={
            onDelete
              ? () => {
                  setError("");
                  setConfirming(true);
                }
              : undefined
          }
          onEdit={onEdit}
          onPlanning={onPlanning}
          row={row}
          title={title}
        />
        <Tabs.Root defaultValue="details">
          <Tabs.List
            aria-label={labels.record}
            className="yayaw-detail-tablist"
          >
            <Tabs.Tab value="details">{labels.details}</Tabs.Tab>
            <Tabs.Tab value="activity">
              <History aria-hidden="true" size={15} />
              {labels.activity}
              <span className="yayaw-detail-count">{activity.length}</span>
            </Tabs.Tab>
          </Tabs.List>
          <Tabs.Panel className="yayaw-detail-body" value="details">
            {sections.map((section) => (
              <section className="yayaw-detail-section" key={section.id}>
                <h3>{section.title}</h3>
                {section.description ? (
                  <p className="yayaw-detail-description">
                    {section.description}
                  </p>
                ) : null}
                <dl>
                  {section.fields.map((field) => (
                    <div className="yayaw-detail-field" key={field.id}>
                      <dt>{field.label}</dt>
                      <dd>
                        {renderField?.(field, detailValue(row, field), row) ?? (
                          <DetailValue
                            field={field}
                            labels={labels}
                            locale={locale}
                            row={row}
                            value={detailValue(row, field)}
                          />
                        )}
                      </dd>
                    </div>
                  ))}
                </dl>
              </section>
            ))}
            {sections.length === 0 ? (
              <p className="yayaw-detail-empty">{labels.empty}</p>
            ) : null}
          </Tabs.Panel>
          <Tabs.Panel className="yayaw-detail-body" value="activity">
            {activity.length ? (
              <ol className="yayaw-detail-timeline">
                {activity.map((entry) => (
                  <ActivityEntry
                    entry={entry}
                    fields={fields}
                    key={entry.id}
                    labels={labels}
                    locale={locale}
                    row={row}
                    undoAction={
                      <ActivityUndoControl
                        busy={deleting || confirming}
                        enabled={Boolean(onRevertActivity)}
                        entry={entry}
                        labels={labels}
                        undo={undo}
                      />
                    }
                  />
                ))}
              </ol>
            ) : (
              <p className="yayaw-detail-empty">{labels.noActivity}</p>
            )}
          </Tabs.Panel>
        </Tabs.Root>
      </article>
      <AlertDialog.Root
        onOpenChange={(open) => {
          if (!deleting) {
            setConfirming(open);
          }
        }}
        open={confirming}
      >
        <AlertDialog.Portal>
          <AlertDialog.Backdrop className="yayaw-detail-overlay yayaw-detail-overlay-confirm" />
          <AlertDialog.Popup
            className="yayaw-detail-surface yayaw-detail-confirm-surface"
            finalFocus={deleteButton}
            initialFocus={cancelButton}
          >
            <AlertDialog.Title>{labels.confirmDelete}</AlertDialog.Title>
            <AlertDialog.Description>
              {labels.deleteDescription}
            </AlertDialog.Description>
            <strong>{title}</strong>
            {error ? <p role="alert">{error}</p> : null}
            <div className="yayaw-detail-actions">
              <Button
                disabled={deleting}
                onClick={() => setConfirming(false)}
                ref={cancelButton}
                variant="outline"
              >
                {labels.cancel}
              </Button>
              <Button
                disabled={deleting || !onDelete}
                onClick={confirmDelete}
                variant="destructive"
              >
                {deleting ? labels.deleting : labels.delete}
              </Button>
            </div>
          </AlertDialog.Popup>
        </AlertDialog.Portal>
      </AlertDialog.Root>
    </>
  );
  if (inline) {
    return content;
  }
  return (
    <Dialog.Root
      onOpenChange={(open) => {
        if (!(open || deleting || confirming || undo.pending)) {
          onClose();
        }
      }}
      open
    >
      <Dialog.Portal>
        <Dialog.Backdrop className="yayaw-detail-overlay" />
        <Dialog.Popup
          className="yayaw-detail-surface"
          data-presentation={config.presentation ?? "drawer"}
          style={{
            width:
              config.width ??
              (config.presentation === "modal"
                ? "min(880px, 94vw)"
                : "min(720px, 100vw)"),
          }}
        >
          <div className="yayaw-detail-dialog-header">
            <Dialog.Title>{labels.record}</Dialog.Title>
            <Button
              aria-label={labels.close}
              disabled={deleting || confirming || Boolean(undo.pending)}
              onClick={onClose}
              size="icon"
              variant="ghost"
            >
              <X size={16} />
            </Button>
          </div>
          {content}
        </Dialog.Popup>
      </Dialog.Portal>
    </Dialog.Root>
  );
}

// packages/yayaw-table-vue/src/components/details/RecordDetails.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { Clock3, History, Pencil, Trash2, Undo2 } from "lucide-vue-next";
import { TabsContent, TabsList, TabsRoot, TabsTrigger } from "reka-ui";
import { detailActivity, detailDate, detailLabels, detailSections, detailValue, type DetailField, type DetailRecord, type RecordDetailsConfig } from "../../record-details";
import type { ColumnDefinition } from "../../types";
import FormDialog from "../forms/FormDialog.vue";
import DetailValue from "./DetailValue.vue";
import "../../record-details.css";
import { canRevertDetailActivity, type DetailActivity, type DetailRevertHandler } from "../../record-details";

const props = withDefaults(defineProps<{
  row: DetailRecord;
  config: RecordDetailsConfig;
  columns?: ColumnDefinition[];
  locale?: string;
  canEdit?: boolean;
  canDelete?: boolean;
  onPlanning?: (row: DetailRecord) => void;
  onDelete?: (row: DetailRecord) => Promise<{ success: boolean; error?: string }> | { success: boolean; error?: string };
  onRevertActivity?: DetailRevertHandler;
}>(), { columns: () => [], locale: "en", canEdit: false, canDelete: false });
const emit = defineEmits<{ close: []; edit: [row: DetailRecord]; deleted: [row: DetailRecord]; reverted: [entry: DetailActivity] }>();
const labels = computed(() => detailLabels(props.locale, props.config.labels));
const title = computed(() => props.config.title?.(props.row) ?? String(props.row.name ?? props.row.title ?? props.row.id ?? labels.value.record));
const sections = computed(() => detailSections(props.config, props.columns, props.row, labels.value.details));
const fields = computed(() => sections.value.flatMap(section => section.fields));
const activity = computed(() => detailActivity(props.config, props.row));
const updated = computed(() => props.config.updatedAt?.(props.row));
const updatedBy = computed(() => props.config.updatedBy?.(props.row));
const confirming = ref(false);
const deleting = ref(false);
const error = ref("");
const undoPending = ref<string>();
const undoError = ref<{ id: string; message: string }>();
const completedUndos = ref<string[]>([]);
const isUndone = (entry: DetailActivity) => completedUndos.value.includes(entry.id) || activity.value.some(item => item.reverts === entry.id);
const canUndo = (entry: DetailActivity) => Boolean(props.onRevertActivity) && !isUndone(entry) && canRevertDetailActivity(entry, activity.value) && props.config.canRevert?.(entry, props.row) !== false;
const undo = async (entry: DetailActivity): Promise<void> => {
  if (undoPending.value || deleting.value || confirming.value || !canUndo(entry) || !props.onRevertActivity) return;
  undoPending.value = entry.id;
  undoError.value = undefined;
  try {
    const result = await props.onRevertActivity(props.row, entry);
    if (!result.success) throw new Error(result.error ?? labels.value.undoError);
    completedUndos.value.push(entry.id);
    emit("reverted", entry);
  } catch (cause) {
    undoError.value = { id: entry.id, message: cause instanceof Error ? cause.message : labels.value.undoError };
  } finally { undoPending.value = undefined; }
};
const cancelButton = ref<HTMLButtonElement>();
const deletionTrigger = ref<HTMLButtonElement>();
const fieldFor = (id: string): DetailField | undefined => fields.value.find(field => field.id === id);
const requestDelete = (): void => {
  if (!props.canDelete || !props.onDelete || deleting.value) return;
  error.value = "";
  confirming.value = true;
};
const confirmDelete = async (): Promise<void> => {
  if (!props.canDelete || !props.onDelete || deleting.value) return;
  deleting.value = true;
  error.value = "";
  try {
    const result = await props.onDelete(props.row);
    if (!result.success) throw new Error(result.error ?? labels.value.deleteError);
    confirming.value = false;
    // A completed mutation is never retried because a subsequent table refresh fails.
    emit("close");
    emit("deleted", props.row);
  } catch (cause) {
    error.value = cause instanceof Error ? cause.message : labels.value.deleteError;
  } finally {
    deleting.value = false;
  }
};
</script>

<template>
  <component :is="config.presentation === 'inline' ? 'section' : FormDialog"
    :open="true" :title="labels.record" :presentation="config.presentation === 'modal' ? 'modal' : 'drawer'"
    :width="config.width ?? (config.presentation === 'modal' ? 'min(880px, 94vw)' : 'min(720px, 100vw)')"
    :busy="confirming || deleting || Boolean(undoPending)" :close-label="labels.close" @close="emit('close')">
    <article class="yayaw-detail" :aria-label="title" :aria-busy="deleting || Boolean(undoPending)">
      <header class="yayaw-detail-header">
        <div class="yayaw-detail-heading"><p class="yayaw-detail-eyebrow">{{ labels.record }} <span v-if="row.id">/ {{ row.id }}</span></p><h2>{{ title }}</h2><p v-if="config.description" class="yayaw-detail-description">{{ config.description(row) }}</p></div>
        <div class="yayaw-detail-actions">
          <button v-if="canEdit" type="button" class="yayaw-button yayaw-button-outline" :disabled="confirming || deleting || Boolean(undoPending)" @click="emit('edit', row)"><Pencil :size="15" aria-hidden="true" />{{ labels.edit }}</button>
          <button v-if="onPlanning" type="button" class="yayaw-button" @click="onPlanning(row)">{{ locale?.startsWith('fr') ? 'Planification' : 'Planning' }}</button>
          <button v-if="canDelete && onDelete" ref="deletionTrigger" type="button" class="yayaw-button yayaw-detail-delete" :disabled="confirming || deleting || Boolean(undoPending)" @click="requestDelete"><Trash2 :size="15" aria-hidden="true" />{{ labels.delete }}</button>
          <button v-if="config.presentation === 'inline'" type="button" class="yayaw-icon-button" :aria-label="labels.close" :disabled="confirming || deleting || Boolean(undoPending)" @click="emit('close')">×</button>
        </div>
      </header>
      <div v-if="updated" class="yayaw-detail-meta"><Clock3 :size="14" aria-hidden="true" /><span>{{ labels.updated }} <time :datetime="updated instanceof Date ? updated.toISOString() : updated">{{ detailDate(updated, locale, true) }}</time><template v-if="updatedBy"> · {{ labels.by }} <strong>{{ updatedBy }}</strong></template></span></div>
      <TabsRoot default-value="details" class="yayaw-detail-tabs">
        <TabsList class="yayaw-detail-tablist" :aria-label="labels.record"><TabsTrigger value="details">{{ labels.details }}</TabsTrigger><TabsTrigger value="activity"><History :size="15" aria-hidden="true" />{{ labels.activity }}<span class="yayaw-detail-count">{{ activity.length }}</span></TabsTrigger></TabsList>
        <TabsContent value="details" class="yayaw-detail-body">
          <section v-for="section in sections" :key="section.id" class="yayaw-detail-section"><h3>{{ section.title }}</h3><p v-if="section.description" class="yayaw-detail-description">{{ section.description }}</p><dl><div v-for="field in section.fields" :key="field.id" class="yayaw-detail-field"><dt>{{ field.label }}</dt><dd><slot :name="`detail-${field.id}`" :row="row" :value="detailValue(row, field)" :field="field"><DetailValue :field="field" :value="detailValue(row, field)" :row="row" :locale="locale" :labels="labels" /></slot></dd></div></dl></section>
          <p v-if="!sections.length" class="yayaw-detail-empty">{{ labels.empty }}</p>
        </TabsContent>
        <TabsContent value="activity" class="yayaw-detail-body">
          <p v-if="!activity.length" class="yayaw-detail-empty">{{ labels.noActivity }}</p>
          <ol v-else class="yayaw-detail-timeline"><li v-for="entry in activity" :key="entry.id"><span class="yayaw-detail-avatar" aria-hidden="true">{{ entry.actor.name.split(' ').map(part => part[0]).slice(0, 2).join('') }}</span><div class="yayaw-detail-event"><p><strong>{{ entry.actor.name }}</strong> {{ entry.action }}</p><time :datetime="entry.at">{{ detailDate(entry.at, locale, true) }}</time><span v-if="isUndone(entry)" class="yayaw-detail-undone">{{ labels.undone }}</span><button v-else-if="onRevertActivity && entry.changes?.length && !entry.reverts && entry.reversible !== false" type="button" class="yayaw-detail-undo" :disabled="!canUndo(entry) || Boolean(undoPending) || confirming || deleting" :title="canUndo(entry) ? labels.undo : labels.undoUnavailable" @click="undo(entry)"><Undo2 :size="13" aria-hidden="true" />{{ undoPending === entry.id ? labels.undoing : labels.undo }}</button><p v-if="undoError?.id === entry.id" role="alert" class="yayaw-error">{{ undoError.message }}</p><div v-for="change in entry.changes?.filter(item => fieldFor(item.field))" :key="change.field" class="yayaw-detail-change"><p>{{ fieldFor(change.field)?.label }}</p><div class="yayaw-detail-diff"><div><small>{{ labels.before }}</small><DetailValue :field="fieldFor(change.field)!" :value="change.before" :row="row" :locale="locale" :labels="labels" /></div><span aria-hidden="true">→</span><div><small>{{ labels.after }}</small><DetailValue :field="fieldFor(change.field)!" :value="change.after" :row="row" :locale="locale" :labels="labels" /></div></div></div></div></li></ol>
        </TabsContent>
      </TabsRoot>
    </article>
    <FormDialog v-if="confirming" :open="true" role="alertdialog" presentation="modal" width="min(460px, 94vw)" :title="labels.confirmDelete" :description="labels.deleteDescription" :busy="deleting" :return-focus="deletionTrigger" :close-label="labels.close" @close="confirming = false" @open-auto-focus="event => { event.preventDefault(); cancelButton?.focus(); }">
      <div class="yayaw-detail-confirm"><strong>{{ title }}</strong><p v-if="error" class="yayaw-error" role="alert">{{ error }}</p><div><button ref="cancelButton" type="button" class="yayaw-button yayaw-button-outline" :disabled="deleting" @click="confirming = false">{{ labels.cancel }}</button><button type="button" class="yayaw-button yayaw-button-danger" :disabled="deleting || !canDelete" @click="confirmDelete">{{ deleting ? labels.deleting : labels.delete }}</button></div></div>
    </FormDialog>
  </component>
</template>
