// registry/default/ui/yayaw-table/components/details/record-activity.tsx
"use client";

import { Undo2 } from "lucide-react";
import { createContext, type ReactNode } from "react";
import {
  type DetailActivity,
  type DetailField,
  type DetailLabels,
  type DetailRecord,
  type DetailRevertHandler,
  detailDate,
  type RecordDetailsConfig,
} from "../../utils/record-details";
import { DetailValue } from "./detail-value";
import { useActivityUndo } from "./use-activity-undo";
import "./record-details.css";

/** The table's record view and rows: the edit form shows the record's activity next to its fields when the host keeps one. */
export const RecordActivityContext = createContext<
  | {
      details?: RecordDetailsConfig;
      onRevertActivity?: DetailRevertHandler;
      rows: DetailRecord[];
      getRowId?: (row: DetailRecord) => string;
      refresh: () => Promise<unknown>;
    }
  | undefined
>(undefined);

function ActivityEntry({
  entry,
  fields,
  row,
  locale,
  labels,
  undoAction,
}: {
  entry: DetailActivity;
  fields: DetailField[];
  row: DetailRecord;
  locale: string;
  labels: DetailLabels;
  undoAction?: ReactNode;
}) {
  return (
    <li>
      <span aria-hidden="true" className="yayaw-detail-avatar">
        {entry.actor.name
          .split(" ")
          .map((part) => part[0])
          .slice(0, 2)
          .join("")}
      </span>
      <div className="yayaw-detail-event">
        <p>
          <strong>{entry.actor.name}</strong> {entry.action}
        </p>
        <time dateTime={entry.at}>{detailDate(entry.at, locale, true)}</time>
        {undoAction}
        {entry.changes?.map((change) => {
          const field = fields.find((item) => item.id === change.field);
          if (!field) {
            return null;
          }
          return (
            <div className="yayaw-detail-change" key={change.field}>
              <p>{field.label}</p>
              <div className="yayaw-detail-diff">
                <div>
                  <small>{labels.before}</small>
                  <DetailValue
                    field={field}
                    labels={labels}
                    locale={locale}
                    row={row}
                    value={change.before}
                  />
                </div>
                <span aria-hidden="true">→</span>
                <div>
                  <small>{labels.after}</small>
                  <DetailValue
                    field={field}
                    labels={labels}
                    locale={locale}
                    row={row}
                    value={change.after}
                  />
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </li>
  );
}

function ActivityUndoControl({
  entry,
  undo,
  labels,
  enabled,
  busy,
}: {
  entry: DetailActivity;
  undo: ReturnType<typeof useActivityUndo>;
  labels: DetailLabels;
  enabled: boolean;
  busy: boolean;
}) {
  const showUndo =
    enabled &&
    Boolean(entry.changes?.length) &&
    !entry.reverts &&
    entry.reversible !== false &&
    !undo.isUndone(entry);
  return (
    <>
      {undo.isUndone(entry) ? (
        <span className="yayaw-detail-undone">{labels.undone}</span>
      ) : null}
      {showUndo ? (
        <button
          className="yayaw-detail-undo"
          disabled={!undo.canUndo(entry) || Boolean(undo.pending) || busy}
          onClick={() => undo.undo(entry)}
          title={undo.canUndo(entry) ? labels.undo : labels.undoUnavailable}
          type="button"
        >
          <Undo2 aria-hidden="true" size={13} />
          {undo.pending === entry.id ? labels.undoing : labels.undo}
        </button>
      ) : null}
      {undo.error?.id === entry.id ? (
        <p role="alert">{undo.error.message}</p>
      ) : null}
    </>
  );
}

/** A record's activity timeline and its undo buttons, shared by the record details and the edit form. */
export function RecordActivity({
  row,
  activity,
  fields,
  labels,
  locale = "en",
  disabled = false,
  config,
  onRevertActivity,
  onReverted,
  onPendingChange,
}: {
  row: DetailRecord;
  activity: DetailActivity[];
  fields: DetailField[];
  labels: DetailLabels;
  locale?: string;
  disabled?: boolean;
  config: RecordDetailsConfig;
  onRevertActivity?: DetailRevertHandler;
  onReverted?: (entry: DetailActivity) => void;
  onPendingChange?: (pending: boolean) => void;
}) {
  const undo = useActivityUndo({
    activity,
    row,
    config,
    labels,
    handler: onRevertActivity,
    onReverted,
    onPendingChange,
  });
  if (!activity.length) {
    return <p className="yayaw-detail-empty">{labels.noActivity}</p>;
  }
  return (
    <ol className="yayaw-detail-timeline">
      {activity.map((entry) => (
        <ActivityEntry
          entry={entry}
          fields={fields}
          key={entry.id}
          labels={labels}
          locale={locale}
          row={row}
          undoAction={
            <ActivityUndoControl
              busy={disabled}
              enabled={Boolean(onRevertActivity)}
              entry={entry}
              labels={labels}
              undo={undo}
            />
          }
        />
      ))}
    </ol>
  );
}

// packages/yayaw-table-vue/src/components/details/RecordActivity.vue
<script setup lang="ts">
import { toast } from "vue-sonner";
import { ref, watch } from "vue";
import { Undo2 } from "lucide-vue-next";
import { canRevertDetailActivity, detailDate, detailUndoMessage, type DetailActivity, type DetailField, type DetailLabels, type DetailRecord, type DetailRevertHandler } from "../../record-details";
import DetailValue from "./DetailValue.vue";

/** A record's activity timeline and its undo buttons, shared by the record details and the edit form. */
const props = withDefaults(defineProps<{
  row: DetailRecord;
  activity: readonly DetailActivity[];
  fields: readonly DetailField[];
  labels: DetailLabels;
  locale?: string;
  disabled?: boolean;
  onRevertActivity?: DetailRevertHandler;
  canRevert?: (entry: DetailActivity, row: DetailRecord) => boolean;
}>(), { locale: "en" });
const emit = defineEmits<{ reverted: [entry: DetailActivity]; pending: [pending: boolean] }>();
const undoPending = ref<string>();
const undoError = ref<{ id: string; message: string }>();
const completedUndos = ref<string[]>([]);
watch(undoPending, pending => emit("pending", Boolean(pending)));
const fieldFor = (id: string): DetailField | undefined => props.fields.find(field => field.id === id);
const isUndone = (entry: DetailActivity) => completedUndos.value.includes(entry.id) || props.activity.some(item => item.reverts === entry.id);
const canUndo = (entry: DetailActivity) => Boolean(props.onRevertActivity) && !isUndone(entry) && canRevertDetailActivity(entry, props.activity) && props.canRevert?.(entry, props.row) !== false;
const undo = async (entry: DetailActivity): Promise<void> => {
  if (undoPending.value || props.disabled || !canUndo(entry) || !props.onRevertActivity) return;
  undoPending.value = entry.id;
  undoError.value = undefined;
  try {
    const result = await props.onRevertActivity(props.row, entry);
    if (!result.success) throw new Error(result.error ?? props.labels.undoError);
    completedUndos.value.push(entry.id);
    emit("reverted", entry);
    toast.success(detailUndoMessage(entry, props.labels));
  } catch (cause) {
    undoError.value = { id: entry.id, message: cause instanceof Error ? cause.message : props.labels.undoError };
  } finally { undoPending.value = undefined; }
};
</script>

<template>
  <p v-if="!activity.length" class="yayaw-detail-empty">{{ labels.noActivity }}</p>
  <ol v-else class="yayaw-detail-timeline"><li v-for="entry in activity" :key="entry.id"><span class="yayaw-detail-avatar" aria-hidden="true">{{ entry.actor.name.split(' ').map(part => part[0]).slice(0, 2).join('') }}</span><div class="yayaw-detail-event"><p><strong>{{ entry.actor.name }}</strong> {{ entry.action }}</p><time :datetime="entry.at">{{ detailDate(entry.at, locale, true) }}</time><span v-if="isUndone(entry)" class="yayaw-detail-undone">{{ labels.undone }}</span><button v-else-if="onRevertActivity && entry.changes?.length && !entry.reverts && entry.reversible !== false" type="button" class="yayaw-detail-undo" :disabled="!canUndo(entry) || Boolean(undoPending) || disabled" :title="canUndo(entry) ? labels.undo : labels.undoUnavailable" @click="undo(entry)"><Undo2 :size="13" aria-hidden="true" />{{ undoPending === entry.id ? labels.undoing : labels.undo }}</button><p v-if="undoError?.id === entry.id" role="alert" class="yayaw-error">{{ undoError.message }}</p><div v-for="change in entry.changes?.filter(item => fieldFor(item.field))" :key="change.field" class="yayaw-detail-change"><p>{{ fieldFor(change.field)?.label }}</p><div class="yayaw-detail-diff"><div><small>{{ labels.before }}</small><DetailValue :field="fieldFor(change.field)!" :value="change.before" :row="row" :locale="locale" :labels="labels" /></div><span aria-hidden="true">→</span><div><small>{{ labels.after }}</small><DetailValue :field="fieldFor(change.field)!" :value="change.after" :row="row" :locale="locale" :labels="labels" /></div></div></div></div></li></ol>
</template>
