// packages/yayaw-table-vue/src/dashboard/DashboardViewEditor.vue
<script setup lang="ts">
/**
 * "Edit view…": a near full-screen dialog (full screen on phones) whose live
 * table of the source is the editor: its toolbar, filters, sort, columns,
 * display modes and their settings, without URL sync, saved views, selection
 * or record changes. "Apply" stores what the table reports; closing with
 * changes asks first.
 */
import { X } from "lucide-vue-next";
import {
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogOverlay,
  AlertDialogPortal,
  AlertDialogRoot,
  AlertDialogTitle,
  DialogContent,
  DialogDescription,
  DialogOverlay,
  DialogPortal,
  DialogRoot,
  DialogTitle,
} from "reka-ui";
import { computed, ref, shallowRef, useId } from "vue";
import YayawDataTable from "../components/YayawDataTable.vue";
import type { DisplayModeRenderers } from "../display-mode-renderer";
import type {
  DataTableTranslations,
  TableActions,
  TableConfig,
  TableRecord,
  TableViewConfig,
} from "../types";
import type { ViewConfig } from "../view-config";
import {
  type DashboardViewEdit,
  dashboardViewEdited,
  dashboardViewEditorActions,
  dashboardViewEditorConfig,
  dashboardViewToApply,
  recordDashboardViewReport,
} from "./dashboard-editor-model";
import type { DashboardInlineView } from "./dashboard-schema";
import type { DashboardLabel, DashboardTableSource } from "./dashboard-types";

const props = defineProps<{
  /** The source whose table is the editor. */
  source: DashboardTableSource;
  sourceId: string;
  /** Where the editor starts (`dashboardViewEditStart`). */
  start: DashboardViewEdit;
  /** Under the title: the widget or source edited. */
  subtitle: string;
  label: DashboardLabel;
  locale: string;
  renderers?: DisplayModeRenderers;
  getRowId?: (row: TableRecord) => string;
  translations?: DataTableTranslations;
}>();
const emit = defineEmits<{
  /** "Apply": the view to store in `widget.view` (`dashboardViewToApply`). */
  apply: [view: DashboardInlineView];
  close: [];
}>();

// A table of its own for each opening.
const instanceId = `view-editor-${useId()}`;
const edit = shallowRef<DashboardViewEdit>(props.start);
const confirming = ref(false);
const edited = computed(() => dashboardViewEdited(edit.value));
const hostProps = computed(() => props.source.tableProps ?? {});
const config = computed(() => dashboardViewEditorConfig(props.source.config) as TableConfig);
const actions = computed(() => dashboardViewEditorActions(props.source.actions) as TableActions);
const tableProps = computed(() => ({
  tableType: props.sourceId,
  tableId: instanceId,
  instanceId,
  config: config.value,
  getTableActions: () => actions.value,
  initialView: { id: null, config: props.start.initial as TableViewConfig },
  syncUrl: false,
  locale: props.locale,
  translations: (hostProps.value.translations as DataTableTranslations | undefined) ?? props.translations,
  getRowId: (hostProps.value.getRowId as ((row: TableRecord) => string) | undefined) ?? props.getRowId,
  displayModeRenderers: {
    ...props.renderers,
    ...(hostProps.value.displayModeRenderers as DisplayModeRenderers | undefined),
  },
  onViewConfigChange: (view: ViewConfig) => {
    edit.value = recordDashboardViewReport(edit.value, view);
  },
}));
const apply = (): void => {
  const view = dashboardViewToApply(edit.value);
  if (view) emit("apply", view);
  emit("close");
};
const requestClose = (): void => {
  if (edited.value) confirming.value = true;
  else emit("close");
};
/** Escape asks before discarding changes; nested menus close first. */
const onEscape = (event: KeyboardEvent): void => {
  event.preventDefault();
  requestClose();
};
const keepOpen = (event: Event): void => event.preventDefault();
</script>

<template>
  <DialogRoot :open="true">
    <DialogPortal>
      <DialogOverlay class="yayaw-dashboard-view-editor-backdrop" />
      <DialogContent
        class="yayaw-dashboard-view-editor"
        data-view-editor=""
        @escape-key-down="onEscape"
        @pointer-down-outside="keepOpen"
        @interact-outside="keepOpen"
      >
        <DialogDescription class="yayaw-dashboard-sr-only">{{ props.label("viewEditorDescription") }}</DialogDescription>
        <header class="yayaw-dashboard-view-editor-bar" data-view-editor-bar="">
          <div class="yayaw-dashboard-view-editor-heading">
            <DialogTitle as="h2" class="yayaw-dashboard-view-editor-title">{{ props.label("viewEditorTitle") }}</DialogTitle>
            <p class="yayaw-dashboard-view-editor-subtitle">{{ props.subtitle }}</p>
          </div>
          <div class="yayaw-dashboard-view-editor-actions">
            <span v-if="edited" class="yayaw-dashboard-view-editor-status" data-view-editor-status="">
              <span class="yayaw-dashboard-view-editor-dot" aria-hidden="true" />{{ props.label("unsavedChanges") }}
            </span>
            <button type="button" class="yayaw-button" data-view-editor-apply="" :disabled="!edited" @click="apply">
              {{ props.label("apply") }}
            </button>
            <button type="button" class="yayaw-dashboard-icon-button" :aria-label="props.label('close')" @click="requestClose">
              <X :size="16" aria-hidden="true" />
            </button>
          </div>
        </header>
        <div class="yayaw-dashboard-view-editor-table" data-view-editor-table="">
          <YayawDataTable v-bind="tableProps" />
        </div>
        <AlertDialogRoot :open="confirming" @update:open="(open: boolean) => { if (!open) confirming = false; }">
          <AlertDialogPortal>
            <AlertDialogOverlay class="yayaw-dashboard-confirm-backdrop" />
            <AlertDialogContent class="yayaw-dashboard-dialog yayaw-dashboard-confirm" data-view-editor-confirm="">
              <AlertDialogTitle as="h2">{{ props.label("discardTitle") }}</AlertDialogTitle>
              <AlertDialogDescription class="yayaw-dashboard-muted">{{ props.label("discardDescription") }}</AlertDialogDescription>
              <div class="yayaw-dashboard-dialog-footer">
                <button type="button" class="yayaw-button yayaw-button-outline" @click="confirming = false">{{ props.label("keepEditing") }}</button>
                <button type="button" class="yayaw-button yayaw-dashboard-danger" @click="emit('close')">{{ props.label("discard") }}</button>
                <button type="button" class="yayaw-button" @click="apply">{{ props.label("applyAndClose") }}</button>
              </div>
            </AlertDialogContent>
          </AlertDialogPortal>
        </AlertDialogRoot>
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
</template>

// registry/default/ui/yayaw-table-dashboard/dashboard-view-editor.tsx
"use client";

import { X } from "lucide-react";
import {
  type RefObject,
  useCallback,
  useId,
  useMemo,
  useRef,
  useState,
} from "react";
import {
  AlertDialog,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogTitle,
} from "@/components/ui/dialog";
import { DataTable } from "@/components/ui/yayaw-table/components/data-table";
import type { TableActions } from "@/components/ui/yayaw-table/providers/table-provider";
import type { DisplayModeRenderers } from "@/components/ui/yayaw-table/types/display-mode-renderer";
import type { DataTableTranslations } from "@/components/ui/yayaw-table/types/translations";
import type { TableViewConfig } from "@/components/ui/yayaw-table/types/view-types";
import type { ViewConfig } from "@/components/ui/yayaw-table/utils/view-config";
import {
  type DashboardViewEdit,
  dashboardViewEdited,
  dashboardViewEditorActions,
  dashboardViewEditorConfig,
  dashboardViewToApply,
  recordDashboardViewReport,
} from "./dashboard-editor-model";
import type { DashboardInlineView } from "./dashboard-schema";
import type { DashboardLabel, DashboardTableSource } from "./dashboard-widget";

export interface DashboardViewEditorProps {
  open: boolean;
  /** The source whose table is the editor. */
  source: DashboardTableSource;
  sourceId: string;
  /** Where the editor starts (`dashboardViewEditStart`). */
  start: DashboardViewEdit;
  /** Under the title: the widget or source edited. */
  subtitle: string;
  label: DashboardLabel;
  locale: string;
  renderers?: DisplayModeRenderers;
  getRowId?: (row: Record<string, unknown>) => string;
  translations?: DataTableTranslations;
  /** "Apply": the view to store in `widget.view` (`dashboardViewToApply`). */
  onApply: (view: DashboardInlineView) => void;
  onClose: () => void;
}

let sessions = 0;

/** One opening: a table of its own, started from the widget's view. */
function ViewEditorSession({
  closeRef,
  getRowId,
  label,
  locale,
  onApply,
  onClose,
  renderers,
  source,
  sourceId,
  start,
  subtitle,
  translations,
}: Omit<DashboardViewEditorProps, "open"> & {
  /** Escape and the dialog's own dismissals ask the session first. */
  closeRef: RefObject<() => void>;
}) {
  const [instanceId] = useState(() => {
    sessions += 1;
    return `view-editor-${sessions}`;
  });
  const [edit, setEdit] = useState(start);
  const [confirming, setConfirming] = useState(false);
  const descriptionId = useId();
  const edited = dashboardViewEdited(edit);
  const config = useMemo(
    () => dashboardViewEditorConfig(source.config),
    [source.config]
  );
  const actions = useMemo(
    () => dashboardViewEditorActions(source.actions) as TableActions,
    [source.actions]
  );
  const initialView = useMemo(
    () => ({ id: null, config: start.initial as TableViewConfig }),
    [start.initial]
  );
  const hostRenderers = source.tableProps?.displayModeRenderers;
  const displayModeRenderers = useMemo(
    () => ({ ...renderers, ...hostRenderers }),
    [hostRenderers, renderers]
  );
  const report = useCallback(
    (view: ViewConfig) =>
      setEdit((current) => recordDashboardViewReport(current, view)),
    []
  );
  const apply = () => {
    const view = dashboardViewToApply(edit);
    if (view) {
      onApply(view);
    }
    onClose();
  };
  const requestClose = () => {
    if (edited) {
      setConfirming(true);
    } else {
      onClose();
    }
  };
  closeRef.current = requestClose;
  return (
    <DialogContent
      aria-describedby={descriptionId}
      className="flex h-[calc(100dvh-2rem)] w-[calc(100vw-2rem)] max-w-none flex-col gap-0 overflow-hidden p-0 max-lg:h-dvh max-lg:w-dvw max-lg:rounded-none max-lg:ring-0 sm:max-w-none"
      data-view-editor=""
      showCloseButton={false}
    >
      <DialogDescription className="sr-only" id={descriptionId}>
        {label("viewEditorDescription")}
      </DialogDescription>
      <header
        className="flex min-h-14 shrink-0 flex-wrap items-center gap-x-4 gap-y-2 border-b px-3 py-2 sm:px-4"
        data-view-editor-bar=""
      >
        <div className="min-w-0 flex-1 basis-40">
          <DialogTitle className="truncate font-medium text-base">
            {label("viewEditorTitle")}
          </DialogTitle>
          <p className="truncate text-muted-foreground text-xs">{subtitle}</p>
        </div>
        <div className="ml-auto flex items-center gap-2">
          {edited ? (
            <span
              className="flex items-center gap-1.5 whitespace-nowrap text-muted-foreground text-xs"
              data-view-editor-status=""
            >
              <span
                aria-hidden="true"
                className="size-2 rounded-full bg-amber-500"
              />
              {label("unsavedChanges")}
            </span>
          ) : null}
          <Button
            data-view-editor-apply=""
            disabled={!edited}
            onClick={apply}
            size="sm"
            type="button"
          >
            {label("apply")}
          </Button>
          <Button
            aria-label={label("close")}
            onClick={requestClose}
            size="icon-sm"
            type="button"
            variant="ghost"
          >
            <X aria-hidden="true" />
          </Button>
        </div>
      </header>
      <div
        className="min-h-0 flex-1 overflow-auto p-3 sm:p-4"
        data-view-editor-table=""
      >
        <DataTable
          displayModeRenderers={displayModeRenderers}
          getRowId={source.tableProps?.getRowId ?? getRowId}
          getTableActions={() => actions}
          getTableConfig={() => config}
          initialView={initialView}
          instanceId={instanceId}
          locale={locale}
          onViewConfigChange={report}
          tableId={instanceId}
          tableType={sourceId}
          translations={source.tableProps?.translations ?? translations}
        />
      </div>
      <AlertDialog
        onOpenChange={(next) => {
          if (!next) {
            setConfirming(false);
          }
        }}
        open={confirming}
      >
        <AlertDialogContent data-view-editor-confirm="">
          <AlertDialogHeader>
            <AlertDialogTitle>{label("discardTitle")}</AlertDialogTitle>
            <AlertDialogDescription>
              {label("discardDescription")}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <Button
              onClick={() => setConfirming(false)}
              type="button"
              variant="outline"
            >
              {label("keepEditing")}
            </Button>
            <Button onClick={onClose} type="button" variant="destructive">
              {label("discard")}
            </Button>
            <Button onClick={apply} type="button">
              {label("applyAndClose")}
            </Button>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </DialogContent>
  );
}

/**
 * "Edit view…": a near full-screen dialog (full screen on phones) whose live
 * table of the source is the editor: its toolbar, filters, sort, columns,
 * display modes and their settings, without URL sync, saved views, selection
 * or record changes. "Apply" stores what the table reports; closing with
 * changes asks first.
 */
export function DashboardViewEditor({
  open,
  ...props
}: DashboardViewEditorProps) {
  const requestClose = useRef<() => void>(props.onClose);
  return (
    <Dialog
      disablePointerDismissal
      onOpenChange={(next) => {
        if (!next) {
          requestClose.current();
        }
      }}
      open={open}
    >
      {open ? <ViewEditorSession {...props} closeRef={requestClose} /> : null}
    </Dialog>
  );
}
