// src/components/ui/yayaw-table/components/tags/bulk-tags-dialog.tsx
"use client";

import { type QueryClient, useQueryClient } from "@tanstack/react-query";
import { useEffect, useId, useMemo, useState } from "react";
import type { Row } from "@/components/ui/yayaw-table/tanstack";
import { toast } from "sonner";
import { Button } from "@/src/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/src/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/src/components/ui/select";
import { buildBulkEditTargets } from "../../hooks/use-bulk-actions";
import type { TableMutationContext } from "../../providers/table-provider";
import {
  type TagCatalogApi,
  useTagCatalog,
} from "../../providers/tag-catalog-provider";
import {
  countTagLabel,
  formatTagLabel,
  planTagBulkUpdate,
  type ResolvedTagColumn,
  selectionTagUsage,
  type TagPatch,
} from "../../utils/tag-catalog";
import { bulkCompletion } from "../forms/bulk-form";
import { TagPicker } from "./tag-picker";

export type BulkTagsMode = "add" | "remove";

export interface BulkTagsTarget {
  id: string;
  /** The row's id in the table's selection, when it differs from `id`. */
  selectionId?: string;
  row: Record<string, unknown>;
}

interface MutationResult {
  success: boolean;
  error?: string;
  failedIds?: string[];
}

export interface BulkTagsActions {
  bulkUpdate?: (
    ids: string[],
    data: Record<string, unknown>
  ) => Promise<MutationResult>;
  update?: (
    id: string,
    data: Record<string, unknown>,
    context?: TableMutationContext
  ) => Promise<MutationResult>;
}

interface CachedPayload {
  data?: unknown[];
  [key: string]: unknown;
}

const rowIdOf = (row: unknown): string | undefined => {
  const record = row as Record<string, unknown>;
  const id = record?.id ?? record?._id;
  return id === null || id === undefined ? undefined : String(id);
};

/** Sets the tags field of cached rows by id; returns what restores them. */
function patchCachedRows(
  queryClient: QueryClient,
  tableId: string,
  field: string,
  values: Record<string, unknown>
): () => void {
  const snapshots = queryClient.getQueriesData<CachedPayload>({
    queryKey: ["tableData", tableId],
  });
  for (const [key, payload] of snapshots) {
    if (!Array.isArray(payload?.data)) {
      continue;
    }
    let changed = false;
    const data = payload.data.map((row) => {
      const id = rowIdOf(row);
      if (id === undefined || !(id in values)) {
        return row;
      }
      changed = true;
      return { ...(row as Record<string, unknown>), [field]: values[id] };
    });
    if (changed) {
      queryClient.setQueryData(key, { ...payload, data });
    }
  }
  return () => {
    for (const [key, payload] of snapshots) {
      queryClient.setQueryData(key, payload);
    }
  };
}

const errorText = (cause: unknown) =>
  cause instanceof Error ? cause.message : String(cause);

/**
 * The bulk menu's "Add tags" and "Remove tags" and their dialog, for tables
 * with tags columns holding lists, when every selected row can be edited
 * with `bulkUpdate` or `update`.
 */
export function useBulkTags<TData>({
  actions,
  allowBulkEdit,
  canEditRow,
  selectedRows,
}: {
  actions?: BulkTagsActions;
  allowBulkEdit?: boolean;
  canEditRow?: (row: Record<string, unknown>) => boolean;
  selectedRows: Row<TData>[];
}) {
  const catalog = useTagCatalog();
  const columns = useMemo(
    () => catalog?.columns.filter((column) => column.multiple) ?? [],
    [catalog]
  );
  const [open, setOpen] = useState<{
    mode: BulkTagsMode;
    targets: BulkTagsTarget[];
  } | null>(null);
  const available =
    columns.length > 0 &&
    allowBulkEdit !== false &&
    Boolean(actions?.bulkUpdate || actions?.update) &&
    selectedRows.every(
      (row) => canEditRow?.(row.original as Record<string, unknown>) !== false
    );
  const menuActions = useMemo(() => {
    if (!(available && catalog)) {
      return;
    }
    const start = (mode: BulkTagsMode) => () =>
      setOpen({ mode, targets: buildBulkEditTargets(selectedRows) });
    return {
      addLabel: catalog.labels.addTags,
      removeLabel: catalog.labels.removeTags,
      onAdd: start("add"),
      onRemove: start("remove"),
    };
  }, [available, catalog, selectedRows]);
  const dialog =
    catalog && columns.length
      ? {
          catalog,
          columns,
          mode: open?.mode ?? null,
          targets: open?.targets ?? [],
          onClose: () => setOpen(null),
        }
      : undefined;
  return { menuActions, dialog };
}

/** Runs a bulk tag plan; answers the ids that were not saved and the first error. */
async function runBulkTagPlan({
  actions,
  column,
  plan,
  targets,
}: {
  actions: BulkTagsActions;
  column: ResolvedTagColumn;
  plan: ReturnType<typeof planTagBulkUpdate>;
  targets: BulkTagsTarget[];
}): Promise<{ failed: string[]; error?: string }> {
  const failed: string[] = [];
  let error: string | undefined;
  for (const call of plan.calls) {
    if (actions.bulkUpdate) {
      try {
        const result = await actions.bulkUpdate(call.ids, call.patch);
        const progress = bulkCompletion(call.ids, result ?? { success: false });
        failed.push(...progress.remaining);
        if (!result?.success) {
          error ??= result?.error;
        }
      } catch (cause) {
        failed.push(...call.ids);
        error ??= errorText(cause);
      }
      continue;
    }
    // Without bulkUpdate, each row gets its resulting tags through update.
    for (const id of call.ids) {
      try {
        const row = targets.find((target) => target.id === id)?.row ?? {};
        const result = await actions.update?.(
          id,
          { [column.field]: plan.next[id] },
          { row: { ...row } }
        );
        if (!result?.success) {
          failed.push(id);
          error ??= result?.error;
        }
      } catch (cause) {
        failed.push(id);
        error ??= errorText(cause);
      }
    }
  }
  return { failed, error };
}

/**
 * Bulk "Add tags" and "Remove tags": pick tags (create them on the fly when
 * adding), then the selection is patched at once and saved through
 * `bulkUpdate` (see `planTagBulkUpdate`), or `update` row by row. Failed rows
 * are restored and stay selected.
 */
export function BulkTagsDialog({
  actions,
  catalog,
  columns,
  mode,
  onClose,
  onCompleted,
  tableId,
  targets,
}: {
  actions: BulkTagsActions;
  catalog: TagCatalogApi;
  /** Tags columns holding lists, the first one preselected. */
  columns: ResolvedTagColumn[];
  mode: BulkTagsMode | null;
  onClose: () => void;
  /** Rows saved (ids of `targets`); the table deselects them and reloads. */
  onCompleted: (
    ids: string[],
    targets: BulkTagsTarget[]
  ) => Promise<void> | void;
  tableId: string;
  targets: BulkTagsTarget[];
}) {
  const queryClient = useQueryClient();
  const labels = catalog.labels;
  const pickerId = useId();
  const [columnId, setColumnId] = useState(columns[0]?.columnId ?? "");
  const [picked, setPicked] = useState<string[]>([]);
  const open = mode !== null && targets.length > 0;
  useEffect(() => {
    if (open) {
      setPicked([]);
      setColumnId((current) =>
        columns.some((column) => column.columnId === current)
          ? current
          : (columns[0]?.columnId ?? "")
      );
    }
  }, [columns, open]);
  const column = columns.find((item) => item.columnId === columnId);
  const catalogTags = column ? catalog.tags(column.columnId) : [];
  const usage = useMemo(
    () =>
      column && mode === "remove"
        ? selectionTagUsage(
            targets.map((target) => target.row[column.field]),
            catalogTags
          )
        : [],
    [catalogTags, column, mode, targets]
  );
  const count = targets.length;
  const title =
    mode === "remove"
      ? countTagLabel(labels.removeTitleOne, labels.removeTitleMany, count)
      : countTagLabel(labels.addTitleOne, labels.addTitleMany, count);

  const apply = () => {
    if (!(column && mode && picked.length)) {
      return;
    }
    const patch: TagPatch =
      mode === "add" ? { add: picked } : { remove: picked };
    const plan = planTagBulkUpdate({
      rows: targets.map((target) => ({
        id: target.id,
        value: target.row[column.field],
      })),
      field: column.field,
      patch,
      mode: column.bulk,
    });
    const restore = patchCachedRows(
      queryClient,
      tableId,
      column.field,
      plan.next
    );
    const selectedTargets = [...targets];
    onClose();
    runBulkTagPlan({ actions, column, plan, targets: selectedTargets })
      .then(async ({ failed, error }) => {
        const completed = selectedTargets
          .map((target) => target.id)
          .filter((id) => !failed.includes(id));
        if (failed.length) {
          restore();
          toast.error(
            error ??
              formatTagLabel(labels.bulkFailed, { count: failed.length })
          );
        } else {
          toast.success(
            mode === "add"
              ? countTagLabel(labels.addedOne, labels.addedMany, count)
              : countTagLabel(labels.removedOne, labels.removedMany, count)
          );
        }
        await onCompleted(completed, selectedTargets);
      })
      .catch((cause) => {
        restore();
        toast.error(errorText(cause));
      });
  };

  return (
    <Dialog
      onOpenChange={(next) => {
        if (!next) {
          onClose();
        }
      }}
      open={open}
    >
      <DialogContent data-bulk-tags={mode ?? undefined}>
        <DialogHeader>
          <DialogTitle>{title}</DialogTitle>
          <DialogDescription>{labels.chooseTags}</DialogDescription>
        </DialogHeader>
        {columns.length > 1 ? (
          <div className="grid gap-1.5">
            <span className="font-medium text-sm" id={`${pickerId}-column`}>
              {labels.column}
            </span>
            <Select
              items={columns.map((item) => ({
                label: catalog.columnLabel(item.columnId),
                value: item.columnId,
              }))}
              onValueChange={(next) => {
                setColumnId(String(next));
                setPicked([]);
              }}
              value={columnId}
            >
              <SelectTrigger aria-labelledby={`${pickerId}-column`}>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {columns.map((item) => (
                  <SelectItem key={item.columnId} value={item.columnId}>
                    {catalog.columnLabel(item.columnId)}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        ) : null}
        {column && mode === "remove" && usage.length === 0 ? (
          <p className="text-muted-foreground text-sm">
            {labels.noSelectionTags}
          </p>
        ) : null}
        {column && !(mode === "remove" && usage.length === 0) ? (
          <TagPicker
            coloredTags={catalog.coloredTags(column.columnId)}
            counts={
              mode === "remove"
                ? Object.fromEntries(
                    usage.map(({ tag, count: uses }) => [tag.id, uses])
                  )
                : undefined
            }
            key={`${mode}:${column.columnId}`}
            label={labels.chooseTags}
            labels={labels}
            multiple
            onChange={(next) => setPicked(next as string[])}
            onCreate={
              mode === "add" && catalog.canCreate(column.columnId)
                ? (name) => catalog.create(column.columnId, name)
                : undefined
            }
            tags={
              mode === "remove" ? usage.map(({ tag }) => tag) : catalogTags
            }
            value={picked}
          />
        ) : null}
        <DialogFooter>
          <Button onClick={onClose} type="button" variant="outline">
            {labels.cancel}
          </Button>
          <Button
            disabled={!picked.length}
            onClick={apply}
            type="button"
            variant={mode === "remove" ? "destructive" : "default"}
          >
            {mode === "remove" ? labels.remove : labels.add}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

/** The bulk tags dialog of a table, when it has tags columns holding lists. */
export function BulkTagsLayer({
  actions,
  dialog,
  onCompleted,
  tableId,
}: {
  actions?: BulkTagsActions;
  dialog: ReturnType<typeof useBulkTags>["dialog"];
  onCompleted: (
    ids: string[],
    targets: BulkTagsTarget[]
  ) => Promise<void> | void;
  tableId: string;
}) {
  if (!dialog) {
    return null;
  }
  return (
    <BulkTagsDialog
      {...dialog}
      actions={actions ?? {}}
      onCompleted={onCompleted}
      tableId={tableId}
    />
  );
}

// packages/yayaw-table-vue/src/components/tags/BulkTagsDialog.vue
<script setup lang="ts">
import { X } from "lucide-vue-next";
import {
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogOverlay,
  DialogPortal,
  DialogRoot,
  DialogTitle,
} from "reka-ui";
import { computed, ref, useId, watch } from "vue";
import { bulkCompletion } from "../../bulk-form";
import { useTableContext } from "../../context";
import {
  countTagLabel,
  formatTagLabel,
  planTagBulkUpdate,
  selectionTagUsage,
  type TagPatch,
} from "../../tag-catalog";
import type { TableRecord } from "../../types";
import FieldSelect from "../forms/FieldSelect.vue";
import TagPicker from "./TagPicker.vue";

/**
 * Bulk "Add tags" and "Remove tags": pick tags (create them on the fly when
 * adding), then the selection is patched at once and saved through
 * `bulkUpdate` (see `planTagBulkUpdate`), or `update` row by row. Failed rows
 * are restored and stay selected.
 */
const props = defineProps<{
  mode: "add" | "remove" | null;
  /** The selected rows when the dialog opened. */
  rows: TableRecord[];
}>();
const emit = defineEmits<{ close: [] }>();
const context = useTableContext();
const catalog = context.tags;
const prefix = useId();
const columns = computed(
  () => catalog?.columns.filter((column) => column.multiple) ?? []
);
const columnId = ref(columns.value[0]?.columnId ?? "");
const picked = ref<string[]>([]);
const open = computed(() => props.mode !== null && props.rows.length > 0);
watch(open, (value) => {
  if (!value) return;
  picked.value = [];
  if (!columns.value.some((column) => column.columnId === columnId.value)) {
    columnId.value = columns.value[0]?.columnId ?? "";
  }
});
const labels = computed(() => catalog?.labels.value);
const column = computed(() =>
  columns.value.find((item) => item.columnId === columnId.value)
);
const catalogTags = computed(() =>
  column.value && catalog ? catalog.tags(column.value.columnId) : []
);
const usage = computed(() =>
  column.value && props.mode === "remove"
    ? selectionTagUsage(
        props.rows.map((row) => row[column.value?.field ?? ""]),
        catalogTags.value
      )
    : []
);
const counts = computed(() =>
  props.mode === "remove"
    ? Object.fromEntries(usage.value.map(({ tag, count }) => [tag.id, count]))
    : undefined
);
const title = computed(() => {
  if (!labels.value) return "";
  const count = props.rows.length;
  return props.mode === "remove"
    ? countTagLabel(labels.value.removeTitleOne, labels.value.removeTitleMany, count)
    : countTagLabel(labels.value.addTitleOne, labels.value.addTitleMany, count);
});
const createTag = computed(() => {
  const current = column.value;
  if (!(catalog && current && props.mode === "add" && catalog.canCreate(current.columnId))) {
    return undefined;
  }
  return (name: string) => catalog.create(current.columnId, name);
});

const errorText = (cause: unknown) =>
  cause instanceof Error ? cause.message : String(cause);

/** Runs a plan; answers the ids that were not saved and the first error. */
const runPlan = async (
  plan: ReturnType<typeof planTagBulkUpdate>,
  field: string,
  rows: TableRecord[]
): Promise<{ failed: string[]; error?: string }> => {
  const actions = context.actions.value;
  const failed: string[] = [];
  let error: string | undefined;
  for (const call of plan.calls) {
    if (actions?.bulkUpdate) {
      try {
        const result = await actions.bulkUpdate(call.ids, call.patch);
        failed.push(...bulkCompletion(call.ids, result ?? { success: false }).remaining);
        if (!result?.success) error ??= result?.error;
      } catch (cause) {
        failed.push(...call.ids);
        error ??= errorText(cause);
      }
      continue;
    }
    // Without bulkUpdate, each row gets its resulting tags through update.
    for (const id of call.ids) {
      try {
        const row = rows.find((item) => context.getRowId(item) === id) ?? {};
        const result = await actions?.update?.(id, { [field]: plan.next[id] }, { row: { ...row } });
        if (!result?.success) {
          failed.push(id);
          error ??= result?.error;
        }
      } catch (cause) {
        failed.push(id);
        error ??= errorText(cause);
      }
    }
  }
  return { failed, error };
};

const apply = (): void => {
  const current = column.value;
  const mode = props.mode;
  const words = labels.value;
  if (!(current && mode && words && picked.value.length)) return;
  const rows = [...props.rows];
  const patch: TagPatch = mode === "add" ? { add: picked.value } : { remove: picked.value };
  const plan = planTagBulkUpdate({
    rows: rows.map((row) => ({ id: context.getRowId(row), value: row[current.field] })),
    field: current.field,
    patch,
    mode: current.bulk,
  });
  // The loaded rows show the result at once; failures restore them.
  const previous = new Map<TableRecord, unknown>();
  for (const row of context.data.rows.value) {
    const next = plan.next[context.getRowId(row)];
    if (next) {
      previous.set(row, row[current.field]);
      row[current.field] = next;
    }
  }
  const restore = () => {
    for (const [row, value] of previous) row[current.field] = value;
  };
  emit("close");
  runPlan(plan, current.field, rows)
    .then(async ({ failed, error }) => {
      const ids = rows.map((row) => context.getRowId(row));
      const completed = new Set(ids.filter((id) => !failed.includes(id)));
      if (failed.length) {
        restore();
        context.status.value = {
          type: "error",
          message: error ?? formatTagLabel(words.bulkFailed, { count: failed.length }),
        };
      } else {
        context.status.value = {
          type: "success",
          message:
            mode === "add"
              ? countTagLabel(words.addedOne, words.addedMany, rows.length)
              : countTagLabel(words.removedOne, words.removedMany, rows.length),
        };
      }
      context.selection.value = Object.fromEntries(
        Object.entries(context.selection.value).filter(
          ([id, value]) => value && !completed.has(id)
        )
      );
      await context.refresh();
    })
    .catch((cause: unknown) => {
      restore();
      context.status.value = { type: "error", message: errorText(cause) };
    });
};
</script>

<template>
  <DialogRoot v-if="catalog && labels" :open="open" @update:open="!$event && emit('close')">
    <DialogPortal>
      <DialogOverlay class="yayaw-tags-overlay" />
      <DialogContent class="yayaw-tags-dialog" :data-bulk-tags="mode ?? undefined">
        <header class="yayaw-tags-dialog-header">
          <DialogTitle as="h2">{{ title }}</DialogTitle>
          <DialogDescription>{{ labels.chooseTags }}</DialogDescription>
        </header>
        <DialogClose class="yayaw-icon-button yayaw-tags-dialog-close" :aria-label="labels.close">
          <X :size="16" aria-hidden="true" />
        </DialogClose>
        <div v-if="columns.length > 1" class="yayaw-tags-field">
          <span :id="`${prefix}-column`" class="yayaw-label">{{ labels.column }}</span>
          <FieldSelect
            :id="`${prefix}-column-select`"
            :model-value="columnId"
            :options="columns.map((item) => ({ value: item.columnId, label: catalog!.columnLabel(item.columnId) }))"
            :placeholder="labels.column"
            :labelled-by="`${prefix}-column`"
            @update:model-value="columnId = String($event); picked = []"
          />
        </div>
        <p v-if="column && mode === 'remove' && !usage.length" class="yayaw-help">{{ labels.noSelectionTags }}</p>
        <TagPicker
          v-else-if="column"
          :key="`${mode}:${column.columnId}`"
          :model-value="picked"
          multiple
          :tags="mode === 'remove' ? usage.map(({ tag }) => tag) : catalogTags"
          :counts="counts"
          :labels="labels"
          :label="labels.chooseTags"
          :colored-tags="catalog.coloredTags(column.columnId)"
          :create="createTag"
          @update:model-value="picked = $event as string[]"
        />
        <div class="yayaw-tags-actions">
          <button type="button" class="yayaw-button yayaw-button-outline" @click="emit('close')">{{ labels.cancel }}</button>
          <button
            type="button"
            class="yayaw-button"
            :class="{ 'yayaw-button-danger': mode === 'remove' }"
            :disabled="!picked.length"
            @click="apply"
          >
            {{ mode === "remove" ? labels.remove : labels.add }}
          </button>
        </div>
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
</template>
