// packages/yayaw-table-vue/src/components/table/TableEmptyState.vue
<script setup lang="ts">
import { Inbox, RotateCcw, SearchX } from "lucide-vue-next";
import { computed } from "vue";
import { useTableContext } from "../../context";
import Empty from "../empty/Empty.vue";
import EmptyContent from "../empty/EmptyContent.vue";
import EmptyDescription from "../empty/EmptyDescription.vue";
import EmptyHeader from "../empty/EmptyHeader.vue";
import EmptyMedia from "../empty/EmptyMedia.vue";
import EmptyTitle from "../empty/EmptyTitle.vue";

const context = useTableContext();
const hasActiveFilters = computed(() =>
  context.state.search.value.trim().length > 0 ||
  context.state.filters.value.length > 0 ||
  context.state.advancedFilters.value.filters.some((filter) => filter.isActive !== false)
);
const title = computed(() => context.config.table.emptyState?.title ?? (
  hasActiveFilters.value ? context.translations.value.noResults : context.translations.value.noDataAvailable
));
const description = computed(() => context.config.table.emptyState?.description ?? (
  hasActiveFilters.value ? context.translations.value.noResultsDescription : undefined
));
</script>

<template>
  <Empty>
    <EmptyHeader>
      <EmptyMedia variant="icon">
        <SearchX v-if="hasActiveFilters" aria-hidden="true" />
        <Inbox v-else aria-hidden="true" />
      </EmptyMedia>
      <EmptyTitle>{{ title }}</EmptyTitle>
      <EmptyDescription v-if="description">{{ description }}</EmptyDescription>
    </EmptyHeader>
    <EmptyContent v-if="hasActiveFilters">
      <button
        type="button"
        class="yayaw-button yayaw-button-outline yayaw-empty-reset"
        @click="context.state.resetFilters()"
      >
        <RotateCcw :size="16" aria-hidden="true" />
        {{ context.translations.value.clearFilters }}
      </button>
    </EmptyContent>
  </Empty>
</template>

// registry/default/ui/yayaw-table/components/table-empty-state.tsx
"use client";

import { Inbox, RotateCcw, SearchX } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "@/components/ui/empty";

/** Shared by the table, Kanban, and Gallery empty states. */
export function TableEmptyStateContent({
  clearFiltersLabel,
  description,
  onClearFilters,
  title,
}: {
  clearFiltersLabel: string;
  description?: string;
  onClearFilters?: () => void;
  title: string;
}) {
  const Icon = onClearFilters ? SearchX : Inbox;
  return (
    <Empty className="min-h-40 px-4 py-10">
      <EmptyHeader>
        <EmptyMedia variant="icon">
          <Icon aria-hidden="true" />
        </EmptyMedia>
        <EmptyTitle>{title}</EmptyTitle>
        {description ? (
          <EmptyDescription>{description}</EmptyDescription>
        ) : null}
      </EmptyHeader>
      {onClearFilters ? (
        <EmptyContent>
          <Button
            onClick={onClearFilters}
            size="sm"
            type="button"
            variant="outline"
          >
            <RotateCcw aria-hidden="true" />
            {clearFiltersLabel}
          </Button>
        </EmptyContent>
      ) : null}
    </Empty>
  );
}
