// packages/yayaw-table-vue/src/components/details/DetailValue.vue
<script setup lang="ts">
import { computed } from "vue";
import { ArrowUpRight, FileText } from "lucide-vue-next";
import { detailDisplay, type DetailField, type DetailLabels, type DetailRecord } from "../../record-details";

const props = defineProps<{ field: DetailField; value: unknown; row: DetailRecord; locale: string; labels: DetailLabels }>();
const display = computed(() => detailDisplay(props.field, props.value, props.row, props.locale, props.labels));
</script>

<template>
  <span v-if="display.kind === 'empty'" class="yayaw-detail-empty">{{ display.text }}</span>
  <pre v-else-if="display.kind === 'code'" class="yayaw-detail-code"><code>{{ display.text }}</code></pre>
  <span v-else-if="display.kind === 'badges'" class="yayaw-detail-badges"><span v-for="item in display.items" :key="item.id" class="yayaw-detail-badge">{{ item.text }}</span></span>
  <a v-else-if="display.kind === 'link'" :href="display.href" target="_blank" rel="noopener noreferrer" class="yayaw-detail-link">{{ display.text }}<ArrowUpRight :size="14" aria-hidden="true" /></a>
  <a v-else-if="display.kind === 'image'" :href="display.href" target="_blank" rel="noopener noreferrer"><img :src="display.href" :alt="field.label" class="yayaw-detail-image" loading="lazy" /></a>
  <ul v-else-if="display.kind === 'items'" class="yayaw-detail-items"><li v-for="item in display.items" :key="item.id"><FileText :size="16" aria-hidden="true" /><a v-if="item.href" :href="item.href" target="_blank" rel="noopener noreferrer">{{ item.text }}</a><span v-else>{{ item.text }}</span></li></ul>
  <span v-else class="yayaw-detail-text">{{ display.text }}</span>
</template>

// src/components/ui/yayaw-table/components/details/detail-value.tsx
"use client";

import { ArrowUpRight, FileText } from "lucide-react";
import {
  type DetailField,
  type DetailLabels,
  type DetailRecord,
  detailDisplay,
} from "../../utils/record-details";

export function DetailValue({
  field,
  value,
  row,
  locale,
  labels,
}: {
  field: DetailField;
  value: unknown;
  row: DetailRecord;
  locale: string;
  labels: DetailLabels;
}) {
  const display = detailDisplay(field, value, row, locale, labels);
  switch (display.kind) {
    case "empty":
      return <span className="yayaw-detail-empty">{display.text}</span>;
    case "code":
      return (
        <pre className="yayaw-detail-code">
          <code>{display.text}</code>
        </pre>
      );
    case "badges":
      return (
        <span className="yayaw-detail-badges">
          {display.items?.map((item) => (
            <span className="yayaw-detail-badge" key={item.id}>
              {item.text}
            </span>
          ))}
        </span>
      );
    case "link":
      return (
        <a
          className="yayaw-detail-link"
          href={display.href}
          rel="noopener noreferrer"
          target="_blank"
        >
          {display.text}
          <ArrowUpRight aria-hidden="true" size={14} />
        </a>
      );
    case "image":
      return (
        <a href={display.href} rel="noopener noreferrer" target="_blank">
          <img
            alt={field.label}
            className="yayaw-detail-image"
            height={160}
            loading="lazy"
            src={display.href}
            width={290}
          />
        </a>
      );
    case "items":
      return (
        <ul className="yayaw-detail-items">
          {display.items?.map((item) => (
            <li key={item.id}>
              <FileText aria-hidden="true" size={16} />
              {item.href ? (
                <a href={item.href} rel="noopener noreferrer" target="_blank">
                  {item.text}
                </a>
              ) : (
                <span>{item.text}</span>
              )}
            </li>
          ))}
        </ul>
      );
    default:
      return <span className="yayaw-detail-text">{display.text}</span>;
  }
}
