// src/components/ui/yayaw-table/components/list-view.tsx
"use client";

import {
  type KeyboardEvent,
  type MouseEvent,
  type PointerEvent,
  type ReactNode,
  useMemo,
  useState,
} from "react";
import { GripVertical } from "lucide-react";
import { cn } from "@/lib/utils";
import type { TableCatalogueColumnConfig } from "../hooks/use-table-config";
import type { Cell, Row, Table as TanStackTable } from "../tanstack";
import { flexRender } from "../tanstack";
import type { TableListConfig } from "../types/display-types";
import { shouldActivateCardFromKeyboard } from "../utils/card-interaction";
import {
  moveInOrder,
  REORDER_ROW_ATTRIBUTE,
  reorderRowAt,
} from "../utils/manual-order";
import {
  isSelectionModifiedClick,
  selectRowWithRange,
} from "../utils/row-selection-interaction";
import {
  createGalleryGroups,
  resolveGalleryPropertyColumnIds,
  resolveGalleryTitleColumnId,
} from "./gallery-view";

type ListCell<TData extends Record<string, unknown>> = Cell<TData, unknown>;

interface DataTableListViewProps<TData extends Record<string, unknown>> {
  className?: string;
  columnDefinitions: TableCatalogueColumnConfig[];
  config?: TableListConfig;
  emptyState: ReactNode;
  groupBy?: string;
  groupLabel?: string;
  isRowActive?: (row: Row<TData>) => boolean;
  isRowClickable?: (row: Row<TData>) => boolean;
  onRowClick?: (row: Row<TData>, event: MouseEvent<HTMLElement>) => void;
  /** Present when the view is sorted by its manual order and may be edited. */
  onReorder?: (row: Row<TData>, neighbours: ListNeighbours<TData>) => void;
  canReorderRow?: (row: Row<TData>) => boolean;
  reorderLabel?: string;
  table: TanStackTable<TData>;
}

export interface ListNeighbours<TData extends Record<string, unknown>> {
  previous?: Row<TData>;
  next?: Row<TData>;
}

interface ListReorder {
  draggable: boolean;
  isDragging: boolean;
  isTarget: boolean;
  label?: string;
  onPointerCancel: () => void;
  onPointerDown: (event: PointerEvent<HTMLButtonElement>) => void;
  onPointerMove: (event: PointerEvent<HTMLButtonElement>) => void;
  onPointerUp: () => void;
  onMove: (offset: number) => void;
}

interface ListItemProps<TData extends Record<string, unknown>> {
  isActive: boolean;
  isClickable: boolean;
  onRowClick?: (row: Row<TData>, event: MouseEvent<HTMLElement>) => void;
  propertyCells: ListCell<TData>[];
  propertyLabels: Map<string, string>;
  reorder?: ListReorder;
  row: Row<TData>;
  showLabels: boolean;
  table: TanStackTable<TData>;
  titleColumnId?: string;
}

const renderCell = <TData extends Record<string, unknown>>(
  cell: ListCell<TData>
) => flexRender(cell.column.columnDef.cell, cell.getContext());

/** The configured properties, in configured order, without the title or the grouped column. */
export function resolveListPropertyColumnIds({
  columnDefinitions,
  config,
  groupBy,
  titleColumnId,
}: {
  columnDefinitions: TableCatalogueColumnConfig[];
  config?: TableListConfig;
  groupBy?: string;
  titleColumnId?: string;
}): string[] {
  return resolveGalleryPropertyColumnIds({
    columnDefinitions,
    config,
    titleColumnId,
  }).filter((columnId) => columnId !== groupBy);
}

function DataTableListItem<TData extends Record<string, unknown>>({
  isActive,
  isClickable,
  onRowClick,
  propertyCells,
  propertyLabels,
  reorder,
  row,
  showLabels,
  table,
  titleColumnId,
}: ListItemProps<TData>) {
  const handleReorderKey = (event: KeyboardEvent<HTMLElement>) => {
    if (!(reorder?.draggable && event.altKey)) {
      return false;
    }
    if (event.key !== "ArrowUp" && event.key !== "ArrowDown") {
      return false;
    }
    event.preventDefault();
    reorder.onMove(event.key === "ArrowUp" ? -1 : 1);
    return true;
  };
  const cells = row.getVisibleCells() as ListCell<TData>[];
  const selectionCell = cells.find((cell) => cell.column.id === "select");
  const actionsCell = cells.find((cell) => cell.column.id === "actions");
  const titleCell = cells.find((cell) => cell.column.id === titleColumnId);
  const shouldSelect = (event: MouseEvent<HTMLElement>) =>
    Boolean(selectionCell) &&
    row.getCanSelect() &&
    isSelectionModifiedClick(event) &&
    !(
      event.target instanceof Element &&
      event.target.closest('[data-column-id="select"]')
    );
  const handleSelectionClick = (event: MouseEvent<HTMLElement>) => {
    if (!shouldSelect(event)) {
      return;
    }
    event.preventDefault();
    event.stopPropagation();
    selectRowWithRange({
      element: event.currentTarget,
      isSelected: event.shiftKey || !row.getIsSelected(),
      row,
      shiftKey: event.shiftKey,
      table,
    });
  };

  return (
    <li
      className={cn(
        "border-b last:border-b-0",
        (isActive || row.getIsSelected()) && "bg-primary/5",
        reorder?.isDragging && "opacity-50",
        reorder?.isTarget && "shadow-[inset_0_2px_0_0_var(--primary)]"
      )}
      data-active={isActive ? "true" : undefined}
      {...(reorder ? { [REORDER_ROW_ATTRIBUTE]: row.id } : {})}
    >
      {/* biome-ignore lint/a11y: a clickable line keeps nested selection/actions valid, takes the button role and provides keyboard activation. */}
      <div
        className={cn(
          "flex min-h-10 items-center gap-3 px-3 py-1.5",
          isClickable && "cursor-pointer hover:bg-muted/40"
        )}
        onClick={isClickable ? (event) => onRowClick?.(row, event) : undefined}
        onClickCapture={handleSelectionClick}
        onKeyDown={
          isClickable || reorder?.draggable
            ? (event) => {
                if (handleReorderKey(event)) {
                  return;
                }
                if (isClickable && shouldActivateCardFromKeyboard(event)) {
                  event.preventDefault();
                  event.currentTarget.click();
                }
              }
            : undefined
        }
        onMouseDownCapture={(event) => {
          if (shouldSelect(event)) {
            event.preventDefault();
          }
        }}
        role={isClickable ? "button" : undefined}
        tabIndex={isClickable || reorder?.draggable ? 0 : undefined}
      >
        {reorder?.draggable ? (
          <button
            aria-label={reorder.label}
            className="-ml-1 shrink-0 cursor-grab touch-none rounded p-1 text-muted-foreground hover:bg-muted active:cursor-grabbing"
            onClick={(event) => event.stopPropagation()}
            onPointerCancel={reorder.onPointerCancel}
            onPointerDown={reorder.onPointerDown}
            onPointerMove={reorder.onPointerMove}
            onPointerUp={reorder.onPointerUp}
            title={reorder.label}
            type="button"
          >
            <GripVertical aria-hidden="true" className="size-4" />
          </button>
        ) : null}
        {selectionCell ? (
          <div className="shrink-0" data-column-id="select">
            {renderCell(selectionCell)}
          </div>
        ) : null}
        <div className="min-w-0 flex-1 truncate font-medium text-sm">
          {titleCell ? renderCell(titleCell) : row.id}
        </div>
        {propertyCells.length > 0 ? (
          <dl className="flex min-w-0 shrink items-center justify-end gap-3 overflow-hidden text-muted-foreground text-xs">
            {propertyCells.map((cell) => (
              <div className="flex min-w-0 items-center gap-1" key={cell.id}>
                <dt className={showLabels ? "shrink-0" : "sr-only"}>
                  {propertyLabels.get(cell.column.id) ?? cell.column.id}
                </dt>
                <dd className="min-w-0 truncate">{renderCell(cell)}</dd>
              </div>
            ))}
          </dl>
        ) : null}
        {actionsCell ? (
          <div className="shrink-0" data-column-id="actions">
            {renderCell(actionsCell)}
          </div>
        ) : null}
      </div>
    </li>
  );
}

/** Rows as compact lines: a title, then the chosen properties. */
export function DataTableListView<TData extends Record<string, unknown>>({
  className,
  columnDefinitions,
  config,
  emptyState,
  groupBy = "",
  groupLabel,
  isRowActive,
  isRowClickable,
  onRowClick,
  onReorder,
  canReorderRow,
  reorderLabel,
  table,
}: DataTableListViewProps<TData>) {
  const hasTableGrouping = table.store.state.grouping.length > 0;
  const loadedRows = (
    hasTableGrouping
      ? table.getPreGroupedRowModel().rows
      : table.getRowModel().rows
  ) as Row<TData>[];
  // A move shows at once; the next server result replaces it.
  const [pending, setPending] = useState<{
    ids: string[];
    rows: Row<TData>[];
  } | null>(null);
  const [draggedId, setDraggedId] = useState<string | null>(null);
  const [targetId, setTargetId] = useState<string | null>(null);
  // A pending order only applies to the rows it was made from.
  const pendingOrder = pending?.rows === loadedRows ? pending.ids : null;
  const setPendingOrder = (ids: string[]) =>
    setPending({ ids, rows: loadedRows });
  const rows = useMemo(() => {
    if (!pendingOrder) {
      return loadedRows;
    }
    const position = new Map(pendingOrder.map((id, index) => [id, index]));
    return [...loadedRows].sort(
      (left, right) =>
        (position.get(left.id) ?? 0) - (position.get(right.id) ?? 0)
    );
  }, [loadedRows, pendingOrder]);
  const titleColumnId = resolveGalleryTitleColumnId({
    columnDefinitions,
    config,
  });
  const propertyColumnIds = resolveListPropertyColumnIds({
    columnDefinitions,
    config,
    groupBy,
    titleColumnId,
  });
  const propertyLabels = useMemo(
    () =>
      new Map(
        columnDefinitions.map((definition) => [
          definition.id,
          definition.header ?? definition.id,
        ])
      ),
    [columnDefinitions]
  );
  const groups = useMemo(
    () => createGalleryGroups({ groupBy, rows }),
    [groupBy, rows]
  );

  if (rows.length === 0) {
    return emptyState ? (
      <div className="rounded-md border">{emptyState}</div>
    ) : null;
  }

  const groupOf = (row: Row<TData>) =>
    groups.find((group) => group.rows.some((item) => item.id === row.id));
  const moveRow = (row: Row<TData>, toIndexInGroup: number) => {
    const group = groupOf(row);
    if (!(group && onReorder)) {
      return;
    }
    const moved = moveInOrder(
      group.rows.map((item) => item.id),
      row.id,
      toIndexInGroup
    );
    if (!moved) {
      return;
    }
    const byId = new Map(rows.map((item) => [item.id, item]));
    const groupIds = new Set(moved.ids);
    const others = rows.map((item) => item.id).filter((id) => !groupIds.has(id));
    const firstIndex = rows.findIndex((item) => groupIds.has(item.id));
    others.splice(Math.max(0, firstIndex), 0, ...moved.ids);
    setPendingOrder(others);
    onReorder(row, {
      previous: moved.previousId ? byId.get(moved.previousId) : undefined,
      next: moved.nextId ? byId.get(moved.nextId) : undefined,
    });
  };
  const reorderFor = (row: Row<TData>): ListReorder | undefined => {
    if (!onReorder) {
      return;
    }
    const group = groupOf(row);
    const index = group?.rows.findIndex((item) => item.id === row.id) ?? -1;
    return {
      draggable: canReorderRow?.(row) ?? true,
      isDragging: draggedId === row.id,
      isTarget: Boolean(draggedId) && targetId === row.id && draggedId !== row.id,
      label: reorderLabel,
      onPointerDown: (event) => {
        event.preventDefault();
        event.currentTarget.setPointerCapture?.(event.pointerId);
        setDraggedId(row.id);
      },
      onPointerMove: (event) => {
        if (draggedId !== row.id) {
          return;
        }
        const id = reorderRowAt(event.clientX, event.clientY);
        const target = rows.find((item) => item.id === id);
        // Moves stay within a group: the manual order never edits the grouped value.
        setTargetId(target && groupOf(target) === group ? target.id : null);
      },
      onPointerUp: () => {
        const target = group?.rows.findIndex((item) => item.id === targetId);
        setDraggedId(null);
        setTargetId(null);
        if (draggedId === row.id && target !== undefined && target >= 0) {
          moveRow(row, target);
        }
      },
      onPointerCancel: () => {
        setDraggedId(null);
        setTargetId(null);
      },
      onMove: (offset) => moveRow(row, index + offset),
    };
  };

  const renderRow = (row: Row<TData>) => {
    const cellById = new Map(
      (row.getVisibleCells() as ListCell<TData>[]).map((cell) => [
        cell.column.id,
        cell,
      ])
    );
    return (
      <DataTableListItem
        isActive={isRowActive?.(row) ?? false}
        isClickable={isRowClickable?.(row) ?? false}
        key={row.id}
        onRowClick={onRowClick}
        propertyCells={propertyColumnIds.flatMap((id) => {
          const cell = cellById.get(id);
          return cell ? [cell] : [];
        })}
        propertyLabels={propertyLabels}
        reorder={reorderFor(row)}
        row={row}
        showLabels={config?.showCardLabels === true}
        table={table}
        titleColumnId={titleColumnId}
      />
    );
  };

  return (
    <div className={cn("rounded-md border bg-background", className)}>
      {groupBy ? (
        groups.map((group) => (
          <section className="border-b last:border-b-0" key={group.id}>
            <div className="flex items-center justify-between gap-3 bg-muted/30 px-3 py-2">
              <h3 className="min-w-0 truncate font-medium text-sm">
                {groupLabel ? (
                  <span className="text-muted-foreground">{groupLabel}: </span>
                ) : null}
                {group.label}
              </h3>
              <span className="rounded-full bg-muted px-2 py-0.5 text-muted-foreground text-xs">
                {group.rows.length}
              </span>
            </div>
            <ul>{group.rows.map(renderRow)}</ul>
          </section>
        ))
      ) : (
        <ul>{rows.map(renderRow)}</ul>
      )}
    </div>
  );
}

// packages/yayaw-table-vue/src/components/list/ListView.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { useCardRows } from "../../composables/use-card-rows";
import { useListSettings } from "../../composables/use-list-settings";
import { displayCellValue } from "../../core";
import { GripVertical } from "lucide-vue-next";
import { isManualOrder, moveInOrder, REORDER_ROW_ATTRIBUTE, reorderRowAt } from "../../manual-order";
import { selectionAfterClick } from "../../selection-interaction";
import type { ColumnDefinition, TableRecord } from "../../types";
import TableCheckbox from "../controls/TableCheckbox.vue";
import CellRenderer from "../table/CellRenderer.vue";
import RowActions from "../table/RowActions.vue";
import TableEmptyState from "../table/TableEmptyState.vue";

const EMPTY_GROUP_LABEL = "No value";
const { context, translate, columns, titleColumn, propertyIds, showLabels } =
  useListSettings();
const loadedRows = useCardRows();
// A move shows at once; the next server result replaces it.
const pendingOrder = ref<string[] | null>(null);
watch(loadedRows, () => {
  pendingOrder.value = null;
});
const rows = computed(() => {
  const order = pendingOrder.value;
  if (!order) {
    return loadedRows.value;
  }
  const position = new Map(order.map((id, index) => [id, index]));
  return [...loadedRows.value].sort(
    (left, right) =>
      (position.get(context.getRowId(left)) ?? 0) -
      (position.get(context.getRowId(right)) ?? 0)
  );
});
const column = (id: string): ColumnDefinition | undefined =>
  columns.value.find((item) => item.id === id);
const value = (row: TableRecord, id: string): unknown =>
  column(id)?.accessorFn
    ? column(id)?.accessorFn?.(row)
    : row[column(id)?.accessorKey ?? id];
const groupBy = computed(() => context.state.grouping.value[0] ?? "");
const properties = computed(() =>
  propertyIds.value.filter(
    (id) => id !== titleColumn.value && id !== groupBy.value && column(id)
  )
);
const sections = computed(() => {
  if (!groupBy.value) {
    return [{ id: "all", label: "", rows: rows.value }];
  }
  const groups = new Map<string, TableRecord[]>();
  for (const row of rows.value) {
    const raw = value(row, groupBy.value);
    const label =
      raw === null || raw === undefined || raw === ""
        ? EMPTY_GROUP_LABEL
        : String(raw);
    groups.set(label, [...(groups.get(label) ?? []), row]);
  }
  return [...groups].map(([label, sectionRows]) => ({
    id: label,
    label,
    rows: sectionRows,
  }));
});
const groupHeader = computed(
  () => column(groupBy.value)?.header ?? groupBy.value
);
const orderedRows = computed(() =>
  sections.value.flatMap((section) => section.rows)
);
const checkboxShift = ref(false);
const canReorder = computed(
  () =>
    context.config.table.manualOrder === true &&
    typeof context.actions.value?.reorder === "function" &&
    context.config.table.allowEdit !== false &&
    isManualOrder(context.state.sorting.value)
);
const canReorderRow = (row: TableRecord): boolean =>
  canReorder.value && context.config.table.canEditRow?.(row) !== false;
const reorderHint = computed(() =>
  translate("reorderHint", "Drag, or press Alt+Arrow keys, to reorder")
);
const dragged = ref<TableRecord>();
const target = ref<TableRecord>();
const sectionOf = (row: TableRecord) =>
  sections.value.find((section) => section.rows.includes(row));
const startDrag = (row: TableRecord, event: PointerEvent): void => {
  event.preventDefault();
  (event.currentTarget as Element).setPointerCapture?.(event.pointerId);
  dragged.value = row;
};
const trackDrag = (event: PointerEvent): void => {
  const row = dragged.value;
  if (!row) {
    return;
  }
  const id = reorderRowAt(event.clientX, event.clientY);
  const over = rows.value.find((item) => context.getRowId(item) === id);
  // Moves stay within a group: the manual order never edits the grouped value.
  target.value = over && sectionOf(over) === sectionOf(row) ? over : undefined;
};
const endDrag = async (): Promise<void> => {
  const row = dragged.value;
  const over = target.value;
  dragged.value = undefined;
  target.value = undefined;
  const section = over && sectionOf(over);
  if (row && over && row !== over && section) {
    await moveRow(row, section.rows.indexOf(over));
  }
};
const cancelDrag = (): void => {
  dragged.value = undefined;
  target.value = undefined;
};
const moveRow = async (row: TableRecord, toIndex: number): Promise<void> => {
  const section = sectionOf(row);
  const reorder = context.actions.value?.reorder;
  if (!(section && reorder && canReorderRow(row))) {
    return;
  }
  const moved = moveInOrder(
    section.rows.map((item) => context.getRowId(item)),
    context.getRowId(row),
    toIndex
  );
  if (!moved) {
    return;
  }
  const sectionIds = new Set(moved.ids);
  const others = rows.value
    .map((item) => context.getRowId(item))
    .filter((id) => !sectionIds.has(id));
  const first = rows.value.findIndex((item) => sectionIds.has(context.getRowId(item)));
  others.splice(Math.max(0, first), 0, ...moved.ids);
  pendingOrder.value = others;
  try {
    const result = await reorder(
      {
        viewId: context.state.activeViewId.value ?? null,
        id: context.getRowId(row),
        previousId: moved.previousId,
        nextId: moved.nextId,
      },
      { row }
    );
    if (!result.success) {
      throw new Error(result.error ?? "Reorder failed");
    }
  } catch (cause) {
    context.status.value = {
      type: "error",
      message: cause instanceof Error ? cause.message : String(cause),
    };
  }
  await context.refresh();
};
const reorderKey = async (row: TableRecord, event: KeyboardEvent): Promise<boolean> => {
  if (!(event.altKey && canReorderRow(row) && ["ArrowUp", "ArrowDown"].includes(event.key))) {
    return false;
  }
  event.preventDefault();
  const section = sectionOf(row);
  if (section) {
    await moveRow(row, section.rows.indexOf(row) + (event.key === "ArrowUp" ? -1 : 1));
  }
  return true;
};
const onKeydown = async (row: TableRecord, event: KeyboardEvent): Promise<void> => {
  if (!(await reorderKey(row, event))) {
    activate(row, event);
  }
};
const selectable = (row: TableRecord): boolean =>
  context.config.table.canSelectRow?.(row) !== false;
const toggleSelection = (
  row: TableRecord,
  checked: boolean,
  shift = false
): void => {
  if (!selectable(row)) {
    return;
  }
  context.selection.value = selectionAfterClick({
    scope: context.selection,
    rows: orderedRows.value
      .filter(selectable)
      .map((item) => ({ id: context.getRowId(item) })),
    selection: context.selection.value,
    id: context.getRowId(row),
    selected: checked,
    shift,
    multiple: context.config.table.enableMultiRowSelection,
  });
};
const captureSelection = (row: TableRecord, event: MouseEvent): void => {
  if (
    !(event.shiftKey || event.metaKey || event.ctrlKey) ||
    !context.config.table.enableRowSelection ||
    (event.target as Element).closest(".yayaw-list-select")
  ) {
    return;
  }
  event.preventDefault();
  event.stopPropagation();
  toggleSelection(
    row,
    event.shiftKey || !context.selection.value[context.getRowId(row)],
    event.shiftKey
  );
};
const activate = (row: TableRecord, event: MouseEvent | KeyboardEvent): void => {
  if (
    event instanceof KeyboardEvent &&
    (event.target !== event.currentTarget || !["Enter", " "].includes(event.key))
  ) {
    return;
  }
  if (
    event.target instanceof Element &&
    event.target.closest("button,a,input,select,textarea,label")
  ) {
    return;
  }
  if (event instanceof KeyboardEvent) {
    event.preventDefault();
  }
  context.activateRow(row, event as MouseEvent);
};
</script>

<template>
  <TableEmptyState
    v-if="!rows.length && !context.data.isLoading.value && !context.data.error.value && context.config.table.emptyState?.show !== false"
    class="yayaw-card-empty"
  />
  <div v-else class="yayaw-list">
    <section v-for="section in sections" :key="section.id" class="yayaw-list-section">
      <div v-if="section.label" class="yayaw-list-group">
        <h3><span class="yayaw-list-group-label">{{ groupHeader }}: </span>{{ section.label }}</h3>
        <span class="yayaw-count">{{ section.rows.length }}</span>
      </div>
      <ul>
        <li
          v-for="row in section.rows"
          :key="context.getRowId(row)"
          v-bind="canReorder ? { [REORDER_ROW_ATTRIBUTE]: context.getRowId(row) } : {}"
          :class="{ selected: context.selection.value[context.getRowId(row)], 'yayaw-list-dragging': dragged === row, 'yayaw-list-target': target === row && dragged !== row }"
          :data-yayaw-row-id="context.getRowId(row)"
        >
          <div
            class="yayaw-list-item"
            tabindex="0"
            role="button"
            @click.capture="captureSelection(row, $event)"
            @mousedown.capture="(event) => { if (event.shiftKey || event.ctrlKey || event.metaKey) event.preventDefault(); }"
            @click="activate(row, $event)"
            @keydown="onKeydown(row, $event)"
          >
            <button
              v-if="canReorderRow(row)"
              type="button"
              class="yayaw-list-handle"
              :aria-label="reorderHint"
              :title="reorderHint"
              @click.stop
              @pointerdown="startDrag(row, $event)"
              @pointermove="trackDrag"
              @pointerup="endDrag"
              @pointercancel="cancelDrag"
            >
              <GripVertical :size="16" aria-hidden="true" />
            </button>
            <span
              v-if="context.config.table.enableRowSelection"
              class="yayaw-list-select"
              @click.capture="checkboxShift = $event.shiftKey"
              @click.stop
            >
              <TableCheckbox
                :label="`${translate('selectRow', 'Select')} ${String(value(row, titleColumn))}`"
                :model-value="Boolean(context.selection.value[context.getRowId(row)])"
                :disabled="!selectable(row)"
                @update:model-value="toggleSelection(row, $event, checkboxShift); checkboxShift = false"
              />
            </span>
            <strong class="yayaw-list-title">{{ displayCellValue(value(row, titleColumn), column(titleColumn) ?? { id: titleColumn, header: titleColumn }, context.locale) }}</strong>
            <dl class="yayaw-list-properties">
              <div v-for="id in properties" :key="id">
                <dt :class="{ 'yayaw-sr-only': !showLabels }">{{ column(id)?.header ?? id }}</dt>
                <dd><CellRenderer :value="value(row, id)" :row="row" :column="column(id) ?? { id, header: id }" /></dd>
              </div>
            </dl>
            <RowActions :row="row" />
          </div>
        </li>
      </ul>
    </section>
  </div>
</template>
