// packages/yayaw-table-vue/src/components/forms/CollectionField.vue
<script setup lang="ts">
import {
  computed,
  defineComponent,
  h,
  ref,
  watch,
  type PropType,
  type VNodeChild,
} from "vue";
import {
  cloneFormValue,
  defaultFieldValue,
  formValuesEqual,
  validateFormFields,
} from "../../form-runtime";
import type {
  CollectionFieldColumnDefinition,
  FormFieldContext,
  FormFieldDefinition,
  TableRecord,
} from "../../types";
import DynamicField from "./DynamicField.vue";
import FormDialog from "./FormDialog.vue";

const props = defineProps<{
  field: FormFieldDefinition;
  modelValue: unknown;
  context: FormFieldContext;
  errors?: Record<string, string>;
  path: string;
  disabled?: boolean;
}>();
const emit = defineEmits<{ "update:modelValue": [value: TableRecord[]] }>();
const items = computed(() =>
  Array.isArray(props.modelValue) ? (props.modelValue as TableRecord[]) : []
);
const dialogMode = computed(() =>
  props.field.collectionMode
    ? props.field.collectionMode === "dialog"
    : Boolean(props.field.columns?.length)
);
const columns = computed<CollectionFieldColumnDefinition[]>(
  () =>
    props.field.columns ?? [
      { id: "item", header: props.field.itemLabel ?? "Item" },
    ]
);
const edit = ref<{
  index: number | null;
  values: TableRecord;
  source: TableRecord[];
}>();
const editErrors = ref<Record<string, string>>({});
const saving = ref(false);
const keys = ref<number[]>([]);
let keySequence = 0;
watch(
  items,
  (next, previous = []) => {
    const oldKeys = keys.value;
    const assigned = new Set<number>();
    const retained = new Set(
      next.map((item) => previous.indexOf(item)).filter((index) => index >= 0)
    );
    keys.value = next.map((item, index) => {
      const oldIndex = previous.indexOf(item);
      const candidate =
        oldIndex >= 0
          ? oldKeys[oldIndex]
          : !retained.has(index)
          ? oldKeys[index]
          : undefined;
      const key =
        candidate !== undefined && !assigned.has(candidate)
          ? candidate
          : keySequence++;
      assigned.add(key);
      return key;
    });
  },
  { immediate: true }
);
const update = (next: TableRecord[]): void => {
  if (!props.disabled) emit("update:modelValue", next);
};
const newItem = (create = props.field.createItem): TableRecord =>
  cloneFormValue(
    create?.(cloneFormValue(items.value)) ??
      Object.fromEntries(
        (props.field.itemFields ?? []).map((field) => [
          field.name,
          defaultFieldValue(field),
        ])
      )
  );
const open = (index: number | null, create = props.field.createItem): void => {
  if (props.disabled) return;
  editErrors.value = {};
  edit.value = {
    index,
    source: cloneFormValue(items.value),
    values:
      index === null
        ? newItem(create)
        : cloneFormValue(items.value[index] ?? {}),
  };
};
const add = (create = props.field.createItem): void => {
  if (props.disabled) return;
  if (dialogMode.value) open(null, create);
  else update([...items.value, newItem(create)]);
};
const changeItem = (index: number, next: TableRecord): void =>
  update(items.value.map((item, current) => (current === index ? next : item)));
const changeField = (index: number, name: string, value: unknown): void =>
  changeItem(index, { ...items.value[index], [name]: value });
const remove = (index: number): void =>
  update(items.value.filter((_, current) => current !== index));
const move = (index: number, offset: number): void => {
  if (
    props.disabled ||
    index + offset < 0 ||
    index + offset >= items.value.length
  )
    return;
  const next = [...items.value];
  const [item] = next.splice(index, 1);
  if (item) next.splice(index + offset, 0, item);
  update(next);
};
const changeDraft = (name: string, value: unknown): void => {
  if (edit.value && !saving.value && !props.disabled)
    edit.value.values = { ...edit.value.values, [name]: value };
};
const draftContext = computed<FormFieldContext>(() => ({
  ...props.context,
  values: edit.value?.values ?? {},
  setFieldValue: changeDraft,
  touchField: undefined,
}));
const save = async (): Promise<void> => {
  if (!edit.value || saving.value || props.disabled) return;
  const draft = edit.value;
  saving.value = true;
  try {
    const result = await validateFormFields(
      props.field.itemFields ?? [],
      draft.values,
      draftContext.value
    );
    if (edit.value !== draft || props.disabled) return;
    editErrors.value = result.errors;
    const issues = props.field.validateItem?.(result.values, draft.index) ?? [];
    if (issues.length) editErrors.value.form = issues.join("; ");
    if (!formValuesEqual(items.value, draft.source))
      editErrors.value.form =
        "The collection changed. Reopen this editor before saving.";
    const next =
      draft.index === null
        ? [...items.value, result.values]
        : items.value.map((item, index) =>
            index === draft.index ? result.values : item
          );
    const collectionIssues = props.field.validateItems?.(next) ?? [];
    if (collectionIssues.length)
      editErrors.value.form = collectionIssues.join("; ");
    if (Object.keys(editErrors.value).length) return;
    update(next);
    edit.value = undefined;
  } catch (cause) {
    editErrors.value.form =
      cause instanceof Error ? cause.message : String(cause);
  } finally {
    saving.value = false;
  }
};
const Node = defineComponent({
  props: { node: { type: null as unknown as PropType<VNodeChild> } },
  setup: (value) => () => h("span", {}, [value.node]),
});
const renderItem = (item: TableRecord, index: number | null, draft = false) =>
  props.field.renderItemForm?.({
    item,
    index,
    disabled: props.disabled || saving.value,
    onChange: (value) => {
      if (draft) {
        if (edit.value && !saving.value && !props.disabled)
          edit.value.values = cloneFormValue(value);
      } else if (index !== null) changeItem(index, value);
    },
  });
</script>

<template>
  <div class="yayaw-collection">
    <p v-if="!items.length && field.emptyLabel" class="yayaw-help">
      {{ field.emptyLabel }}
    </p>
    <div v-if="dialogMode" class="yayaw-collection-table-wrap">
      <table class="yayaw-collection-table">
        <thead>
          <tr>
            <th v-for="column in columns" :key="column.id">
              {{ column.header }}
            </th>
            <th><span class="yayaw-sr-only">Actions</span></th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="(item, index) in items"
            :key="field.getItemKey?.(item, index) ?? keys[index]"
          >
            <td v-for="column in columns" :key="column.id">
              <Node
                v-if="column.render"
                :node="column.render(item, index)"
              /><template v-else>{{
                item[column.id] ?? `${field.itemLabel ?? "Item"} ${index + 1}`
              }}</template>
            </td>
            <td>
              <button
                type="button"
                class="yayaw-button yayaw-button-outline"
                :disabled="disabled"
                @click="open(index)"
              >
                Edit</button
              ><button
                type="button"
                class="yayaw-icon-button"
                :disabled="disabled || index === 0"
                aria-label="Move item up"
                @click="move(index, -1)"
              >
                ↑</button
              ><button
                type="button"
                class="yayaw-icon-button"
                :disabled="disabled || index === items.length - 1"
                aria-label="Move item down"
                @click="move(index, 1)"
              >
                ↓</button
              ><button
                type="button"
                class="yayaw-icon-button yayaw-danger"
                :disabled="disabled"
                aria-label="Remove item"
                @click="remove(index)"
              >
                ×
              </button>
            </td>
          </tr>
        </tbody>
      </table>
      <p
        v-for="(message, key) in Object.fromEntries(
          Object.entries(errors ?? {}).filter(([key]) =>
            key.startsWith(`${path}.`)
          )
        )"
        :key="key"
        class="yayaw-field-error"
        role="alert"
      >
        {{ message }}
      </p>
    </div>
    <template v-else>
      <article
        v-for="(item, index) in items"
        :key="field.getItemKey?.(item, index) ?? keys[index]"
        class="yayaw-collection-item"
      >
        <div class="yayaw-collection-actions">
          <span>{{ field.itemLabel }} {{ index + 1 }}</span
          ><button
            type="button"
            class="yayaw-icon-button"
            :disabled="disabled || index === 0"
            aria-label="Move item up"
            @click="move(index, -1)"
          >
            ↑</button
          ><button
            type="button"
            class="yayaw-icon-button"
            :disabled="disabled || index === items.length - 1"
            aria-label="Move item down"
            @click="move(index, 1)"
          >
            ↓</button
          ><button
            type="button"
            class="yayaw-icon-button yayaw-danger"
            :disabled="disabled"
            aria-label="Remove item"
            @click="remove(index)"
          >
            ×
          </button>
        </div>
        <Node v-if="field.renderItemForm" :node="renderItem(item, index)" />
        <DynamicField
          v-for="child in field.renderItemForm ? [] : field.itemFields ?? []"
          :key="child.name"
          :field="disabled ? { ...child, disabled: true } : child"
          :model-value="item[child.name]"
          :context="{
            ...context,
            values: item,
            setFieldValue: (name, value) => changeField(index, name, value),
            touchField: () => context.touchField?.(field.name),
          }"
          :errors="errors"
          :path="`${path}.${index}.${child.name}`"
          @update:model-value="changeField(index, child.name, $event)"
        />
        <p
          v-if="errors?.[`${path}.${index}`]"
          class="yayaw-field-error"
          role="alert"
        >
          {{ errors[`${path}.${index}`] }}
        </p>
      </article>
    </template>
    <button
      type="button"
      class="yayaw-button yayaw-button-outline"
      :disabled="disabled"
      @click="add()"
    >
      + {{ field.addLabel ?? "Add item" }}
    </button>
    <button
      v-for="action in field.createActions"
      :key="action.id ?? action.label"
      type="button"
      class="yayaw-button yayaw-button-outline"
      :disabled="disabled"
      @click="add(action.createItem)"
    >
      + {{ action.label }}
    </button>
    <FormDialog
      v-if="edit"
      :open="true"
      :title="`${edit.index === null ? 'Add' : 'Edit'} ${
        field.itemLabel ?? field.label
      }`"
      presentation="modal"
      :busy="saving"
      @close="edit = undefined"
    >
      <div class="yayaw-form">
        <p v-if="editErrors.form" class="yayaw-field-error" role="alert">
          {{ editErrors.form }}
        </p>
        <Node
          v-if="field.renderItemForm"
          :node="renderItem(edit.values, edit.index, true)"
        />
        <DynamicField
          v-for="child in field.renderItemForm ? [] : field.itemFields ?? []"
          :key="child.name"
          :field="saving || disabled ? { ...child, disabled: true } : child"
          :model-value="edit.values[child.name]"
          :context="draftContext"
          :errors="editErrors"
          @update:model-value="changeDraft(child.name, $event)"
        />
        <footer class="yayaw-form-footer">
          <button
            type="button"
            class="yayaw-button yayaw-button-outline"
            :disabled="saving"
            @click="edit = undefined"
          >
            Cancel</button
          ><button
            type="button"
            class="yayaw-button"
            :disabled="saving || disabled"
            @click="save"
          >
            {{ saving ? "Saving…" : "Save item" }}
          </button>
        </footer>
      </div>
    </FormDialog>
  </div>
</template>

// src/components/ui/yayaw-table/components/forms/fields/collection-field.tsx
/**
 * Collection field component for array-like form values.
 */
"use client";

import {
  ArrowDownIcon,
  ArrowUpIcon,
  PencilIcon,
  PlusIcon,
  Trash2Icon,
} from "lucide-react";
import type { ReactNode } from "react";
import { Fragment, useEffect, useId, useMemo, useState } from "react";
import { cn } from "@/lib/utils";
import { Button } from "@/src/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/src/components/ui/dialog";
import {
  Field,
  FieldDescription,
  FieldError,
  FieldLabel,
} from "@/src/components/ui/field";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/src/components/ui/table";
import { useTranslations } from "../../../providers/table-provider";
import { FormBuilder } from "../form-builder";
import {
  defaultFieldValue,
  formValuesEqual,
  validateFormFields,
} from "../form-runtime";
import { useFormBuilder } from "../hooks/use-form-builder";
import type {
  AnyFieldDefinition,
  CollectionFieldActionLabels,
  CollectionFieldColumnDefinition,
  CollectionFieldCreateAction,
  CollectionFieldDefinition,
  FieldValues,
  FormConfigContext,
  FormFieldApi,
} from "../types";
import {
  type CollectionItem,
  cloneCollectionItem,
  getCollectionItemErrors,
  getCollectionValidationResult,
  insertCollectionItem,
  moveCollectionItem,
  normalizeCollectionItems,
  removeCollectionItem,
  replaceCollectionItem,
} from "./collection-field-utils";

function DeclarativeCollectionItem({
  fields,
  item,
  onChange,
  disabled,
  context,
}: {
  context?: FormConfigContext;
  fields: AnyFieldDefinition[];
  item: FieldValues;
  onChange: (item: FieldValues) => void;
  disabled?: boolean;
}) {
  const { form } = useFormBuilder({
    config: { id: "collection-item", fields },
    initialData: item,
    context: context ? { ...context, values: item } : undefined,
    onValuesChange: (values) => {
      if (!formValuesEqual(values, item)) {
        onChange(values);
      }
    },
  });
  return (
    <fieldset disabled={disabled}>
      <FormBuilder asFieldset context={context} fields={fields} form={form} />
    </fieldset>
  );
}

interface CollectionEditorState {
  draft: CollectionItem;
  index: number | null;
  mode: "create" | "edit";
}

export interface CollectionEditorProps {
  addLabel: string;
  columns: CollectionFieldColumnDefinition[];
  createActions?: CollectionFieldCreateAction[];
  createItem: (items: readonly CollectionItem[]) => CollectionItem;
  description?: ReactNode;
  disabled?: boolean;
  emptyLabel?: string;
  errors?: string[];
  getItemKey?: (item: CollectionItem, index: number) => string;
  id?: string;
  itemLabel: string;
  label?: ReactNode;
  labelKeys?: Partial<Record<keyof CollectionFieldActionLabels, string>>;
  labels?: Partial<CollectionFieldActionLabels>;
  onChange: (items: CollectionItem[]) => void;
  renderItemForm: (props: {
    disabled?: boolean;
    index: number | null;
    item: CollectionItem;
    onChange: (item: CollectionItem) => void;
  }) => ReactNode;
  validateDraft?: (
    item: CollectionItem
  ) => Promise<{ values: CollectionItem; errors: Record<string, string> }>;
  validateItem?: (item: CollectionItem, index: number | null) => string[];
  validateItems?: (items: readonly CollectionItem[]) => string[];
  value: unknown;
}

interface ResolvedCollectionLabels extends CollectionFieldActionLabels {
  addTitle: string;
  editTitle: string;
}

function uniqueMessages(messages: readonly string[]): string[] {
  return [...new Set(messages.filter(Boolean))];
}

function translateWithFallback(
  t: (key: string) => string,
  key: string,
  fallback: string
): string {
  const translated = t(key);
  return translated === key ? fallback : translated;
}

function resolveCollectionLabels({
  itemLabel,
  labelKeys,
  labels,
  t,
}: {
  itemLabel: string;
  labelKeys?: Partial<Record<keyof CollectionFieldActionLabels, string>>;
  labels?: Partial<CollectionFieldActionLabels>;
  t: (key: string) => string;
}): ResolvedCollectionLabels {
  const fallbackLabels: CollectionFieldActionLabels = {
    actions: translateWithFallback(t, "collection.actions", "Actions"),
    addTitle: `Add ${itemLabel}`,
    cancel: translateWithFallback(t, "collection.cancel", "Cancel"),
    deleteItem: translateWithFallback(t, "collection.deleteItem", "Delete"),
    editItem: translateWithFallback(t, "collection.editItem", "Edit"),
    editTitle: `Edit ${itemLabel}`,
    moveDown: translateWithFallback(t, "collection.moveDown", "Move down"),
    moveUp: translateWithFallback(t, "collection.moveUp", "Move up"),
    save: translateWithFallback(t, "collection.save", "Save"),
  };

  const resolvedEntries = Object.entries(fallbackLabels).map(
    ([name, fallback]) => {
      const typedName = name as keyof CollectionFieldActionLabels;
      const key = labelKeys?.[typedName];
      if (key) {
        return [typedName, t(key)];
      }
      return [typedName, labels?.[typedName] ?? fallback];
    }
  );

  return Object.fromEntries(resolvedEntries) as ResolvedCollectionLabels;
}

function formatCollectionValue(value: unknown): ReactNode {
  if (value == null || value === "") {
    return <span className="text-muted-foreground">-</span>;
  }
  if (typeof value === "boolean") {
    return value ? "Yes" : "No";
  }
  if (typeof value === "number" || typeof value === "string") {
    return String(value);
  }
  return (
    <code className="rounded bg-muted px-1 py-0.5 text-xs">
      {JSON.stringify(value)}
    </code>
  );
}

function renderCollectionCell(
  column: CollectionFieldColumnDefinition,
  item: CollectionItem,
  index: number
): ReactNode {
  if (column.render) {
    return column.render(item, index);
  }
  return formatCollectionValue(item[column.id]);
}

function getEditorTitle(
  state: CollectionEditorState,
  labels: ResolvedCollectionLabels
): string {
  if (state.mode === "create") {
    return labels.addTitle;
  }
  return `${labels.editTitle} ${state.index == null ? "" : state.index + 1}`.trim();
}

export function CollectionEditor({
  addLabel,
  columns,
  createActions,
  createItem,
  description,
  disabled,
  emptyLabel,
  errors = [],
  getItemKey,
  id,
  itemLabel,
  label,
  labelKeys,
  labels,
  onChange,
  renderItemForm,
  validateDraft,
  validateItem,
  validateItems,
  value,
}: CollectionEditorProps) {
  const [saving, setSaving] = useState(false);
  const [draftIssues, setDraftIssues] = useState<string[]>([]);
  const generatedId = useId();
  const fieldId = id ?? generatedId;
  const { t } = useTranslations();
  const items = useMemo(() => normalizeCollectionItems(value), [value]);
  const [editorState, setEditorState] = useState<CollectionEditorState | null>(
    null
  );
  const resolvedLabels = useMemo(
    () => resolveCollectionLabels({ itemLabel, labelKeys, labels, t }),
    [itemLabel, labelKeys, labels, t]
  );
  const validation = useMemo(
    () =>
      getCollectionValidationResult(
        { itemLabel, validateItem, validateItems },
        items
      ),
    [itemLabel, items, validateItem, validateItems]
  );
  const visibleErrors = uniqueMessages([...validation.globalErrors, ...errors]);
  const isInvalid = validation.messages.length > 0 || visibleErrors.length > 0;
  const visibleColumns =
    columns.length > 0
      ? columns
      : [
          {
            header: itemLabel,
            id: "value",
          } satisfies CollectionFieldColumnDefinition,
        ];
  const addActions =
    createActions && createActions.length > 0
      ? createActions
      : [{ createItem, label: addLabel }];

  const openCreateEditor = (
    actionCreateItem: (items: readonly CollectionItem[]) => CollectionItem
  ) => {
    setDraftIssues([]);
    setEditorState({
      draft: cloneCollectionItem(actionCreateItem(items)),
      index: null,
      mode: "create",
    });
  };

  const openEditEditor = (item: CollectionItem, index: number) => {
    setDraftIssues([]);
    setEditorState({
      draft: cloneCollectionItem(item),
      index,
      mode: "edit",
    });
  };

  const closeEditor = () => {
    setEditorState(null);
  };

  const saveEditor = async () => {
    if (!editorState || saving || disabled) {
      return;
    }
    setSaving(true);
    try {
      const validated = await validateDraft?.(editorState.draft);
      if (validated && Object.keys(validated.errors).length) {
        setDraftIssues(Object.values(validated.errors));
        return;
      }
      const item = validated?.values ?? editorState.draft;
      onChange(
        editorState.index == null
          ? insertCollectionItem(items, item)
          : replaceCollectionItem(items, editorState.index, item)
      );
      closeEditor();
    } catch (cause) {
      setDraftIssues([cause instanceof Error ? cause.message : String(cause)]);
    } finally {
      setSaving(false);
    }
  };

  const draftErrors = editorState
    ? getCollectionItemErrors(
        { validateItem },
        editorState.draft,
        editorState.index
      )
    : [];

  return (
    <Field
      aria-describedby={description ? `${fieldId}-description` : undefined}
      aria-invalid={isInvalid}
      className="gap-3"
      data-invalid={isInvalid}
    >
      {label && <FieldLabel>{label}</FieldLabel>}
      {description && (
        <FieldDescription id={`${fieldId}-description`}>
          {description}
        </FieldDescription>
      )}

      <div className="rounded-md border bg-background">
        <div className="flex flex-wrap items-center justify-between gap-2 border-b p-3">
          <div className="text-muted-foreground text-sm">
            {items.length} {itemLabel}
          </div>
          <div className="flex flex-wrap gap-2">
            {addActions.map((action) => (
              <Button
                disabled={disabled}
                key={action.id ?? action.label}
                onClick={() => openCreateEditor(action.createItem)}
                size="sm"
                type="button"
                variant="outline"
              >
                <PlusIcon />
                <span>{action.label}</span>
              </Button>
            ))}
          </div>
        </div>

        {items.length === 0 ? (
          <div className="p-4 text-muted-foreground text-sm">
            {emptyLabel ?? `No ${itemLabel.toLowerCase()} yet.`}
          </div>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                {visibleColumns.map((column) => (
                  <TableHead key={column.id}>{column.header}</TableHead>
                ))}
                <TableHead className="w-36 text-right">
                  {resolvedLabels.actions}
                </TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {items.map((item, index) => {
                const rowErrors = validation.itemErrors[index] ?? [];
                const rowInvalid = rowErrors.length > 0;
                const itemKey =
                  getItemKey?.(item, index) ?? `${index}-${itemLabel}`;
                return (
                  <Fragment key={itemKey}>
                    <TableRow
                      aria-invalid={rowInvalid}
                      className={cn(rowInvalid && "bg-destructive/5")}
                      data-invalid={rowInvalid}
                    >
                      {visibleColumns.map((column) => (
                        <TableCell key={column.id}>
                          {renderCollectionCell(column, item, index)}
                        </TableCell>
                      ))}
                      <TableCell>
                        <div className="flex justify-end gap-1">
                          <Button
                            aria-label={`${resolvedLabels.moveUp} ${itemLabel} ${index + 1}`}
                            disabled={disabled || index === 0}
                            onClick={() =>
                              onChange(
                                moveCollectionItem(items, index, index - 1)
                              )
                            }
                            size="icon-sm"
                            type="button"
                            variant="ghost"
                          >
                            <ArrowUpIcon />
                          </Button>
                          <Button
                            aria-label={`${resolvedLabels.moveDown} ${itemLabel} ${index + 1}`}
                            disabled={disabled || index === items.length - 1}
                            onClick={() =>
                              onChange(
                                moveCollectionItem(items, index, index + 1)
                              )
                            }
                            size="icon-sm"
                            type="button"
                            variant="ghost"
                          >
                            <ArrowDownIcon />
                          </Button>
                          <Button
                            aria-label={`${resolvedLabels.editItem} ${itemLabel} ${index + 1}`}
                            disabled={disabled}
                            onClick={() => openEditEditor(item, index)}
                            size="icon-sm"
                            type="button"
                            variant="ghost"
                          >
                            <PencilIcon />
                          </Button>
                          <Button
                            aria-label={`${resolvedLabels.deleteItem} ${itemLabel} ${index + 1}`}
                            disabled={disabled}
                            onClick={() =>
                              onChange(removeCollectionItem(items, index))
                            }
                            size="icon-sm"
                            type="button"
                            variant="ghost"
                          >
                            <Trash2Icon />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    {rowInvalid && (
                      <TableRow key={`${itemKey}-errors`}>
                        <TableCell colSpan={visibleColumns.length + 1}>
                          <FieldError
                            errors={rowErrors.map((message) => ({ message }))}
                          />
                        </TableCell>
                      </TableRow>
                    )}
                  </Fragment>
                );
              })}
            </TableBody>
          </Table>
        )}
      </div>

      <FieldError errors={visibleErrors.map((message) => ({ message }))} />

      {editorState && (
        <Dialog
          onOpenChange={(open) => {
            if (!(open || saving)) {
              closeEditor();
            }
          }}
          open
        >
          <DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl">
            <DialogHeader>
              <DialogTitle>
                {getEditorTitle(editorState, resolvedLabels)}
              </DialogTitle>
              {draftErrors.length > 0 && (
                <DialogDescription>
                  {draftErrors.length === 1
                    ? draftErrors[0]
                    : `${draftErrors.length} validation errors`}
                </DialogDescription>
              )}
            </DialogHeader>
            <div className="space-y-4">
              {renderItemForm({
                disabled: disabled || saving,
                index: editorState.index,
                item: editorState.draft,
                onChange: (item) =>
                  setEditorState((current) =>
                    current
                      ? { ...current, draft: cloneCollectionItem(item) }
                      : current
                  ),
              })}
              <FieldError
                errors={[...draftErrors, ...draftIssues].map((message) => ({
                  message,
                }))}
              />
            </div>
            <DialogFooter>
              <Button
                disabled={saving}
                onClick={closeEditor}
                type="button"
                variant="outline"
              >
                {resolvedLabels.cancel}
              </Button>
              <Button
                disabled={disabled || saving}
                onClick={async () => {
                  await saveEditor();
                }}
                type="button"
              >
                {resolvedLabels.save}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}
    </Field>
  );
}

interface CollectionFieldProps<TFieldValues extends FieldValues> {
  field: CollectionFieldDefinition<TFieldValues>;
  fieldApi: FormFieldApi<unknown>;
  context?: FormConfigContext;
}

export function CollectionField<TFieldValues extends FieldValues>({
  field,
  fieldApi,
  context,
}: CollectionFieldProps<TFieldValues>) {
  const { t } = useTranslations();
  const errors = fieldApi.state.meta.errors;
  const errorMessages = Array.isArray(errors)
    ? errors.map((error) => (typeof error === "string" ? error : String(error)))
    : [];

  useEffect(() => {
    if (!Array.isArray(fieldApi.state.value)) {
      fieldApi.handleChange([]);
    }
  }, [fieldApi.handleChange, fieldApi.state.value]);

  const itemContext: FormConfigContext = context ?? {
    formType: "collection",
    tableId: "collection",
    tableType: "collection",
    mode: "create",
  };
  const createItem =
    field.createItem ??
    (() =>
      Object.fromEntries(
        (field.itemFields ?? []).map((item) => [
          item.name,
          defaultFieldValue(item),
        ])
      ));
  const renderItem =
    field.renderItemForm ??
    ((props) => (
      <DeclarativeCollectionItem
        {...props}
        context={itemContext}
        fields={field.itemFields ?? []}
      />
    ));
  const items = normalizeCollectionItems(fieldApi.state.value);
  if (field.collectionMode === "inline") {
    return (
      <fieldset className="space-y-3" disabled={field.disabled === true}>
        <legend>{field.label}</legend>
        {items.map((item, index) => (
          <div
            className="space-y-2 rounded-md border p-3"
            key={field.getItemKey?.(item, index) ?? String(item.id ?? index)}
          >
            {renderItem({
              item,
              index,
              disabled: field.disabled === true,
              onChange: (next) =>
                fieldApi.handleChange(
                  replaceCollectionItem(items, index, next)
                ),
            })}
            <div className="flex gap-2">
              <Button
                aria-label={`Move item ${index + 1} up`}
                disabled={index === 0}
                onClick={() =>
                  fieldApi.handleChange(
                    moveCollectionItem(items, index, index - 1)
                  )
                }
                type="button"
                variant="outline"
              >
                ↑
              </Button>
              <Button
                aria-label={`Move item ${index + 1} down`}
                disabled={index === items.length - 1}
                onClick={() =>
                  fieldApi.handleChange(
                    moveCollectionItem(items, index, index + 1)
                  )
                }
                type="button"
                variant="outline"
              >
                ↓
              </Button>
              <Button
                onClick={() =>
                  fieldApi.handleChange(removeCollectionItem(items, index))
                }
                type="button"
                variant="outline"
              >
                {field.labels?.deleteItem ?? "Delete"}
              </Button>
            </div>
          </div>
        ))}
        <Button
          onClick={() =>
            fieldApi.handleChange(
              insertCollectionItem(items, createItem(items))
            )
          }
          type="button"
        >
          {field.addLabel ?? "Add item"}
        </Button>
        <FieldError errors={errorMessages.map((message) => ({ message }))} />
      </fieldset>
    );
  }

  return (
    <CollectionEditor
      addLabel={field.addLabel ?? "Add item"}
      columns={
        field.columns ??
        (field.itemFields ?? []).map((item) => ({
          id: item.name,
          header: item.label,
        }))
      }
      createActions={field.createActions}
      createItem={createItem}
      description={
        field.descriptionKey ? t(field.descriptionKey) : field.description
      }
      disabled={field.disabled === true}
      emptyLabel={field.emptyLabel}
      errors={errorMessages}
      getItemKey={field.getItemKey}
      itemLabel={field.itemLabel ?? "item"}
      label={field.labelKey ? t(field.labelKey) : field.label}
      labelKeys={field.labelKeys}
      labels={field.labels}
      onChange={fieldApi.handleChange}
      renderItemForm={renderItem}
      validateDraft={
        field.itemFields
          ? (item) =>
              validateFormFields(field.itemFields ?? [], item, {
                ...itemContext,
                values: item,
              })
          : undefined
      }
      validateItem={field.validateItem}
      validateItems={field.validateItems}
      value={fieldApi.state.value}
    />
  );
}
