// registry/default/ui/yayaw-table/feed/feed-settings.tsx
"use client";

import { Button } from "@/components/ui/button";
import { ViewSettingsPanel } from "../components/toolbar/view-settings-panel";
import type { DisplayModeSettingsContext } from "../types/display-mode-renderer";
import {
  type FeedColumn,
  type FeedViewSettings,
  feedSettingFields,
} from "../utils/feed-view";

/** View → Card settings of the feed: columns, dates, body, cards and loading. */
export function FeedSettings({
  context,
}: {
  context: DisplayModeSettingsContext;
}) {
  const view = context.settings as FeedViewSettings;
  const { fields, properties } = feedSettingFields({
    columns: context.columns as FeedColumn[],
    defaults: context.defaults as FeedViewSettings,
    view,
    locale: context.locale,
    translate: (key, fallback) => context.translate(`feed.${key}`, fallback),
    update: (next) => context.updateSettings(next),
  });
  return (
    <ViewSettingsPanel fields={fields} properties={properties}>
      <Button
        className="font-normal"
        disabled={Object.keys(view).length === 0}
        onClick={() => context.updateSettings(undefined)}
        size="sm"
        type="button"
        variant="outline"
      >
        {context.translate("common.reset", "Reset")}
      </Button>
    </ViewSettingsPanel>
  );
}

// packages/yayaw-table-vue/src/feed/FeedSettings.vue
<script setup lang="ts">
import { computed } from "vue";
import ViewSettingsPanel from "../components/controls/ViewSettingsPanel.vue";
import type { DisplayModeSettingsContext } from "../display-mode-renderer";
import {
  type FeedColumn,
  type FeedViewSettings,
  feedSettingFields,
} from "../feed-view";

const props = defineProps<{ context: DisplayModeSettingsContext }>();
const view = computed(() => props.context.settings as FeedViewSettings);
const panel = computed(() =>
  feedSettingFields({
    columns: props.context.columns as unknown as FeedColumn[],
    defaults: props.context.defaults as FeedViewSettings,
    view: view.value,
    locale: props.context.locale,
    translate: (key, fallback) =>
      props.context.translate(`feed.${key}`, fallback),
    update: (next) => props.context.updateSettings(next),
  })
);
</script>

<template>
  <ViewSettingsPanel :fields="panel.fields" :properties="panel.properties">
    <button
      type="button"
      class="yayaw-button yayaw-button-outline"
      :disabled="Object.keys(view).length === 0"
      @click="props.context.updateSettings(undefined)"
    >
      {{ props.context.translate("reset", "Reset") }}
    </button>
  </ViewSettingsPanel>
</template>
