// packages/yayaw-table-vue/src/form/FormDateField.vue
<script setup lang="ts">
import { type DateValue, parseDate } from "@internationalized/date";
import {
  Calendar as CalendarIcon,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
} from "lucide-vue-next";
import {
  CalendarCell,
  CalendarCellTrigger,
  CalendarGrid,
  CalendarGridBody,
  CalendarGridHead,
  CalendarGridRow,
  CalendarHeadCell,
  CalendarHeader,
  CalendarHeading,
  CalendarNext,
  CalendarPrev,
  CalendarRoot,
  PopoverContent,
  PopoverPortal,
  PopoverRoot,
  PopoverTrigger,
} from "reka-ui";
import { computed, ref, useTemplateRef } from "vue";
import { useOverlayTheme } from "../composables/use-overlay-theme";
import { formDateDisplay, formWeekStart } from "../form-view";

/** A date question: a button showing the date in the form's language, and a calendar. */
const props = defineProps<{
  /** Id of the trigger, so the question's label points at it. */
  id: string;
  /** Id of the question label; the trigger is named by it and its date. */
  labelId: string;
  value: string;
  locale: string;
  placeholder: string;
  clearLabel: string;
  disabled?: boolean;
  invalid?: boolean;
  required?: boolean;
  describedBy?: string;
  /** Earliest and latest days that can be picked (`YYYY-MM-DD`). */
  min?: string;
  max?: string;
}>();
const emit = defineEmits<{ change: [value: string] }>();

type WeekStart = 0 | 1 | 2 | 3 | 4 | 5 | 6;

const open = ref(false);
const anchor = useTemplateRef<HTMLElement>("anchor");
const { overlayStyle, updateOpen } = useOverlayTheme(anchor);
const shown = computed(() => formDateDisplay(props.value, props.locale));
const selected = computed<DateValue | undefined>(() =>
  shown.value ? parseDate(props.value) : undefined
);
const weekStart = computed(() => formWeekStart(props.locale) as WeekStart);
const dayOf = (value?: string): DateValue | undefined =>
  value && formDateDisplay(value, props.locale) ? parseDate(value) : undefined;
const minValue = computed(() => dayOf(props.min));
const maxValue = computed(() => dayOf(props.max));
const valueId = computed(() => `${props.id}-value`);
const setOpen = (next: boolean): void => {
  updateOpen(next);
  open.value = next;
};
const pick = (next: string): void => {
  emit("change", next);
  open.value = false;
};
const choose = (date: DateValue | undefined): void =>
  pick(date ? date.toString() : "");
</script>

<template>
  <span ref="anchor" class="yayaw-form-date-anchor">
    <PopoverRoot :open="open" @update:open="setOpen">
      <PopoverTrigger as-child>
        <button
          :id="id"
          type="button"
          class="yayaw-button yayaw-button-outline yayaw-form-date"
          data-form-focus
          :disabled="disabled"
          :aria-labelledby="`${labelId} ${valueId}`"
          :aria-describedby="describedBy"
          :aria-invalid="invalid ? true : undefined"
          :aria-required="required || undefined"
        >
          <CalendarIcon :size="16" aria-hidden="true" class="yayaw-form-date-icon" />
          <span :id="valueId" class="yayaw-form-date-value" :data-empty="!shown || undefined">{{ shown ?? placeholder }}</span>
          <ChevronDown :size="16" aria-hidden="true" class="yayaw-form-date-icon" />
        </button>
      </PopoverTrigger>
      <PopoverPortal>
        <PopoverContent
          class="yayaw-form-popover yayaw-form-calendar-popover"
          :style="overlayStyle"
          align="start"
          :side-offset="4"
          :collision-padding="8"
        >
          <CalendarRoot
            v-slot="{ weekDays, grid }"
            :model-value="selected"
            :default-placeholder="selected"
            :locale="locale"
            :week-starts-on="weekStart"
            :min-value="minValue"
            :max-value="maxValue"
            weekday-format="short"
            initial-focus
            class="yayaw-form-calendar"
            @update:model-value="choose($event as DateValue | undefined)"
          >
            <CalendarHeader class="yayaw-form-calendar-header">
              <CalendarPrev class="yayaw-button yayaw-button-ghost yayaw-form-calendar-nav">
                <ChevronLeft :size="16" aria-hidden="true" />
              </CalendarPrev>
              <CalendarHeading class="yayaw-form-calendar-heading" />
              <CalendarNext class="yayaw-button yayaw-button-ghost yayaw-form-calendar-nav">
                <ChevronRight :size="16" aria-hidden="true" />
              </CalendarNext>
            </CalendarHeader>
            <CalendarGrid v-for="month in grid" :key="month.value.toString()" class="yayaw-form-calendar-grid">
              <CalendarGridHead>
                <CalendarGridRow class="yayaw-form-calendar-row">
                  <CalendarHeadCell v-for="day in weekDays" :key="day" class="yayaw-form-calendar-weekday">{{ day }}</CalendarHeadCell>
                </CalendarGridRow>
              </CalendarGridHead>
              <CalendarGridBody>
                <CalendarGridRow v-for="(week, index) in month.rows" :key="`week-${index}`" class="yayaw-form-calendar-row">
                  <CalendarCell v-for="day in week" :key="day.toString()" :date="day" class="yayaw-form-calendar-cell">
                    <CalendarCellTrigger :day="day" :month="month.value" class="yayaw-form-calendar-day" />
                  </CalendarCell>
                </CalendarGridRow>
              </CalendarGridBody>
            </CalendarGrid>
          </CalendarRoot>
          <div v-if="shown" class="yayaw-form-calendar-footer">
            <button type="button" class="yayaw-button yayaw-button-ghost" @click="pick('')">{{ clearLabel }}</button>
          </div>
        </PopoverContent>
      </PopoverPortal>
    </PopoverRoot>
  </span>
</template>

// registry/default/ui/yayaw-table/form/form-date-field.tsx
"use client";

import { CalendarIcon, ChevronDown } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { cn } from "@/lib/utils";
import { Calendar } from "../components/filters/calendar";
import {
  formDateAnswer,
  formDateDisplay,
  formWeekStart,
} from "../utils/form-view";
import { parseDateValue } from "../utils/value-format";

type WeekStart = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export interface FormDateFieldProps {
  /** Id of the trigger, so the question's label points at it. */
  id: string;
  /** Id of the question label; the trigger is named by it and its date. */
  labelId: string;
  value: string;
  locale: string;
  placeholder: string;
  clearLabel: string;
  disabled?: boolean;
  invalid?: boolean;
  required?: boolean;
  describedBy?: string;
  /** Earliest and latest days that can be picked (`YYYY-MM-DD`). */
  min?: string;
  max?: string;
  onChange: (value: string) => void;
}

/** Days outside `min`…`max` cannot be picked. */
const outside = (min?: string, max?: string) => {
  const before = min ? parseDateValue(min) : undefined;
  const after = max ? parseDateValue(max) : undefined;
  return [...(before ? [{ before }] : []), ...(after ? [{ after }] : [])];
};

/** Captions, weekdays and day names in the form's language. */
function useCalendarText(locale: string) {
  return useMemo(() => {
    const month = new Intl.DateTimeFormat(locale, {
      month: "long",
      year: "numeric",
    });
    const weekday = new Intl.DateTimeFormat(locale, { weekday: "short" });
    const day = new Intl.DateTimeFormat(locale, { dateStyle: "full" });
    return {
      formatters: {
        formatCaption: (date: Date) => month.format(date),
        formatWeekdayName: (date: Date) => weekday.format(date),
      },
      labels: {
        labelDayButton: (date: Date) => day.format(date),
      },
    };
  }, [locale]);
}

/** A date question: a button showing the date in the form's language, and a calendar. */
export function FormDateField({
  clearLabel,
  describedBy,
  disabled,
  id,
  invalid,
  labelId,
  locale,
  max,
  min,
  onChange,
  placeholder,
  required,
  value,
}: FormDateFieldProps) {
  const [open, setOpen] = useState(false);
  const text = useCalendarText(locale);
  const shown = formDateDisplay(value, locale);
  const selected = shown ? parseDateValue(value) : undefined;
  const valueId = `${id}-value`;
  const calendar = useRef<HTMLDivElement>(null);
  // Open on the picked day, or today, so arrow keys move through the month.
  const dayToFocus = () =>
    calendar.current?.querySelector<HTMLElement>(
      '[data-selected="true"] button, [data-today="true"] button'
    ) ?? true;
  const pick = (next: string) => {
    onChange(next);
    setOpen(false);
  };
  return (
    <Popover onOpenChange={setOpen} open={open}>
      <PopoverTrigger
        render={
          <Button
            aria-describedby={describedBy}
            aria-invalid={invalid ? true : undefined}
            aria-labelledby={`${labelId} ${valueId}`}
            aria-required={required || undefined}
            className="w-full justify-start gap-2 px-2.5 font-normal"
            data-form-focus
            disabled={disabled}
            id={id}
            type="button"
            variant="outline"
          />
        }
      >
        <CalendarIcon aria-hidden="true" className="text-muted-foreground" />
        <span
          className={cn(
            "min-w-0 flex-1 truncate text-left",
            !shown && "text-muted-foreground"
          )}
          id={valueId}
        >
          {shown ?? placeholder}
        </span>
        <ChevronDown aria-hidden="true" className="text-muted-foreground" />
      </PopoverTrigger>
      <PopoverContent
        align="start"
        className="w-auto gap-0 p-0"
        initialFocus={dayToFocus}
        ref={calendar}
      >
        <Calendar
          className="[--cell-size:--spacing(8)]"
          defaultMonth={selected}
          disabled={outside(min, max)}
          formatters={text.formatters}
          labels={text.labels}
          lang={locale}
          mode="single"
          onSelect={(date) => pick(date ? formDateAnswer(date) : "")}
          selected={selected}
          weekStartsOn={formWeekStart(locale) as WeekStart}
        />
        {shown ? (
          <div className="flex justify-end border-t p-2">
            <Button
              onClick={() => pick("")}
              size="sm"
              type="button"
              variant="ghost"
            >
              {clearLabel}
            </Button>
          </div>
        ) : null}
      </PopoverContent>
    </Popover>
  );
}
