// registry/default/ui/yayaw-table-dashboard/dashboard-section-bar.tsx
"use client";

import { ArrowDown, ArrowUp, MoreHorizontal, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import type { DashboardSectionMove } from "./dashboard-editor-model";
import type { DashboardSection } from "./dashboard-schema";
import type { DashboardLabel } from "./dashboard-widget";

export interface DashboardSectionBarProps {
  section: DashboardSection;
  /** The section's name in menus: its title, else "Section 2". */
  name: string;
  /** The title in the language edited (no other language's version). */
  titleInput: string;
  label: DashboardLabel;
  canMove: (direction: DashboardSectionMove) => boolean;
  onRename: (title: string) => void;
  onMove: (direction: DashboardSectionMove) => void;
  onAddWidget: () => void;
  onRemove: () => void;
}

/** A section in edit mode: its title and its menu (move, add a widget, remove). */
export function DashboardSectionBar({
  canMove,
  label,
  name,
  onAddWidget,
  onMove,
  onRemove,
  onRename,
  section,
  titleInput,
}: DashboardSectionBarProps) {
  return (
    <div
      className="flex min-h-10 items-center gap-2 rounded-lg border border-dashed px-2 py-1"
      data-section-bar={section.id}
    >
      <Input
        aria-label={label("sectionTitle")}
        className="h-8 max-w-80 flex-1 font-semibold"
        maxLength={120}
        onChange={(event) => onRename(event.target.value)}
        placeholder={name}
        value={titleInput}
      />
      <span className="shrink-0 text-muted-foreground text-xs">
        {label(section.type === "grid" ? "sectionGrid" : "sectionFlow")}
      </span>
      <span className="ms-auto">
        <DropdownMenu>
          <DropdownMenuTrigger
            render={
              <Button
                aria-label={label("sectionMenu", { title: name })}
                size="icon-sm"
                type="button"
                variant="ghost"
              />
            }
          >
            <MoreHorizontal aria-hidden="true" />
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="min-w-48">
            <DropdownMenuItem
              disabled={!canMove("up")}
              onClick={() => onMove("up")}
            >
              <ArrowUp aria-hidden="true" />
              {label("moveUp")}
            </DropdownMenuItem>
            <DropdownMenuItem
              disabled={!canMove("down")}
              onClick={() => onMove("down")}
            >
              <ArrowDown aria-hidden="true" />
              {label("moveDown")}
            </DropdownMenuItem>
            <DropdownMenuItem onClick={onAddWidget}>
              <Plus aria-hidden="true" />
              {label("addWidgetHere")}
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={onRemove} variant="destructive">
              <Trash2 aria-hidden="true" />
              {label("remove")}
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </span>
    </div>
  );
}

/** An empty section in edit mode: a dashed placeholder offering to add a widget. */
export function DashboardEmptySection({
  label,
  onAddWidget,
}: {
  label: DashboardLabel;
  onAddWidget: () => void;
}) {
  return (
    <div
      className="flex min-h-24 flex-col items-center justify-center gap-2 rounded-xl border border-dashed p-4 text-center text-muted-foreground text-sm"
      data-section-empty=""
    >
      <p className="m-0">{label("emptySection")}</p>
      <Button onClick={onAddWidget} size="sm" type="button" variant="outline">
        <Plus aria-hidden="true" />
        {label("addWidgetHere")}
      </Button>
    </div>
  );
}

// packages/yayaw-table-vue/src/dashboard/DashboardSectionBar.vue
<script setup lang="ts">
import { ArrowDown, ArrowUp, MoreHorizontal, Plus, Trash2 } from "lucide-vue-next";
import {
  DropdownMenuContent, DropdownMenuItem, DropdownMenuPortal, DropdownMenuRoot, DropdownMenuSeparator, DropdownMenuTrigger,
} from "reka-ui";
import type { DashboardSectionMove } from "./dashboard-editor-model";
import type { DashboardSection } from "./dashboard-schema";
import type { DashboardLabel } from "./dashboard-types";

/** A section in edit mode: its title and its menu (move, add a widget, remove). */
const props = defineProps<{
  section: DashboardSection;
  /** The section's name in menus: its title, else "Section 2". */
  name: string;
  /** The title in the language edited (no other language's version). */
  titleInput: string;
  label: DashboardLabel;
  canMove: (direction: DashboardSectionMove) => boolean;
}>();
const emit = defineEmits<{
  rename: [title: string];
  move: [direction: DashboardSectionMove];
  addWidget: [];
  remove: [];
}>();
</script>

<template>
  <div class="yayaw-dashboard-section-bar" :data-section-bar="props.section.id">
    <input
      class="yayaw-input yayaw-dashboard-section-input"
      :aria-label="props.label('sectionTitle')"
      :placeholder="props.name"
      :value="props.titleInput"
      maxlength="120"
      @input="emit('rename', ($event.target as HTMLInputElement).value)"
    >
    <span class="yayaw-dashboard-edit-bar-type">{{ props.label(props.section.type === "grid" ? "sectionGrid" : "sectionFlow") }}</span>
    <DropdownMenuRoot :modal="false">
      <DropdownMenuTrigger as-child>
        <button
          type="button"
          class="yayaw-dashboard-icon-button yayaw-dashboard-edit-bar-menu"
          :aria-label="props.label('sectionMenu', { title: props.name })"
        >
          <MoreHorizontal :size="16" aria-hidden="true" />
        </button>
      </DropdownMenuTrigger>
      <DropdownMenuPortal>
        <DropdownMenuContent class="yayaw-row-actions-menu yayaw-dashboard-menu" align="end" :side-offset="4" :collision-padding="8">
          <DropdownMenuItem as-child :disabled="!props.canMove('up')" @select="emit('move', 'up')">
            <button type="button" class="yayaw-row-action-item" :disabled="!props.canMove('up')">
              <ArrowUp :size="16" aria-hidden="true" />{{ props.label("moveUp") }}
            </button>
          </DropdownMenuItem>
          <DropdownMenuItem as-child :disabled="!props.canMove('down')" @select="emit('move', 'down')">
            <button type="button" class="yayaw-row-action-item" :disabled="!props.canMove('down')">
              <ArrowDown :size="16" aria-hidden="true" />{{ props.label("moveDown") }}
            </button>
          </DropdownMenuItem>
          <DropdownMenuItem as-child @select="emit('addWidget')">
            <button type="button" class="yayaw-row-action-item">
              <Plus :size="16" aria-hidden="true" />{{ props.label("addWidgetHere") }}
            </button>
          </DropdownMenuItem>
          <DropdownMenuSeparator class="yayaw-row-actions-divider" />
          <DropdownMenuItem as-child @select="emit('remove')">
            <button type="button" class="yayaw-row-action-item yayaw-row-action-danger">
              <Trash2 :size="16" aria-hidden="true" />{{ props.label("remove") }}
            </button>
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenuPortal>
    </DropdownMenuRoot>
  </div>
</template>
