// registry/default/ui/yayaw-table-dashboard/dashboard-widget-dialog.tsx
"use client";

import { ChevronLeft, Pencil } from "lucide-react";
import {
  type FormEvent,
  type ReactNode,
  useEffect,
  useId,
  useReducer,
  useRef,
  useState,
} from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import {
  NativeSelect,
  NativeSelectOptGroup,
  NativeSelectOption,
} from "@/components/ui/native-select";
import { Textarea } from "@/components/ui/textarea";
import type { DisplayModeRenderers } from "@/components/ui/yayaw-table/types/display-mode-renderer";
import type { DataTableTranslations } from "@/components/ui/yayaw-table/types/translations";
import { canonicalViewConfig } from "@/components/ui/yayaw-table/utils/view-config";
import type { DashboardBlockRegistry } from "./dashboard-block";
import { Field, KpiFields, OverflowField } from "./dashboard-dialogs";
import {
  type DashboardBlockPropsDraft,
  type DashboardWidgetChoice,
  type DashboardWidgetDialogTarget,
  dashboardBlockPropsText,
  dashboardKindReadsSource,
  dashboardViewEditStart,
  dashboardWidgetChoices,
  parseDashboardBlockProps,
} from "./dashboard-editor-model";
import { tableInfo } from "./dashboard-hooks";
import {
  type DashboardTableInfo,
  type DashboardTranslate,
  type DashboardView,
  type DashboardWidgetDraft,
  dashboardUnavailableText,
  dashboardWidgetDraft,
  dashboardWidgetFromDraft,
  emptyWidgetDraft,
  loadDashboardViews,
} from "./dashboard-model";
import {
  checkDashboardBlockProps,
  type DashboardJsonObject,
  type DashboardWidget,
} from "./dashboard-schema";
import { DashboardSourcePicker } from "./dashboard-source-picker";
import type {
  DashboardSourceLoader,
  DashboardSourceState,
} from "./dashboard-sources";
import { DashboardViewEditor } from "./dashboard-view-editor";
import type { DashboardLabel, DashboardTableSource } from "./dashboard-widget";

export interface DashboardWidgetDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  target: DashboardWidgetDialogTarget;
  loader: DashboardSourceLoader<DashboardTableSource>;
  blocks?: DashboardBlockRegistry;
  label: DashboardLabel;
  locale: string;
  translate: DashboardTranslate;
  /** For the view editor's table. */
  renderers?: DisplayModeRenderers;
  getRowId?: (row: Record<string, unknown>) => string;
  tableTranslations?: DataTableTranslations;
  /** The widget the dialog describes (without its id), and its source's saved views. */
  onSubmit: (
    widget: Omit<DashboardWidget, "id">,
    views: readonly DashboardView[] | undefined
  ) => void;
}

type Step = "what" | "source" | "settings";

const STEP_LABELS = {
  what: "stepWhat",
  source: "stepSource",
  settings: "stepSettings",
} as const;

/** Value of "Start from" for a custom view (never a saved view's id). */
const CUSTOM_VIEW = "__custom_view__";

/** Re-renders when a source's state changes. */
function useLoaderUpdates(loader: DashboardSourceLoader<DashboardTableSource>) {
  const [, rerender] = useReducer((value: number) => value + 1, 0);
  useEffect(() => loader.subscribe(() => rerender()), [loader]);
}

/** The saved views of the source picked (static ones, then `views.list`). */
function usePickedViews(
  source: DashboardTableSource | undefined,
  tableId: string
): DashboardView[] | undefined {
  const [views, setViews] = useState<DashboardView[]>();
  useEffect(() => {
    setViews(undefined);
    if (!(source && tableId)) {
      return;
    }
    let cancelled = false;
    loadDashboardViews(source, tableId)
      .catch(() => loadDashboardViews({ views: source.views }, tableId))
      .then((loaded) => {
        if (!cancelled) {
          setViews(loaded);
        }
      })
      .catch(() => undefined);
    return () => {
      cancelled = true;
    };
  }, [source, tableId]);
  return views;
}

/** Step 1: a number, a view, a table page, a note, or one of the host's blocks. */
function KindStep({
  choices,
  label,
  onChoose,
}: {
  choices: DashboardWidgetChoice[];
  label: DashboardLabel;
  onChoose: (choice: DashboardWidgetChoice) => void;
}) {
  const groups = [...new Set(choices.map((choice) => choice.group))];
  const prefix = useId();
  return (
    <fieldset className="grid gap-3" data-widget-kinds="">
      <legend className="mb-2 font-medium text-sm">
        {label("chooseKind")}
      </legend>
      {groups.map((group) => (
        <div className="grid gap-1.5" key={group || "-"}>
          {group ? (
            <p className="text-muted-foreground text-xs" data-kind-group="">
              {group}
            </p>
          ) : null}
          <ul className="m-0 grid list-none gap-1.5 p-0 sm:grid-cols-2">
            {choices
              .filter((choice) => choice.group === group)
              .map((choice) => {
                const key = choice.block ?? choice.kind;
                const hint = `${prefix}-${key}`;
                return (
                  <li key={key}>
                    <button
                      aria-describedby={choice.description ? hint : undefined}
                      aria-label={choice.label}
                      className="flex h-full w-full flex-col items-start gap-0.5 rounded-lg border px-3 py-2 text-left text-sm hover:bg-muted focus-visible:outline-2 focus-visible:outline-ring"
                      data-widget-block={choice.block}
                      data-widget-kind={choice.kind}
                      onClick={() => onChoose(choice)}
                      type="button"
                    >
                      <span className="font-medium">{choice.label}</span>
                      {choice.description ? (
                        <span
                          className="text-muted-foreground text-xs"
                          id={hint}
                        >
                          {choice.description}
                        </span>
                      ) : null}
                    </button>
                  </li>
                );
              })}
          </ul>
        </div>
      ))}
    </fieldset>
  );
}

/** "Start from": the source's default view, a saved view, or a custom view edited in the view editor. */
function ViewChoice({
  canEditView,
  draft,
  id,
  label,
  onEditView,
  setDraft,
  views,
}: {
  canEditView: boolean;
  draft: DashboardWidgetDraft;
  id: string;
  label: DashboardLabel;
  onEditView: () => void;
  setDraft: (draft: DashboardWidgetDraft) => void;
  views?: readonly DashboardView[];
}) {
  const known = views?.some((view) => view.id === draft.viewId);
  const choose = (value: string) => {
    const { view: _view, ...rest } = draft;
    if (value !== CUSTOM_VIEW) {
      setDraft({ ...rest, viewId: value });
      return;
    }
    // A custom view starts from the view chosen so far.
    const saved = views?.find((view) => view.id === draft.viewId);
    setDraft({
      ...rest,
      viewId: "",
      view: saved ? canonicalViewConfig(saved.config) : {},
    });
  };
  return (
    <>
      <Field htmlFor={id} label={label("startFrom")}>
        <NativeSelect
          className="w-full"
          id={id}
          onChange={(event) => choose(event.target.value)}
          value={draft.view ? CUSTOM_VIEW : draft.viewId}
        >
          <NativeSelectOption value="">
            {label("defaultView")}
          </NativeSelectOption>
          {views?.length ? (
            <NativeSelectOptGroup label={label("savedViews")}>
              {views.map((view) => (
                <NativeSelectOption key={view.id} value={view.id}>
                  {view.name}
                </NativeSelectOption>
              ))}
            </NativeSelectOptGroup>
          ) : null}
          {draft.viewId && !known ? (
            <NativeSelectOption value={draft.viewId}>
              {draft.viewId}
            </NativeSelectOption>
          ) : null}
          <NativeSelectOption value={CUSTOM_VIEW}>
            {label("customView")}
          </NativeSelectOption>
        </NativeSelect>
      </Field>
      {draft.view ? (
        <div
          className="flex flex-wrap items-center gap-2 rounded-lg border border-dashed px-3 py-2 text-sm"
          data-custom-view=""
        >
          <p className="m-0 min-w-0 flex-1 text-muted-foreground">
            {label("customViewHint")}
          </p>
          <Button
            disabled={!canEditView}
            onClick={onEditView}
            size="sm"
            type="button"
            variant="outline"
          >
            <Pencil aria-hidden="true" />
            {label("editView")}
          </Button>
        </div>
      ) : null}
    </>
  );
}

/** A block's props: the host's settings component, else JSON checked before it applies. */
function BlockPropsField({
  blocks,
  check,
  draft,
  id,
  label,
  locale,
  onText,
  setDraft,
  text,
  widgetId,
}: {
  blocks?: DashboardBlockRegistry;
  check?: DashboardBlockPropsDraft;
  draft: DashboardWidgetDraft;
  id: string;
  label: DashboardLabel;
  locale: string;
  onText: (text: string) => void;
  setDraft: (draft: DashboardWidgetDraft) => void;
  text: string;
  widgetId: string;
}) {
  const block =
    blocks && draft.block && Object.hasOwn(blocks, draft.block)
      ? blocks[draft.block]
      : undefined;
  const Settings = block?.settings;
  const problems = check?.issues.filter((issue) =>
    check.ok ? issue.severity === "warning" : true
  );
  return (
    <div className="grid gap-2" data-block-props="">
      {Settings ? (
        <Settings
          locale={locale}
          onChange={(props: DashboardJsonObject) =>
            setDraft({ ...draft, props })
          }
          props={draft.props ?? {}}
          widgetId={widgetId}
        />
      ) : (
        <Field htmlFor={id} label={label("blockProps")}>
          <Textarea
            aria-invalid={check && !check.ok ? true : undefined}
            className="font-mono text-xs"
            id={id}
            onChange={(event) => onText(event.target.value)}
            rows={8}
            spellCheck={false}
            value={text}
          />
        </Field>
      )}
      {check && !check.json ? (
        <p
          className="m-0 text-destructive text-sm"
          data-props-error=""
          role="alert"
        >
          {label("invalidJson")}
        </p>
      ) : null}
      {problems?.length ? (
        <div
          className="grid gap-1 text-sm"
          data-props-error=""
          role={check?.ok ? undefined : "alert"}
        >
          {check?.ok ? null : (
            <p className="m-0 text-destructive">{label("propsRefused")}</p>
          )}
          <ul className="m-0 list-disc ps-5">
            {problems.map((issue) => (
              <li key={`${issue.path ?? ""}:${issue.message}`}>
                {issue.path ? <code>{issue.path}</code> : null}
                {issue.path ? ": " : null}
                {issue.message}
              </li>
            ))}
          </ul>
        </div>
      ) : null}
    </div>
  );
}

/** The dialog's steps: what, source (widgets reading one), settings; edits start at the settings. */
const dialogSteps = (reads: boolean, editing: boolean): Step[] => {
  const steps: Step[] = reads
    ? ["what", "source", "settings"]
    : ["what", "settings"];
  return editing ? steps.filter((step) => step !== "what") : steps;
};

/** A block's props checked before they apply: its settings component's, else the JSON typed. */
const checkBlockDraft = (
  draft: DashboardWidgetDraft,
  text: string,
  blocks?: DashboardBlockRegistry
): DashboardBlockPropsDraft => {
  const key = draft.block ?? "";
  const hasSettings = Boolean(
    blocks && Object.hasOwn(blocks, key) && blocks[key]?.settings
  );
  return hasSettings
    ? {
        json: true,
        ...checkDashboardBlockProps(key, draft.props ?? {}, { blocks }),
      }
    : parseDashboardBlockProps(text, key, { blocks });
};

/** Why a picked source cannot be used: unavailable (its reason) or failing. */
const loadFailureText = (
  loaded: DashboardSourceState<DashboardTableSource>,
  locale: string,
  translate: DashboardTranslate,
  label: DashboardLabel
): string =>
  loaded.status === "unavailable"
    ? dashboardUnavailableText(loaded.reason, loaded.message, locale, translate)
    : label("widgetError", {
        error: loaded.status === "error" ? loaded.message : "",
      });

/** The draft of a new source: its view and columns start over. */
const withSource = (
  draft: DashboardWidgetDraft,
  tableId: string
): DashboardWidgetDraft => {
  if (draft.tableId === tableId) {
    return draft;
  }
  const { view: _view, ...rest } = draft;
  return {
    ...rest,
    tableId,
    viewId: "",
    metricColumn: "",
    dateColumn: "",
    compare: false,
    sparkline: false,
  };
};

interface SettingsStepProps {
  blocks?: DashboardBlockRegistry;
  draft: DashboardWidgetDraft;
  setDraft: (draft: DashboardWidgetDraft) => void;
  ids: Record<string, string>;
  info?: DashboardTableInfo;
  label: DashboardLabel;
  locale: string;
  onEditView: () => void;
  onText: (text: string) => void;
  propsCheck?: DashboardBlockPropsDraft;
  propsText: string;
  source?: DashboardTableSource;
  sourceName: string;
  translate: DashboardTranslate;
  views?: readonly DashboardView[];
  widgetId: string;
}

/** Step 3: the widget's view, value, title, text or props. */
function SettingsStep({
  blocks,
  draft,
  ids,
  info,
  label,
  locale,
  onEditView,
  onText,
  propsCheck,
  propsText,
  setDraft,
  source,
  sourceName,
  translate,
  views,
  widgetId,
}: SettingsStepProps) {
  const reads = dashboardKindReadsSource(draft.type);
  return (
    <div className="grid gap-4">
      {reads ? (
        <p className="m-0 text-muted-foreground text-sm" data-widget-source="">
          {label("stepSource")}:{" "}
          <span className="text-foreground">{sourceName}</span>
        </p>
      ) : null}
      {reads ? (
        <ViewChoice
          canEditView={Boolean(source)}
          draft={draft}
          id={ids.view ?? ""}
          label={label}
          onEditView={onEditView}
          setDraft={setDraft}
          views={views}
        />
      ) : null}
      {draft.type === "view" ? (
        <OverflowField
          draft={draft}
          ids={ids}
          label={label}
          setDraft={setDraft}
        />
      ) : null}
      {draft.type === "kpi" && info ? (
        <KpiFields
          draft={draft}
          ids={ids}
          label={label}
          locale={locale}
          setDraft={setDraft}
          tables={{ [draft.tableId]: info }}
          translate={translate}
        />
      ) : null}
      <Field htmlFor={ids.title ?? ""} label={label("widgetTitle")}>
        <Input
          id={ids.title}
          maxLength={120}
          onChange={(event) =>
            setDraft({ ...draft, title: event.target.value })
          }
          value={draft.title}
        />
      </Field>
      {draft.type === "note" ? (
        <Field htmlFor={ids.text ?? ""} label={label("noteText")}>
          <Textarea
            id={ids.text}
            maxLength={20_000}
            onChange={(event) =>
              setDraft({ ...draft, text: event.target.value })
            }
            rows={5}
            value={draft.text}
          />
        </Field>
      ) : null}
      {draft.type === "block" ? (
        <BlockPropsField
          blocks={blocks}
          check={propsCheck}
          draft={draft}
          id={ids.props ?? ""}
          label={label}
          locale={locale}
          onText={onText}
          setDraft={setDraft}
          text={propsText}
          widgetId={widgetId}
        />
      ) : null}
    </div>
  );
}

/** Picking a source: it loads once; unavailable or failing, the reason shows. */
function useSourcePick({
  label,
  loader,
  locale,
  onReady,
  translate,
}: {
  label: DashboardLabel;
  loader: DashboardSourceLoader<DashboardTableSource>;
  locale: string;
  onReady: (id: string) => void;
  translate: DashboardTranslate;
}) {
  const [picking, setPicking] = useState<string>();
  const [pickError, setPickError] = useState<string>();
  const mounted = useRef(true);
  useEffect(
    () => () => {
      mounted.current = false;
    },
    []
  );
  const ready = useRef(onReady);
  ready.current = onReady;
  const pickSource = (id: string) => {
    setPicking(id);
    setPickError(undefined);
    loader
      .load(id)
      .then((loaded) => {
        if (!mounted.current) {
          return;
        }
        setPicking(undefined);
        if (loaded.status === "ready") {
          ready.current(id);
        } else {
          setPickError(loadFailureText(loaded, locale, translate, label));
        }
      })
      .catch(() => setPicking(undefined));
  };
  return { picking, pickError, pickSource };
}

/** Back (when there is a step before), Cancel, and Add or Apply on the settings. */
function DialogButtons({
  canSubmit,
  editing,
  label,
  onBack,
  onCancel,
  step,
}: {
  canSubmit: boolean;
  editing: boolean;
  label: DashboardLabel;
  onBack?: () => void;
  onCancel: () => void;
  step: Step;
}) {
  return (
    <DialogFooter>
      {onBack ? (
        <Button
          className="sm:me-auto"
          onClick={onBack}
          type="button"
          variant="ghost"
        >
          <ChevronLeft aria-hidden="true" />
          {label("back")}
        </Button>
      ) : null}
      <Button onClick={onCancel} type="button" variant="outline">
        {label("cancel")}
      </Button>
      {step === "settings" ? (
        <Button disabled={!canSubmit} type="submit">
          {label(editing ? "apply" : "add")}
        </Button>
      ) : null}
    </DialogFooter>
  );
}

/** One opening of the dialog: its draft, steps and the view editor on top. */
function WidgetDialogSession({
  blocks,
  getRowId,
  label,
  loader,
  locale,
  onOpenChange,
  onSubmit,
  renderers,
  tableTranslations,
  target,
  translate,
}: Omit<DashboardWidgetDialogProps, "open">) {
  useLoaderUpdates(loader);
  const edited = target.mode === "edit" ? target.widget : undefined;
  const [draft, setDraft] = useState<DashboardWidgetDraft>(() =>
    edited ? dashboardWidgetDraft(edited, locale) : emptyWidgetDraft()
  );
  const [step, setStep] = useState<Step>(edited ? "settings" : "what");
  const [propsText, setPropsText] = useState(() =>
    dashboardBlockPropsText(draft.props)
  );
  const [propsCheck, setPropsCheck] = useState<DashboardBlockPropsDraft>();
  const [viewEditing, setViewEditing] = useState(false);
  const { picking, pickError, pickSource } = useSourcePick({
    label,
    loader,
    locale,
    onReady: (id) => {
      setDraft((current) => withSource(current, id));
      setStep("settings");
    },
    translate,
  });
  const prefix = useId();
  const ids = Object.fromEntries(
    [
      "view",
      "overflow",
      "metric",
      "column",
      "date",
      "compare",
      "days",
      "better",
      "sparkline",
      "title",
      "text",
      "props",
    ].map((name) => [name, `${prefix}-${name}`])
  );

  const reads = dashboardKindReadsSource(draft.type);
  const state = draft.tableId ? loader.state(draft.tableId) : undefined;
  const source = state?.status === "ready" ? state.source : undefined;
  const views = usePickedViews(source, draft.tableId);
  // An edited widget's source loads once, like on the screen.
  useEffect(() => {
    if (reads && draft.tableId) {
      loader.load(draft.tableId).catch(() => undefined);
    }
  }, [draft.tableId, loader, reads]);
  const info = source ? tableInfo(draft.tableId, source) : undefined;
  const steps = dialogSteps(reads, Boolean(edited));
  const index = steps.indexOf(step);

  const chooseKind = (choice: DashboardWidgetChoice) => {
    const block =
      choice.block && blocks && Object.hasOwn(blocks, choice.block)
        ? blocks[choice.block]
        : undefined;
    const props = { ...block?.defaultProps };
    setDraft({
      ...emptyWidgetDraft(),
      type: choice.kind,
      ...(choice.block ? { block: choice.block, props } : {}),
    });
    setPropsText(dashboardBlockPropsText(props));
    setPropsCheck(undefined);
    setStep(dashboardKindReadsSource(choice.kind) ? "source" : "settings");
  };
  const submit = (event: FormEvent) => {
    event.preventDefault();
    // Enter in the catalogue's search picks a source; only settings submit.
    if (step !== "settings") {
      return;
    }
    let next = draft;
    if (draft.type === "block") {
      const checked = checkBlockDraft(draft, propsText, blocks);
      setPropsCheck(checked);
      if (!(checked.ok && checked.props)) {
        return;
      }
      next = { ...draft, props: checked.props };
    }
    onSubmit(
      dashboardWidgetFromDraft(
        next,
        edited ? { widget: edited, locale } : undefined
      ),
      views
    );
    onOpenChange(false);
  };
  const sourceName = info?.name ?? draft.tableId;
  let body: ReactNode;
  if (step === "what") {
    body = (
      <KindStep
        choices={dashboardWidgetChoices({
          section: target.mode === "add" ? target.sectionType : undefined,
          blocks,
          locale,
          translate,
        })}
        label={label}
        onChoose={chooseKind}
      />
    );
  } else if (step === "source") {
    body = (
      <div className="grid gap-2">
        <DashboardSourcePicker
          label={label}
          loader={loader}
          locale={locale}
          onPick={pickSource}
          picking={picking}
          translate={translate}
          value={draft.tableId}
        />
        {pickError ? (
          <p className="m-0 text-destructive text-sm" role="alert">
            {pickError}
          </p>
        ) : null}
      </div>
    );
  } else {
    body = (
      <SettingsStep
        blocks={blocks}
        draft={draft}
        ids={ids}
        info={info}
        label={label}
        locale={locale}
        onEditView={() => setViewEditing(true)}
        onText={(text) => {
          setPropsText(text);
          setPropsCheck(undefined);
        }}
        propsCheck={propsCheck}
        propsText={propsText}
        setDraft={setDraft}
        source={source}
        sourceName={sourceName}
        translate={translate}
        views={views}
        widgetId={edited?.id ?? ""}
      />
    );
  }
  return (
    <DialogContent
      className="max-h-[calc(100dvh-2rem)] overflow-y-auto sm:max-w-2xl"
      data-dashboard-dialog="widget"
      data-widget-step={step}
    >
      <DialogHeader>
        <DialogTitle>
          {label(edited ? "editWidgetTitle" : "addWidgetTitle")}
        </DialogTitle>
        <DialogDescription data-widget-step-label="">
          {label("stepOf", { step: index + 1, count: steps.length })} ·{" "}
          {label(STEP_LABELS[step])}
        </DialogDescription>
      </DialogHeader>
      <form className="grid gap-4" onSubmit={submit}>
        {body}
        <DialogButtons
          canSubmit={!reads || Boolean(draft.tableId)}
          editing={Boolean(edited)}
          label={label}
          onBack={
            index > 0 ? () => setStep(steps[index - 1] ?? step) : undefined
          }
          onCancel={() => onOpenChange(false)}
          step={step}
        />
      </form>
      {source && viewEditing ? (
        <DashboardViewEditor
          getRowId={getRowId}
          label={label}
          locale={locale}
          onApply={(view) => setDraft({ ...draft, viewId: "", view })}
          onClose={() => setViewEditing(false)}
          open
          renderers={renderers}
          source={source}
          sourceId={draft.tableId}
          start={dashboardViewEditStart({ view: draft.view ?? {} })}
          subtitle={sourceName}
          translations={tableTranslations}
        />
      ) : null}
    </DialogContent>
  );
}

/**
 * The widget dialog, adding or editing a widget in three steps: what (a
 * number, a view, a table page, a note or one of the host's blocks, as the
 * section takes them), its source (the host's catalogue, searchable; sources
 * this user cannot use are listed, disabled, with the reason) and its
 * settings (a saved, default or custom view edited in the view editor; the
 * number's value, period and trend; a block's settings or props as JSON,
 * checked before they apply).
 */
export function DashboardWidgetDialog({
  open,
  ...props
}: DashboardWidgetDialogProps) {
  return (
    <Dialog onOpenChange={props.onOpenChange} open={open}>
      {open ? <WidgetDialogSession {...props} /> : null}
    </Dialog>
  );
}

// packages/yayaw-table-vue/src/dashboard/DashboardWidgetDialog.vue
<script setup lang="ts">
/**
 * The widget dialog, adding or editing a widget in three steps: what (a
 * number, a view, a table page, a note or one of the host's blocks, as the
 * section takes them), its source (the host's catalogue, searchable; sources
 * this user cannot use are listed, disabled, with the reason) and its
 * settings (a saved, default or custom view edited in the view editor; the
 * number's value, period and trend; a block's settings or props as JSON,
 * checked before they apply).
 */
import { ChevronLeft, Pencil, X } from "lucide-vue-next";
import {
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogOverlay,
  DialogPortal,
  DialogRoot,
  DialogTitle,
} from "reka-ui";
import { computed, onBeforeUnmount, ref, shallowRef, useId, watch } from "vue";
import type { DisplayModeRenderers } from "../display-mode-renderer";
import type { DataTableTranslations, TableRecord } from "../types";
import { canonicalViewConfig } from "../view-config";
import DashboardBlockProps from "./DashboardBlockProps.vue";
import DashboardKpiFields from "./DashboardKpiFields.vue";
import DashboardSourcePicker from "./DashboardSourcePicker.vue";
import DashboardViewEditor from "./DashboardViewEditor.vue";
import { tableInfo } from "./dashboard-composables";
import {
  type DashboardBlockPropsDraft,
  type DashboardWidgetChoice,
  type DashboardWidgetDialogTarget,
  dashboardBlockPropsText,
  dashboardKindReadsSource,
  dashboardViewEditStart,
  dashboardWidgetChoices,
  parseDashboardBlockProps,
} from "./dashboard-editor-model";
import {
  type DashboardOverflow,
  type DashboardTranslate,
  type DashboardView,
  type DashboardWidgetDraft,
  dashboardUnavailableText,
  dashboardWidgetDraft,
  dashboardWidgetFromDraft,
  emptyWidgetDraft,
  loadDashboardViews,
} from "./dashboard-model";
import {
  checkDashboardBlockProps,
  type DashboardWidget,
} from "./dashboard-schema";
import type { DashboardSourceLoader } from "./dashboard-sources";
import type {
  DashboardBlockRegistry,
  DashboardLabel,
  DashboardTableSource,
} from "./dashboard-types";

const props = defineProps<{
  target: DashboardWidgetDialogTarget;
  loader: DashboardSourceLoader<DashboardTableSource>;
  blocks?: DashboardBlockRegistry;
  label: DashboardLabel;
  locale: string;
  translate: DashboardTranslate;
  /** For the view editor's table. */
  renderers?: DisplayModeRenderers;
  getRowId?: (row: TableRecord) => string;
  tableTranslations?: DataTableTranslations;
}>();
const emit = defineEmits<{
  close: [];
  /** The widget the dialog describes (without its id), and its source's saved views. */
  submit: [widget: Omit<DashboardWidget, "id">, views: readonly DashboardView[] | undefined];
}>();

type Step = "what" | "source" | "settings";
const STEP_LABELS = { what: "stepWhat", source: "stepSource", settings: "stepSettings" } as const;
/** Value of "Start from" for a custom view (never a saved view's id). */
const CUSTOM_VIEW = "__custom_view__";

const target = props.target;
const editing = target.mode === "edit";
// Replaced on every change (never mutated): shallow, like the JSON it holds.
const draft = shallowRef<DashboardWidgetDraft>(
  target.mode === "edit" ? dashboardWidgetDraft(target.widget, props.locale) : emptyWidgetDraft()
);
const step = ref<Step>(editing ? "settings" : "what");
const picking = ref<string>();
const pickError = ref<string>();
const propsText = ref(dashboardBlockPropsText(draft.value.props));
const propsCheck = shallowRef<DashboardBlockPropsDraft>();
const viewEditing = ref(false);
const prefix = `dashboard-widget-${useId()}`;

// Sources change state as they load: follow them.
const version = ref(0);
const unsubscribe = props.loader.subscribe(() => {
  version.value += 1;
});
let unmounted = false;
onBeforeUnmount(() => {
  unmounted = true;
  unsubscribe();
});

const reads = computed(() => dashboardKindReadsSource(draft.value.type));
const source = computed(() => {
  version.value;
  const state = draft.value.tableId ? props.loader.state(draft.value.tableId) : undefined;
  return state?.status === "ready" ? state.source : undefined;
});
const info = computed(() => (source.value ? tableInfo(draft.value.tableId, source.value) : undefined));
const sourceName = computed(() => info.value?.name ?? draft.value.tableId);
// An edited widget's source loads once, like on the screen.
watch(
  () => [reads.value, draft.value.tableId] as const,
  ([sourced, tableId]) => {
    if (sourced && tableId) props.loader.load(tableId).catch(() => undefined);
  },
  { immediate: true }
);
/** The saved views of the source picked (static ones, then `views.list`). */
const views = shallowRef<DashboardView[]>();
watch(
  () => [source.value, draft.value.tableId] as const,
  ([picked, tableId], _previous, onCleanup) => {
    views.value = undefined;
    if (!(picked && tableId)) return;
    let cancelled = false;
    onCleanup(() => {
      cancelled = true;
    });
    loadDashboardViews(picked, tableId)
      .catch(() => loadDashboardViews({ views: picked.views }, tableId))
      .then((loaded) => {
        if (!cancelled) views.value = loaded;
      })
      .catch(() => undefined);
  },
  { immediate: true }
);
const knownView = computed(() => views.value?.some((view) => view.id === draft.value.viewId) ?? false);

const steps = computed<Step[]>(() => {
  const all: Step[] = reads.value ? ["what", "source", "settings"] : ["what", "settings"];
  return editing ? all.filter((item) => item !== "what") : all;
});
const index = computed(() => steps.value.indexOf(step.value));
const choices = computed(() =>
  dashboardWidgetChoices({
    section: target.mode === "add" ? target.sectionType : undefined,
    blocks: props.blocks,
    locale: props.locale,
    translate: props.translate,
  })
);
const groups = computed(() => [...new Set(choices.value.map((choice) => choice.group))]);
const inGroup = (group: string) => choices.value.filter((choice) => choice.group === group);
const choiceKey = (choice: DashboardWidgetChoice) => choice.block ?? choice.kind;

const chooseKind = (choice: DashboardWidgetChoice): void => {
  const block =
    choice.block && props.blocks && Object.hasOwn(props.blocks, choice.block)
      ? props.blocks[choice.block]
      : undefined;
  const blockProps = { ...block?.defaultProps };
  draft.value = {
    ...emptyWidgetDraft(),
    type: choice.kind,
    ...(choice.block ? { block: choice.block, props: blockProps } : {}),
  };
  propsText.value = dashboardBlockPropsText(blockProps);
  propsCheck.value = undefined;
  step.value = dashboardKindReadsSource(choice.kind) ? "source" : "settings";
};
const pickSource = (id: string): void => {
  picking.value = id;
  pickError.value = undefined;
  props.loader
    .load(id)
    .then((loaded) => {
      if (unmounted) return;
      picking.value = undefined;
      if (loaded.status !== "ready") {
        pickError.value =
          loaded.status === "unavailable"
            ? dashboardUnavailableText(loaded.reason, loaded.message, props.locale, props.translate)
            : props.label("widgetError", { error: loaded.status === "error" ? loaded.message : "" });
        return;
      }
      if (draft.value.tableId !== id) {
        const { view: _view, ...rest } = draft.value;
        draft.value = {
          ...rest,
          tableId: id,
          viewId: "",
          metricColumn: "",
          dateColumn: "",
          compare: false,
          sparkline: false,
        };
      }
      step.value = "settings";
    })
    .catch(() => {
      picking.value = undefined;
    });
};
const chooseView = (value: string): void => {
  const { view: _view, ...rest } = draft.value;
  if (value !== CUSTOM_VIEW) {
    draft.value = { ...rest, viewId: value };
    return;
  }
  // A custom view starts from the view chosen so far.
  const saved = views.value?.find((view) => view.id === draft.value.viewId);
  draft.value = { ...rest, viewId: "", view: saved ? canonicalViewConfig(saved.config) : {} };
};
const setDraft = (patch: Partial<DashboardWidgetDraft>): void => {
  draft.value = { ...draft.value, ...patch };
};
const setText = (text: string): void => {
  propsText.value = text;
  propsCheck.value = undefined;
};
const back = (): void => {
  step.value = steps.value[index.value - 1] ?? step.value;
};
const ready = computed(() => (reads.value ? Boolean(draft.value.tableId) : true));
const submit = (): void => {
  // Enter in the catalogue's search picks a source; only settings submit.
  if (step.value !== "settings") return;
  let next = draft.value;
  const key = next.block;
  if (next.type === "block" && key) {
    const hasSettings = Boolean(props.blocks && Object.hasOwn(props.blocks, key) && props.blocks[key]?.settings);
    const checked: DashboardBlockPropsDraft = hasSettings
      ? { json: true, ...checkDashboardBlockProps(key, next.props ?? {}, { blocks: props.blocks }) }
      : parseDashboardBlockProps(propsText.value, key, { blocks: props.blocks });
    propsCheck.value = checked;
    if (!(checked.ok && checked.props)) return;
    next = { ...next, props: checked.props };
  }
  emit(
    "submit",
    dashboardWidgetFromDraft(next, target.mode === "edit" ? { widget: target.widget, locale: props.locale } : undefined),
    views.value
  );
  emit("close");
};
const viewStart = computed(() => dashboardViewEditStart({ view: draft.value.view ?? {} }));
</script>

<template>
  <DialogRoot :open="true" @update:open="(open: boolean) => { if (!open) emit('close'); }">
    <DialogPortal>
      <DialogOverlay class="yayaw-dashboard-dialog-backdrop" />
      <DialogContent
        class="yayaw-dashboard-dialog yayaw-dashboard-dialog-wide yayaw-dashboard-editor-dialog"
        data-dashboard-dialog="widget"
        :data-widget-step="step"
      >
        <div class="yayaw-dashboard-dialog-heading">
          <DialogTitle as="h2">{{ props.label(editing ? "editWidgetTitle" : "addWidgetTitle") }}</DialogTitle>
          <DialogDescription class="yayaw-dashboard-muted" data-widget-step-label="">
            {{ props.label("stepOf", { step: index + 1, count: steps.length }) }} · {{ props.label(STEP_LABELS[step]) }}
          </DialogDescription>
        </div>
        <DialogClose class="yayaw-dashboard-icon-button yayaw-dashboard-dialog-close" :aria-label="props.label('close')">
          <X :size="16" aria-hidden="true" />
        </DialogClose>
        <form class="yayaw-dashboard-dialog-form" @submit.prevent="submit">
          <div class="yayaw-dashboard-dialog-body" data-dashboard-dialog-body="">
            <fieldset v-if="step === 'what'" class="yayaw-dashboard-kinds" data-widget-kinds="">
              <legend>{{ props.label("chooseKind") }}</legend>
              <div v-for="group in groups" :key="group || '-'" class="yayaw-dashboard-kind-group">
                <p v-if="group" class="yayaw-dashboard-kind-heading" data-kind-group="">{{ group }}</p>
                <ul class="yayaw-dashboard-kind-list">
                  <li v-for="choice in inGroup(group)" :key="choiceKey(choice)">
                    <button
                      type="button"
                      class="yayaw-dashboard-kind"
                      :aria-label="choice.label"
                      :aria-describedby="choice.description ? `${prefix}-${choiceKey(choice)}` : undefined"
                      :data-widget-kind="choice.kind"
                      :data-widget-block="choice.block"
                      @click="chooseKind(choice)"
                    >
                      <span class="yayaw-dashboard-kind-label">{{ choice.label }}</span>
                      <span v-if="choice.description" :id="`${prefix}-${choiceKey(choice)}`" class="yayaw-dashboard-kind-hint">{{ choice.description }}</span>
                    </button>
                  </li>
                </ul>
              </div>
            </fieldset>
            <div v-else-if="step === 'source'" class="yayaw-dashboard-form">
              <DashboardSourcePicker
                :loader="props.loader"
                :label="props.label"
                :locale="props.locale"
                :translate="props.translate"
                :value="draft.tableId"
                :picking="picking"
                @pick="pickSource"
              />
              <p v-if="pickError" class="yayaw-dashboard-props-error" role="alert">{{ pickError }}</p>
            </div>
            <template v-else>
              <div class="yayaw-dashboard-field">
                <label :for="`${prefix}-title`">{{ props.label("widgetTitle") }}</label>
                <input
                  :id="`${prefix}-title`"
                  class="yayaw-input"
                  maxlength="120"
                  :value="draft.title"
                  @input="setDraft({ title: ($event.target as HTMLInputElement).value })"
                >
              </div>

              <fieldset v-if="reads" class="yayaw-dashboard-settings-group">
                <legend>{{ props.label("stepSource") }}</legend>
                <div class="yayaw-dashboard-settings-fields">
                  <p class="yayaw-dashboard-muted yayaw-dashboard-source-line" data-widget-source="">
                    <span>{{ sourceName }}</span>
                  </p>
                  <div class="yayaw-dashboard-field">
                    <label :for="`${prefix}-view`">{{ props.label("startFrom") }}</label>
                    <select
                      :id="`${prefix}-view`"
                      class="yayaw-select"
                      :value="draft.view ? CUSTOM_VIEW : draft.viewId"
                      @change="chooseView(($event.target as HTMLSelectElement).value)"
                    >
                      <option value="">{{ props.label("defaultView") }}</option>
                      <optgroup v-if="views?.length" :label="props.label('savedViews')">
                        <option v-for="view in views" :key="view.id" :value="view.id">{{ view.name }}</option>
                      </optgroup>
                      <option v-if="draft.viewId && !knownView" :value="draft.viewId">{{ draft.viewId }}</option>
                      <option :value="CUSTOM_VIEW">{{ props.label("customView") }}</option>
                    </select>
                  </div>
                  <div v-if="draft.view" class="yayaw-dashboard-custom-view" data-custom-view="">
                    <p>{{ props.label("customViewHint") }}</p>
                    <button type="button" class="yayaw-button yayaw-button-outline" :disabled="!source" @click="viewEditing = true">
                      <Pencil :size="16" aria-hidden="true" />{{ props.label("editView") }}
                    </button>
                  </div>
                </div>
              </fieldset>
              <div v-if="draft.type === 'view'" class="yayaw-dashboard-field">
                <label :for="`${prefix}-overflow`">{{ props.label("overflow") }}</label>
                <select
                  :id="`${prefix}-overflow`"
                  class="yayaw-select"
                  :value="draft.overflow"
                  @change="setDraft({ overflow: ($event.target as HTMLSelectElement).value as DashboardOverflow })"
                >
                  <option value="fit">{{ props.label("overflowFit") }}</option>
                  <option value="scroll">{{ props.label("overflowScroll") }}</option>
                </select>
              </div>
              <DashboardKpiFields
                v-if="draft.type === 'kpi' && info"
                :draft="draft"
                :columns="info.columns"
                :prefix="prefix"
                :label="props.label"
                :locale="props.locale"
                :translate="props.translate"
                @update:draft="(next) => (draft = next)"
              />
              <div v-if="draft.type === 'note'" class="yayaw-dashboard-field">
                <label :for="`${prefix}-text`">{{ props.label("noteText") }}</label>
                <textarea
                  :id="`${prefix}-text`"
                  class="yayaw-textarea"
                  rows="5"
                  maxlength="20000"
                  :value="draft.text"
                  @input="setDraft({ text: ($event.target as HTMLTextAreaElement).value })"
                />
              </div>
              <DashboardBlockProps
                v-if="draft.type === 'block'"
                :blocks="props.blocks"
                :draft="draft"
                :text="propsText"
                :check="propsCheck"
                :id="`${prefix}-props`"
                :label="props.label"
                :locale="props.locale"
                :widget-id="target.mode === 'edit' ? target.widget.id : ''"
                @update:draft="(next) => (draft = next)"
                @update:text="setText"
              />
            </template>
          </div>
          <footer class="yayaw-dashboard-dialog-footer">
            <button v-if="index > 0" type="button" class="yayaw-button yayaw-button-ghost yayaw-dashboard-back" @click="back">
              <ChevronLeft :size="16" aria-hidden="true" />{{ props.label("back") }}
            </button>
            <button type="button" class="yayaw-button yayaw-button-outline" @click="emit('close')">{{ props.label("cancel") }}</button>
            <button v-if="step === 'settings'" type="submit" class="yayaw-button" :disabled="!ready">
              {{ props.label(editing ? "apply" : "add") }}
            </button>
          </footer>
        </form>
        <DashboardViewEditor
          v-if="viewEditing && source"
          :source="source"
          :source-id="draft.tableId"
          :start="viewStart"
          :subtitle="sourceName"
          :label="props.label"
          :locale="props.locale"
          :renderers="props.renderers"
          :get-row-id="props.getRowId"
          :translations="props.tableTranslations"
          @apply="(view) => setDraft({ viewId: '', view })"
          @close="viewEditing = false"
        />
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
</template>
