// src/components/ui/yayaw-table-dashboard/dashboard-filters.tsx
"use client";

import { X } from "lucide-react";
import { Button } from "@/src/components/ui/button";
import { Input } from "@/src/components/ui/input";
import {
  NativeSelect,
  NativeSelectOption,
} from "@/src/components/ui/native-select";
import {
  type DashboardDateRange,
  type DashboardFilter,
  type DashboardTableInfo,
  dashboardFilterOptions,
  dashboardFilterTargetsLabel,
  isDashboardFilterActive,
} from "./dashboard-model";
import type { DashboardLabel } from "./dashboard-widget";

interface FilterControlProps {
  filter: DashboardFilter;
  tables: Record<string, DashboardTableInfo>;
  editing: boolean;
  label: DashboardLabel;
  onChange: (value: DashboardDateRange | string[] | undefined) => void;
  onRemove: () => void;
}

function DateRangeControl({ filter, label, onChange }: FilterControlProps) {
  const range = (filter.value ?? {}) as DashboardDateRange;
  const update = (part: "start" | "end", value: string) =>
    onChange({ ...range, [part]: value || undefined });
  return (
    <div className="flex flex-wrap items-center gap-2">
      <Input
        aria-label={`${filter.label}: ${label("from")}`}
        className="h-8 w-40"
        data-filter-part="start"
        onChange={(event) => update("start", event.target.value)}
        type="date"
        value={range.start ?? ""}
      />
      <span aria-hidden="true" className="text-muted-foreground">
        –
      </span>
      <Input
        aria-label={`${filter.label}: ${label("to")}`}
        className="h-8 w-40"
        data-filter-part="end"
        onChange={(event) => update("end", event.target.value)}
        type="date"
        value={range.end ?? ""}
      />
    </div>
  );
}

function SelectControl({
  filter,
  label,
  onChange,
  tables,
}: FilterControlProps) {
  const values = Array.isArray(filter.value) ? filter.value : [];
  return (
    <NativeSelect
      aria-label={filter.label}
      className="w-44"
      onChange={(event) =>
        onChange(event.target.value ? [event.target.value] : undefined)
      }
      size="sm"
      value={values.at(0) ?? ""}
    >
      <NativeSelectOption value="">{label("any")}</NativeSelectOption>
      {dashboardFilterOptions(filter, tables).map((option) => (
        <NativeSelectOption key={option.value} value={option.value}>
          {option.label}
        </NativeSelectOption>
      ))}
    </NativeSelect>
  );
}

function DashboardFilterControl(props: FilterControlProps) {
  const { editing, filter, label, onChange, onRemove, tables } = props;
  return (
    <fieldset
      className="flex min-w-0 flex-col gap-1.5"
      data-dashboard-filter={filter.id}
    >
      <legend className="mb-1.5 flex items-center gap-1 font-medium text-sm">
        {filter.label}
        {editing && (
          <Button
            aria-label={label("removeFilter", { name: filter.label })}
            onClick={onRemove}
            size="icon-xs"
            type="button"
            variant="ghost"
          >
            <X aria-hidden="true" />
          </Button>
        )}
      </legend>
      <div className="flex flex-wrap items-center gap-2">
        {filter.type === "dateRange" ? (
          <DateRangeControl {...props} />
        ) : (
          <SelectControl {...props} />
        )}
        {isDashboardFilterActive(filter) && (
          <Button
            onClick={() => onChange(undefined)}
            size="sm"
            type="button"
            variant="ghost"
          >
            {label("clear")}
          </Button>
        )}
      </div>
      <p className="text-muted-foreground text-xs" data-filter-targets="">
        {label("appliesTo", {
          targets: dashboardFilterTargetsLabel(filter, tables),
        })}
      </p>
    </fieldset>
  );
}

/** The dashboard's filters; each joins the widgets it targets. */
export function DashboardFilterBar({
  editing,
  filters,
  label,
  onAddFilter,
  onChange,
  onRemove,
  tables,
}: {
  editing: boolean;
  filters: DashboardFilter[];
  label: DashboardLabel;
  onAddFilter: () => void;
  onChange: (
    filterId: string,
    value: DashboardDateRange | string[] | undefined
  ) => void;
  onRemove: (filterId: string) => void;
  tables: Record<string, DashboardTableInfo>;
}) {
  if (!(filters.length || editing)) {
    return null;
  }
  return (
    <section
      aria-label={label("filters")}
      className="flex flex-wrap items-end gap-x-6 gap-y-3 rounded-xl border bg-muted/40 p-3"
      data-dashboard-filters=""
    >
      {filters.map((filter) => (
        <DashboardFilterControl
          editing={editing}
          filter={filter}
          key={filter.id}
          label={label}
          onChange={(value) => onChange(filter.id, value)}
          onRemove={() => onRemove(filter.id)}
          tables={tables}
        />
      ))}
      {editing && (
        <Button onClick={onAddFilter} size="sm" type="button" variant="outline">
          {label("addFilter")}
        </Button>
      )}
    </section>
  );
}

// packages/yayaw-table-vue/src/dashboard/DashboardFilters.vue
<script setup lang="ts">
import { X } from "lucide-vue-next";
import {
  type DashboardDateRange,
  type DashboardFilter,
  type DashboardTableInfo,
  dashboardFilterOptions,
  dashboardFilterTargetsLabel,
  isDashboardFilterActive,
} from "./dashboard-model";
import type { DashboardLabel } from "./dashboard-types";

/** The dashboard's filters; each joins the widgets it targets. */
const props = defineProps<{
  filters: DashboardFilter[];
  tables: Record<string, DashboardTableInfo>;
  editing: boolean;
  label: DashboardLabel;
}>();
const emit = defineEmits<{
  change: [filterId: string, value: DashboardDateRange | string[] | undefined];
  remove: [filterId: string];
  add: [];
}>();

const rangeOf = (filter: DashboardFilter): DashboardDateRange =>
  (filter.value && !Array.isArray(filter.value) ? filter.value : {}) as DashboardDateRange;
const updateRange = (filter: DashboardFilter, part: "start" | "end", value: string) =>
  emit("change", filter.id, { ...rangeOf(filter), [part]: value || undefined });
const selected = (filter: DashboardFilter): string =>
  Array.isArray(filter.value) ? (filter.value[0] ?? "") : "";
const choose = (filter: DashboardFilter, value: string) =>
  emit("change", filter.id, value ? [value] : undefined);
</script>

<template>
  <section
    v-if="props.filters.length || props.editing"
    class="yayaw-dashboard-filters"
    :aria-label="props.label('filters')"
    data-dashboard-filters=""
  >
    <fieldset v-for="filter in props.filters" :key="filter.id" class="yayaw-dashboard-filter" :data-dashboard-filter="filter.id">
      <legend>
        {{ filter.label }}
        <button
          v-if="props.editing"
          type="button"
          class="yayaw-dashboard-icon-button"
          data-size="xs"
          :aria-label="props.label('removeFilter', { name: filter.label })"
          @click="emit('remove', filter.id)"
        >
          <X :size="12" aria-hidden="true" />
        </button>
      </legend>
      <div class="yayaw-dashboard-filter-row">
        <template v-if="filter.type === 'dateRange'">
          <input
            type="date"
            class="yayaw-input"
            data-filter-part="start"
            :aria-label="`${filter.label}: ${props.label('from')}`"
            :value="rangeOf(filter).start ?? ''"
            @input="updateRange(filter, 'start', ($event.target as HTMLInputElement).value)"
          >
          <span aria-hidden="true" class="yayaw-dashboard-muted">–</span>
          <input
            type="date"
            class="yayaw-input"
            data-filter-part="end"
            :aria-label="`${filter.label}: ${props.label('to')}`"
            :value="rangeOf(filter).end ?? ''"
            @input="updateRange(filter, 'end', ($event.target as HTMLInputElement).value)"
          >
        </template>
        <select
          v-else
          class="yayaw-select"
          :aria-label="filter.label"
          :value="selected(filter)"
          @change="choose(filter, ($event.target as HTMLSelectElement).value)"
        >
          <option value="">{{ props.label("any") }}</option>
          <option v-for="option in dashboardFilterOptions(filter, props.tables)" :key="option.value" :value="option.value">
            {{ option.label }}
          </option>
        </select>
        <button
          v-if="isDashboardFilterActive(filter)"
          type="button"
          class="yayaw-button yayaw-button-ghost"
          @click="emit('change', filter.id, undefined)"
        >
          {{ props.label("clear") }}
        </button>
      </div>
      <p class="yayaw-dashboard-targets" data-filter-targets="">
        {{ props.label("appliesTo", { targets: dashboardFilterTargetsLabel(filter, props.tables) }) }}
      </p>
    </fieldset>
    <button v-if="props.editing" type="button" class="yayaw-button yayaw-button-outline" @click="emit('add')">
      {{ props.label("addFilter") }}
    </button>
  </section>
</template>
