// registry/default/ui/yayaw-table-dashboard/dashboard-page-table.tsx
"use client";

import { useQueryClient } from "@tanstack/react-query";
import {
  type ReactNode,
  useCallback,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { DataTable } from "@/components/ui/yayaw-table/components/data-table";
import type { TableConfig } from "@/components/ui/yayaw-table/config/helpers";
import { invalidateTableDataQuery } from "@/components/ui/yayaw-table/hooks/query-cache-utils";
import type { TableActions } from "@/components/ui/yayaw-table/providers/table-provider";
import type { DisplayModeRenderers } from "@/components/ui/yayaw-table/types/display-mode-renderer";
import type { DataTableTranslations } from "@/components/ui/yayaw-table/types/translations";
import type { TableView } from "@/components/ui/yayaw-table/types/view-types";
import type { ViewConfig } from "@/components/ui/yayaw-table/utils/view-config";
import {
  type DashboardNotice,
  type DashboardWidget,
  dashboardScreenView,
  dashboardTableViews,
  withDashboardFilters,
  withDashboardTableViews,
  withMutationSignal,
  withNoticeCapture,
} from "./dashboard-model";
import {
  type DashboardDataTableProps,
  type DashboardTableSource,
  WidgetNotice,
} from "./dashboard-widget";

// Layout effects run before paint in the browser; the server skips them.
const useBrowserLayoutEffect =
  typeof window === "undefined" ? useEffect : useLayoutEffect;

export interface DashboardPageTableProps {
  dashboardId: string;
  widget: DashboardWidget;
  /** The source id: the table's id, so URL keys, saved views and favorites stay the list page's. */
  sourceId: string;
  source: DashboardTableSource;
  /** None for the screen's first table (canonical URL keys), else the widget's id. */
  instanceId?: string;
  /** Name of the screen's default view (the widget's inline view). */
  screenViewName: string;
  /** The screen filters' rules for this widget (`requiredFilters`). */
  rules: Record<string, unknown>[];
  /** Changes with "Refresh all" and a refresh of this source: rows load again. */
  revision: number;
  /** After each change of the table's records: the screen reloads its other widgets. */
  onMutated: () => void;
  /**
   * The view the table shows (`onViewConfigChange`), which "Make the current
   * view the screen default" stores.
   */
  onViewConfigChange?: (config: ViewConfig) => void;
  /** The screen's URL sync: off keeps the table's state out of the URL too. */
  syncUrl: boolean;
  renderers?: DisplayModeRenderers;
  locale: string;
  translations?: DataTableTranslations;
  getRowId?: (row: Record<string, unknown>) => string;
  noticeText: (notice: DashboardNotice) => string;
}

/** The source's config as a page table on a screen: the screen names it, not the table's header. */
const pageConfig = (config: TableConfig, syncUrl: boolean): TableConfig => ({
  ...config,
  table: {
    ...config.table,
    showToolbarHeader: false,
    ...(syncUrl ? {} : { syncUrl: false }),
  },
});

/**
 * A `table` widget: the source's full list page (toolbar, saved views,
 * selection, URL state) without a card. Its inline view is the screen's
 * default view; the screen's filters reach every request as
 * `requiredFilters`; its changes reload the screen's other widgets.
 */
export function DashboardPageTable({
  dashboardId,
  getRowId,
  instanceId,
  locale,
  noticeText,
  onMutated,
  onViewConfigChange,
  renderers,
  revision,
  rules,
  screenViewName,
  source,
  sourceId,
  syncUrl,
  translations,
  widget,
}: DashboardPageTableProps) {
  const queryClient = useQueryClient();
  const rulesKey = JSON.stringify(rules);
  const mutated = useRef(onMutated);
  mutated.current = onMutated;
  const [notice, setNotice] = useState<DashboardNotice>();
  const screenView = useMemo(
    () => dashboardScreenView(dashboardId, widget, screenViewName),
    [dashboardId, screenViewName, widget]
  );
  const defaultViewId = screenView?.id ?? widget.viewId;
  const actions = useMemo(
    () =>
      withDashboardTableViews(
        withNoticeCapture(
          withMutationSignal(
            withDashboardFilters(
              source.actions,
              JSON.parse(rulesKey) as Record<string, unknown>[]
            ),
            () => mutated.current()
          ),
          setNotice
        ),
        defaultViewId
      ) as TableActions,
    [defaultViewId, rulesKey, source.actions]
  );
  const config = useMemo(
    () => pageConfig(source.config, syncUrl),
    [source.config, syncUrl]
  );
  const hostProps = source.tableProps ?? {};
  const initialViews = useMemo(
    () =>
      dashboardTableViews(
        [...(source.views ?? []), ...(hostProps.initialViews ?? [])],
        {
          screenView: screenView as unknown as TableView | undefined,
          defaultViewId: widget.viewId,
        }
      ),
    [hostProps.initialViews, screenView, source.views, widget.viewId]
  );

  // "Refresh all": the rows load again (a remount would show cached rows).
  const refreshed = useRef(revision);
  useEffect(() => {
    if (refreshed.current === revision) {
      return;
    }
    refreshed.current = revision;
    invalidateTableDataQuery({ queryClient, tableId: sourceId }).catch(
      () => undefined
    );
  }, [queryClient, revision, sourceId]);
  // New screen filters: the table remounts (its key) without the rows cached
  // under the previous filters.
  const filtered = useRef(rulesKey);
  useBrowserLayoutEffect(() => {
    if (filtered.current === rulesKey) {
      return;
    }
    filtered.current = rulesKey;
    queryClient
      .resetQueries({ queryKey: ["tableData", sourceId] })
      .catch(() => undefined);
  }, [queryClient, rulesKey, sourceId]);

  const hostRenderers = hostProps.displayModeRenderers;
  const displayModeRenderers = useMemo(
    () => ({ ...renderers, ...hostRenderers }),
    [hostRenderers, renderers]
  );
  const getTableActions = useCallback(() => actions, [actions]);
  const getTableConfig = useCallback(() => config, [config]);
  // The screen and the host both hear the view the table shows.
  const reported = useRef(onViewConfigChange);
  reported.current = onViewConfigChange;
  const hostReport = hostProps.onViewConfigChange;
  const reportView = useCallback(
    (view: ViewConfig) => {
      reported.current?.(view);
      hostReport?.(view);
    },
    [hostReport]
  );
  const props: DashboardDataTableProps = {
    ...hostProps,
    displayModeRenderers,
    getRowId: hostProps.getRowId ?? getRowId,
    locale: hostProps.locale ?? locale,
    translations: hostProps.translations ?? translations,
    tableType: sourceId,
    tableId: sourceId,
    instanceId,
    getTableActions,
    getTableConfig,
    initialViews,
    onViewConfigChange: reportView,
  };
  const table: ReactNode = source.renderTable ? (
    source.renderTable(props)
  ) : (
    <DataTable {...props} />
  );
  return (
    <div className="flex min-w-0 flex-col gap-2" data-page-table={sourceId}>
      {notice ? (
        <WidgetNotice kind="notice" reason={notice.code}>
          {noticeText(notice)}
        </WidgetNotice>
      ) : null}
      {/* Kept mounted behind a notice, so "Refresh all" asks again. */}
      <div className={notice ? "hidden" : "contents"} key={rulesKey}>
        {table}
      </div>
    </div>
  );
}

// packages/yayaw-table-vue/src/dashboard/DashboardPageTable.vue
<script setup lang="ts">
import { QueryClient } from "@tanstack/vue-query";
import { computed, ref, shallowRef, watch } from "vue";
import YayawDataTable from "../components/YayawDataTable.vue";
import type { DisplayModeRenderers } from "../display-mode-renderer";
import type {
  DataTableTranslations,
  TableActions,
  TableConfig,
  TableRecord,
  TableView,
} from "../types";
import {
  type DashboardNotice,
  type DashboardWidget,
  dashboardScreenView,
  dashboardTableViews,
  withDashboardFilters,
  withDashboardTableViews,
  withMutationSignal,
  withNoticeCapture,
} from "./dashboard-model";
import type { ViewConfig } from "../view-config";
import type { DashboardDataTableProps, DashboardTableSource } from "./dashboard-types";

/**
 * A `table` widget: the source's full list page (toolbar, saved views,
 * selection, URL state) without a card. Its inline view is the screen's
 * default view; the screen's filters reach every request as
 * `requiredFilters`; its changes reload the screen's other widgets.
 */
const props = defineProps<{
  dashboardId: string;
  widget: DashboardWidget;
  /** The source id: the table's id, so URL keys, saved views and favorites stay the list page's. */
  sourceId: string;
  source: DashboardTableSource;
  /** None for the screen's first table (canonical URL keys), else the widget's id. */
  instanceId?: string;
  /** Name of the screen's default view (the widget's inline view). */
  screenViewName: string;
  /** The screen filters' rules for this widget (`requiredFilters`). */
  rules: Record<string, unknown>[];
  /** Changes with "Refresh all" and a refresh of this source: rows load again. */
  revision: number;
  /** The screen's URL sync: off keeps the table's state out of the URL too. */
  syncUrl: boolean;
  renderers?: DisplayModeRenderers;
  locale: string;
  translations?: DataTableTranslations;
  getRowId?: (row: TableRecord) => string;
  noticeText: (notice: DashboardNotice) => string;
}>();
/**
 * `mutated`: after each change of the table's records (the screen reloads its
 * other widgets). `view-config-change`: the view the table shows, which "Make
 * the current view the screen default" stores.
 */
const emit = defineEmits<{ mutated: []; viewConfigChange: [config: ViewConfig] }>();

const notice = ref<DashboardNotice>();
const rulesKey = computed(() => JSON.stringify(props.rules));
const screenView = computed(() =>
  dashboardScreenView(props.dashboardId, props.widget, props.screenViewName)
);
const actions = computed(
  () =>
    withDashboardTableViews(
      withNoticeCapture(
        withMutationSignal(
          withDashboardFilters(
            props.source.actions,
            JSON.parse(rulesKey.value) as Record<string, unknown>[]
          ),
          () => emit("mutated")
        ),
        (found) => {
          notice.value = found;
        }
      ),
      screenView.value?.id ?? props.widget.viewId
    ) as TableActions
);
// The screen names the table, not the table's own header.
const config = computed<TableConfig>(() => ({
  ...props.source.config,
  table: {
    ...props.source.config.table,
    showToolbarHeader: false,
    ...(props.syncUrl ? {} : { syncUrl: false }),
  },
}));
const hostProps = computed(() => props.source.tableProps ?? {});
const initialViews = computed(() =>
  dashboardTableViews(
    [
      ...(props.source.views ?? []),
      ...((hostProps.value.initialViews as TableView[] | undefined) ?? []),
    ],
    {
      screenView: screenView.value as unknown as TableView | undefined,
      defaultViewId: props.widget.viewId,
    }
  )
);
// "Refresh all" reaches a host's table through its query client.
const queryClient = new QueryClient();
const tableProps = computed<DashboardDataTableProps>(() => ({
  queryClient,
  ...hostProps.value,
  displayModeRenderers: {
    ...props.renderers,
    ...(hostProps.value.displayModeRenderers as DisplayModeRenderers | undefined),
  },
  getRowId: hostProps.value.getRowId ?? props.getRowId,
  locale: hostProps.value.locale ?? props.locale,
  translations: hostProps.value.translations ?? props.translations,
  tableType: props.sourceId,
  tableId: props.sourceId,
  instanceId: props.instanceId,
  config: config.value,
  getTableActions: () => actions.value,
  initialViews: initialViews.value,
  // The screen and the host both hear the view the table shows.
  onViewConfigChange: (view: ViewConfig) => {
    emit("viewConfigChange", view);
    (hostProps.value.onViewConfigChange as ((config: ViewConfig) => void) | undefined)?.(view);
  },
}));
const HostTable = () => props.source.renderTable?.(tableProps.value);

const table = shallowRef<{ refresh?: () => Promise<void> }>();
watch(
  () => props.revision,
  async () => {
    const client = (hostProps.value.queryClient as QueryClient | undefined) ?? queryClient;
    try {
      await (table.value?.refresh
        ? table.value.refresh()
        : client.invalidateQueries({ queryKey: ["yayaw-table"] }));
    } catch {
      // The table shows its own error.
    }
  }
);
</script>

<template>
  <div class="yayaw-dashboard-page-table" :data-page-table="props.sourceId">
    <div
      v-if="notice"
      class="yayaw-dashboard-message yayaw-dashboard-notice"
      data-widget-state="notice"
      :data-widget-reason="notice.code"
    >
      <p>{{ props.noticeText(notice) }}</p>
    </div>
    <!-- Kept mounted behind a notice, so "Refresh all" asks again; new filters remount it. -->
    <div :key="rulesKey" :class="notice ? 'yayaw-dashboard-hidden' : 'yayaw-dashboard-contents'">
      <HostTable v-if="props.source.renderTable" />
      <YayawDataTable v-else ref="table" v-bind="tableProps" />
    </div>
  </div>
</template>
