// packages/yayaw-table-vue/src/components/kanban/ServerKanbanView.vue
<script setup lang="ts">
import { onBeforeUnmount, shallowRef, watch } from "vue";
import { createServerKanban, type ServerKanbanSource, type ServerKanbanState } from "../../server-kanban";
import { useTableContext } from "../../context";
import CellRenderer from "../table/CellRenderer.vue";
const props = defineProps<{ source: ServerKanbanSource; titleColumn: string; propertyIds: string[] }>();
const context = useTableContext();
const state = shallowRef<ServerKanbanState>({ lanes: [], loading: true });
let session: ReturnType<typeof createServerKanban> | undefined;
watch(() => props.source.queryKey, () => { session?.dispose(); session = createServerKanban(props.source, value => { state.value = value; }); void session.load(); }, { immediate: true });
onBeforeUnmount(() => session?.dispose());
const column = (id: string) => context.config.columns.definitions.find(item => item.id === id) ?? { id, header: id };
const value = (row: Record<string, unknown>, id: string) => column(id).accessorFn?.(row) ?? row[column(id).accessorKey ?? id];
const label = (key: "loading" | "retry" | "loadMore" | "empty", fallback: string) => props.source.labels?.[key] ?? fallback;
</script>
<template>
 <div>
 <p v-if="state.loading" role="status">{{ label('loading', 'Loading…') }}</p>
 <div v-if="state.error" role="alert">{{ state.error }}<button class="yayaw-button" type="button" @click="session?.load()">{{ label('retry', 'Retry') }}</button></div>
 <p v-if="!state.loading && !state.error && !state.lanes.length">{{ label('empty', 'No results') }}</p>
 <div class="yayaw-card-view-shell"><div class="yayaw-kanban">
 <section v-for="lane in state.lanes" :key="lane.value" class="yayaw-kanban-lane" :aria-label="lane.label">
 <header><strong>{{ lane.label }}</strong><span class="yayaw-count">{{ lane.totalCount }}</span></header>
 <div class="yayaw-kanban-cards">
 <article v-for="row in lane.rows" :key="source.getRowId?.(row) ?? String(row.id)" class="yayaw-card yayaw-kanban-card">
 <button type="button" class="yayaw-button yayaw-button-ghost" :disabled="!source.onActivate" @click="source.onActivate?.(row)">{{ value(row, titleColumn) ?? row.id }}</button>
 <dl class="yayaw-card-properties labeled"><template v-for="id in propertyIds.filter(item => item !== titleColumn)" :key="id"><dt>{{ column(id).header }}</dt><dd><CellRenderer :column="column(id)" :row="row" :value="value(row, id)" /></dd></template></dl>
 </article>
 <p v-if="lane.loading" role="status">{{ label('loading', 'Loading…') }}</p><p v-if="lane.error" role="alert">{{ lane.error }}</p>
 <button v-if="!lane.loading && (lane.error || lane.nextCursor !== null)" type="button" class="yayaw-button" @click="session?.loadLane(lane.value)">{{ lane.error ? label('retry', 'Retry') : label('loadMore', 'Load more') }}</button>
 <p v-if="!lane.loading && !lane.error && lane.totalCount === 0">{{ label('empty', 'No results') }}</p>
 </div></section></div></div></div>
</template>

// src/components/ui/yayaw-table/components/server-kanban-view.tsx
"use client";
import { useEffect, useRef, useState } from "react";
import type { TableCatalogueColumnConfig } from "../hooks/use-table-config";
import {
  createServerKanban,
  type ServerKanbanSource,
  type ServerKanbanState,
} from "../utils/server-kanban";

export function ServerKanbanView({
  source,
  columns,
  titleColumn,
  propertyIds,
}: {
  source: ServerKanbanSource;
  columns: TableCatalogueColumnConfig[];
  titleColumn?: string;
  propertyIds: string[];
}) {
  const [state, setState] = useState<ServerKanbanState>({
    lanes: [],
    loading: true,
  });
  const sourceRef = useRef(source);
  sourceRef.current = source;
  const session = useRef<ReturnType<typeof createServerKanban> | null>(null);
  const queryKey = source.queryKey;
  useEffect(() => {
    const next = createServerKanban({ ...sourceRef.current, queryKey }, setState);
    session.current = next;
    next.load();
    return () => next.dispose();
  }, [queryKey]);
  const labels = {
    loading: "Loading…",
    retry: "Retry",
    loadMore: "Load more",
    empty: "No results",
    ...source.labels,
  };
  const value = (row: Record<string, unknown>, id: string) => row[id];
  return (
    <div>
      {state.loading && <output>{labels.loading}</output>}
      {state.error && (
        <div role="alert">
          {state.error}
          <button
            onClick={() => {
              session.current?.load();
            }}
            type="button"
          >
            {labels.retry}
          </button>
        </div>
      )}
      {!(state.loading || state.error || state.lanes.length) && (
        <p>{labels.empty}</p>
      )}
      <div className="flex gap-3 overflow-x-auto p-3">
        {state.lanes.map((lane) => (
          <section
            aria-label={lane.label}
            className="w-72 shrink-0 rounded-md border bg-muted/20 p-3"
            key={lane.value}
          >
            <h3 className="mb-3 flex justify-between font-medium">
              <span>{lane.label}</span>
              <span>{lane.totalCount}</span>
            </h3>
            {lane.rows.map((row) => (
              <article
                className="mb-3 rounded-md border bg-background p-3"
                key={source.getRowId?.(row) ?? String(row.id)}
              >
                <button
                  className="w-full text-left font-medium"
                  disabled={!source.onActivate}
                  onClick={() => source.onActivate?.(row)}
                  type="button"
                >
                  {String(value(row, titleColumn ?? "name") ?? row.id)}
                </button>
                <dl>
                  {propertyIds
                    .filter((id) => id !== titleColumn)
                    .map((id) => {
                      const column = columns.find((item) => item.id === id);
                      const cell = value(row, id);
                      return (
                        <div key={id}>
                          <dt className="text-muted-foreground text-xs">
                            {column?.header ?? id}
                          </dt>
                          <dd className="text-sm">
                            {column?.cellRenderer
                              ? column.cellRenderer(cell, row)
                              : String(cell ?? "")}
                          </dd>
                        </div>
                      );
                    })}
                </dl>
              </article>
            ))}
            {lane.loading && <output>{labels.loading}</output>}
            {lane.error && <p role="alert">{lane.error}</p>}
            {!lane.loading && (lane.error || lane.nextCursor !== null) && (
              <button
                onClick={() => {
                  session.current?.loadLane(lane.value);
                }}
                type="button"
              >
                {lane.error ? labels.retry : labels.loadMore}
              </button>
            )}
            {!(lane.loading || lane.error) && lane.totalCount === 0 && (
              <p>{labels.empty}</p>
            )}
          </section>
        ))}
      </div>
    </div>
  );
}
