// packages/yayaw-table-vue/src/components/filters/OptionFilter.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { ChevronDown, Filter } from "lucide-vue-next";
import { PopoverContent, PopoverPortal, PopoverRoot, PopoverTrigger } from "reka-ui";
import { useTableContext, useTableTranslation } from "../../context";
import { filterBarOptions, filterValueKey, filterValues, replaceColumnFilter } from "../../filter-bar";
import type { ColumnDefinition } from "../../types";

const props = defineProps<{ column: ColumnDefinition }>();
const context = useTableContext();
const translate = useTableTranslation();
const search = ref("");
const value = computed(() => context.state.filters.value.find(filter => filter.id === props.column.id)?.value);
const selected = computed(() => filterValues(value.value));
const options = computed(() => filterBarOptions(props.column, value.value, {
  yes: translate("common.true", "True"), no: translate("common.false", "False"),
}));
const visibleOptions = computed(() => options.value.filter(option => option.label.toLocaleLowerCase().includes(search.value.trim().toLocaleLowerCase())));
const update = (values: unknown[]): void => {
  context.state.filters.value = replaceColumnFilter(context.state.filters.value, props.column.id, values);
};
const checked = (candidate: unknown): boolean => selected.value.some(item => filterValueKey(item) === filterValueKey(candidate));
const toggle = (candidate: unknown): void => update(checked(candidate)
  ? selected.value.filter(item => filterValueKey(item) !== filterValueKey(candidate))
  : [...selected.value, candidate]);
</script>

<template>
  <PopoverRoot @update:open="search = ''">
    <PopoverTrigger as-child>
      <button type="button" class="yayaw-button yayaw-button-outline yayaw-filter-trigger" :aria-label="column.header">
        <Filter :size="16" aria-hidden="true" />
        <span>{{ column.header }}</span>
        <span v-if="selected.length" class="yayaw-filter-count">{{ selected.length }}</span>
        <ChevronDown :size="14" aria-hidden="true" />
      </button>
    </PopoverTrigger>
    <PopoverPortal>
      <PopoverContent class="yayaw-filter-picker" :data-yayaw-filter-picker="context.config.id" :aria-label="column.header" align="start" :side-offset="4" :collision-padding="8">
        <p class="yayaw-filter-heading">{{ column.header }}</p>
        <input v-model="search" type="search" class="yayaw-input" :aria-label="translate('searchOptions', 'Search options…')" :placeholder="translate('searchOptions', 'Search options…')" autocomplete="off" />
        <div class="yayaw-filter-choices" role="group" :aria-label="column.header">
          <label v-for="option in visibleOptions" :key="filterValueKey(option.value)" class="yayaw-filter-choice">
            <input type="checkbox" :checked="checked(option.value)" :disabled="option.disabled" @change="toggle(option.value)" />
            <span>{{ option.label }}</span>
          </label>
          <p v-if="!visibleOptions.length" class="yayaw-help" role="status">{{ translate('noResults', 'No results') }}</p>
        </div>
        <button type="button" class="yayaw-button yayaw-button-outline" :disabled="!selected.length" @click="update([])">{{ translate('clearFilters', 'Clear filters') }}</button>
      </PopoverContent>
    </PopoverPortal>
  </PopoverRoot>
</template>

// registry/default/ui/yayaw-table/components/filters/option-filter.tsx
"use client";

import { ChevronDown, Filter } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Popover,
  PopoverContent,
  PopoverTitle,
  PopoverTrigger,
} from "@/components/ui/popover";
import { useTranslations } from "../../providers/table-provider";
import {
  type FilterBarColumn,
  filterBarOptions,
  filterValueKey,
  filterValues,
} from "../../utils/filter-bar";

export function OptionFilter({
  column,
  value,
  onChange,
}: {
  column: FilterBarColumn;
  value: unknown;
  onChange: (values: unknown[]) => void;
}) {
  const { t } = useTranslations();
  const [search, setSearch] = useState("");
  const selected = filterValues(value);
  const options = filterBarOptions(column, value, {
    yes: t("common.true"),
    no: t("common.false"),
  });
  const checked = (candidate: unknown) =>
    selected.some((item) => filterValueKey(item) === filterValueKey(candidate));
  const visible = options.filter((option) =>
    option.label.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())
  );
  return (
    <Popover onOpenChange={() => setSearch("")}>
      <PopoverTrigger
        render={
          <Button
            aria-label={column.header}
            className="h-8 max-w-full gap-2 font-normal"
            type="button"
            variant="outline"
          />
        }
      >
        <Filter aria-hidden="true" className="size-4 shrink-0" />
        <span className="truncate">{column.header}</span>
        {selected.length > 0 && (
          <span className="rounded-sm bg-muted px-1.5 text-xs">
            {selected.length}
          </span>
        )}
        <ChevronDown aria-hidden="true" className="size-3.5 shrink-0" />
      </PopoverTrigger>
      <PopoverContent
        align="start"
        className="w-72 max-w-[calc(100vw-1rem)] gap-2 p-3"
      >
        <PopoverTitle className="font-medium text-sm">
          {column.header}
        </PopoverTitle>
        <Input
          aria-label={t("common.search")}
          autoComplete="off"
          onChange={(event) => setSearch(event.target.value)}
          placeholder={t("common.search")}
          type="search"
          value={search}
        />
        <fieldset
          aria-label={column.header}
          className="m-0 max-h-60 min-w-0 overflow-auto border-0 p-0"
        >
          {visible.map((option) => (
            <label
              className="flex cursor-pointer items-center gap-2 rounded-sm px-2 py-1.5 text-sm hover:bg-accent"
              key={filterValueKey(option.value)}
            >
              <input
                checked={checked(option.value)}
                disabled={option.disabled}
                onChange={() =>
                  onChange(
                    checked(option.value)
                      ? selected.filter(
                          (item) =>
                            filterValueKey(item) !==
                            filterValueKey(option.value)
                        )
                      : [...selected, option.value]
                  )
                }
                type="checkbox"
              />
              <span>{option.label}</span>
            </label>
          ))}
          {!visible.length && (
            <output className="block p-2 text-muted-foreground text-sm">
              {t("filters.noResults")}
            </output>
          )}
        </fieldset>
        <Button
          disabled={!selected.length}
          onClick={() => onChange([])}
          type="button"
          variant="outline"
        >
          {t("filters.clear")}
        </Button>
      </PopoverContent>
    </Popover>
  );
}
