// registry/default/ui/yayaw-table/components/gantt-view.tsx
"use client";

import {
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  FileText,
  Layers,
  RotateCw,
} from "lucide-react";
import {
  type MouseEvent as ReactMouseEvent,
  type ReactNode,
  type PointerEvent as ReactPointerEvent,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { dateDay, dayDate } from "../planning/calendar";
import {
  type PlanningFormatters,
  planningFormatters,
} from "../planning/format";
import type { PlanningSurfaceLabels } from "../planning/labels";
import type { PlanningSession } from "../planning/session";
import {
  TIMELINE_HEADER_HEIGHT,
  TIMELINE_ROW_HEIGHT,
  type TimelineGeometry,
  type TimelineGroupRow,
  type TimelineTaskRow,
  timelineBar,
  timelineCanEdit,
  timelineCanResize,
  timelineDateMutation,
  timelineDayCells,
  timelineFirstDate,
  timelineGeometry,
  timelineLinks,
  timelineMonths,
  timelineOffDays,
  timelinePeriodStep,
  timelineRows,
  timelineToday,
  timelineTodayOffset,
} from "../planning/timeline";
import {
  type PlanningMutation,
  type PlanningSnapshot,
  type PlanningTask,
  planningKey,
  type TableGanttConfig,
  type TableGanttViewConfig,
} from "../planning/types";
import type { Row, Table as TanStackTable } from "../tanstack";
import { flexRender } from "../tanstack";

const SELECTION_COLUMN_ID = "select";
const SYSTEM_COLUMN_IDS = new Set([SELECTION_COLUMN_ID, "actions"]);
const EMPTY_FORMAT_COLUMNS: never[] = [];
const TREE_INDENT = 16;
const LABEL_PADDING = 8;
const KEYBOARD_WEEK = 7;
const MIN_BAR_WIDTH = 8;

type DragOperation = "move" | "start" | "end";

interface DragState {
  key: string;
  operation: DragOperation;
  originX: number;
  deltaDays: number;
  moved: boolean;
}

export interface DataTableGanttViewProps<
  TData extends Record<string, unknown>,
> {
  busy: boolean;
  className?: string;
  compare?: (a: PlanningTask, b: PlanningTask) => number;
  config: TableGanttConfig;
  emptyState: ReactNode;
  error?: string;
  getRowId?: (row: TData) => string;
  /** Column grouping the root tasks: the table's first grouping level. */
  groupBy?: string;
  /** Its header, before each group's value. */
  groupLabel?: string;
  isRowActive?: (row: Row<TData>) => boolean;
  isRowClickable?: (row: Row<TData>) => boolean;
  labels: PlanningSurfaceLabels;
  locale: string;
  onClearFilters?: () => void;
  onRowClick?: (row: Row<TData>, event: ReactMouseEvent<HTMLElement>) => void;
  onViewChange: (view: TableGanttViewConfig) => void;
  session: PlanningSession;
  snapshot?: PlanningSnapshot;
  table: TanStackTable<TData>;
  view: TableGanttViewConfig;
  visible?: (task: PlanningTask) => boolean;
  /** The table's columns: names and days read in their formats. */
  columns?: readonly PlanningFormatColumn[];
}

type PlanningFormatColumn = Parameters<typeof planningFormatters>[0][number];

function rowIdentity<TData extends Record<string, unknown>>(
  row: Row<TData>,
  getRowId?: (row: TData) => string
): string {
  return getRowId?.(row.original) ?? String(row.original.id ?? row.id);
}

/** Table rows keyed the way planning refs are, so a task can find its record. */
function useRowsByTaskId<TData extends Record<string, unknown>>(
  table: TanStackTable<TData>,
  getRowId?: (row: TData) => string
): Map<string, Row<TData>> {
  // Table grouping nests the row model; tasks need the records themselves.
  const rows = table.store.state.grouping.length
    ? table.getPreGroupedRowModel().rows
    : table.getRowModel().rows;
  return useMemo(() => {
    const index = new Map<string, Row<TData>>();
    for (const row of rows) {
      index.set(rowIdentity(row, getRowId), row);
    }
    return index;
  }, [rows, getRowId]);
}

function titleColumnId<TData extends Record<string, unknown>>(
  table: TanStackTable<TData>,
  configured?: string
): string | undefined {
  if (configured) {
    return configured;
  }
  return table
    .getVisibleLeafColumns()
    .find((column) => !SYSTEM_COLUMN_IDS.has(column.id))?.id;
}

function GanttControls({
  busy,
  labels,
  onNavigate,
  onReload,
  period,
}: {
  busy: boolean;
  labels: PlanningSurfaceLabels;
  onNavigate: (anchorDate: string | undefined) => void;
  onReload: () => void;
  period: { label: string; previous: string; next: string };
}) {
  return (
    <div className="flex flex-wrap items-center justify-between gap-2 py-2">
      <h3 className="font-medium text-base">{period.label}</h3>
      <div className="flex items-center gap-1">
        <Button
          aria-label={labels.previous}
          className="size-8"
          onClick={() => onNavigate(period.previous)}
          size="icon"
          title={labels.previous}
          type="button"
          variant="ghost"
        >
          <ChevronLeft aria-hidden="true" className="size-4" />
        </Button>
        <Button
          className="h-8 font-normal"
          onClick={() => onNavigate(timelineToday())}
          size="sm"
          type="button"
          variant="ghost"
        >
          {labels.today}
        </Button>
        <Button
          aria-label={labels.next}
          className="size-8"
          onClick={() => onNavigate(period.next)}
          size="icon"
          title={labels.next}
          type="button"
          variant="ghost"
        >
          <ChevronRight aria-hidden="true" className="size-4" />
        </Button>
        <Button
          aria-label={labels.retry}
          className="size-8"
          disabled={busy}
          onClick={onReload}
          size="icon"
          title={labels.retry}
          type="button"
          variant="ghost"
        >
          <RotateCw aria-hidden="true" className="size-4" />
        </Button>
      </div>
    </div>
  );
}

function GanttHeader({
  formatDay,
  geometry,
  labels,
  locale,
  view,
}: {
  formatDay: PlanningFormatters["day"];
  geometry: TimelineGeometry;
  labels: PlanningSurfaceLabels;
  locale: string;
  view: TableGanttViewConfig;
}) {
  const days = timelineDayCells(geometry, view);
  const months = timelineMonths(geometry);
  const weekdayFormat = useMemo(
    () =>
      new Intl.DateTimeFormat(locale, {
        weekday: view.zoom === "day" ? "short" : "narrow",
        timeZone: "UTC",
      }),
    [locale, view.zoom]
  );
  const monthFormat = useMemo(
    () =>
      new Intl.DateTimeFormat(locale, {
        month: "long",
        year: "numeric",
        timeZone: "UTC",
      }),
    [locale]
  );
  return (
    <div
      className="sticky top-0 z-20 bg-background"
      style={{ height: TIMELINE_HEADER_HEIGHT }}
    >
      <div
        className="sticky left-0 z-30 flex h-full items-end gap-2 border-border border-r border-b bg-background px-2 pb-2 font-medium text-muted-foreground text-sm"
        style={{ width: geometry.labelWidth }}
      >
        <FileText aria-hidden="true" className="size-4" />
        <span>{labels.task}</span>
      </div>
      {months.map((month) => (
        <div
          className="absolute top-0 truncate border-border border-b px-2 py-1 text-muted-foreground text-xs"
          key={month.date}
          style={{ left: month.left, width: month.width }}
        >
          {monthFormat.format(new Date(`${month.date}T00:00:00Z`))}
        </div>
      ))}
      {days.map((cell) => (
        <div
          aria-current={cell.isToday ? "date" : undefined}
          className={cn(
            "absolute flex flex-col items-center justify-end gap-0.5 border-border border-b pb-1 text-[11px]",
            cell.isToday
              ? "font-semibold text-destructive"
              : "text-muted-foreground"
          )}
          key={cell.date}
          style={{ left: cell.left, top: 24, width: cell.width, height: 40 }}
          title={formatDay(cell.date)}
        >
          {cell.weekday ? (
            <span className="opacity-70">
              {weekdayFormat.format(new Date(`${cell.date}T00:00:00Z`))}
            </span>
          ) : null}
          {cell.number ? (
            <span
              className={cn(
                cell.isToday &&
                  "flex size-5 items-center justify-center rounded-full bg-destructive text-destructive-foreground"
              )}
            >
              {cell.number}
            </span>
          ) : null}
        </div>
      ))}
    </div>
  );
}

function GanttBar({
  canResize,
  dragDelta,
  editable,
  formatters,
  geometry,
  labels,
  onDrag,
  onKeyAdjust,
  onOpen,
  span,
  summary,
  task,
}: {
  canResize: boolean;
  formatters: PlanningFormatters;
  dragDelta: { operation: DragOperation; days: number } | undefined;
  editable: boolean;
  geometry: TimelineGeometry;
  labels: PlanningSurfaceLabels;
  onDrag: (
    event: ReactPointerEvent<HTMLElement>,
    operation: DragOperation
  ) => void;
  onKeyAdjust: (operation: DragOperation, days: number) => void;
  onOpen: () => void;
  span: { left: number; width: number };
  summary: boolean;
  task: PlanningTask;
}) {
  const shift = dragDelta ? dragDelta.days * geometry.width : 0;
  const moveShift = dragDelta?.operation === "move" ? shift : 0;
  const startShift = dragDelta?.operation === "start" ? shift : 0;
  const endShift = dragDelta?.operation === "end" ? shift : 0;
  // Names and days as the table shows the title, start and end columns.
  const range = `${formatters.day(task.start, "start")} – ${formatters.day(task.end, "end")}`;
  const name = formatters.task(task);
  const keyAdjust =
    (operation: DragOperation) => (event: React.KeyboardEvent) => {
      if (event.key !== "ArrowLeft" && event.key !== "ArrowRight") {
        return;
      }
      event.preventDefault();
      onKeyAdjust(
        operation,
        (event.key === "ArrowLeft" ? -1 : 1) *
          (event.shiftKey ? KEYBOARD_WEEK : 1)
      );
    };
  return (
    <div
      className={cn(
        "group/bar absolute top-1.5 bottom-1.5 rounded-md border",
        summary ? "border-border bg-muted" : "border-primary/25 bg-primary/15"
      )}
      style={{
        left: span.left + moveShift + startShift,
        width: Math.max(MIN_BAR_WIDTH, span.width - startShift + endShift),
      }}
    >
      <button
        aria-label={`${labels.move} ${name}: ${range}`}
        className={cn(
          "flex size-full items-center truncate rounded-md px-2 text-left font-medium text-xs",
          editable ? "cursor-grab active:cursor-grabbing" : "cursor-pointer"
        )}
        onClick={onOpen}
        onKeyDown={editable ? keyAdjust("move") : undefined}
        onPointerDown={editable ? (event) => onDrag(event, "move") : undefined}
        title={`${name}: ${range}`}
        type="button"
      >
        {name}
      </button>
      {editable && canResize
        ? (["start", "end"] as const).map((side) => (
            <button
              aria-label={`${side === "start" ? labels.resizeStart : labels.resizeEnd} ${name}`}
              className={cn(
                "absolute inset-y-0 w-2 cursor-ew-resize rounded-sm opacity-0 transition-opacity focus-visible:opacity-100 group-hover/bar:opacity-100",
                "bg-primary/40 [@media(hover:none)]:opacity-100",
                side === "start" ? "left-0" : "right-0"
              )}
              key={side}
              onKeyDown={keyAdjust(side)}
              onPointerDown={(event) => onDrag(event, side)}
              type="button"
            />
          ))
        : null}
    </div>
  );
}

function GanttTrack({
  dragDelta,
  formatters,
  geometry,
  labels,
  onDrag,
  onKeyAdjust,
  onOpen,
  row,
  session,
  snapshot,
}: {
  dragDelta: { operation: DragOperation; days: number } | undefined;
  formatters: PlanningFormatters;
  geometry: TimelineGeometry;
  labels: PlanningSurfaceLabels;
  onDrag: (
    event: ReactPointerEvent<HTMLElement>,
    operation: DragOperation
  ) => void;
  onKeyAdjust: (operation: DragOperation, days: number) => void;
  onOpen: () => void;
  row: TimelineTaskRow;
  session: PlanningSession;
  snapshot: PlanningSnapshot;
}) {
  const { task, hasChildren } = row;
  const span = timelineBar(task, geometry);
  const offDays = timelineOffDays(task, snapshot, geometry);
  const editable = timelineCanEdit({ task, hasChildren, session, snapshot });
  const summary = hasChildren && session.config.parentDates !== "independent";
  return (
    <div
      className="absolute inset-y-0"
      style={{
        left: geometry.labelWidth,
        width: geometry.count * geometry.width,
        backgroundImage:
          "linear-gradient(to right, var(--border) 0 1px, transparent 1px)",
        backgroundSize: `${geometry.width}px 100%`,
      }}
    >
      {offDays.map((off) => (
        <span
          aria-hidden="true"
          className="absolute inset-y-0 bg-muted/45"
          key={off.left}
          style={{ left: off.left, width: off.width }}
        />
      ))}
      {span ? (
        <GanttBar
          canResize={timelineCanResize({ hasChildren, session })}
          dragDelta={dragDelta}
          editable={editable}
          formatters={formatters}
          geometry={geometry}
          labels={labels}
          onDrag={onDrag}
          onKeyAdjust={onKeyAdjust}
          onOpen={onOpen}
          span={span}
          summary={summary}
          task={task}
        />
      ) : (
        <span className="absolute top-1/2 left-2 -translate-y-1/2 text-muted-foreground text-xs italic">
          {labels.unscheduled}
        </span>
      )}
    </div>
  );
}

/** A group heading: only its chevron reacts; the bar spans the group's dates. */
function GanttGroupRow({
  collapsed,
  formatters,
  geometry,
  groupBy = "",
  heading = groupBy,
  labels,
  onToggle,
  row,
  top,
}: {
  collapsed: boolean;
  formatters: PlanningFormatters;
  geometry: TimelineGeometry;
  groupBy?: string;
  /** The grouped column's header. */
  heading?: string;
  labels: PlanningSurfaceLabels;
  onToggle: () => void;
  row: TimelineGroupRow;
  top: number;
}) {
  const span = timelineBar(row, geometry);
  const label = formatters.group(groupBy, row.value);
  const name = `${heading}: ${label}`;
  return (
    <div
      className="absolute inset-x-0 border-border border-b bg-muted/40"
      style={{ top, height: TIMELINE_ROW_HEIGHT }}
    >
      <div
        className="sticky left-0 z-10 flex h-full items-center gap-1 border-border border-r bg-muted pr-2"
        style={{ width: geometry.labelWidth, paddingLeft: LABEL_PADDING }}
      >
        <Button
          aria-expanded={!collapsed}
          aria-label={`${collapsed ? labels.expand : labels.collapse} ${name}`}
          className="size-5 shrink-0 text-muted-foreground"
          onClick={onToggle}
          size="icon"
          type="button"
          variant="ghost"
        >
          {collapsed ? (
            <ChevronRight aria-hidden="true" className="size-4" />
          ) : (
            <ChevronDown aria-hidden="true" className="size-4" />
          )}
        </Button>
        <span
          className="min-w-0 flex-1 truncate font-medium text-sm"
          title={name}
        >
          <span className="text-muted-foreground">{heading}: </span>
          {label}
        </span>
        <span className="shrink-0 rounded-full bg-background px-2 py-0.5 text-muted-foreground text-xs">
          {row.count}
        </span>
      </div>
      {span ? (
        <span
          aria-hidden="true"
          className="absolute top-3 bottom-3 rounded-sm bg-muted-foreground/25"
          style={{ left: geometry.labelWidth + span.left, width: span.width }}
        />
      ) : null}
    </div>
  );
}

export function DataTableGanttView<TData extends Record<string, unknown>>({
  busy,
  className,
  compare,
  config,
  emptyState,
  error,
  getRowId,
  groupBy,
  groupLabel,
  isRowActive,
  isRowClickable,
  labels,
  locale,
  onClearFilters,
  onRowClick,
  onViewChange,
  session,
  snapshot,
  table,
  view,
  visible,
  columns = EMPTY_FORMAT_COLUMNS,
}: DataTableGanttViewProps<TData>) {
  const viewportRef = useRef<HTMLDivElement>(null);
  const [scroll, setScroll] = useState({ top: 0, left: 0 });
  const [availableWidth, setAvailableWidth] = useState(0);
  const [collapsed, setCollapsed] = useState<ReadonlySet<string>>(
    () => new Set()
  );
  const [drag, setDrag] = useState<DragState | undefined>(undefined);
  const rowsByTaskId = useRowsByTaskId(table, getRowId);
  const titleId = titleColumnId(table, config.titleColumn);
  const formatters = useMemo(
    () => planningFormatters(columns, config, locale, titleId),
    [columns, config, locale, titleId]
  );

  useEffect(() => {
    const element = viewportRef.current;
    if (!element || typeof ResizeObserver === "undefined") {
      return;
    }
    const observer = new ResizeObserver(() => {
      setAvailableWidth(element.clientWidth);
    });
    observer.observe(element);
    setAvailableWidth(element.clientWidth);
    return () => observer.disconnect();
  }, []);

  const rows = useMemo(
    () =>
      snapshot
        ? timelineRows(snapshot, {
            hierarchy: session.config.hierarchy,
            visible,
            compare,
            collapsed: new Set(collapsed),
            groupBy,
          })
        : [],
    [snapshot, session.config.hierarchy, visible, compare, collapsed, groupBy]
  );

  const geometry = useMemo(
    () =>
      timelineGeometry({
        rowCount: rows.length,
        view,
        availableWidth,
        height: config.height,
        scrollTop: scroll.top,
        scrollLeft: scroll.left,
        firstDate: timelineFirstDate(snapshot),
      }),
    [rows.length, view, availableWidth, config.height, scroll, snapshot]
  );

  const requestDates = useCallback(
    (mutations: PlanningMutation[]) => {
      if (mutations.length) {
        session.request(mutations).catch(() => undefined);
      }
    },
    [session]
  );

  const toggleCollapsed = useCallback((key: string) => {
    setCollapsed((current) => {
      const next = new Set(current);
      if (next.has(key)) {
        next.delete(key);
      } else {
        next.add(key);
      }
      return next;
    });
  }, []);

  const handleScroll = useCallback(() => {
    const element = viewportRef.current;
    if (element) {
      setScroll({ top: element.scrollTop, left: element.scrollLeft });
    }
  }, []);

  const startDrag = useCallback(
    (
      event: ReactPointerEvent<HTMLElement>,
      key: string,
      operation: DragOperation
    ) => {
      if (event.button !== 0) {
        return;
      }
      setDrag({
        key,
        operation,
        originX: event.clientX,
        deltaDays: 0,
        moved: false,
      });
    },
    []
  );

  const moveDrag = useCallback(
    (event: ReactPointerEvent<HTMLElement>) => {
      setDrag((current) => {
        if (!current) {
          return current;
        }
        const days = Math.round(
          (event.clientX - current.originX) / geometry.width
        );
        if (days === current.deltaDays) {
          return current;
        }
        return { ...current, deltaDays: days, moved: true };
      });
    },
    [geometry.width]
  );

  const periodLabel = useMemo(
    () =>
      new Intl.DateTimeFormat(locale, {
        month: "long",
        year: "numeric",
        timeZone: "UTC",
      }).format(new Date(`${dayDate(geometry.from)}T00:00:00Z`)),
    [locale, geometry.from]
  );

  const step = timelinePeriodStep(view.zoom);
  const anchor = dateDay(view.anchorDate ?? timelineFirstDate(snapshot));

  if (!snapshot) {
    return (
      <div className={cn("space-y-2", className)}>
        <output className="block text-muted-foreground text-sm">
          {busy ? labels.loading : labels.noAdapter}
        </output>
      </div>
    );
  }

  if (!rows.length) {
    return (
      <div className={cn("space-y-3", className)}>
        {emptyState}
        {onClearFilters ? (
          <div className="flex justify-center">
            <Button
              onClick={onClearFilters}
              size="sm"
              type="button"
              variant="outline"
            >
              {labels.clear}
            </Button>
          </div>
        ) : null}
      </div>
    );
  }

  const todayOffset = timelineTodayOffset(geometry);
  const links =
    view.showDependencies === false
      ? []
      : timelineLinks(rows, snapshot, geometry);

  return (
    <section
      aria-label={labels.planning}
      className={cn("space-y-1", className)}
    >
      <GanttControls
        busy={busy}
        labels={labels}
        onNavigate={(anchorDate) => onViewChange({ ...view, anchorDate })}
        onReload={() => session.load()}
        period={{
          label: periodLabel,
          previous: dayDate(anchor - step),
          next: dayDate(anchor + step),
        }}
      />
      {error ? (
        <p className="text-destructive text-sm" role="alert">
          {error}
        </p>
      ) : null}
      <div
        className="relative overflow-auto rounded-md border border-border"
        onScroll={handleScroll}
        ref={viewportRef}
        style={{ height: geometry.height }}
      >
        <div
          className="relative"
          style={{ width: geometry.totalWidth, height: geometry.canvasHeight }}
        >
          <GanttHeader
            formatDay={formatters.day}
            geometry={geometry}
            labels={labels}
            locale={locale}
            view={view}
          />
          {rows.slice(geometry.firstRow, geometry.lastRow).map((row, index) => {
            const position = geometry.firstRow + index;
            if ("group" in row) {
              return (
                <GanttGroupRow
                  collapsed={collapsed.has(row.group)}
                  formatters={formatters}
                  geometry={geometry}
                  groupBy={groupBy}
                  heading={groupLabel}
                  key={row.group}
                  labels={labels}
                  onToggle={() => toggleCollapsed(row.group)}
                  row={row}
                  top={TIMELINE_HEADER_HEIGHT + position * TIMELINE_ROW_HEIGHT}
                />
              );
            }
            const key = planningKey(row.task.ref);
            const tableRow =
              row.task.ref.source === session.config.sourceId
                ? rowsByTaskId.get(row.task.ref.id)
                : undefined;
            return (
              <div
                className={cn(
                  "absolute inset-x-0 border-border border-b",
                  row.hasChildren && "bg-muted/25",
                  tableRow && isRowActive?.(tableRow) && "bg-accent/40"
                )}
                data-task={key}
                key={key}
                style={{
                  top: TIMELINE_HEADER_HEIGHT + position * TIMELINE_ROW_HEIGHT,
                  height: TIMELINE_ROW_HEIGHT,
                }}
              >
                <div
                  className="sticky left-0 z-10 flex h-full items-center gap-1 border-border border-r bg-background pr-2"
                  style={{
                    width: geometry.labelWidth,
                    paddingLeft: LABEL_PADDING + row.depth * TREE_INDENT,
                  }}
                >
                  {row.hasChildren ? (
                    <Button
                      aria-expanded={!collapsed.has(key)}
                      aria-label={
                        collapsed.has(key) ? labels.expand : labels.collapse
                      }
                      className="size-5 shrink-0 text-muted-foreground"
                      onClick={() => toggleCollapsed(key)}
                      size="icon"
                      type="button"
                      variant="ghost"
                    >
                      {collapsed.has(key) ? (
                        <ChevronRight aria-hidden="true" className="size-4" />
                      ) : (
                        <ChevronDown aria-hidden="true" className="size-4" />
                      )}
                    </Button>
                  ) : (
                    <span aria-hidden="true" className="size-5 shrink-0" />
                  )}
                  {tableRow
                    ?.getVisibleCells()
                    .filter((cell) => cell.column.id === SELECTION_COLUMN_ID)
                    .map((cell) => (
                      <span className="shrink-0" key={cell.id}>
                        {flexRender(
                          cell.column.columnDef.cell,
                          cell.getContext()
                        )}
                      </span>
                    ))}
                  {row.hasChildren ? (
                    <Layers
                      aria-hidden="true"
                      className="size-4 shrink-0 text-muted-foreground"
                    />
                  ) : (
                    <FileText
                      aria-hidden="true"
                      className="size-4 shrink-0 text-muted-foreground"
                    />
                  )}
                  <GanttLabel
                    isClickable={
                      tableRow ? isRowClickable?.(tableRow) !== false : false
                    }
                    onOpen={() => session.open(row.task.ref)}
                    onRowClick={onRowClick}
                    row={tableRow}
                    task={row.task}
                    taskName={formatters.task(row.task)}
                    titleId={titleId}
                  />
                </div>
                <GanttTrack
                  dragDelta={
                    drag?.key === key
                      ? { operation: drag.operation, days: drag.deltaDays }
                      : undefined
                  }
                  formatters={formatters}
                  geometry={geometry}
                  labels={labels}
                  onDrag={(event, operation) =>
                    startDrag(event, key, operation)
                  }
                  onKeyAdjust={(operation, days) =>
                    requestDates(
                      timelineDateMutation(row.task, operation, days)
                    )
                  }
                  onOpen={() => session.open(row.task.ref)}
                  row={row}
                  session={session}
                  snapshot={snapshot}
                />
              </div>
            );
          })}
          {links.length ? (
            <svg
              aria-hidden="true"
              className="pointer-events-none absolute inset-0 text-muted-foreground/70"
              height={geometry.canvasHeight}
              width={geometry.totalWidth}
            >
              <title>{labels.dependencies}</title>
              {links.map((link) => (
                <path
                  d={link.d}
                  fill="none"
                  key={link.id}
                  stroke="currentColor"
                />
              ))}
            </svg>
          ) : null}
          {todayOffset === undefined ? null : (
            <span
              aria-hidden="true"
              className="pointer-events-none absolute w-px bg-destructive/60"
              style={{
                left: todayOffset,
                top: TIMELINE_HEADER_HEIGHT,
                height: geometry.canvasHeight - TIMELINE_HEADER_HEIGHT,
              }}
            />
          )}
        </div>
      </div>
      {drag ? (
        <DragSurface
          onMove={moveDrag}
          onRelease={() => {
            const target = rows.find(
              (row): row is TimelineTaskRow =>
                "task" in row && planningKey(row.task.ref) === drag.key
            );
            if (target && drag.moved && drag.deltaDays) {
              requestDates(
                timelineDateMutation(
                  target.task,
                  drag.operation,
                  drag.deltaDays
                )
              );
            } else if (target && drag.operation === "move") {
              // The surface swallows the click, so a press without a drag still opens the task.
              session.open(target.task.ref);
            }
            setDrag(undefined);
          }}
        />
      ) : null}
    </section>
  );
}

/** A transparent layer keeps pointer tracking alive while a bar is dragged. */
function DragSurface({
  onMove,
  onRelease,
}: {
  onMove: (event: ReactPointerEvent<HTMLElement>) => void;
  onRelease: () => void;
}) {
  return (
    <div
      aria-hidden="true"
      className="fixed inset-0 z-50 cursor-grabbing"
      onPointerCancel={onRelease}
      onPointerMove={onMove}
      onPointerUp={onRelease}
    />
  );
}

function GanttLabel<TData extends Record<string, unknown>>({
  isClickable,
  onOpen,
  onRowClick,
  row,
  task,
  taskName,
  titleId,
}: {
  isClickable: boolean;
  onOpen: () => void;
  onRowClick?: (row: Row<TData>, event: ReactMouseEvent<HTMLElement>) => void;
  row?: Row<TData>;
  task: PlanningTask;
  /** The title as the table shows it, for tooltips and unloaded rows. */
  taskName: string;
  titleId?: string;
}) {
  const cell = row
    ?.getVisibleCells()
    .find((item) => item.column.id === titleId);
  const content = cell
    ? flexRender(cell.column.columnDef.cell, cell.getContext())
    : taskName;
  if (row && onRowClick && isClickable) {
    return (
      <button
        className="min-w-0 flex-1 truncate text-left text-sm hover:underline"
        onClick={(event) => onRowClick(row, event)}
        title={`${task.ref.source} · ${taskName}`}
        type="button"
      >
        {content}
      </button>
    );
  }
  return (
    <button
      className="min-w-0 flex-1 truncate text-left text-sm hover:underline"
      onClick={onOpen}
      title={`${task.ref.source} · ${taskName}`}
      type="button"
    >
      {content}
    </button>
  );
}

// packages/yayaw-table-vue/src/components/planning/GanttView.vue
<script setup lang="ts">
import { ChevronDown, ChevronLeft, ChevronRight, FileText, Layers, RotateCw } from "lucide-vue-next";
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import { useTableContext } from "../../context";
import { useCardRows } from "../../composables/use-card-rows";
import { exportColumns } from "../../core";
import { dateDay, dayDate } from "../../planning/calendar";
import { normalizeGanttView } from "../../planning/engine";
import { planningFormatters } from "../../planning/format";
import { planningLabelOverrides, planningLabels } from "../../planning/labels";
import {
  TIMELINE_HEADER_HEIGHT,
  TIMELINE_ROW_HEIGHT,
  timelineBar,
  timelineCanEdit,
  timelineCanResize,
  timelineDateMutation,
  timelineDayCells,
  timelineFirstDate,
  timelineGeometry,
  timelineLinks,
  timelineMonths,
  timelineOffDays,
  timelinePeriodStep,
  timelineRows,
  timelineToday,
  timelineTodayOffset,
  type TimelineTaskRow,
} from "../../planning/timeline";
import { comparePlanningTasks, planningTaskMatches } from "../../planning/query";
import { planningKey, type PlanningRef, type PlanningTask } from "../../planning/types";
import type { ColumnDefinition, TableRecord } from "../../types";
import TableCheckbox from "../controls/TableCheckbox.vue";
import CellRenderer from "../table/CellRenderer.vue";
import TableEmptyState from "../table/TableEmptyState.vue";

type DragOperation = "move" | "start" | "end";
const TREE_INDENT = 16;
const LABEL_PADDING = 8;
const KEYBOARD_WEEK = 7;
const MIN_BAR_WIDTH = 8;

const context = useTableContext();
const rows = useCardRows();
const viewport = ref<HTMLElement>();
const scrollTop = ref(0);
const scrollLeft = ref(0);
const available = ref(0);
const collapsed = ref(new Set<string>());
const drag = ref<{ key: string; operation: DragOperation; originX: number; days: number; moved: boolean }>();
let observer: ResizeObserver | undefined;

const translate = (key: string): string => {
  const value = context.translations.value[key];
  return typeof value === "string" ? value : key;
};
const labels = computed(() => planningLabels(context.locale, planningLabelOverrides(translate)));
const planning = computed(() => context.planning);
const snapshot = computed(() => context.planningState?.value?.snapshot);
const busy = computed(() => context.planningState?.value?.busy === true);
const error = computed(() => context.planningState?.value?.error);
const view = computed(() => normalizeGanttView({ ...context.config.table.gantt, ...context.state.gantt.value }));
const sourceId = computed(() => context.config.table.planning?.sourceId);

const rowsById = computed(() => {
  const index = new Map<string, TableRecord>();
  for (const row of rows.value) {
    index.set(context.getRowId(row), row);
  }
  return index;
});
const recordFor = (task: PlanningTask): TableRecord | undefined =>
  task.ref.source === sourceId.value ? rowsById.value.get(task.ref.id) : undefined;

// The configured title column, else the first visible data column, as in React.
const titleColumn = computed<ColumnDefinition | undefined>(() => {
  const configured = context.config.table.gantt?.titleColumn;
  const definitions = context.config.columns.definitions;
  return (
    definitions.find((item) => item.id === configured) ??
    exportColumns(
      definitions,
      context.state.visibility.value,
      context.state.order.value
    ).find((item) => item.id !== "select" && item.id !== "actions")
  );
});

// Names and days read as the table shows the title, start and end columns.
const formatters = computed(() =>
  planningFormatters(
    context.config.columns.definitions,
    context.config.table.gantt,
    context.locale,
    titleColumn.value?.id
  )
);

/** The timeline projects the same search, filters and sort as the rest of the table. */
const matches = computed(() => {
  const query = {
    search: context.state.search.value,
    filters: context.state.filters.value,
    advancedFilters: context.state.advancedFilters.value,
    columns: context.config.columns.definitions,
  };
  return (task: PlanningTask) => planningTaskMatches(task, query);
});
const order = computed(() => {
  const query = { sorting: context.state.sorting.value, columns: context.config.columns.definitions };
  return (a: PlanningTask, b: PlanningTask) => comparePlanningTasks(a, b, query);
});
// Root tasks are grouped by the table's first grouping level, like List.
const groupBy = computed(() => context.state.grouping.value[0] ?? "");
const groupHeader = computed(
  () =>
    context.config.columns.definitions.find((item) => item.id === groupBy.value)?.header ??
    groupBy.value
);
const timeline = computed(() =>
  snapshot.value
    ? timelineRows(snapshot.value, {
        hierarchy: context.config.table.planning?.hierarchy,
        visible: matches.value,
        compare: order.value,
        collapsed: collapsed.value,
        groupBy: groupBy.value,
      })
    : []
);
const geometry = computed(() =>
  timelineGeometry({
    rowCount: timeline.value.length,
    view: view.value,
    availableWidth: available.value,
    height: context.config.table.gantt?.height,
    scrollTop: scrollTop.value,
    scrollLeft: scrollLeft.value,
    firstDate: timelineFirstDate(snapshot.value),
  })
);
const visibleRows = computed(() => timeline.value.slice(geometry.value.firstRow, geometry.value.lastRow));
const rowTop = (index: number): string =>
  `${TIMELINE_HEADER_HEIGHT + (geometry.value.firstRow + index) * TIMELINE_ROW_HEIGHT}px`;
const groupName = (value: unknown): string => `${groupHeader.value}: ${formatters.value.group(groupBy.value, value)}`;
const links = computed(() =>
  view.value.showDependencies === false || !snapshot.value ? [] : timelineLinks(timeline.value, snapshot.value, geometry.value)
);
const days = computed(() => timelineDayCells(geometry.value, view.value));
const months = computed(() => timelineMonths(geometry.value));
const todayOffset = computed(() => timelineTodayOffset(geometry.value));
const anchorDay = computed(() => dateDay(view.value.anchorDate ?? timelineFirstDate(snapshot.value)));
const periodLabel = computed(() =>
  new Intl.DateTimeFormat(context.locale, { month: "long", year: "numeric", timeZone: "UTC" }).format(
    new Date(`${dayDate(geometry.value.from)}T00:00:00Z`)
  )
);
const weekdayFormat = computed(
  () => new Intl.DateTimeFormat(context.locale, { weekday: view.value.zoom === "day" ? "short" : "narrow", timeZone: "UTC" })
);
const monthFormat = computed(() => new Intl.DateTimeFormat(context.locale, { month: "long", year: "numeric", timeZone: "UTC" }));
const formatUtc = (format: Intl.DateTimeFormat, date: string): string => format.format(new Date(`${date}T00:00:00Z`));

const navigate = (anchorDate: string): void => {
  context.state.gantt.value = { ...context.state.gantt.value, anchorDate };
};
const toggle = (key: string): void => {
  const next = new Set(collapsed.value);
  if (next.has(key)) {
    next.delete(key);
  } else {
    next.add(key);
  }
  collapsed.value = next;
};
const request = (task: PlanningTask, operation: DragOperation, amount: number): void => {
  const mutations = timelineDateMutation(task, operation, amount);
  if (mutations.length) {
    planning.value?.request(mutations).catch(() => undefined);
  }
};
const open = (ref_: PlanningRef): void => planning.value?.open(ref_);
const activate = (task: PlanningTask): void => {
  const record = recordFor(task);
  if (record && context.openDetails) {
    context.openDetails(record);
    return;
  }
  open(task.ref);
};
const editable = (task: PlanningTask, hasChildren: boolean): boolean =>
  Boolean(planning.value && snapshot.value) &&
  timelineCanEdit({ task, hasChildren, session: planning.value!, snapshot: snapshot.value! });
const resizable = (hasChildren: boolean): boolean =>
  Boolean(planning.value) && timelineCanResize({ hasChildren, session: planning.value! });
const summary = (hasChildren: boolean): boolean =>
  hasChildren && context.config.table.planning?.parentDates !== "independent";
const shift = (key: string, operation: DragOperation): number =>
  drag.value?.key === key && drag.value.operation === operation ? drag.value.days * geometry.value.width : 0;

const startDrag = (event: PointerEvent, key: string, operation: DragOperation): void => {
  if (event.button !== 0) {
    return;
  }
  drag.value = { key, operation, originX: event.clientX, days: 0, moved: false };
};
const moveDrag = (event: PointerEvent): void => {
  if (!drag.value) {
    return;
  }
  const days = Math.round((event.clientX - drag.value.originX) / geometry.value.width);
  if (days !== drag.value.days) {
    drag.value = { ...drag.value, days, moved: true };
  }
};
const endDrag = (): void => {
  const current = drag.value;
  drag.value = undefined;
  if (!current) {
    return;
  }
  const target = timeline.value.find(
    (row): row is TimelineTaskRow => "task" in row && planningKey(row.task.ref) === current.key
  );
  if (!target) {
    return;
  }
  if (current.moved && current.days) {
    request(target.task, current.operation, current.days);
  } else if (current.operation === "move") {
    // The drag layer swallows the click, so a press without movement still opens the task.
    open(target.task.ref);
  }
};
const keyAdjust = (event: KeyboardEvent, task: PlanningTask, operation: DragOperation): void => {
  if (event.key !== "ArrowLeft" && event.key !== "ArrowRight") {
    return;
  }
  event.preventDefault();
  request(task, operation, (event.key === "ArrowLeft" ? -1 : 1) * (event.shiftKey ? KEYBOARD_WEEK : 1));
};
const hasQuery = computed(() => {
  const advanced = context.state.advancedFilters.value;
  const active = Array.isArray(advanced) ? advanced : (advanced?.filters ?? []);
  return (
    Boolean(context.state.search.value) ||
    Object.keys(context.state.filters.value ?? {}).length > 0 ||
    active.length > 0
  );
});
const onScroll = (): void => {
  scrollTop.value = viewport.value?.scrollTop ?? 0;
  scrollLeft.value = viewport.value?.scrollLeft ?? 0;
};
const toggleSelection = (record: TableRecord, checked: boolean): void => {
  context.selection.value[context.getRowId(record)] = checked;
};

onMounted(() => {
  const element = viewport.value;
  if (!element || typeof ResizeObserver === "undefined") {
    return;
  }
  observer = new ResizeObserver(() => {
    available.value = element.clientWidth;
  });
  observer.observe(element);
  available.value = element.clientWidth;
});
onBeforeUnmount(() => observer?.disconnect());
</script>

<template>
  <p v-if="!planning" class="yayaw-gantt-message" role="alert">{{ labels.noAdapter }}</p>
  <p v-else-if="!snapshot" class="yayaw-gantt-message" role="status">
    {{ busy ? labels.loading : labels.noAdapter }}
  </p>
  <div v-else-if="!timeline.length" class="yayaw-gantt-empty">
    <TableEmptyState />
    <button v-if="hasQuery" type="button" class="yayaw-ghost-button" @click="context.state.resetFilters()">{{ labels.clear }}</button>
  </div>
  <section v-else class="yayaw-gantt" :aria-label="labels.planning">
    <div class="yayaw-gantt-toolbar">
      <h3>{{ periodLabel }}</h3>
      <div class="yayaw-gantt-nav">
        <button type="button" class="yayaw-icon-button" :title="labels.previous" :aria-label="labels.previous" @click="navigate(dayDate(anchorDay - timelinePeriodStep(view.zoom)))">
          <ChevronLeft :size="16" aria-hidden="true" />
        </button>
        <button type="button" class="yayaw-ghost-button" @click="navigate(timelineToday())">{{ labels.today }}</button>
        <button type="button" class="yayaw-icon-button" :title="labels.next" :aria-label="labels.next" @click="navigate(dayDate(anchorDay + timelinePeriodStep(view.zoom)))">
          <ChevronRight :size="16" aria-hidden="true" />
        </button>
        <button type="button" class="yayaw-icon-button" :disabled="busy" :title="labels.retry" :aria-label="labels.retry" @click="planning?.load()">
          <RotateCw :size="16" aria-hidden="true" />
        </button>
      </div>
    </div>
    <p v-if="error" class="yayaw-gantt-error" role="alert">{{ error }}</p>
    <div ref="viewport" class="yayaw-gantt-viewport" :style="{ height: `${geometry.height}px` }" @scroll="onScroll">
      <div class="yayaw-gantt-canvas" :style="{ width: `${geometry.totalWidth}px`, height: `${geometry.canvasHeight}px` }">
        <div class="yayaw-gantt-header" :style="{ height: `${TIMELINE_HEADER_HEIGHT}px` }">
          <div class="yayaw-gantt-label yayaw-gantt-heading" :style="{ width: `${geometry.labelWidth}px` }">
            <FileText :size="16" aria-hidden="true" /><span>{{ labels.task }}</span>
          </div>
          <div v-for="month in months" :key="month.date" class="yayaw-gantt-month" :style="{ left: `${month.left}px`, width: `${month.width}px` }">
            {{ formatUtc(monthFormat, month.date) }}
          </div>
          <div
            v-for="cell in days"
            :key="cell.date"
            class="yayaw-gantt-date"
            :class="{ today: cell.isToday }"
            :title="formatters.day(cell.date)"
            :aria-current="cell.isToday ? 'date' : undefined"
            :style="{ left: `${cell.left}px`, width: `${cell.width}px` }"
          >
            <span v-if="cell.weekday" class="yayaw-gantt-weekday">{{ formatUtc(weekdayFormat, cell.date) }}</span>
            <span v-if="cell.number" class="yayaw-gantt-day">{{ cell.number }}</span>
          </div>
        </div>
        <template v-for="(row, index) in visibleRows" :key="'group' in row ? row.group : planningKey(row.task.ref)">
          <div
            v-if="'group' in row"
            class="yayaw-gantt-row group"
            :style="{ top: rowTop(index), height: `${TIMELINE_ROW_HEIGHT}px` }"
          >
            <div class="yayaw-gantt-label" :style="{ width: `${geometry.labelWidth}px`, paddingLeft: `${LABEL_PADDING}px` }">
              <button
                type="button"
                class="yayaw-icon-button yayaw-gantt-toggle"
                :aria-expanded="!collapsed.has(row.group)"
                :aria-label="`${collapsed.has(row.group) ? labels.expand : labels.collapse} ${groupName(row.value)}`"
                @click="toggle(row.group)"
              >
                <ChevronRight v-if="collapsed.has(row.group)" :size="16" aria-hidden="true" />
                <ChevronDown v-else :size="16" aria-hidden="true" />
              </button>
              <span class="yayaw-gantt-group-name" :title="groupName(row.value)">
                <span class="yayaw-gantt-group-label">{{ groupHeader }}: </span>{{ formatters.group(groupBy, row.value) }}
              </span>
              <span class="yayaw-count">{{ row.count }}</span>
            </div>
            <span
              v-if="timelineBar(row, geometry)"
              class="yayaw-gantt-group-span"
              aria-hidden="true"
              :style="{ left: `${geometry.labelWidth + timelineBar(row, geometry)!.left}px`, width: `${timelineBar(row, geometry)!.width}px` }"
            />
          </div>
          <div
            v-else
            class="yayaw-gantt-row"
            :class="{ summary: row.hasChildren }"
            :style="{ top: rowTop(index), height: `${TIMELINE_ROW_HEIGHT}px` }"
          >
            <div class="yayaw-gantt-label" :style="{ width: `${geometry.labelWidth}px`, paddingLeft: `${LABEL_PADDING + row.depth * TREE_INDENT}px` }">
              <button
                v-if="row.hasChildren"
                type="button"
                class="yayaw-icon-button yayaw-gantt-toggle"
                :aria-expanded="!collapsed.has(planningKey(row.task.ref))"
                :aria-label="collapsed.has(planningKey(row.task.ref)) ? labels.expand : labels.collapse"
                @click="toggle(planningKey(row.task.ref))"
              >
                <ChevronRight v-if="collapsed.has(planningKey(row.task.ref))" :size="16" aria-hidden="true" />
                <ChevronDown v-else :size="16" aria-hidden="true" />
              </button>
              <span v-else class="yayaw-gantt-spacer" aria-hidden="true" />
              <span v-if="context.config.table.enableRowSelection && recordFor(row.task)" class="yayaw-gantt-select" @click.stop>
                <TableCheckbox
                  :label="`${translate('selectRow')} ${formatters.task(row.task)}`"
                  :model-value="Boolean(context.selection.value[context.getRowId(recordFor(row.task)!)])"
                  :disabled="context.config.table.canSelectRow?.(recordFor(row.task)!) === false"
                  @update:model-value="toggleSelection(recordFor(row.task)!, $event)"
                />
              </span>
              <Layers v-if="row.hasChildren" :size="16" aria-hidden="true" class="yayaw-gantt-kind" />
              <FileText v-else :size="16" aria-hidden="true" class="yayaw-gantt-kind" />
              <CellRenderer
                v-if="recordFor(row.task) && titleColumn"
                :column="titleColumn"
                :row="recordFor(row.task)!"
                :value="recordFor(row.task)![titleColumn.accessorKey ?? titleColumn.id]"
              />
              <button v-else type="button" class="yayaw-gantt-title" :title="`${row.task.ref.source} · ${formatters.task(row.task)}`" @click="activate(row.task)">
                {{ formatters.task(row.task) }}
              </button>
            </div>
            <div
              class="yayaw-gantt-track"
              :style="{ left: `${geometry.labelWidth}px`, width: `${geometry.count * geometry.width}px`, backgroundSize: `${geometry.width}px 100%` }"
            >
              <span
                v-for="off in timelineOffDays(row.task, snapshot, geometry)"
                :key="off.left"
                class="yayaw-gantt-off"
                aria-hidden="true"
                :style="{ left: `${off.left}px`, width: `${off.width}px` }"
              />
              <div
                v-if="timelineBar(row.task, geometry)"
                class="yayaw-gantt-bar"
                :class="{ summary: summary(row.hasChildren) }"
                :style="{
                  left: `${timelineBar(row.task, geometry)!.left + shift(planningKey(row.task.ref), 'move') + shift(planningKey(row.task.ref), 'start')}px`,
                  width: `${Math.max(MIN_BAR_WIDTH, timelineBar(row.task, geometry)!.width - shift(planningKey(row.task.ref), 'start') + shift(planningKey(row.task.ref), 'end'))}px`,
                }"
              >
                <button
                  type="button"
                  class="yayaw-gantt-bar-body"
                  :aria-label="`${labels.move} ${formatters.task(row.task)}: ${formatters.day(row.task.start, 'start')} – ${formatters.day(row.task.end, 'end')}`"
                  :title="`${formatters.task(row.task)}: ${formatters.day(row.task.start, 'start')} – ${formatters.day(row.task.end, 'end')}`"
                  @click="open(row.task.ref)"
                  @keydown="editable(row.task, row.hasChildren) && keyAdjust($event, row.task, 'move')"
                  @pointerdown="editable(row.task, row.hasChildren) && startDrag($event, planningKey(row.task.ref), 'move')"
                >
                  {{ formatters.task(row.task) }}
                </button>
                <template v-if="editable(row.task, row.hasChildren) && resizable(row.hasChildren)">
                  <button
                    v-for="side in (['start', 'end'] as const)"
                    :key="side"
                    type="button"
                    class="yayaw-gantt-handle"
                    :class="side"
                    :aria-label="`${side === 'start' ? labels.resizeStart : labels.resizeEnd} ${formatters.task(row.task)}`"
                    @keydown="keyAdjust($event, row.task, side)"
                    @pointerdown="startDrag($event, planningKey(row.task.ref), side)"
                  />
                </template>
              </div>
              <span v-else class="yayaw-gantt-unscheduled">{{ labels.unscheduled }}</span>
            </div>
          </div>
        </template>
        <svg v-if="links.length" class="yayaw-gantt-links" aria-hidden="true" :width="geometry.totalWidth" :height="geometry.canvasHeight">
          <title>{{ labels.dependencies }}</title>
          <path v-for="link in links" :key="link.id" :d="link.d" fill="none" stroke="currentColor" />
        </svg>
        <span
          v-if="todayOffset !== undefined"
          class="yayaw-gantt-today"
          aria-hidden="true"
          :style="{ left: `${todayOffset}px`, top: `${TIMELINE_HEADER_HEIGHT}px`, height: `${geometry.canvasHeight - TIMELINE_HEADER_HEIGHT}px` }"
        />
      </div>
    </div>
    <div v-if="drag" class="yayaw-gantt-drag-layer" aria-hidden="true" @pointermove="moveDrag" @pointerup="endDrag" @pointercancel="endDrag" />
  </section>
</template>
