// packages/yayaw-table-vue/src/calendar/CalendarView.vue
<script setup lang="ts">
import FullCalendar, {
  type CalendarOptions,
  type DateClickInfo,
  type DatesSetInfo,
  type EventChangeInfo,
  type EventClickInfo,
  type EventInput,
  useCalendarController,
} from "@fullcalendar/vue3";
import dayGridPlugin from "@fullcalendar/vue3/daygrid";
import interactionPlugin from "@fullcalendar/vue3/interaction";
import listPlugin from "@fullcalendar/vue3/list";
import frLocale from "@fullcalendar/vue3/locales/fr";
import classicThemePlugin from "@fullcalendar/vue3/themes/classic";
import "@fullcalendar/vue3/skeleton.css";
import "@fullcalendar/vue3/themes/classic/theme.css";
import { ChevronLeft, ChevronRight } from "lucide-vue-next";
import { computed, ref, shallowRef, watch } from "vue";
import {
  addDays,
  type CalendarLayout,
  type CalendarViewSettings,
  calendarEvents,
  calendarMovePatch,
  calendarScope,
  daysBetween,
  resolveCalendarSettings,
} from "../calendar-model";
import type { DisplayModeRenderContext } from "../display-mode-renderer";
import { loadScopedRows, localDayKey } from "../scoped-rows";
import { tagAppearance } from "../tag-colors";
import "../tag-colors.css";
import "./calendar.css";
import type { TableRecord } from "../types";

const props = defineProps<{ context: DisplayModeRenderContext }>();

const VIEW_TYPES: Record<CalendarLayout, string> = {
  month: "dayGridMonth",
  week: "dayGridWeek",
  list: "listMonth",
};
const LAYOUT_LABELS: Record<CalendarLayout, string> = {
  month: "Month",
  week: "Week",
  list: "List",
};
const LAYOUTS = Object.keys(LAYOUT_LABELS) as CalendarLayout[];
const MAX_EVENTS_PER_DAY = 4;

const label = (key: string, fallback: string): string =>
  props.context.translate(`calendar.${key}`, fallback);
const settings = computed(() =>
  resolveCalendarSettings(
    props.context.columns,
    props.context.defaults as CalendarViewSettings,
    props.context.settings as CalendarViewSettings
  )
);
const controller = useCalendarController();
const range = shallowRef<{ start: Date; end: Date }>();
const title = ref("");
const rows = shallowRef<TableRecord[]>([]);
const truncated = ref(false);
const error = ref<string>();

let request: AbortController | undefined;
watch(
  () => [
    range.value,
    settings.value.dateColumn,
    settings.value.endColumn,
    props.context.list,
    props.context.listParams,
    props.context.list ? undefined : props.context.rows,
    props.context.revision,
  ],
  async () => {
    const { dateColumn, endColumn } = settings.value;
    if (!(range.value && dateColumn)) return;
    request?.abort();
    const controllerSignal = new AbortController();
    request = controllerSignal;
    try {
      const result = await loadScopedRows({
        list: props.context.list,
        rows: props.context.list ? undefined : props.context.rows,
        params: props.context.listParams,
        scope: calendarScope({ dateColumn, endColumn }, range.value.start, range.value.end),
        signal: controllerSignal.signal,
      });
      rows.value = result.rows;
      truncated.value = result.truncated;
      error.value = undefined;
    } catch (cause) {
      if (!controllerSignal.signal.aborted)
        error.value = cause instanceof Error ? cause.message : String(cause);
    }
  },
  { immediate: true }
);

const rowsById = computed(
  () => new Map(rows.value.map((row) => [props.context.getRowId(row), row]))
);
const colorColumn = computed(() =>
  props.context.columns.find((column) => column.id === settings.value.colorColumn)
);
const events = computed<EventInput[]>(() =>
  calendarEvents(rows.value, settings.value, props.context.getRowId, {
    columns: props.context.columns,
    locale: props.context.locale,
  }).map((event) => {
    const row = rowsById.value.get(event.id) ?? {};
    const editable = props.context.canEditRow(row);
    const column = colorColumn.value;
    return {
      id: event.id,
      title: event.title,
      start: event.start,
      end: event.end,
      allDay: true,
      startEditable: settings.value.allowDragUpdate && editable,
      durationEditable:
        settings.value.allowResize && Boolean(settings.value.endColumn) && editable,
      extendedProps: {
        appearance:
          event.colorValue === undefined
            ? undefined
            : tagAppearance(
                event.colorValue,
                (column?.coloredTags as boolean | undefined) ?? true,
                column?.tagColorMap as Record<string, string> | undefined
              ),
      },
    };
  })
);

const moveEvent = async (info: EventChangeInfo): Promise<void> => {
  const row = rowsById.value.get(info.event.id);
  const start = localDayKey(info.event.start);
  if (!(row && start)) {
    info.revert();
    return;
  }
  const previousStart = localDayKey(info.oldEvent.start) ?? start;
  const previousEnd = localDayKey(info.oldEvent.end) ?? addDays(previousStart, 1);
  const end =
    localDayKey(info.event.end) ?? addDays(start, daysBetween(previousStart, previousEnd));
  const patch = calendarMovePatch(row, settings.value, start, end);
  // Show the move at once; a failed save puts the event back.
  rows.value = rows.value.map((item) => (item === row ? { ...item, ...patch } : item));
  if (!(await props.context.updateRow(row, patch))) {
    rows.value = rows.value.map((item) =>
      props.context.getRowId(item) === info.event.id ? row : item
    );
    info.revert();
  }
};

const createOn = (info: DateClickInfo): void => {
  const { allowCreate, dateColumn, endColumn } = settings.value;
  const day = localDayKey(info.date);
  if (!(allowCreate && props.context.canCreate && dateColumn && day)) return;
  props.context.createRow({
    [dateColumn]: day,
    ...(endColumn ? { [endColumn]: day } : {}),
  });
};

const setLayout = (layout: CalendarLayout): void => {
  props.context.updateSettings({ ...props.context.settings, layout });
};
watch(
  () => settings.value.layout,
  (layout) => {
    if (controller.view && controller.view.type !== VIEW_TYPES[layout]) {
      controller.changeView(VIEW_TYPES[layout]);
    }
  }
);

const options = computed<CalendarOptions>(() => ({
  plugins: [classicThemePlugin, dayGridPlugin, listPlugin, interactionPlugin],
  controller,
  borderless: true,
  headerToolbar: false,
  height: "auto",
  initialView: VIEW_TYPES[settings.value.layout],
  locale: props.context.locale.startsWith("fr") ? frLocale : props.context.locale,
  firstDay: settings.value.weekStartsOn,
  weekends: settings.value.showWeekends,
  dayMaxEvents: MAX_EVENTS_PER_DAY,
  events: events.value,
  eventClass: "yayaw-calendar-event",
  eventDrop: moveEvent,
  eventResize: moveEvent,
  dateClick: createOn,
  eventClick: (info: EventClickInfo) => {
    info.jsEvent.preventDefault();
    const row = rowsById.value.get(info.event.id);
    if (row) props.context.openRow(row, info.jsEvent);
  },
  datesSet: (info: DatesSetInfo) => {
    const current = range.value;
    if (
      current?.start.getTime() !== info.start.getTime() ||
      current.end.getTime() !== info.end.getTime()
    ) {
      range.value = { start: info.start, end: info.end };
    }
    title.value = info.view.title;
  },
}));
</script>

<template>
  <output v-if="!settings.dateColumn" class="yayaw-calendar-message yayaw-calendar-empty">
    {{ label("noDateColumn", "Add a date column to show this table as a calendar.") }}
  </output>
  <div v-else class="yayaw-calendar-view" :data-calendar-layout="settings.layout">
    <div class="yayaw-calendar-toolbar">
      <div class="yayaw-calendar-nav">
        <button type="button" class="yayaw-button yayaw-button-outline yayaw-icon-only" :aria-label="label('previous', 'Previous')" @click="controller.prev()">
          <ChevronLeft :size="16" aria-hidden="true" />
        </button>
        <button type="button" class="yayaw-button yayaw-button-outline" @click="controller.today()">
          {{ label("today", "Today") }}
        </button>
        <button type="button" class="yayaw-button yayaw-button-outline yayaw-icon-only" :aria-label="label('next', 'Next')" @click="controller.next()">
          <ChevronRight :size="16" aria-hidden="true" />
        </button>
        <h3 class="yayaw-calendar-title" data-calendar-title>{{ title }}</h3>
      </div>
      <fieldset class="yayaw-calendar-layouts">
        <legend class="yayaw-sr-only">{{ label("layout", "Layout") }}</legend>
        <button
          v-for="item in LAYOUTS"
          :key="item"
          type="button"
          class="yayaw-button"
          :class="settings.layout === item ? 'yayaw-button-secondary' : 'yayaw-button-ghost'"
          :aria-pressed="settings.layout === item"
          @click="setLayout(item)"
        >
          {{ label(item, LAYOUT_LABELS[item]) }}
        </button>
      </fieldset>
    </div>
    <div v-if="error" class="yayaw-calendar-message yayaw-calendar-error" role="alert">{{ error }}</div>
    <output v-if="truncated" class="yayaw-calendar-message">
      {{ label("truncated", "Only part of the records are shown. Narrow the filters to see all of them.") }}
    </output>
    <div class="yayaw-calendar">
      <FullCalendar :options="options">
        <template #eventContent="arg">
          <span
            class="yayaw-tag yayaw-calendar-pill"
            :class="arg.event.extendedProps.appearance?.className"
            :data-colored="arg.event.extendedProps.appearance?.colored ? 'true' : undefined"
            :data-custom-color="arg.event.extendedProps.appearance?.className ? '' : undefined"
            :style="arg.event.extendedProps.appearance?.style"
            :title="arg.event.title"
          >{{ arg.event.title }}</span>
        </template>
      </FullCalendar>
    </div>
  </div>
</template>

// src/components/ui/yayaw-table-calendar/calendar-view.tsx
"use client";

import FullCalendar, {
  type DateClickInfo,
  type DatesSetInfo,
  type EventChangeInfo,
  type EventClickInfo,
  type EventDisplayInfo,
  type EventInput,
  useCalendarController,
} from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/react/daygrid";
import interactionPlugin from "@fullcalendar/react/interaction";
import listPlugin from "@fullcalendar/react/list";
import frLocale from "@fullcalendar/react/locales/fr";
import classicThemePlugin from "@fullcalendar/react/themes/classic";
import "@fullcalendar/react/skeleton.css";
import "@fullcalendar/react/themes/classic/theme.css";
import { ChevronLeft, ChevronRight } from "lucide-react";
import {
  type CSSProperties,
  type MouseEvent,
  useEffect,
  useMemo,
  useState,
} from "react";
import { cn } from "@/lib/utils";
import { Button } from "@/src/components/ui/button";
import type { DisplayModeRenderContext } from "@/src/components/ui/yayaw-table/types/display-mode-renderer";
import {
  addDays,
  type CalendarLayout,
  type CalendarViewSettings,
  calendarEvents,
  calendarMovePatch,
  calendarScope,
  daysBetween,
  resolveCalendarSettings,
} from "@/src/components/ui/yayaw-table/utils/calendar-model";
import { localDayKey, loadScopedRows } from "@/src/components/ui/yayaw-table/utils/scoped-rows";
import { tagAppearance } from "@/src/components/ui/yayaw-table/utils/tag-colors";
import "@/src/components/ui/yayaw-table/utils/tag-colors.css";

type RowRecord = Record<string, unknown>;

const VIEW_TYPES: Record<CalendarLayout, string> = {
  month: "dayGridMonth",
  week: "dayGridWeek",
  list: "listMonth",
};
const LAYOUT_LABELS: Record<CalendarLayout, string> = {
  month: "Month",
  week: "Week",
  list: "List",
};
const LAYOUTS = Object.keys(LAYOUT_LABELS) as CalendarLayout[];
const MAX_EVENTS_PER_DAY = 4;

/** The classic theme follows the host's shadcn tokens, light and dark. */
const THEME_STYLE = {
  "--fc-classic-button": "var(--secondary)",
  "--fc-classic-button-border": "var(--border)",
  "--fc-classic-button-strong": "var(--accent)",
  "--fc-classic-button-strong-border": "var(--border)",
  "--fc-classic-button-outline": "var(--ring)",
  "--fc-classic-button-foreground": "var(--secondary-foreground)",
  "--fc-classic-primary": "var(--primary)",
  "--fc-classic-primary-foreground": "var(--primary-foreground)",
  "--fc-classic-event": "transparent",
  "--fc-classic-event-contrast": "var(--foreground)",
  "--fc-classic-background-event": "var(--muted)",
  "--fc-classic-background-event-opacity": "100%",
  "--fc-classic-background-event-foreground-opacity": "60%",
  "--fc-classic-highlight": "color-mix(in oklab, var(--primary) 12%, transparent)",
  "--fc-classic-today": "color-mix(in oklab, var(--primary) 6%, transparent)",
  "--fc-classic-now": "var(--destructive)",
  "--fc-classic-small-dot-width": "8px",
  "--fc-classic-large-dot-width": "10px",
  "--fc-classic-background": "var(--background)",
  "--fc-classic-faint": "color-mix(in oklab, var(--muted) 40%, transparent)",
  "--fc-classic-muted": "var(--muted)",
  "--fc-classic-strong": "var(--accent)",
  "--fc-classic-foreground": "var(--foreground)",
  "--fc-classic-faint-foreground": "var(--muted-foreground)",
  "--fc-classic-muted-foreground": "var(--muted-foreground)",
  "--fc-classic-border": "var(--border)",
  "--fc-classic-strong-border": "var(--input)",
} as CSSProperties;

interface EventMeta {
  row: RowRecord;
  appearance?: ReturnType<typeof tagAppearance>;
}

function useCalendarRows(
  context: DisplayModeRenderContext,
  settings: CalendarViewSettings,
  range: { start: Date; end: Date } | undefined
) {
  const [rows, setRows] = useState<RowRecord[]>([]);
  const [truncated, setTruncated] = useState(false);
  const [error, setError] = useState<string>();
  const { list, listParams, revision } = context;
  const pageRows = list ? undefined : context.rows;
  const { dateColumn, endColumn } = settings;
  // A new request after every mutation (`revision`) as well as query changes.
  const request = useMemo(
    () => ({ params: listParams, revision }),
    [listParams, revision]
  );
  useEffect(() => {
    if (!(range && dateColumn && request.revision >= 0)) {
      return;
    }
    const controller = new AbortController();
    const scope = calendarScope(
      { dateColumn, endColumn },
      range.start,
      range.end
    );
    loadScopedRows({
      list,
      rows: pageRows,
      params: request.params,
      scope,
      signal: controller.signal,
    })
      .then((result) => {
        setRows(result.rows);
        setTruncated(result.truncated);
        setError(undefined);
      })
      .catch((reason: unknown) => {
        if (!controller.signal.aborted) {
          setError(reason instanceof Error ? reason.message : String(reason));
        }
      });
    return () => controller.abort();
  }, [dateColumn, endColumn, list, pageRows, range, request]);
  return { rows, setRows, truncated, error };
}

function EventContent({ info }: { info: EventDisplayInfo }) {
  const meta = info.event.extendedProps as unknown as EventMeta;
  const appearance = meta.appearance;
  return (
    <span
      className={cn(
        "yayaw-tag block w-full truncate px-1.5 py-0.5 text-xs",
        appearance?.colored
          ? appearance.className
          : "bg-secondary text-secondary-foreground",
        !appearance?.colored && "rounded-[0.35rem]"
      )}
      data-colored={appearance?.colored ? "true" : undefined}
      data-custom-color={appearance?.className ? "" : undefined}
      style={appearance?.style as CSSProperties | undefined}
      title={info.event.title}
    >
      {info.event.title}
    </span>
  );
}

function CalendarToolbar({
  context,
  layout,
  onLayout,
  controller,
  title,
}: {
  context: DisplayModeRenderContext;
  layout: CalendarLayout;
  onLayout: (layout: CalendarLayout) => void;
  controller: ReturnType<typeof useCalendarController>;
  title: string;
}) {
  const label = (key: string, fallback: string) =>
    context.translate(`views.calendar.${key}`, fallback);
  return (
    <div className="flex flex-wrap items-center justify-between gap-2">
      <div className="flex items-center gap-1">
        <Button
          aria-label={label("previous", "Previous")}
          className="size-8"
          onClick={() => controller.prev()}
          size="icon"
          type="button"
          variant="outline"
        >
          <ChevronLeft aria-hidden="true" className="size-4" />
        </Button>
        <Button
          className="h-8 font-normal text-xs"
          onClick={() => controller.today()}
          size="sm"
          type="button"
          variant="outline"
        >
          {label("today", "Today")}
        </Button>
        <Button
          aria-label={label("next", "Next")}
          className="size-8"
          onClick={() => controller.next()}
          size="icon"
          type="button"
          variant="outline"
        >
          <ChevronRight aria-hidden="true" className="size-4" />
        </Button>
        <h3 className="ml-2 font-medium text-sm capitalize" data-calendar-title>
          {title}
        </h3>
      </div>
      <fieldset className="flex items-center gap-1">
        <legend className="sr-only">{label("layout", "Layout")}</legend>
        {LAYOUTS.map((item) => (
          <Button
            aria-pressed={layout === item}
            className="h-8 font-normal text-xs"
            key={item}
            onClick={() => onLayout(item)}
            size="sm"
            type="button"
            variant={layout === item ? "secondary" : "ghost"}
          >
            {label(item, LAYOUT_LABELS[item])}
          </Button>
        ))}
      </fieldset>
    </div>
  );
}

/** Calendar display mode for YaYaw Table, rendered with FullCalendar. */
export function CalendarView({
  context,
}: {
  context: DisplayModeRenderContext;
}) {
  const settings = useMemo(
    () =>
      resolveCalendarSettings(
        context.columns,
        context.defaults as CalendarViewSettings,
        context.settings as CalendarViewSettings
      ),
    [context.columns, context.defaults, context.settings]
  );
  const controller = useCalendarController();
  const [range, setRange] = useState<{ start: Date; end: Date }>();
  const [title, setTitle] = useState("");
  const { rows, setRows, truncated, error } = useCalendarRows(
    context,
    settings,
    range
  );
  const colorColumn = context.columns.find(
    (column) => column.id === settings.colorColumn
  );
  const rowsById = useMemo(
    () => new Map(rows.map((row) => [context.getRowId(row), row])),
    [context, rows]
  );
  const events = useMemo<EventInput[]>(
    () =>
      calendarEvents(rows, settings, context.getRowId, {
        columns: context.columns,
        locale: context.locale,
      }).map((event) => {
        const row = rowsById.get(event.id) ?? {};
        const editable = context.canEditRow(row);
        return {
          id: event.id,
          title: event.title,
          start: event.start,
          end: event.end,
          allDay: true,
          startEditable: settings.allowDragUpdate && editable,
          durationEditable:
            settings.allowResize && Boolean(settings.endColumn) && editable,
          extendedProps: {
            row,
            appearance:
              event.colorValue === undefined
                ? undefined
                : tagAppearance(
                    event.colorValue,
                    colorColumn?.coloredTags ?? true,
                    colorColumn?.tagColorMap
                  ),
          } satisfies EventMeta,
        };
      }),
    [colorColumn, context, rows, rowsById, settings]
  );

  const layout = settings.layout;
  useEffect(() => {
    if (controller.view && controller.view.type !== VIEW_TYPES[layout]) {
      controller.changeView(VIEW_TYPES[layout]);
    }
  }, [controller, layout]);

  const moveEvent = async (info: EventChangeInfo) => {
    const row = rowsById.get(info.event.id);
    const start = localDayKey(info.event.start);
    if (!(row && start)) {
      info.revert();
      return;
    }
    const previousStart = localDayKey(info.oldEvent.start) ?? start;
    const previousEnd = localDayKey(info.oldEvent.end) ?? addDays(previousStart, 1);
    const end =
      localDayKey(info.event.end) ??
      addDays(start, daysBetween(previousStart, previousEnd));
    const patch = calendarMovePatch(row, settings, start, end);
    // Show the move at once; a failed save puts the event back.
    setRows((current) =>
      current.map((item) => (item === row ? { ...item, ...patch } : item))
    );
    if (!(await context.updateRow(row, patch))) {
      setRows((current) =>
        current.map((item) =>
          context.getRowId(item) === info.event.id ? row : item
        )
      );
      info.revert();
    }
  };

  const createOn = (info: DateClickInfo) => {
    if (!(settings.allowCreate && context.canCreate && settings.dateColumn)) {
      return;
    }
    const day = localDayKey(info.date);
    if (!day) {
      return;
    }
    context.createRow({
      [settings.dateColumn]: day,
      ...(settings.endColumn ? { [settings.endColumn]: day } : {}),
    });
  };

  if (!settings.dateColumn) {
    return (
      <output className="block rounded-md border p-6 text-muted-foreground text-sm">
        {context.translate(
          "views.calendar.noDateColumn",
          "Add a date column to show this table as a calendar."
        )}
      </output>
    );
  }

  return (
    <div className="grid gap-3" data-calendar-layout={layout}>
      <CalendarToolbar
        context={context}
        controller={controller}
        layout={layout}
        onLayout={(next) =>
          context.updateSettings({ ...context.settings, layout: next })
        }
        title={title}
      />
      {error ? (
        <div className="text-destructive text-sm" role="alert">
          {error}
        </div>
      ) : null}
      {truncated ? (
        <output className="block text-muted-foreground text-sm">
          {context.translate(
            "views.calendar.truncated",
            "Only part of the records are shown. Narrow the filters to see all of them."
          )}
        </output>
      ) : null}
      <div
        className="yayaw-calendar overflow-hidden rounded-md border text-sm"
        style={THEME_STYLE}
      >
        <FullCalendar
          borderless
          controller={controller}
          dateClick={createOn}
          datesSet={(info: DatesSetInfo) => {
            setRange((current) =>
              current?.start.getTime() === info.start.getTime() &&
              current.end.getTime() === info.end.getTime()
                ? current
                : { start: info.start, end: info.end }
            );
            setTitle(info.view.title);
          }}
          dayMaxEvents={MAX_EVENTS_PER_DAY}
          eventClick={(info: EventClickInfo) => {
            info.jsEvent.preventDefault();
            const row = rowsById.get(info.event.id);
            if (row) {
              context.openRow(
                row,
                info.jsEvent as unknown as MouseEvent<HTMLElement>
              );
            }
          }}
          eventClass="yayaw-calendar-event"
          eventContent={(info: EventDisplayInfo) => <EventContent info={info} />}
          eventDrop={moveEvent}
          eventResize={moveEvent}
          events={events}
          firstDay={settings.weekStartsOn}
          headerToolbar={false}
          height="auto"
          initialView={VIEW_TYPES[layout]}
          locale={context.locale.startsWith("fr") ? frLocale : context.locale}
          plugins={[
            classicThemePlugin,
            dayGridPlugin,
            listPlugin,
            interactionPlugin,
          ]}
          weekends={settings.showWeekends}
        />
      </div>
    </div>
  );
}
