// src/components/ui/yayaw-table-chart/chart-funnel.tsx
"use client";

import { useId, useLayoutEffect, useRef, useState } from "react";
import { cn } from "@/lib/utils";
import { Button } from "@/src/components/ui/button";
import {
  type ChartCategory,
  type ChartFunnelStage,
  type ChartFunnelText,
  type ChartLabelKey,
  type ChartModel,
  chartFunnelLayout,
} from "@/src/components/ui/yayaw-table/utils/chart-model";

type Label = (
  key: ChartLabelKey,
  params?: Record<string, number | string>
) => string;

const percentOf = (part: number, whole: number) =>
  `${whole ? (part / whole) * 100 : 0}%`;

/** The funnel's width: measured, and followed as the container resizes. */
function useWidth() {
  const container = useRef<HTMLDivElement>(null);
  const [width, setWidth] = useState(0);
  useLayoutEffect(() => {
    const element = container.current;
    if (!element) {
      return;
    }
    const measure = () => setWidth(Math.round(element.clientWidth));
    measure();
    if (typeof ResizeObserver === "undefined") {
      return;
    }
    const observer = new ResizeObserver(measure);
    observer.observe(element);
    return () => observer.disconnect();
  }, []);
  return { container, width };
}

function FunnelText({
  className,
  text,
}: {
  className: string;
  text: ChartFunnelText;
}) {
  return (
    <text
      className={className}
      textAnchor={text.anchor}
      x={text.x}
      y={text.y}
    >
      {text.text}
    </text>
  );
}

/** "Active: 3, 100% of first" and so on, for assistive technology. */
const stageSummary = (stage: ChartFunnelStage) =>
  [stage.valueText, stage.shareText, stage.conversionText]
    .filter(Boolean)
    .join(", ");

/**
 * The funnel: SVG shapes from the shared geometry (the Vue edition draws the
 * same), with a button over each stage that shows its records.
 */
export function FunnelChart({
  model,
  clickable,
  onGroup,
  label,
}: {
  model: ChartModel;
  clickable: boolean;
  onGroup: (category?: ChartCategory) => void;
  label: Label;
}) {
  const id = useId();
  const { container, width } = useWidth();
  const [active, setActive] = useState<string>();
  const layout = chartFunnelLayout(model.stages ?? [], width);
  return (
    <div
      className="relative w-full"
      data-chart-funnel={layout.orientation}
      ref={container}
    >
      <svg
        aria-describedby={`${id}-desc`}
        aria-labelledby={`${id}-title`}
        className="block h-auto w-full overflow-visible"
        height={layout.height}
        role="img"
        viewBox={`0 0 ${layout.width} ${layout.height}`}
        width={layout.width}
      >
        <title id={`${id}-title`}>{model.title}</title>
        <desc id={`${id}-desc`}>
          {layout.shapes
            .map((shape) => `${shape.stage.label}: ${stageSummary(shape.stage)}`)
            .join("; ")}
        </desc>
        {layout.shapes.map((shape) => (
          <g data-funnel-stage={shape.stage.label} key={shape.stage.id}>
            <polygon
              className={cn(
                "transition-opacity",
                active && active !== shape.stage.id && "opacity-50"
              )}
              fill={shape.stage.color}
              points={shape.points}
            />
            <FunnelText
              className="fill-foreground font-medium text-xs"
              text={shape.name}
            />
            <FunnelText
              className="fill-foreground font-semibold text-xs tabular-nums"
              text={shape.value}
            />
            <FunnelText
              className="fill-muted-foreground text-[11px] tabular-nums"
              text={shape.share}
            />
            {shape.conversion ? (
              <FunnelText
                className="fill-muted-foreground text-[11px] tabular-nums"
                text={shape.conversion}
              />
            ) : null}
          </g>
        ))}
      </svg>
      {clickable
        ? layout.shapes
            .filter((shape) => !shape.stage.category.other)
            .map((shape) => (
              <button
                aria-label={label("showRecords", { group: shape.stage.label })}
                className="absolute cursor-pointer rounded-md outline-none hover:bg-foreground/5 focus-visible:ring-2 focus-visible:ring-ring"
                data-funnel-button
                key={shape.stage.id}
                onBlur={() => setActive(undefined)}
                onClick={() => onGroup(shape.stage.category)}
                onFocus={() => setActive(shape.stage.id)}
                onMouseEnter={() => setActive(shape.stage.id)}
                onMouseLeave={() => setActive(undefined)}
                style={{
                  left: percentOf(shape.box.x, layout.width),
                  top: percentOf(shape.box.y, layout.height),
                  width: percentOf(shape.box.width, layout.width),
                  height: percentOf(shape.box.height, layout.height),
                }}
                type="button"
              />
            ))
        : null}
    </div>
  );
}

/** The funnel's numbers as a table: stage, value, share of the first stage and conversion. */
export function FunnelDataTable({
  model,
  clickable,
  onGroup,
  label,
}: {
  model: ChartModel;
  clickable: boolean;
  onGroup: (category?: ChartCategory) => void;
  label: Label;
}) {
  const percent = (share: number | undefined) =>
    share === undefined ? "—" : model.formatShare(share);
  return (
    <div className="overflow-x-auto rounded-md border">
      <table className="w-full text-sm" data-chart-table>
        <caption className="sr-only">{model.title}</caption>
        <thead className="bg-muted/50 text-left text-muted-foreground">
          <tr>
            <th className="px-3 py-2 font-medium" scope="col">
              {label("stage")}
            </th>
            <th className="px-3 py-2 text-right font-medium" scope="col">
              {model.valueLabel}
            </th>
            <th className="px-3 py-2 text-right font-medium" scope="col">
              {label("shareOfFirst")}
            </th>
            <th className="px-3 py-2 text-right font-medium" scope="col">
              {label("conversion")}
            </th>
          </tr>
        </thead>
        <tbody>
          {(model.stages ?? []).map((stage) => (
            <tr className="border-t" key={stage.id}>
              <th className="px-3 py-1.5 text-left font-normal" scope="row">
                {clickable ? (
                  <Button
                    aria-label={label("showRecords", { group: stage.label })}
                    className="h-auto px-0 py-0 font-normal"
                    onClick={() => onGroup(stage.category)}
                    type="button"
                    variant="link"
                  >
                    {stage.label}
                  </Button>
                ) : (
                  stage.label
                )}
              </th>
              <td className="px-3 py-1.5 text-right tabular-nums">
                {stage.valueText}
              </td>
              <td className="px-3 py-1.5 text-right tabular-nums">
                {percent(stage.shareOfFirst)}
              </td>
              <td className="px-3 py-1.5 text-right tabular-nums">
                {percent(stage.conversion)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// packages/yayaw-table-vue/src/chart/ChartFunnel.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, useId } from "vue";
import {
  type ChartCategory,
  type ChartFunnelStage,
  type ChartLabelKey,
  type ChartModel,
  chartFunnelLayout,
} from "../chart-model";

const props = defineProps<{
  model: ChartModel;
  clickable: boolean;
  label: (key: ChartLabelKey, params?: Record<string, number | string>) => string;
}>();
const emit = defineEmits<{ group: [category: ChartCategory] }>();

const id = useId();
const container = ref<HTMLDivElement>();
const width = ref(0);
const active = ref<string>();
let observer: ResizeObserver | undefined;

// The funnel's width: measured, and followed as the container resizes.
const measure = (): void => {
  width.value = Math.round(container.value?.clientWidth ?? 0);
};
onMounted(() => {
  measure();
  if (typeof ResizeObserver === "undefined" || !container.value) return;
  observer = new ResizeObserver(measure);
  observer.observe(container.value);
});
onBeforeUnmount(() => observer?.disconnect());

/** The same shapes and texts as the React edition, from the shared geometry. */
const layout = computed(() => chartFunnelLayout(props.model.stages ?? [], width.value));
const percentOf = (part: number, whole: number): string =>
  `${whole ? (part / whole) * 100 : 0}%`;
/** "Active: 3, 100% of first" and so on, for assistive technology. */
const summary = computed(() =>
  layout.value.shapes
    .map(({ stage }: { stage: ChartFunnelStage }) =>
      `${stage.label}: ${[stage.valueText, stage.shareText, stage.conversionText].filter(Boolean).join(", ")}`
    )
    .join("; ")
);
const buttons = computed(() =>
  props.clickable ? layout.value.shapes.filter((shape) => !shape.stage.category.other) : []
);
</script>

<template>
  <div ref="container" class="yayaw-chart-funnel" :data-chart-funnel="layout.orientation">
    <svg
      role="img"
      :aria-labelledby="`${id}-title`"
      :aria-describedby="`${id}-desc`"
      :viewBox="`0 0 ${layout.width} ${layout.height}`"
      :width="layout.width"
      :height="layout.height"
    >
      <title :id="`${id}-title`">{{ props.model.title }}</title>
      <desc :id="`${id}-desc`">{{ summary }}</desc>
      <g v-for="shape in layout.shapes" :key="shape.stage.id" :data-funnel-stage="shape.stage.label">
        <polygon
          :points="shape.points"
          :fill="shape.stage.color"
          :class="{ 'yayaw-chart-funnel-dim': active && active !== shape.stage.id }"
        />
        <text class="yayaw-chart-funnel-name" :x="shape.name.x" :y="shape.name.y" :text-anchor="shape.name.anchor">{{ shape.name.text }}</text>
        <text class="yayaw-chart-funnel-value" :x="shape.value.x" :y="shape.value.y" :text-anchor="shape.value.anchor">{{ shape.value.text }}</text>
        <text class="yayaw-chart-funnel-rate" :x="shape.share.x" :y="shape.share.y" :text-anchor="shape.share.anchor">{{ shape.share.text }}</text>
        <text
          v-if="shape.conversion"
          class="yayaw-chart-funnel-rate"
          :x="shape.conversion.x"
          :y="shape.conversion.y"
          :text-anchor="shape.conversion.anchor"
        >{{ shape.conversion.text }}</text>
      </g>
    </svg>
    <button
      v-for="shape in buttons"
      :key="shape.stage.id"
      type="button"
      class="yayaw-chart-funnel-button"
      data-funnel-button
      :aria-label="props.label('showRecords', { group: shape.stage.label })"
      :style="{
        left: percentOf(shape.box.x, layout.width),
        top: percentOf(shape.box.y, layout.height),
        width: percentOf(shape.box.width, layout.width),
        height: percentOf(shape.box.height, layout.height),
      }"
      @click="emit('group', shape.stage.category)"
      @focus="active = shape.stage.id"
      @blur="active = undefined"
      @mouseenter="active = shape.stage.id"
      @mouseleave="active = undefined"
    />
  </div>
</template>
