// src/components/ui/yayaw-table/components/toolbar/import-panel.tsx
"use client";

import { FileUp, Loader2, RefreshCw, Upload } from "lucide-react";
import { type DragEvent, useEffect, useId, useRef, useState } from "react";
import {
  StackMenuContent,
  StackMenuItem,
  useStackMenu,
} from "@/components/ui/custom/stack-menu";
import { cn } from "@/lib/utils";
import { Button } from "@/src/components/ui/button";
import { Checkbox } from "@/src/components/ui/checkbox";
import { Textarea } from "@/src/components/ui/textarea";
import {
  applyImportField,
  canRunImport,
  createImportFlow,
  describeImportResult,
  type ImportFlow,
  type ImportFlowState,
  type ImportSource,
  type ImportT,
  type ImportTranslate,
  importErrorLines,
  importFailureLines,
  importLabels,
  importMappingRows,
  importPreview,
  importRowCount,
  importSettingsFields,
  importSummaryLines,
} from "../../utils/import-flow";
import type {
  ImportAdapters,
  ImportColumn,
  ImportRunResult,
} from "../../utils/import-model";
import { ColumnMapping } from "./column-mapping";

/** A connector that can pull: it opens its own screen, direction preset to pull. */
export interface ConnectorImportSource {
  id: string;
  label: string;
  description?: string;
  /** The stack menu screen to open. */
  screen: string;
  title: string;
}

export interface ImportPanelProps {
  columns: ImportColumn[];
  locale: string;
  translate: ImportTranslate;
  adapters: ImportAdapters;
  /** Offer CSV and JSON files and pasted text (default true). */
  csv?: boolean;
  sources?: Pick<ImportSource, "id" | "label" | "description">[];
  /** Connectors listed with the sources ("From Notion"). */
  connectorSources?: ConnectorImportSource[];
  loadSource?: Parameters<typeof createImportFlow>[0]["loadSource"];
  findExisting: Parameters<typeof createImportFlow>[0]["findExisting"];
  batchSize?: number;
  allowNewOptions?: boolean;
  /** `actions.geocode`: addresses imported into location columns become places. */
  geocode?: Parameters<typeof createImportFlow>[0]["geocode"];
  onImported: (result: ImportRunResult) => void;
}

interface StepProps {
  flow: ImportFlow;
  state: ImportFlowState;
  t: ImportT;
}

/** The CSV or JSON drop zone, file picker and paste box. */
function CsvSource({ flow, state, t }: StepProps) {
  const id = useId();
  const [text, setText] = useState("");
  const [dragging, setDragging] = useState(false);
  const input = useRef<HTMLInputElement>(null);
  const readFile = (file: File | undefined) => {
    if (file) {
      flow.loadFile(file).catch(() => undefined);
    }
  };
  const onDrop = (event: DragEvent<HTMLElement>) => {
    event.preventDefault();
    setDragging(false);
    readFile(event.dataTransfer.files[0]);
  };
  return (
    <div className="grid gap-3" data-import-csv>
      <button
        className={cn(
          "grid h-auto cursor-pointer justify-items-center gap-2 rounded-md border border-dashed px-3 py-5 text-center text-sm hover:bg-accent/50",
          dragging && "border-primary bg-accent"
        )}
        data-import-drop
        onClick={() => input.current?.click()}
        onDragLeave={() => setDragging(false)}
        onDragOver={(event) => {
          event.preventDefault();
          setDragging(true);
        }}
        onDrop={onDrop}
        type="button"
      >
        <FileUp aria-hidden="true" className="size-5 text-muted-foreground" />
        <span className="font-medium">{t("sourceCsv")}</span>
        <span className="text-muted-foreground text-xs">
          {t("dropHint")} · {t("sourceCsvHint")}
        </span>
        <span className="mt-1 inline-flex h-8 items-center rounded-md border bg-background px-3 font-medium text-sm">
          {t("chooseFile")}
        </span>
      </button>
      <input
        accept=".csv,.tsv,.txt,.json,.jsonl,.ndjson,text/csv,text/plain,application/json,application/x-ndjson"
        aria-label={t("chooseFile")}
        className="sr-only"
        onChange={(event) => {
          readFile(event.target.files?.[0]);
          event.target.value = "";
        }}
        ref={input}
        tabIndex={-1}
        type="file"
      />
      {state.loading ? (
        <p className="flex items-center gap-2 text-muted-foreground text-sm">
          <Loader2 aria-hidden="true" className="size-4 animate-spin" />
          {t("reading")}
        </p>
      ) : null}
      <div className="grid gap-1.5">
        <label className="text-muted-foreground text-sm" htmlFor={`${id}-paste`}>
          {t("pasteLabel")}
        </label>
        <Textarea
          className="min-h-20 font-mono text-xs"
          id={`${id}-paste`}
          onChange={(event) => setText(event.target.value)}
          value={text}
        />
        <Button
          className="justify-self-end"
          disabled={!text.trim()}
          onClick={() => flow.loadText(text)}
          type="button"
          variant="outline"
        >
          {t("usePasted")}
        </Button>
      </div>
    </div>
  );
}

/** Step 1: CSV and the host's sources. */
function SourceStep({
  csv,
  sources,
  connectorSources = [],
  ...props
}: StepProps & {
  csv: boolean;
  sources: ImportPanelProps["sources"];
  connectorSources?: ConnectorImportSource[];
}) {
  const { flow, state, t } = props;
  return (
    <div className="grid gap-3" data-import-step="source">
      {csv ? <CsvSource {...props} /> : null}
      {sources?.length || connectorSources.length > 0 ? (
        <div className="grid gap-1">
          <h3 className="font-medium text-sm">{t("source")}</h3>
          {connectorSources.map((source) => (
            <StackMenuItem
              data-import-connector={source.id}
              description={source.description}
              icon={<RefreshCw className="size-4" />}
              key={`connector:${source.id}`}
              navigateTitle={source.title}
              navigateTo={source.screen}
            >
              {source.label}
            </StackMenuItem>
          ))}
          {(sources ?? []).map((source) => (
            <StackMenuItem
              data-import-source={source.id}
              description={source.description}
              disabled={state.loading}
              icon={<Upload className="size-4" />}
              key={source.id}
              onClick={() => {
                flow.loadSource(source.id).catch(() => undefined);
              }}
            >
              {source.label}
            </StackMenuItem>
          ))}
        </div>
      ) : null}
      {state.error ? (
        <p
          className="rounded-md border border-destructive/40 px-3 py-2 text-destructive text-sm"
          data-import-error
          role="alert"
        >
          {state.error}
        </p>
      ) : null}
    </div>
  );
}

/** Step 2: the column mapping, separator, header row and key column. */
function MappingStep({
  columns,
  locale,
  allowNewOptions,
  ...props
}: StepProps & {
  columns: ImportColumn[];
  locale: string;
  allowNewOptions?: boolean;
}) {
  const { flow, state, t } = props;
  const id = useId();
  const settings = importSettingsFields(state, { columns, t });
  const delimiter = settings.find((field) => field.id === "delimiter");
  const key = settings.find((field) => field.id === "key");
  return (
    <div className="grid min-w-0 gap-3" data-import-step="mapping">
      <ColumnMapping
        intro={
          <>
            <p className="text-muted-foreground text-sm" data-import-file>
              {[state.sourceName, importRowCount(state, t)]
                .filter(Boolean)
                .join(" · ")}
            </p>
            {state.text === null ? null : (
              <div className="flex min-h-8 items-center gap-2 text-sm">
                <Checkbox
                  aria-label={t("headers")}
                  checked={state.hasHeaders}
                  id={`${id}-headers`}
                  onCheckedChange={(checked) =>
                    flow.setHasHeaders(checked === true)
                  }
                />
                <label className="cursor-pointer" htmlFor={`${id}-headers`}>
                  {t("headers")}
                </label>
              </div>
            )}
          </>
        }
        after={[]}
        before={delimiter ? [delimiter] : []}
        keyField={
          key
            ? {
                ...key,
                after: (
                  <p className="text-muted-foreground text-xs">{t("keyHint")}</p>
                ),
              }
            : undefined
        }
        onChange={(fieldId, value) => applyImportField(flow, fieldId, value)}
        preview={{
          label: t("preview"),
          ...importPreview(state, { columns, locale, t, allowNewOptions }),
        }}
        rows={importMappingRows(state, { columns, locale, t, allowNewOptions })}
      >
        {state.error ? (
          <p className="text-destructive text-sm" role="alert">
            {state.error}
          </p>
        ) : null}
        <div className="flex gap-2">
          <Button
            className="flex-1"
            onClick={flow.back}
            type="button"
            variant="outline"
          >
            {t("back")}
          </Button>
          <Button
            aria-busy={state.loading}
            className="flex-1"
            disabled={state.loading}
            onClick={() => {
              flow.review().catch(() => undefined);
            }}
            type="button"
          >
            {state.loading ? (
              <Loader2 aria-hidden="true" className="size-4 animate-spin" />
            ) : null}
            {t("review")}
          </Button>
        </div>
      </ColumnMapping>
    </div>
  );
}

/** Step 3: counts, first errors, skip errors, then Import. */
function ReviewStep({
  columns,
  ...props
}: StepProps & { columns: ImportColumn[] }) {
  const { flow, state, t } = props;
  const { goBack } = useStackMenu();
  const id = useId();
  if (!state.plan) {
    return null;
  }
  const lines = importSummaryLines(state.plan, state.skipErrors, t);
  const errors = importErrorLines(state.plan, {
    columns,
    t,
    hasHeaders: state.hasHeaders,
  });
  const runnable = canRunImport(state.plan, state.skipErrors);
  return (
    <div className="grid gap-3" data-import-step="review">
      <output
        aria-live="polite"
        className="grid gap-1 rounded-md bg-muted px-3 py-2 text-sm"
        data-import-summary
      >
        {lines.creates ? (
          <p data-import-creates>{lines.creates}</p>
        ) : null}
        {lines.updates ? (
          <p data-import-updates>{lines.updates}</p>
        ) : null}
        {lines.errors ? (
          <p className="text-destructive" data-import-errors>
            {lines.errors}
          </p>
        ) : null}
        {errors.map((line) => (
          <p className="text-destructive text-xs" key={line}>
            {line}
          </p>
        ))}
        {lines.creates || lines.updates || lines.errors ? null : (
          <p>{t("nothingToImport")}</p>
        )}
      </output>
      {state.plan.errorRows.length > 0 ? (
        <div className="flex min-h-8 items-center gap-2 text-sm">
          <Checkbox
            checked={state.skipErrors}
            id={`${id}-skip`}
            aria-label={t("skipErrors")}
            onCheckedChange={(checked) => flow.setSkipErrors(checked === true)}
          />
          <label className="cursor-pointer" htmlFor={`${id}-skip`}>
            {t("skipErrors")}
          </label>
        </div>
      ) : null}
      {state.plan.errorRows.length > 0 && !state.skipErrors ? (
        <p className="text-muted-foreground text-xs">{t("errorsBlock")}</p>
      ) : null}
      {state.error ? (
        <p className="text-destructive text-sm" role="alert">
          {state.error}
        </p>
      ) : null}
      <div className="flex flex-wrap gap-2">
        <Button className="flex-1" onClick={flow.back} type="button" variant="outline">
          {t("back")}
        </Button>
        <Button className="flex-1" onClick={goBack} type="button" variant="outline">
          {t("cancel")}
        </Button>
        <Button
          className="w-full"
          disabled={!runnable}
          onClick={() => {
            flow.run().catch(() => undefined);
          }}
          type="button"
        >
          <Upload aria-hidden="true" className="size-4" />
          {t("import")}
        </Button>
      </div>
    </div>
  );
}

/** Step 4: progress, then the result. */
function RunStep({ flow, state, t }: StepProps) {
  const { goBack } = useStackMenu();
  if (state.step === "running") {
    const { done, total } = state.progress ?? { done: 0, total: 0 };
    return (
      <div className="grid gap-3" data-import-step="running">
        <p className="text-sm">{t("importing", { done, total })}</p>
        <div
          aria-label={t("importing", { done, total })}
          aria-valuemax={total}
          aria-valuemin={0}
          aria-valuenow={done}
          className="h-2 overflow-hidden rounded-full bg-muted"
          role="progressbar"
        >
          <div
            className="h-full bg-primary transition-[width]"
            style={{ width: `${total ? (done / total) * 100 : 0}%` }}
          />
        </div>
        <Button onClick={flow.stop} type="button" variant="outline">
          {t("stop")}
        </Button>
      </div>
    );
  }
  if (!state.result) {
    return null;
  }
  const failures = importFailureLines(state.result, {
    t,
    hasHeaders: state.hasHeaders,
  });
  return (
    <div className="grid gap-3" data-import-step="result">
      <output
        aria-live="polite"
        className="grid gap-1 rounded-md bg-muted px-3 py-2 text-sm"
      >
        <p className="font-medium" data-import-result>
          {describeImportResult(state.result, t)}
        </p>
        {failures.map((line) => (
          <p className="text-destructive" key={line}>
            {line}
          </p>
        ))}
        {state.result.aborted ? (
          <p className="text-muted-foreground">{t("stopped")}</p>
        ) : null}
      </output>
      <div className="flex flex-wrap gap-2">
        <Button className="flex-1" onClick={goBack} type="button">
          {t("done")}
        </Button>
        <Button className="flex-1" onClick={flow.reset} type="button" variant="outline">
          {t("another")}
        </Button>
      </div>
    </div>
  );
}

/**
 * Data › Import: a source (CSV file, pasted text or a host source), the
 * column mapping, a review, then progress and the result. The flow is shared
 * with the Vue edition; the host only writes rows.
 */
export function ImportPanel(props: ImportPanelProps) {
  // The table the screen was opened on owns the import; capture it once.
  const [opened] = useState(() => ({
    ...props,
    t: importLabels(props.locale, props.translate),
  }));
  const [state, setState] = useState<ImportFlowState>();
  const flowRef = useRef<ImportFlow>(null);
  useEffect(() => {
    const flow = createImportFlow({
      columns: opened.columns,
      locale: opened.locale,
      t: opened.t,
      adapters: opened.adapters,
      findExisting: opened.findExisting,
      loadSource: opened.loadSource,
      batchSize: opened.batchSize,
      allowNewOptions: opened.allowNewOptions,
      geocode: opened.geocode,
      onChange: setState,
      onImported: opened.onImported,
    });
    flowRef.current = flow;
    setState(flow.state);
    return () => flow.dispose();
  }, [opened]);
  const flow = flowRef.current;
  const { t } = opened;
  if (!(state && flow)) {
    return null;
  }
  const step = { flow, state, t };
  return (
    <StackMenuContent className="p-3" data-import-panel>
      {state.step === "source" ? (
        <SourceStep
          {...step}
          connectorSources={opened.connectorSources}
          csv={opened.csv !== false}
          sources={opened.sources}
        />
      ) : null}
      {state.step === "mapping" ? (
        <MappingStep
          {...step}
          allowNewOptions={opened.allowNewOptions}
          columns={opened.columns}
          locale={opened.locale}
        />
      ) : null}
      {state.step === "review" ? (
        <ReviewStep {...step} columns={opened.columns} />
      ) : null}
      {state.step === "running" || state.step === "result" ? (
        <RunStep {...step} />
      ) : null}
    </StackMenuContent>
  );
}

// packages/yayaw-table-vue/src/components/toolbar/ImportPanel.vue
<script setup lang="ts">
import { FileUp, RefreshCw, Upload } from "lucide-vue-next";
import { computed, onBeforeUnmount, ref, shallowRef, useId, useTemplateRef } from "vue";
import {
  applyImportField,
  canRunImport,
  createImportFlow,
  describeImportResult,
  type ImportFlowOptions,
  type ImportFlowState,
  type ImportSource,
  type ImportTranslate,
  importErrorLines,
  importFailureLines,
  importLabels,
  importMappingRows,
  importPreview,
  importRowCount,
  importSettingsFields,
  importSummaryLines,
} from "../../import-flow";
import type { ImportAdapters, ImportColumn, ImportRunResult } from "../../import-model";
import TableCheckbox from "../controls/TableCheckbox.vue";
import ColumnMapping from "./ColumnMapping.vue";

/**
 * Data › Import: a source (CSV file, pasted text or a host source), the
 * column mapping, a review, then progress and the result. The flow is shared
 * with the React edition; the host only writes rows.
 */
const props = defineProps<{
  columns: ImportColumn[];
  locale: string;
  translate: ImportTranslate;
  adapters: ImportAdapters;
  /** Offer CSV and JSON files and pasted text (default true). */
  csv?: boolean;
  sources?: Pick<ImportSource, "id" | "label" | "description">[];
  /** Connectors that can pull, listed with the sources ("From Notion"); they open their own screen. */
  connectorSources?: { id: string; label: string; description?: string }[];
  loadSource?: ImportFlowOptions["loadSource"];
  findExisting: ImportFlowOptions["findExisting"];
  batchSize?: number;
  allowNewOptions?: boolean;
  /** `actions.geocode`: addresses imported into location columns become places. */
  geocode?: ImportFlowOptions["geocode"];
}>();
const emit = defineEmits<{ done: []; imported: [result: ImportRunResult]; connector: [id: string] }>();
const id = useId();
// The table the screen was opened on owns the import; capture it once.
const opened = { columns: props.columns, locale: props.locale, allowNewOptions: props.allowNewOptions };
const t = importLabels(props.locale, props.translate);
const flow = createImportFlow({
  columns: opened.columns,
  locale: opened.locale,
  t,
  adapters: props.adapters,
  findExisting: props.findExisting,
  loadSource: props.loadSource,
  batchSize: props.batchSize,
  allowNewOptions: opened.allowNewOptions,
  geocode: props.geocode,
  onChange: (next) => {
    state.value = next;
  },
  onImported: (result) => emit("imported", result),
});
const state = shallowRef<ImportFlowState>(flow.state);
onBeforeUnmount(() => flow.dispose());

const pasted = ref("");
const fileInput = useTemplateRef<HTMLInputElement>("fileInput");
const dragging = ref(false);
const readFile = (file: File | undefined): void => {
  if (file) {
    flow.loadFile(file).catch(() => undefined);
  }
};
const onFile = (event: Event): void => {
  const input = event.target as HTMLInputElement;
  readFile(input.files?.[0]);
  input.value = "";
};
const onDrop = (event: DragEvent): void => {
  dragging.value = false;
  readFile(event.dataTransfer?.files[0]);
};

const screen = { columns: opened.columns, locale: opened.locale, t, allowNewOptions: opened.allowNewOptions };
const settings = computed(() => importSettingsFields(state.value, { columns: opened.columns, t }));
const delimiterFields = computed(() => settings.value.filter((field) => field.id === "delimiter"));
const keyField = computed(() => settings.value.find((field) => field.id === "key"));
const rows = computed(() => importMappingRows(state.value, screen));
const preview = computed(() => ({ label: t("preview"), ...importPreview(state.value, screen) }));
const fileLine = computed(() => [state.value.sourceName, importRowCount(state.value, t)].filter(Boolean).join(" · "));
const summary = computed(() => (state.value.plan ? importSummaryLines(state.value.plan, state.value.skipErrors, t) : null));
const errorLines = computed(() =>
  state.value.plan ? importErrorLines(state.value.plan, { columns: opened.columns, t, hasHeaders: state.value.hasHeaders }) : []
);
const runnable = computed(() => (state.value.plan ? canRunImport(state.value.plan, state.value.skipErrors) : false));
const hasErrors = computed(() => (state.value.plan?.errorRows.length ?? 0) > 0);
const progress = computed(() => state.value.progress ?? { done: 0, total: 0 });
const progressText = computed(() => t("importing", progress.value));
const failures = computed(() =>
  state.value.result ? importFailureLines(state.value.result, { t, hasHeaders: state.value.hasHeaders }) : []
);
const change = (fieldId: string, value: string): void => applyImportField(flow, fieldId, value);
const review = (): void => {
  flow.review().catch(() => undefined);
};
const run = (): void => {
  flow.run().catch(() => undefined);
};
const loadSource = (sourceId: string): void => {
  flow.loadSource(sourceId).catch(() => undefined);
};
</script>

<template>
  <div class="yayaw-import-panel" data-import-panel>
    <div v-if="state.step === 'source'" class="yayaw-import-step" data-import-step="source">
      <div v-if="csv !== false" class="yayaw-import-step" data-import-csv>
        <button type="button" class="yayaw-import-drop" :class="{ 'yayaw-import-dragging': dragging }" data-import-drop
          @click="fileInput?.click()" @dragover.prevent="dragging = true" @dragleave="dragging = false" @drop.prevent="onDrop">
          <FileUp :size="20" aria-hidden="true" class="yayaw-import-muted" />
          <span class="yayaw-import-strong">{{ t("sourceCsv") }}</span>
          <span class="yayaw-import-muted yayaw-import-small">{{ t("dropHint") }} · {{ t("sourceCsvHint") }}</span>
          <span class="yayaw-import-choose">{{ t("chooseFile") }}</span>
        </button>
        <input ref="fileInput" class="yayaw-sr-only" type="file" tabindex="-1" :aria-label="t('chooseFile')"
          accept=".csv,.tsv,.txt,.json,.jsonl,.ndjson,text/csv,text/plain,application/json,application/x-ndjson" @change="onFile" />
        <p v-if="state.loading" class="yayaw-schedule-loading"><span class="yayaw-spinner" aria-hidden="true" />{{ t("reading") }}</p>
        <div class="yayaw-import-paste">
          <label :for="`${id}-paste`">{{ t("pasteLabel") }}</label>
          <textarea :id="`${id}-paste`" v-model="pasted" class="yayaw-textarea yayaw-import-textarea" />
          <button type="button" class="yayaw-button yayaw-button-outline" :disabled="!pasted.trim()" @click="flow.loadText(pasted)">
            {{ t("usePasted") }}
          </button>
        </div>
      </div>
      <div v-if="sources?.length || connectorSources?.length" class="yayaw-options-list">
        <h3 class="yayaw-setting-heading">{{ t("source") }}</h3>
        <button v-for="source in connectorSources ?? []" :key="`connector:${source.id}`" type="button" class="yayaw-options-item"
          :data-import-connector="source.id" @click="emit('connector', source.id)">
          <span class="yayaw-options-item-icon"><RefreshCw :size="16" aria-hidden="true" /></span>
          <span class="yayaw-options-item-copy"><span>{{ source.label }}</span><small v-if="source.description">{{ source.description }}</small></span>
        </button>
        <button v-for="source in sources ?? []" :key="source.id" type="button" class="yayaw-options-item" :disabled="state.loading"
          :data-import-source="source.id" @click="loadSource(source.id)">
          <span class="yayaw-options-item-icon"><Upload :size="16" aria-hidden="true" /></span>
          <span class="yayaw-options-item-copy"><span>{{ source.label }}</span><small v-if="source.description">{{ source.description }}</small></span>
        </button>
      </div>
      <p v-if="state.error" class="yayaw-connector-error" data-import-error role="alert">{{ state.error }}</p>
    </div>

    <div v-else-if="state.step === 'mapping'" class="yayaw-import-step" data-import-step="mapping">
      <ColumnMapping :before="delimiterFields" :rows="rows" :key-field="keyField" :preview="preview" @change="change">
        <template #intro>
          <p class="yayaw-import-muted yayaw-import-text" data-import-file>{{ fileLine }}</p>
          <label v-if="state.text !== null" class="yayaw-import-check">
            <TableCheckbox :model-value="state.hasHeaders" :label="t('headers')" @update:model-value="flow.setHasHeaders" />
            <span>{{ t("headers") }}</span>
          </label>
        </template>
        <template #after-key>
          <p class="yayaw-connector-hint">{{ t("keyHint") }}</p>
        </template>
        <p v-if="state.error" class="yayaw-connector-error" role="alert">{{ state.error }}</p>
        <div class="yayaw-schedule-actions">
          <button type="button" class="yayaw-button yayaw-button-outline" @click="flow.back()">{{ t("back") }}</button>
          <button type="button" class="yayaw-button" :disabled="state.loading" :aria-busy="state.loading" @click="review">
            <span v-if="state.loading" class="yayaw-spinner" aria-hidden="true" />{{ t("review") }}
          </button>
        </div>
      </ColumnMapping>
    </div>

    <div v-else-if="state.step === 'review' && state.plan" class="yayaw-import-step" data-import-step="review">
      <output class="yayaw-connector-summary" aria-live="polite" data-import-summary>
        <p v-if="summary?.creates" data-import-creates>{{ summary.creates }}</p>
        <p v-if="summary?.updates" data-import-updates>{{ summary.updates }}</p>
        <p v-if="summary?.errors" class="yayaw-connector-failure" data-import-errors>{{ summary.errors }}</p>
        <p v-for="line in errorLines" :key="line" class="yayaw-connector-failure yayaw-import-small">{{ line }}</p>
        <p v-if="!(summary?.creates || summary?.updates || summary?.errors)">{{ t("nothingToImport") }}</p>
      </output>
      <label v-if="hasErrors" class="yayaw-import-check">
        <TableCheckbox :model-value="state.skipErrors" :label="t('skipErrors')" @update:model-value="flow.setSkipErrors" />
        <span>{{ t("skipErrors") }}</span>
      </label>
      <p v-if="hasErrors && !state.skipErrors" class="yayaw-connector-hint">{{ t("errorsBlock") }}</p>
      <p v-if="state.error" class="yayaw-connector-error" role="alert">{{ state.error }}</p>
      <div class="yayaw-schedule-actions">
        <button type="button" class="yayaw-button yayaw-button-outline" @click="flow.back()">{{ t("back") }}</button>
        <button type="button" class="yayaw-button yayaw-button-outline" @click="emit('done')">{{ t("cancel") }}</button>
        <button type="button" class="yayaw-button yayaw-import-run" :disabled="!runnable" @click="run">
          <Upload :size="16" aria-hidden="true" />{{ t("import") }}
        </button>
      </div>
    </div>

    <div v-else-if="state.step === 'running'" class="yayaw-import-step" data-import-step="running">
      <p class="yayaw-import-text">{{ progressText }}</p>
      <div class="yayaw-import-progress" role="progressbar" :aria-label="progressText" :aria-valuemin="0"
        :aria-valuemax="progress.total" :aria-valuenow="progress.done">
        <div :style="{ width: `${progress.total ? (progress.done / progress.total) * 100 : 0}%` }" />
      </div>
      <button type="button" class="yayaw-button yayaw-button-outline" @click="flow.stop()">{{ t("stop") }}</button>
    </div>

    <div v-else-if="state.step === 'result' && state.result" class="yayaw-import-step" data-import-step="result">
      <output class="yayaw-connector-summary" aria-live="polite">
        <p class="yayaw-connector-counts" data-import-result>{{ describeImportResult(state.result, t) }}</p>
        <p v-for="line in failures" :key="line" class="yayaw-connector-failure">{{ line }}</p>
        <p v-if="state.result.aborted" class="yayaw-schedule-muted">{{ t("stopped") }}</p>
      </output>
      <div class="yayaw-schedule-actions">
        <button type="button" class="yayaw-button" @click="emit('done')">{{ t("done") }}</button>
        <button type="button" class="yayaw-button yayaw-button-outline" @click="flow.reset()">{{ t("another") }}</button>
      </div>
    </div>
  </div>
</template>
