// registry/default/ui/yayaw-table/components/cells/cell-actions.tsx
"use client";

import { Check, Copy } from "lucide-react";
import { type ReactNode, type SyntheticEvent, useState } from "react";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { ColumnDefinition } from "../../config/helpers";
import { useTranslations } from "../../providers/table-provider";
import {
  type ResolvedCellAction,
  resolveCellActions,
} from "../../utils/cell-actions";
import { TableTooltip } from "../../utils/table-tooltip";

const COPIED_FEEDBACK_MS = 1500;

/** Actions sit at the control size of the table's density, like row actions. */
const actionClassName = cn(
  buttonVariants({ variant: "ghost", size: "sm" }),
  "[&_svg]:!size-[1.1em] h-[var(--yayaw-inline-control-height,1.75rem)] min-w-[var(--yayaw-inline-control-height,1.75rem)] gap-1 px-1 font-normal text-[length:inherit] text-muted-foreground aria-disabled:cursor-not-allowed aria-disabled:opacity-50"
);

// Actions keep their clicks: no row click, no inline edit, no drag.
const stop = (event: SyntheticEvent) => event.stopPropagation();

function CellActionControl({
  action,
  copiedLabel,
}: {
  action: ResolvedCellAction<ReactNode>;
  copiedLabel: string;
}) {
  const [copied, setCopied] = useState(false);
  const isCopy = action.copyText !== undefined;
  const label = copied ? copiedLabel : action.label;
  let icon = action.icon;
  if (isCopy) {
    icon = copied ? <Check aria-hidden /> : <Copy aria-hidden />;
  }
  const content = (
    <>
      {icon ?? <span>{action.label}</span>}
      {action.count === undefined ? null : (
        <span className="tabular-nums">{action.count}</span>
      )}
    </>
  );
  const iconOnly = Boolean(icon) && action.count === undefined;
  const common = {
    "aria-label": label,
    onDoubleClick: stop,
    onKeyDown: stop,
    onPointerDown: stop,
    className: cn(
      actionClassName,
      iconOnly && "px-0",
      action.reveal === "hover" &&
        "[@media(hover:hover)]:opacity-0 [@media(hover:hover)]:group-focus-within/cell-actions:opacity-100 [@media(hover:hover)]:group-hover/cell-actions:opacity-100"
    ),
    "data-cell-action": action.id,
  };

  if (action.href) {
    return (
      <TableTooltip label={label}>
        <a
          {...common}
          href={action.href}
          onClick={stop}
          rel="noopener noreferrer"
          target="_blank"
        >
          {content}
        </a>
      </TableTooltip>
    );
  }

  const run = async () => {
    if (isCopy) {
      await navigator.clipboard.writeText(action.copyText ?? "");
      setCopied(true);
      setTimeout(() => setCopied(false), COPIED_FEEDBACK_MS);
      return;
    }
    await action.run?.();
  };

  return (
    <TableTooltip label={label}>
      <button
        {...common}
        // aria-disabled keeps the click here, where it is ignored, instead of on the row.
        aria-disabled={action.disabled || undefined}
        onClick={(event) => {
          stop(event);
          if (!action.disabled) {
            run();
          }
        }}
        type="button"
      >
        {content}
      </button>
    </TableTooltip>
  );
}

/** A cell's value followed by its column's `cellActions` (and copy). */
export function CellWithActions({
  children,
  column,
  row,
  value,
}: {
  children?: ReactNode;
  column: ColumnDefinition;
  row: Record<string, unknown>;
  value: unknown;
}) {
  const { t } = useTranslations();
  const actions = resolveCellActions(column, row, value, t("actions.copy"));
  if (actions.length === 0) {
    return children;
  }
  return (
    <span className="group/cell-actions flex w-full min-w-0 items-center gap-1">
      <span className="min-w-0 truncate">{children}</span>
      <span className="flex shrink-0 items-center" data-cell-actions="">
        {actions.map((action) => (
          <CellActionControl
            action={action}
            copiedLabel={t("actions.copied")}
            key={action.id}
          />
        ))}
      </span>
    </span>
  );
}

// packages/yayaw-table-vue/src/components/table/CellActions.vue
<script setup lang="ts">
import { onBeforeUnmount, ref, type Component } from "vue";
import { Check, Copy } from "lucide-vue-next";
import { useTableContext } from "../../context";
import type { ResolvedCellAction } from "../../cell-actions";
import TableTooltip from "../toolbar/TableTooltip.vue";

const COPIED_FEEDBACK_MS = 1500;

/** Resolved by CellRenderer, which only mounts this when there is one. */
defineProps<{ actions: ResolvedCellAction<Component>[] }>();
const context = useTableContext();
const copied = ref(false);
let copiedTimer: ReturnType<typeof setTimeout> | undefined;
onBeforeUnmount(() => clearTimeout(copiedTimer));

const label = (action: ResolvedCellAction<Component>) =>
  action.copyText !== undefined && copied.value
    ? String(context.translations.value.copied ?? "Copied")
    : action.label;
const icon = (action: ResolvedCellAction<Component>) => {
  if (action.copyText === undefined) return action.icon;
  return copied.value ? Check : Copy;
};

async function run(action: ResolvedCellAction<Component>) {
  // aria-disabled keeps the click here, where it is ignored, instead of on the row.
  if (action.disabled) return;
  if (action.copyText === undefined) {
    await action.run?.();
    return;
  }
  await navigator.clipboard.writeText(action.copyText);
  copied.value = true;
  clearTimeout(copiedTimer);
  copiedTimer = setTimeout(() => {
    copied.value = false;
  }, COPIED_FEEDBACK_MS);
}
</script>

<template>
  <!-- Actions keep their clicks: no row click, no inline edit, no drag. -->
  <span
    class="yayaw-cell-actions"
    data-cell-actions=""
    @click.stop
    @dblclick.stop
    @pointerdown.stop
    @keydown.stop
  >
    <TableTooltip v-for="action in actions" :key="action.id" :label="label(action)">
      <a
        v-if="action.href"
        class="yayaw-cell-action"
        :data-cell-action="action.id"
        :data-reveal="action.reveal"
        :data-icon-only="icon(action) && action.count === undefined ? '' : undefined"
        :href="action.href"
        target="_blank"
        rel="noopener noreferrer"
        :aria-label="label(action)"
      >
        <component :is="icon(action)" v-if="icon(action)" aria-hidden="true" />
        <span v-else>{{ action.label }}</span>
        <span v-if="action.count !== undefined" class="yayaw-cell-action-count">{{ action.count }}</span>
      </a>
      <button
        v-else
        type="button"
        class="yayaw-cell-action"
        :data-cell-action="action.id"
        :data-reveal="action.reveal"
        :data-icon-only="icon(action) && action.count === undefined ? '' : undefined"
        :aria-disabled="action.disabled || undefined"
        :aria-label="label(action)"
        @click="run(action)"
      >
        <component :is="icon(action)" v-if="icon(action)" aria-hidden="true" />
        <span v-else>{{ action.label }}</span>
        <span v-if="action.count !== undefined" class="yayaw-cell-action-count">{{ action.count }}</span>
      </button>
    </TableTooltip>
  </span>
</template>
