// src/components/ui/yayaw-table/form/form-share.tsx
"use client";

import { ExternalLink, Link2 } from "lucide-react";
import { useEffect, useId, useState } from "react";
import { Button } from "@/src/components/ui/button";
import { Input } from "@/src/components/ui/input";
import {
  type FormLabelKey,
  type FormLinkActions,
  type FormLinkStatus,
  type FormTranslate,
  formLabel,
  type PublicFormSnapshot,
} from "../utils/form-view";

interface FormShareProps {
  formLinks: FormLinkActions;
  viewId: string | null;
  /** The form as it would be published now. */
  snapshot: () => PublicFormSnapshot;
  locale: string;
  translate?: FormTranslate;
}

type Label = (key: FormLabelKey) => string;

const SWITCH_CLASS = "size-4 shrink-0 accent-primary";

function useLinkStatus(formLinks: FormLinkActions, viewId: string | null) {
  const [status, setStatus] = useState<FormLinkStatus | null>(null);
  const [loading, setLoading] = useState(false);
  const [failed, setFailed] = useState(false);
  useEffect(() => {
    if (!viewId) {
      setStatus(null);
      return;
    }
    let active = true;
    setLoading(true);
    formLinks
      .status(viewId)
      .then((next) => {
        if (active) {
          setStatus(next);
          setFailed(false);
        }
      })
      .catch(() => {
        if (active) {
          setFailed(true);
        }
      })
      .finally(() => {
        if (active) {
          setLoading(false);
        }
      });
    return () => {
      active = false;
    };
  }, [formLinks, viewId]);
  return { failed, loading, setFailed, setStatus, status };
}

function SwitchRow({
  checked,
  disabled,
  id,
  label,
  onChange,
}: {
  checked: boolean;
  disabled?: boolean;
  id: string;
  label: string;
  onChange: (checked: boolean) => void;
}) {
  return (
    <label className="flex min-h-9 items-center gap-2 text-sm" htmlFor={id}>
      <input
        aria-checked={checked}
        checked={checked}
        className={SWITCH_CLASS}
        disabled={disabled}
        id={id}
        onChange={(event) => onChange(event.target.checked)}
        role="switch"
        type="checkbox"
      />
      {label}
    </label>
  );
}

function PublicLink({
  copied,
  id,
  label,
  onCopy,
  url,
}: {
  copied: boolean;
  id: string;
  label: Label;
  onCopy: () => void;
  url: string;
}) {
  return (
    <div className="grid gap-1.5">
      <label className="text-sm" htmlFor={id}>
        {label("publicLink")}
      </label>
      <div className="flex flex-wrap gap-2">
        <Input className="min-w-0 flex-1" id={id} readOnly value={url} />
        <Button onClick={onCopy} size="sm" type="button" variant="outline">
          {copied ? label("copied") : label("copy")}
        </Button>
        <a
          className="inline-flex h-8 items-center gap-1.5 rounded-md border px-3 text-sm hover:bg-accent"
          href={url}
          rel="noopener"
          target="_blank"
        >
          <ExternalLink aria-hidden="true" className="size-4" />
          {label("open")}
        </a>
      </div>
    </div>
  );
}

function PublishedControls({
  accepting,
  busy,
  canClose,
  copied,
  id,
  label,
  onAccepting,
  onCopy,
  onRepublish,
  url,
}: {
  accepting: boolean;
  busy: boolean;
  canClose: boolean;
  copied: boolean;
  id: string;
  label: Label;
  onAccepting: (accepting: boolean) => void;
  onCopy: () => void;
  onRepublish: () => void;
  url: string;
}) {
  return (
    <div className="grid gap-3">
      <PublicLink
        copied={copied}
        id={`${id}-url`}
        label={label}
        onCopy={onCopy}
        url={url}
      />
      {canClose ? (
        <SwitchRow
          checked={accepting}
          disabled={busy}
          id={`${id}-accept`}
          label={label("acceptResponses")}
          onChange={onAccepting}
        />
      ) : null}
      <div className="flex flex-wrap items-center gap-3">
        <Button
          disabled={busy}
          onClick={onRepublish}
          size="sm"
          type="button"
          variant="outline"
        >
          {label("republish")}
        </Button>
        <p className="text-muted-foreground text-sm">
          {label("republishHint")}
        </p>
      </div>
    </div>
  );
}

/**
 * "Share form": publish the view's form on a public link served by the host.
 * Republishing is explicit: edits reach the link with "Update public form",
 * so unsaved experiments never go live by accident.
 */
export function FormShare({
  formLinks,
  locale,
  snapshot,
  translate,
  viewId,
}: FormShareProps) {
  const id = useId();
  const label: Label = (key) => formLabel(key, locale, translate);
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [copied, setCopied] = useState(false);
  const { failed, loading, setFailed, setStatus, status } = useLinkStatus(
    formLinks,
    viewId
  );
  const url = status?.published ? status.url : undefined;
  const accepting = status?.acceptsResponses !== false;

  const run = async (task: () => Promise<FormLinkStatus | null>) => {
    setBusy(true);
    try {
      setStatus(await task());
      setFailed(false);
    } catch {
      setFailed(true);
    } finally {
      setBusy(false);
    }
  };
  const publish = (target: string) =>
    run(async () => {
      const result = await formLinks.publish(target, {
        ...snapshot(),
        viewId: target,
      });
      return {
        acceptsResponses: accepting,
        ...status,
        published: true,
        url: result.url,
      };
    });
  const unpublish = (target: string) =>
    run(async () => {
      await formLinks.unpublish(target);
      return { published: false };
    });
  const setAccepting = (target: string, next: boolean) =>
    run(async () => {
      await formLinks.setAcceptingResponses?.(target, next);
      return { published: true, ...status, acceptsResponses: next };
    });
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(url ?? "");
      setCopied(true);
    } catch {
      setCopied(false);
    }
  };

  const panel = viewId ? (
    <>
      <SwitchRow
        checked={Boolean(url)}
        disabled={busy || loading}
        id={`${id}-publish`}
        label={label("publish")}
        onChange={(next) => (next ? publish(viewId) : unpublish(viewId))}
      />
      {url ? (
        <PublishedControls
          accepting={accepting}
          busy={busy}
          canClose={Boolean(formLinks.setAcceptingResponses)}
          copied={copied}
          id={id}
          label={label}
          onAccepting={(next) => setAccepting(viewId, next)}
          onCopy={copy}
          onRepublish={() => publish(viewId)}
          url={url}
        />
      ) : null}
    </>
  ) : (
    <p className="text-muted-foreground text-sm">{label("saveFirst")}</p>
  );

  return (
    <section
      aria-label={label("share")}
      className="grid gap-3 rounded-lg border px-4 py-3"
      data-form-share
    >
      <div className="flex flex-wrap items-center justify-between gap-2">
        <Button
          aria-controls={`${id}-panel`}
          aria-expanded={open}
          className="gap-2"
          onClick={() => setOpen((value) => !value)}
          size="sm"
          type="button"
          variant="outline"
        >
          <Link2 aria-hidden="true" className="size-4" />
          {label("share")}
        </Button>
      </div>
      {open ? (
        <div className="grid gap-3" id={`${id}-panel`}>
          {panel}
          {failed ? (
            <p className="text-destructive text-sm" role="alert">
              {label("shareError")}
            </p>
          ) : null}
          {copied ? (
            <output className="sr-only">{label("copied")}</output>
          ) : null}
        </div>
      ) : null}
    </section>
  );
}

// packages/yayaw-table-vue/src/form/FormShare.vue
<script setup lang="ts">
import { ExternalLink, Link2 } from "lucide-vue-next";
import { computed, ref, useId, watch } from "vue";
import {
  type FormLabelKey,
  type FormLinkActions,
  type FormLinkStatus,
  type FormTranslate,
  formLabel,
  type PublicFormSnapshot,
} from "../form-view";

/**
 * "Share form": publish the view's form on a public link served by the host.
 * Republishing is explicit: edits reach the link with "Update public form",
 * so unsaved experiments never go live by accident.
 */
const props = defineProps<{
  formLinks: FormLinkActions;
  viewId: string | null;
  /** The form as it would be published now. */
  snapshot: () => PublicFormSnapshot;
  locale: string;
  translate?: FormTranslate;
}>();

const id = `yayaw-form-share-${useId()}`;
const label = (key: FormLabelKey): string =>
  formLabel(key, props.locale, props.translate);
const open = ref(false);
const busy = ref(false);
const loading = ref(false);
const failed = ref(false);
const copied = ref(false);
const status = ref<FormLinkStatus | null>(null);
const published = computed(() =>
  Boolean(status.value?.published && status.value.url)
);
const accepting = computed(() => status.value?.acceptsResponses !== false);

let request = 0;
watch(
  () => [props.formLinks, props.viewId] as const,
  async ([formLinks, viewId]) => {
    const current = ++request;
    status.value = null;
    if (!viewId) return;
    loading.value = true;
    try {
      const next = await formLinks.status(viewId);
      if (current === request) {
        status.value = next;
        failed.value = false;
      }
    } catch {
      if (current === request) failed.value = true;
    } finally {
      if (current === request) loading.value = false;
    }
  },
  { immediate: true }
);

const run = async (task: () => Promise<FormLinkStatus | null>) => {
  busy.value = true;
  try {
    status.value = await task();
    failed.value = false;
  } catch {
    failed.value = true;
  } finally {
    busy.value = false;
  }
};
const publish = (viewId: string) =>
  run(async () => {
    const { url } = await props.formLinks.publish(viewId, {
      ...props.snapshot(),
      viewId,
    });
    return {
      acceptsResponses: accepting.value,
      ...status.value,
      published: true,
      url,
    };
  });
const unpublish = (viewId: string) =>
  run(async () => {
    await props.formLinks.unpublish(viewId);
    return { published: false };
  });
const setAccepting = (viewId: string, next: boolean) =>
  run(async () => {
    await props.formLinks.setAcceptingResponses?.(viewId, next);
    return { published: true, ...status.value, acceptsResponses: next };
  });
const togglePublished = (viewId: string, event: Event) =>
  (event.target as HTMLInputElement).checked ? publish(viewId) : unpublish(viewId);
const copy = async () => {
  if (!status.value?.url) return;
  try {
    await navigator.clipboard.writeText(status.value.url);
    copied.value = true;
  } catch {
    copied.value = false;
  }
};
</script>

<template>
  <section class="yayaw-form-share" :aria-label="label('share')" data-form-share>
    <div class="yayaw-form-share-bar">
      <button
        type="button"
        class="yayaw-button yayaw-button-outline"
        :aria-expanded="open"
        :aria-controls="`${id}-panel`"
        @click="open = !open"
      >
        <Link2 :size="16" aria-hidden="true" />{{ label("share") }}
      </button>
    </div>
    <div v-if="open" :id="`${id}-panel`" class="yayaw-form-share-panel">
      <template v-if="viewId">
        <label class="yayaw-form-check" :for="`${id}-publish`">
          <input
            :id="`${id}-publish`"
            type="checkbox"
            role="switch"
            :aria-checked="published"
            :checked="published"
            :disabled="busy || loading"
            @change="togglePublished(viewId, $event)"
          />
          <span>{{ label("publish") }}</span>
        </label>
        <div v-if="published && status?.url" class="yayaw-form-share-panel">
          <div class="yayaw-form-question">
            <label class="yayaw-form-label" :for="`${id}-url`">{{ label("publicLink") }}</label>
            <div class="yayaw-form-share-link">
              <input :id="`${id}-url`" class="yayaw-input" readonly :value="status.url" />
              <button type="button" class="yayaw-button yayaw-button-outline" @click="copy">
                {{ copied ? label("copied") : label("copy") }}
              </button>
              <a class="yayaw-button yayaw-button-outline" :href="status.url" target="_blank" rel="noopener">
                <ExternalLink :size="16" aria-hidden="true" />{{ label("open") }}
              </a>
            </div>
          </div>
          <label v-if="formLinks.setAcceptingResponses" class="yayaw-form-check" :for="`${id}-accept`">
            <input
              :id="`${id}-accept`"
              type="checkbox"
              role="switch"
              :aria-checked="accepting"
              :checked="accepting"
              :disabled="busy"
              @change="setAccepting(viewId, ($event.target as HTMLInputElement).checked)"
            />
            <span>{{ label("acceptResponses") }}</span>
          </label>
          <div class="yayaw-form-share-bar">
            <button type="button" class="yayaw-button yayaw-button-outline" :disabled="busy" @click="publish(viewId)">
              {{ label("republish") }}
            </button>
            <p class="yayaw-form-help">{{ label("republishHint") }}</p>
          </div>
        </div>
      </template>
      <p v-else class="yayaw-form-help">{{ label("saveFirst") }}</p>
      <p v-if="failed" class="yayaw-form-error" role="alert">{{ label("shareError") }}</p>
      <output v-if="copied" class="yayaw-sr-only">{{ label("copied") }}</output>
    </div>
  </section>
</template>
