// src/components/ui/yayaw-table/form/form-view.tsx
"use client";

import { useCallback, useMemo, useState } from "react";
import type { DisplayModeRenderContext } from "../types/display-mode-renderer";
import { formLanguage } from "../utils/form-text";
import {
  type FormLabelKey,
  formLabel,
  formMatchLocale,
  formViewLocales,
  mergeFormSettings,
  publicFormSnapshot,
} from "../utils/form-view";
import { FormLanguageSwitch } from "./form-languages";
import { FormShare } from "./form-share";
import { YayawTableForm } from "./yayaw-table-form";

/**
 * The Form display mode: the view's form, creating records in this table. A
 * form written in several languages can be previewed in each of them.
 */
export function FormView({ context }: { context: DisplayModeRenderContext }) {
  const { columns, createRecord, defaults, formLinks, locale, settings } =
    context;
  const translate = useCallback(
    (key: FormLabelKey, fallback: string) =>
      context.translate(`form.${key}`, fallback),
    [context.translate]
  );
  const form = useMemo(
    () => mergeFormSettings(defaults, settings),
    [defaults, settings]
  );
  const languages = useMemo(
    () => formViewLocales(defaults, settings, formLanguage(locale) || "en"),
    [defaults, settings, locale]
  );
  const [preview, setPreview] = useState<string>();
  const previewed = preview && languages.includes(preview) ? preview : undefined;
  // Tags look like the table's: its colored-tags setting applies to the form.
  const formColumns = useMemo(
    () =>
      columns.map((column) => ({
        ...column,
        coloredTags: column.coloredTags ?? context.coloredTags,
      })),
    [columns, context.coloredTags]
  );
  const snapshot = useCallback(
    () => publicFormSnapshot(form, formColumns),
    [formColumns, form]
  );
  const multilingual = languages.length > 1;
  return (
    <div className="grid min-w-0 gap-3 py-2" data-form-view>
      {formLinks || multilingual ? (
        <div
          className="flex min-h-8 flex-wrap items-center gap-2"
          data-form-toolbar
        >
          {multilingual ? (
            <FormLanguageSwitch
              label={formLabel("previewLanguage", locale, translate)}
              languages={languages}
              onChange={setPreview}
              value={
                previewed ??
                formMatchLocale(languages, locale) ??
                languages[0] ??
                locale
              }
            />
          ) : null}
          {formLinks ? (
            <div className="ml-auto">
              <FormShare
                formLinks={formLinks}
                locale={locale}
                snapshot={snapshot}
                translate={translate}
                viewId={context.viewId}
              />
            </div>
          ) : null}
        </div>
      ) : null}
      <div className="rounded-lg bg-muted/40 px-3 py-6 sm:px-6 sm:py-10 dark:bg-muted/20">
        <YayawTableForm
          columns={formColumns}
          key={context.viewId ?? "form"}
          form={form}
          locale={previewed ?? locale}
          onSubmit={(values) => createRecord(values)}
          translate={translate}
        />
      </div>
    </div>
  );
}

// packages/yayaw-table-vue/src/form/FormView.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import type { DisplayModeRenderContext } from "../display-mode-renderer";
import { formLanguage } from "../form-text";
import {
  type FormColumn,
  type FormLabelKey,
  formLabel,
  formMatchLocale,
  formViewLocales,
  mergeFormSettings,
  publicFormSnapshot,
} from "../form-view";
import FormLanguageSwitch from "./FormLanguageSwitch.vue";
import FormShare from "./FormShare.vue";
import YayawTableForm from "./YayawTableForm.vue";

/**
 * The Form display mode: the view's form, creating records in this table. A
 * form written in several languages can be previewed in each of them.
 */
const props = defineProps<{ context: DisplayModeRenderContext }>();
const columns = computed(
  () => props.context.columns as unknown as readonly FormColumn[]
);
// Tags look like the table's: its colored-tags setting applies to the form.
const formColumns = computed(() =>
  columns.value.map((column) => ({
    ...column,
    coloredTags: column.coloredTags ?? props.context.coloredTags,
  }))
);
const form = computed(() =>
  mergeFormSettings(props.context.defaults, props.context.settings)
);
const translate = (key: FormLabelKey, fallback: string): string =>
  props.context.translate(`form.${key}`, fallback);
const snapshot = () => publicFormSnapshot(form.value, formColumns.value);
const languages = computed(() =>
  formViewLocales(
    props.context.defaults,
    props.context.settings,
    formLanguage(props.context.locale) || "en"
  )
);
const preview = ref<string>();
const previewed = computed(() =>
  preview.value && languages.value.includes(preview.value)
    ? preview.value
    : undefined
);
const shown = computed(
  () =>
    previewed.value ??
    formMatchLocale(languages.value, props.context.locale) ??
    languages.value[0] ??
    props.context.locale
);
const multilingual = computed(() => languages.value.length > 1);
</script>

<template>
  <div class="yayaw-form-view" data-form-view>
    <div v-if="context.formLinks || multilingual" class="yayaw-form-toolbar" data-form-toolbar>
      <FormLanguageSwitch
        v-if="multilingual"
        :label="formLabel('previewLanguage', context.locale, translate)"
        :languages="languages"
        :value="shown"
        @change="preview = $event"
      />
      <div v-if="context.formLinks" class="yayaw-form-toolbar-end">
        <FormShare
          :form-links="context.formLinks"
          :view-id="context.viewId"
          :snapshot="snapshot"
          :locale="context.locale"
          :translate="translate"
        />
      </div>
    </div>
    <div class="yayaw-form-canvas">
      <YayawTableForm
        :key="context.viewId ?? 'form'"
        :columns="formColumns"
        :form="form"
        :locale="previewed ?? context.locale"
        :translate="translate"
        :on-submit="(values) => context.createRecord(values)"
      />
    </div>
  </div>
</template>
