// src/components/ui/yayaw-table/form/yayaw-table-form.tsx
"use client";

/**
 * Standalone form that creates a record from table columns. It needs no
 * table state, URL state or provider, so it can be mounted on a public route:
 *
 * ```tsx
 * <YayawTableForm
 *   columns={snapshot.columns}
 *   form={snapshot.form}
 *   onSubmit={async (values) => (await post(values)).ok ? { ok: true } : { errors }}
 * />
 * ```
 *
 * Spam protection and hidden context stay with the host: render them through
 * `extraFields` and pass `context`, which `onSubmit` receives unchanged.
 */
import {
  type FormEvent,
  type ReactNode,
  useCallback,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
} from "react";
import { CircleCheck, Lock } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/src/components/ui/button";
import {
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "@/src/components/ui/empty";
import {
  type FormColumn,
  type FormDraft,
  type FormLabelKey,
  type FormSubmitResult,
  type FormTranslate,
  type FormViewSettings,
  formDraftValues,
  formLabel,
  formSubmission,
  formTranslateFrom,
  initialFormDraft,
  type ResolvedFormQuestion,
  resolveFormSettings,
  validateFormValues,
} from "../utils/form-view";
import { FormQuestionField } from "./form-question";

export interface YayawTableFormProps {
  /** Table columns; only the asked ones are needed (see `publicFormSnapshot`). */
  columns: readonly FormColumn[];
  /** Form settings, e.g. `formSettingsFromView(view)` or `snapshot.form`. */
  form?: FormViewSettings;
  /** Create the record. Resolve `{ ok: true }`, or `{ errors, message }`. */
  onSubmit: (
    values: Record<string, unknown>,
    meta: { context?: Record<string, unknown> }
  ) => FormSubmitResult | Promise<FormSubmitResult>;
  /** Extra checks after the built-in ones, e.g. on the host's server; return errors by column id. */
  validate?: (
    values: Record<string, unknown>
  ) =>
    | Record<string, string>
    | undefined
    | Promise<Record<string, string> | undefined>;
  /** Called after a success with the settings' redirect URL; the host decides whether to follow it. */
  onSuccess?: (info: {
    values: Record<string, unknown>;
    redirectUrl?: string;
  }) => void;
  /** Label overrides, as `{ submit }` or `{ "form.submit" }`. */
  translations?: Record<string, string | undefined>;
  /** Label overrides as a function; wins over `translations`. */
  translate?: FormTranslate;
  /** Built-in labels are English, or French for `fr*` locales. */
  locale?: string;
  /** Host data passed to `onSubmit` unchanged (campaign, referrer, …). */
  context?: Record<string, unknown>;
  /** Host fields rendered before the submit button (honeypot, captcha). */
  extraFields?: ReactNode;
  /** Show the closed message instead of the questions. */
  closed?: boolean;
  className?: string;
}

type Status = "idle" | "submitting" | "success";

const errorMessages = (
  codes: Record<string, FormLabelKey>,
  label: (key: FormLabelKey) => string
) =>
  Object.fromEntries(
    Object.entries(codes).map(([columnId, code]) => [columnId, label(code)])
  );

/** The control a question focuses (the first choice of a multi-select). */
const questionControl = (
  form: HTMLElement | null,
  question: ResolvedFormQuestion
) =>
  form?.querySelector<HTMLElement>(
    `[data-form-question="${CSS.escape(question.id)}"] [data-form-focus]`
  );

/** Question ids in order, for focusing the first invalid one. */
const firstInvalid = (
  questions: readonly ResolvedFormQuestion[],
  errors: Record<string, string>
) => questions.find((question) => errors[question.columnId]);

function useFormLabels(
  locale: string,
  translate: FormTranslate | undefined,
  translations: Record<string, string | undefined> | undefined
) {
  const override = useMemo(
    () => translate ?? formTranslateFrom(translations),
    [translate, translations]
  );
  return useCallback(
    (key: FormLabelKey, params?: Record<string, number | string>) =>
      formLabel(key, locale, override, params),
    [locale, override]
  );
}

async function collectErrors(
  questions: readonly ResolvedFormQuestion[],
  values: Record<string, unknown>,
  label: (key: FormLabelKey) => string,
  validate: YayawTableFormProps["validate"]
): Promise<Record<string, string>> {
  const builtIn = errorMessages(validateFormValues(questions, values), label);
  if (Object.keys(builtIn).length || !validate) {
    return builtIn;
  }
  return (await validate(values)) ?? {};
}

function FormHeader({
  description,
  title,
}: {
  description?: string;
  title?: string;
}) {
  if (!(title || description)) {
    return null;
  }
  return (
    <header className="grid gap-1.5 border-b pb-5">
      {title ? (
        <h2 className="font-semibold text-lg leading-tight tracking-tight">
          {title}
        </h2>
      ) : null}
      {description ? (
        <p className="whitespace-pre-line text-muted-foreground text-sm">
          {description}
        </p>
      ) : null}
    </header>
  );
}

/** The end states (sent, closed), styled like the table's empty states. */
function FormState({
  action,
  icon,
  message,
  title,
}: {
  action?: ReactNode;
  icon: ReactNode;
  message: string;
  title?: string;
}) {
  return (
    <Empty className="gap-5 p-0 py-6">
      <EmptyHeader>
        <EmptyMedia variant="icon">{icon}</EmptyMedia>
        <output className="grid gap-2">
          {title ? <EmptyTitle>{title}</EmptyTitle> : null}
          <EmptyDescription>{message}</EmptyDescription>
        </output>
      </EmptyHeader>
      {action ? <EmptyContent>{action}</EmptyContent> : null}
    </Empty>
  );
}

/** A form that creates one record per response, from table columns. */
export function YayawTableForm({
  className,
  closed,
  columns,
  context,
  extraFields,
  form,
  locale = "en",
  onSubmit,
  onSuccess,
  translate,
  translations,
  validate,
}: YayawTableFormProps) {
  const id = useId();
  const label = useFormLabels(locale, translate, translations);
  const settings = useMemo(
    () => resolveFormSettings(columns, undefined, form),
    [columns, form]
  );
  const { questions } = settings;
  const [draft, setDraft] = useState<FormDraft>(() =>
    initialFormDraft(questions)
  );
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [message, setMessage] = useState<string>();
  const [status, setStatus] = useState<Status>("idle");
  const [focusRequest, setFocusRequest] = useState(0);
  const formRef = useRef<HTMLFormElement>(null);
  const inputId = (question: ResolvedFormQuestion) =>
    `${id}-${question.id}`;

  // Move focus after the errors render, so the invalid field is announced.
  useEffect(() => {
    if (!focusRequest) {
      return;
    }
    const question = firstInvalid(questions, errors);
    const target = question
      ? questionControl(formRef.current, question)
      : formRef.current?.querySelector<HTMLElement>("[data-form-message]");
    target?.focus();
  }, [focusRequest, errors, questions]);

  const fail = (next: Record<string, string>, text?: string) => {
    setErrors(next);
    setMessage(text);
    setStatus("idle");
    setFocusRequest((value) => value + 1);
  };

  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (status === "submitting") {
      return;
    }
    setStatus("submitting");
    const values = formDraftValues(questions, draft);
    const found = await collectErrors(questions, values, label, validate);
    if (Object.keys(found).length) {
      fail(found, label("errorSummary", { count: Object.keys(found).length }));
      return;
    }
    try {
      const record = formSubmission(settings, values);
      const result = await onSubmit(record, { context });
      if (result.ok) {
        setErrors({});
        setMessage(undefined);
        setStatus("success");
        onSuccess?.({ values: record, redirectUrl: settings.redirectUrl });
        return;
      }
      fail(result.errors ?? {}, result.message ?? label("submitError"));
    } catch {
      fail({}, label("submitError"));
    }
  };

  const restart = () => {
    setDraft(initialFormDraft(questions));
    setErrors({});
    setMessage(undefined);
    setStatus("idle");
    requestAnimationFrame(() => {
      const first = questions[0];
      if (first) {
        questionControl(formRef.current, first)?.focus();
      }
    });
  };

  const header = (
    <FormHeader description={settings.description} title={settings.title} />
  );
  const shell = cn(
    "mx-auto grid w-full min-w-0 max-w-[640px] gap-6 rounded-xl border bg-card px-5 py-6 text-card-foreground shadow-xs sm:px-8 sm:py-8",
    className
  );

  if (closed) {
    return (
      <section className={shell} data-yayaw-form="closed">
        {header}
        <FormState
          icon={<Lock aria-hidden="true" />}
          message={label("closed")}
        />
      </section>
    );
  }
  if (status === "success") {
    return (
      <section className={shell} data-yayaw-form="success">
        {header}
        <FormState
          action={
            settings.allowAnotherResponse ? (
              <Button onClick={restart} type="button" variant="outline">
                {label("another")}
              </Button>
            ) : undefined
          }
          icon={<CircleCheck aria-hidden="true" />}
          message={settings.successMessage ?? label("success")}
          title={label("successTitle")}
        />
      </section>
    );
  }
  const submitting = status === "submitting";
  const questionLabels = {
    choose: label("choose"),
    clearDate: label("clearDate"),
    pickDate: label("pickDate"),
  };
  return (
    <form
      aria-busy={submitting}
      className={shell}
      data-yayaw-form="open"
      noValidate
      onSubmit={submit}
      ref={formRef}
    >
      {header}
      {message ? (
        <p
          className="rounded-md border border-destructive/40 bg-destructive/5 px-3 py-2 text-destructive text-sm dark:bg-destructive/10"
          data-form-message
          role="alert"
          tabIndex={-1}
        >
          {message}
        </p>
      ) : null}
      {questions.length === 0 ? (
        <p className="text-muted-foreground text-sm">{label("noQuestions")}</p>
      ) : null}
      <div className="grid gap-6">
        {questions.map((question) => (
          <FormQuestionField
            disabled={submitting}
            error={errors[question.columnId]}
            inputId={inputId(question)}
            key={question.id}
            labels={questionLabels}
            locale={locale}
            onChange={(value) =>
              setDraft((current) => ({
                ...current,
                [question.columnId]: value,
              }))
            }
            question={question}
            value={draft[question.columnId]}
          />
        ))}
      </div>
      {extraFields}
      <div className="flex justify-end border-t pt-5">
        <Button
          className="w-full sm:w-fit"
          disabled={submitting || questions.length === 0}
          type="submit"
        >
          {submitting
            ? label("submitting")
            : (settings.submitLabel ?? label("submit"))}
        </Button>
      </div>
    </form>
  );
}

// packages/yayaw-table-vue/src/form/YayawTableForm.vue
<script setup lang="ts">
/**
 * Standalone form that creates a record from table columns. It needs no table
 * state, URL state or provider, so it can be mounted on a public route.
 * Spam protection and hidden context stay with the host: render them in the
 * `extra-fields` slot and pass `context`, which `onSubmit` receives unchanged.
 */
import { CircleCheck, Lock } from "lucide-vue-next";
import { computed, nextTick, ref, useId } from "vue";
import Empty from "../components/empty/Empty.vue";
import EmptyContent from "../components/empty/EmptyContent.vue";
import EmptyDescription from "../components/empty/EmptyDescription.vue";
import EmptyHeader from "../components/empty/EmptyHeader.vue";
import EmptyMedia from "../components/empty/EmptyMedia.vue";
import EmptyTitle from "../components/empty/EmptyTitle.vue";
import {
  type FormColumn,
  type FormDraft,
  type FormLabelKey,
  type FormSubmitResult,
  type FormTranslate,
  type FormViewSettings,
  formDraftValues,
  formLabel,
  formSubmission,
  formTranslateFrom,
  initialFormDraft,
  type ResolvedFormQuestion,
  resolveFormSettings,
  validateFormValues,
} from "../form-view";
import FormQuestion from "./FormQuestion.vue";

const props = withDefaults(
  defineProps<{
    /** Table columns; only the asked ones are needed (see `publicFormSnapshot`). */
    columns: readonly FormColumn[];
    /** Form settings, e.g. `formSettingsFromView(view)` or `snapshot.form`. */
    form?: FormViewSettings;
    /** Create the record. Resolve `{ ok: true }`, or `{ errors, message }`. */
    onSubmit: (
      values: Record<string, unknown>,
      meta: { context?: Record<string, unknown> }
    ) => FormSubmitResult | Promise<FormSubmitResult>;
    /** Extra checks after the built-in ones, e.g. on the host's server; return errors by column id. */
    validate?: (
      values: Record<string, unknown>
    ) =>
      | Record<string, string>
      | undefined
      | Promise<Record<string, string> | undefined>;
    /** Called after a success with the settings' redirect URL; the host decides whether to follow it. */
    onSuccess?: (info: {
      values: Record<string, unknown>;
      redirectUrl?: string;
    }) => void;
    /** Label overrides, as `{ submit }` or `{ "form.submit" }`. */
    translations?: Record<string, string | undefined>;
    /** Label overrides as a function; wins over `translations`. */
    translate?: FormTranslate;
    /** Built-in labels are English, or French for `fr*` locales. */
    locale?: string;
    /** Host data passed to `onSubmit` unchanged (campaign, referrer, …). */
    context?: Record<string, unknown>;
    /** Show the closed message instead of the questions. */
    closed?: boolean;
  }>(),
  { locale: "en" }
);
defineSlots<{
  /** Host fields rendered before the submit button (honeypot, captcha). */
  "extra-fields"?: () => unknown;
}>();

const id = `yayaw-form-${useId()}`;
const override = computed(
  () => props.translate ?? formTranslateFrom(props.translations)
);
const label = (
  key: FormLabelKey,
  params?: Record<string, number | string>
): string => formLabel(key, props.locale, override.value, params);
const settings = computed(() =>
  resolveFormSettings(props.columns, undefined, props.form)
);
const questions = computed(() => settings.value.questions);
const draft = ref<FormDraft>(initialFormDraft(questions.value));
const errors = ref<Record<string, string>>({});
const message = ref<string>();
const status = ref<"idle" | "submitting" | "success">("idle");
const formElement = ref<HTMLFormElement>();
const inputId = (question: ResolvedFormQuestion): string =>
  `${id}-${question.id}`;
/** The control a question focuses (the first choice of a multi-select). */
const questionControl = (question: ResolvedFormQuestion) =>
  formElement.value?.querySelector<HTMLElement>(
    `[data-form-question="${CSS.escape(question.id)}"] [data-form-focus]`
  );
const questionLabels = computed(() => ({
  choose: label("choose"),
  clearDate: label("clearDate"),
  pickDate: label("pickDate"),
}));

const setAnswer = (columnId: string, value: FormDraft[string]): void => {
  draft.value = { ...draft.value, [columnId]: value };
};

const collectErrors = async (
  values: Record<string, unknown>
): Promise<Record<string, string>> => {
  const builtIn = Object.fromEntries(
    Object.entries(validateFormValues(questions.value, values)).map(
      ([columnId, code]) => [columnId, label(code)]
    )
  );
  if (Object.keys(builtIn).length || !props.validate) return builtIn;
  return (await props.validate(values)) ?? {};
};

/** Show the errors, then move focus to the first invalid question. */
const fail = async (next: Record<string, string>, text?: string) => {
  errors.value = next;
  message.value = text;
  status.value = "idle";
  await nextTick();
  const question = questions.value.find((item) => next[item.columnId]);
  const target = question
    ? questionControl(question)
    : formElement.value?.querySelector<HTMLElement>("[data-form-message]");
  target?.focus();
};

const submit = async (): Promise<void> => {
  if (status.value === "submitting") return;
  status.value = "submitting";
  const values = formDraftValues(questions.value, draft.value);
  const found = await collectErrors(values);
  if (Object.keys(found).length) {
    await fail(found, label("errorSummary", { count: Object.keys(found).length }));
    return;
  }
  try {
    const record = formSubmission(settings.value, values);
    const result = await props.onSubmit(record, { context: props.context });
    if (result.ok) {
      errors.value = {};
      message.value = undefined;
      status.value = "success";
      props.onSuccess?.({ values: record, redirectUrl: settings.value.redirectUrl });
      return;
    }
    await fail(result.errors ?? {}, result.message ?? label("submitError"));
  } catch {
    await fail({}, label("submitError"));
  }
};

const restart = async (): Promise<void> => {
  draft.value = initialFormDraft(questions.value);
  errors.value = {};
  message.value = undefined;
  status.value = "idle";
  await nextTick();
  const first = questions.value[0];
  if (first) questionControl(first)?.focus();
};
</script>

<template>
  <section v-if="closed" class="yayaw-form-root" data-yayaw-form="closed">
    <header v-if="settings.title || settings.description" class="yayaw-form-intro">
      <h2 v-if="settings.title" class="yayaw-form-title">{{ settings.title }}</h2>
      <p v-if="settings.description" class="yayaw-form-description">{{ settings.description }}</p>
    </header>
    <Empty class="yayaw-form-state">
      <EmptyHeader>
        <EmptyMedia variant="icon"><Lock aria-hidden="true" /></EmptyMedia>
        <output class="yayaw-form-state-text">
          <EmptyDescription>{{ label("closed") }}</EmptyDescription>
        </output>
      </EmptyHeader>
    </Empty>
  </section>
  <section v-else-if="status === 'success'" class="yayaw-form-root" data-yayaw-form="success">
    <header v-if="settings.title || settings.description" class="yayaw-form-intro">
      <h2 v-if="settings.title" class="yayaw-form-title">{{ settings.title }}</h2>
      <p v-if="settings.description" class="yayaw-form-description">{{ settings.description }}</p>
    </header>
    <Empty class="yayaw-form-state">
      <EmptyHeader>
        <EmptyMedia variant="icon"><CircleCheck aria-hidden="true" /></EmptyMedia>
        <output class="yayaw-form-state-text">
          <EmptyTitle>{{ label("successTitle") }}</EmptyTitle>
          <EmptyDescription>{{ settings.successMessage ?? label("success") }}</EmptyDescription>
        </output>
      </EmptyHeader>
      <EmptyContent v-if="settings.allowAnotherResponse">
        <button type="button" class="yayaw-button yayaw-button-outline" @click="restart">
          {{ label("another") }}
        </button>
      </EmptyContent>
    </Empty>
  </section>
  <form
    v-else
    ref="formElement"
    class="yayaw-form-root"
    data-yayaw-form="open"
    novalidate
    :aria-busy="status === 'submitting'"
    @submit.prevent="submit"
  >
    <header v-if="settings.title || settings.description" class="yayaw-form-intro">
      <h2 v-if="settings.title" class="yayaw-form-title">{{ settings.title }}</h2>
      <p v-if="settings.description" class="yayaw-form-description">{{ settings.description }}</p>
    </header>
    <p v-if="message" class="yayaw-form-message" data-form-message role="alert" tabindex="-1">
      {{ message }}
    </p>
    <p v-if="questions.length === 0" class="yayaw-form-help">{{ label("noQuestions") }}</p>
    <div class="yayaw-form-questions">
      <FormQuestion
        v-for="question in questions"
        :key="question.id"
        :question="question"
        :input-id="inputId(question)"
        :value="draft[question.columnId]"
        :error="errors[question.columnId]"
        :disabled="status === 'submitting'"
        :locale="locale"
        :labels="questionLabels"
        @change="setAnswer(question.columnId, $event)"
      />
    </div>
    <slot name="extra-fields" />
    <div class="yayaw-form-submit-bar">
      <button
        type="submit"
        class="yayaw-button yayaw-form-action"
        :disabled="status === 'submitting' || questions.length === 0"
      >
        {{ status === "submitting" ? label("submitting") : (settings.submitLabel ?? label("submit")) }}
      </button>
    </div>
  </form>
</template>
