// packages/yayaw-table-vue/src/components/toolbar/TableDensityMenu.vue
<script setup lang="ts">
import { Check, Rows3 } from "lucide-vue-next";
import {
  DropdownMenuContent,
  DropdownMenuItemIndicator,
  DropdownMenuLabel,
  DropdownMenuPortal,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuRoot,
  DropdownMenuTrigger,
} from "reka-ui";
import { computed } from "vue";
import { useTableContext } from "../../context";
import { isTableDensity, TABLE_DENSITY_OPTIONS } from "../../table-contracts";

const context = useTableContext();
const label = computed(() => String(context.translations.value.density ?? "Table density"));
const size = computed(() => TABLE_DENSITY_OPTIONS.find(
  (option) => option.value === context.state.density.value
)?.label);
const setDensity = (value: unknown): void => {
  if (isTableDensity(value)) {
    context.state.density.value = value;
  }
};
</script>

<template>
  <DropdownMenuRoot :modal="false">
    <DropdownMenuTrigger as-child>
      <button
        type="button"
        class="yayaw-button yayaw-button-outline yayaw-icon-only"
        :aria-label="`${label}: ${size}`"
        :title="`${label}: ${size}`"
      >
        <Rows3 :size="16" aria-hidden="true" />
      </button>
    </DropdownMenuTrigger>
    <DropdownMenuPortal>
      <DropdownMenuContent class="yayaw-column-menu yayaw-density-menu" align="end" :side-offset="4" :aria-label="label">
        <DropdownMenuLabel class="yayaw-density-label">{{ label }}</DropdownMenuLabel>
        <DropdownMenuRadioGroup :model-value="context.state.density.value" @update:model-value="setDensity">
          <DropdownMenuRadioItem
            v-for="option in TABLE_DENSITY_OPTIONS"
            :key="option.value"
            :value="option.value"
            class="yayaw-column-menu-item yayaw-density-option"
          >
            {{ option.label }}
            <DropdownMenuItemIndicator><Check :size="16" aria-hidden="true" /></DropdownMenuItemIndicator>
          </DropdownMenuRadioItem>
        </DropdownMenuRadioGroup>
      </DropdownMenuContent>
    </DropdownMenuPortal>
  </DropdownMenuRoot>
</template>

// src/components/ui/yayaw-table/components/toolbar/table-density-menu.tsx
"use client";

import { useAtom } from "jotai";
import { Rows3 } from "lucide-react";
import { Button } from "@/src/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuLabel,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuTrigger,
} from "@/src/components/ui/dropdown-menu";
import { tableDensityAtom } from "../../atoms/table-atoms";
import { useTranslations } from "../../providers/table-provider";
import { useTableUrlState } from "../../hooks/use-table-url-state";
import type { TableDensity, TableDisplayMode } from "../../types/display-types";
import {
  isTableDensity,
  TABLE_DENSITY_OPTIONS,
} from "../../utils/table-contracts";

export function TableDensityMenu({
  defaultDensity = "medium",
  defaultDisplayMode,
  tableId,
}: {
  defaultDensity?: TableDensity;
  defaultDisplayMode?: TableDisplayMode;
  tableId: string;
}) {
  const { t } = useTranslations();
  const { displayModeParam } = useTableUrlState({
    defaultDisplayMode,
    tableId,
  });
  const [override, setDensity] = useAtom(tableDensityAtom(tableId));
  const density = override ?? defaultDensity;
  const translated = t("menu.density");
  const label = translated === "menu.density" ? "Table density" : translated;
  const size = TABLE_DENSITY_OPTIONS.find(
    (option) => option.value === density
  )?.label;

  if (displayModeParam !== "table") {
    return null;
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger
        render={
          <Button
            aria-label={`${label}: ${size}`}
            className="h-8 w-8"
            size="icon-sm"
            title={`${label}: ${size}`}
            type="button"
            variant="outline"
          >
            <Rows3 aria-hidden="true" className="h-4 w-4" />
          </Button>
        }
      />
      <DropdownMenuContent align="end" className="min-w-32">
        <DropdownMenuGroup>
          <DropdownMenuLabel>{label}</DropdownMenuLabel>
          <DropdownMenuRadioGroup
            onValueChange={(value) => {
              if (isTableDensity(value)) {
                setDensity(value);
              }
            }}
            value={density}
          >
            {TABLE_DENSITY_OPTIONS.map((option) => (
              <DropdownMenuRadioItem key={option.value} value={option.value}>
                {option.label}
              </DropdownMenuRadioItem>
            ))}
          </DropdownMenuRadioGroup>
        </DropdownMenuGroup>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
