// packages/yayaw-table-vue/src/components/controls/ViewSettingsPanel.vue
<script setup lang="ts">
import { ChevronDown, ChevronRight, SlidersHorizontal } from "lucide-vue-next";
import { RadioGroupRoot, RadioGroupItem, RadioGroupIndicator } from "reka-ui";
import {
  computed,
  inject,
  nextTick,
  onBeforeUnmount,
  ref,
  useId,
  watch,
} from "vue";
import { useTableContext } from "../../context";
import { settingsNavigationKey } from "../toolbar/settings-navigation";
import TableSelect from "./TableSelect.vue";
import TableCheckbox from "./TableCheckbox.vue";

interface SettingField {
  id: string;
  label: string;
  value: string;
  /** Disabled choices stay listed; their label says why. */
  options: { value: string; label: string; disabled?: boolean }[];
  onChange: (value: string) => void;
  /** Section title shown above the field. */
  heading?: string;
  /** Label and control on one row (column mappings). */
  inline?: boolean;
  /** Shown but not changeable. */
  disabled?: boolean;
}
interface SettingProperties {
  label: string;
  value: string[];
  options: { value: string; label: string }[];
  onChange: (value: string[]) => void;
  showLabels: boolean;
  showLabelsLabel: string;
  onShowLabelsChange: (value: boolean) => void;
}
const props = defineProps<{
  fields: SettingField[];
  properties?: SettingProperties;
}>();
const context = useTableContext();
const id = useId();
const screen = ref<string>();
const triggerId = ref("");
const navigation = inject(settingsNavigationKey);
const field = computed(() =>
  props.fields.find((item) => item.id === screen.value),
);
const showProperties = computed(
  () => screen.value === "properties" && props.properties,
);
const open = async (name: string) => {
  triggerId.value = `${id}-${name}`;
  screen.value = name;
  await nextTick();
};
const back = async () => {
  screen.value = undefined;
  await nextTick();
  document.getElementById(triggerId.value)?.focus();
};
const choose = (value: unknown) => {
  if (typeof value !== "string" || !field.value) return;
  field.value.onChange(value);
  back();
};
const toggle = (value: string, checked: boolean) => {
  const properties = props.properties;
  if (!properties) return;
  const remaining = properties.value.filter((item) => item !== value);
  properties.onChange(checked ? [...remaining, value] : remaining);
};
// Reuse the same header and modal boundary instead of opening a nested overlay.
watch([field, showProperties], () => {
  if (navigation)
    navigation.value =
      field.value || showProperties.value
        ? { title: field.value?.label ?? props.properties?.label ?? "", back }
        : undefined;
});
onBeforeUnmount(() => {
  if (navigation) navigation.value = undefined;
});
</script>

<template>
  <div
    v-if="field || showProperties"
    class="yayaw-card-settings"
    :data-view-settings-screen="screen"
  >
    <RadioGroupRoot
      v-if="field"
      :model-value="field.value"
      :aria-label="field.label"
      class="yayaw-settings-choices"
      @update:model-value="choose"
    >
      <label
        v-for="option in field.options"
        :key="option.value"
        class="yayaw-settings-choice"
      >
        <RadioGroupItem :value="option.value" :disabled="option.disabled" class="yayaw-settings-radio"
          ><RadioGroupIndicator class="yayaw-settings-radio-indicator"
        /></RadioGroupItem>
        <span>{{ option.label }}</span>
      </label>
    </RadioGroupRoot>
    <fieldset v-else-if="properties" class="yayaw-settings-choices">
      <legend class="yayaw-sr-only">{{ properties.label }}</legend>
      <label
        v-for="option in properties.options"
        :key="option.value"
        class="yayaw-settings-choice"
      >
        <TableCheckbox
          :model-value="properties.value.includes(option.value)"
          :label="option.label"
          @update:model-value="toggle(option.value, $event)"
        /><span>{{ option.label }}</span>
      </label>
      <label class="yayaw-settings-choice yayaw-settings-labels">
        <TableCheckbox
          :model-value="properties.showLabels"
          :label="properties.showLabelsLabel"
          @update:model-value="properties.onShowLabelsChange"
        /><span>{{ properties.showLabelsLabel }}</span>
      </label>
    </fieldset>
  </div>
  <div v-else class="yayaw-card-settings" data-view-settings>
    <slot name="intro" />
    <template v-for="item in fields" :key="item.id">
      <h3 v-if="item.heading" class="yayaw-setting-heading" data-setting-heading>{{ item.heading }}</h3>
      <div :class="{ 'yayaw-setting-inline': item.inline }" :data-setting-field="item.id">
      <div v-if="context.toolbarCompact.value" class="yayaw-control-field">
        <label :for="`${id}-${item.id}`">{{ item.label }}</label>
        <button
          :id="`${id}-${item.id}`"
          :aria-label="item.label"
          type="button"
          class="yayaw-select-trigger"
          :disabled="item.disabled"
          @click="open(item.id)"
        >
          <span>{{
            item.options.find((option) => option.value === item.value)?.label ??
            item.label
          }}</span
          ><ChevronDown :size="16" aria-hidden="true" />
        </button>
      </div>
      <TableSelect
        v-else
        :model-value="item.value"
        :label="item.label"
        :options="item.options"
        :disabled="item.disabled"
        @update:model-value="item.onChange"
      />
      </div>
      <slot :name="`after-${item.id}`" />
    </template>
    <button
      v-if="properties"
      :id="`${id}-properties`"
      :aria-label="properties.label"
      type="button"
      class="yayaw-button yayaw-button-outline yayaw-settings-properties"
      @click="open('properties')"
    >
      <SlidersHorizontal :size="16" aria-hidden="true" /><span>{{
        properties.label
      }}</span
      ><ChevronRight :size="16" aria-hidden="true" />
    </button>
    <slot />
  </div>
</template>

// src/components/ui/yayaw-table/components/toolbar/view-settings-panel.tsx
"use client";

import { ChevronDown, ChevronRight, SlidersHorizontal } from "lucide-react";
import {
  type ReactNode,
  useCallback,
  useId,
  useLayoutEffect,
  useRef,
  useState,
} from "react";
import { useStackMenu } from "@/components/ui/custom/stack-menu";
import { Button } from "@/src/components/ui/button";
import { Checkbox } from "@/src/components/ui/checkbox";
import { RadioGroup, RadioGroupItem } from "@/src/components/ui/radio-group";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/src/components/ui/select";
import { useIsMobile } from "../../hooks/use-mobile";

export interface ViewSettingField {
  id: string;
  label: string;
  value: string;
  /** Disabled choices stay listed; their label says why. */
  options: { value: string; label: string; disabled?: boolean }[];
  onChange: (value: string) => void;
  /** Section title shown above the field. */
  heading?: string;
  /** Label and control on one row (column mappings). */
  inline?: boolean;
  /** Content right after the field, such as a hint or an input. */
  after?: ReactNode;
  /** Shown but not changeable. */
  disabled?: boolean;
}
export interface ViewSettingProperties {
  label: string;
  options: { value: string; label: string }[];
  value: string[];
  onChange: (value: string[]) => void;
  showLabels: boolean;
  showLabelsLabel: string;
  onShowLabelsChange: (value: boolean) => void;
}

/** One setting: a select, or on touch layouts a button that opens its choices. */
function SettingFieldRow({
  controlId,
  field,
  mobile,
  onOpen,
}: {
  controlId: string;
  field: ViewSettingField;
  mobile: boolean;
  onOpen: (button: HTMLButtonElement) => void;
}) {
  const control = mobile ? (
    <Button
      aria-label={field.label}
      className="w-full min-w-0 justify-between font-normal"
      disabled={field.disabled}
      id={controlId}
      onClick={(event) => onOpen(event.currentTarget)}
      variant="outline"
    >
      <span className="truncate">
        {field.options.find((option) => option.value === field.value)?.label ??
          field.label}
      </span>
      <ChevronDown aria-hidden="true" className="size-4" />
    </Button>
  ) : (
    <Select
      disabled={field.disabled}
      items={field.options}
      onValueChange={(value) => {
        if (value !== null) {
          field.onChange(value);
        }
      }}
      value={field.value}
    >
      <SelectTrigger
        aria-label={field.label}
        className="w-full min-w-0 font-normal"
        id={controlId}
      >
        <SelectValue />
      </SelectTrigger>
      <SelectContent align="start" alignItemWithTrigger={false}>
        {field.options.map((option) => (
          <SelectItem
            disabled={option.disabled}
            key={option.value}
            value={option.value}
          >
            {option.label}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
  return (
    <>
      {field.heading ? (
        <h3 className="mt-1 font-medium text-sm" data-setting-heading>
          {field.heading}
        </h3>
      ) : null}
      <div
        className={
          field.inline
            ? "grid min-w-0 grid-cols-[minmax(0,2fr)_minmax(0,3fr)] items-center gap-2"
            : "grid min-w-0 gap-1.5"
        }
        data-setting-field={field.id}
      >
        <label
          className={
            field.inline
              ? "truncate text-sm"
              : "text-muted-foreground text-sm"
          }
          htmlFor={controlId}
        >
          {field.label}
        </label>
        {control}
      </div>
      {field.after}
    </>
  );
}

/** Mobile choices stay inside the owning drawer, with one scroll region and focus boundary. */
export function ViewSettingsPanel({
  fields,
  properties,
  children,
  intro,
}: {
  children?: ReactNode;
  fields: ViewSettingField[];
  /** Content before the fields, hidden while a choice list is open. */
  intro?: ReactNode;
  properties?: ViewSettingProperties;
}) {
  const isMobile = useIsMobile();
  const { compact, setChildView } = useStackMenu();
  const mobile = isMobile || compact;
  const id = useId();
  const [screen, setScreen] = useState<string>();
  const trigger = useRef<HTMLButtonElement | null>(null);
  const activeField = fields.find((field) => field.id === screen);
  const showProperties = screen === "properties" && properties;
  const goBack = useCallback(() => {
    setScreen(undefined);
    // Wait for the settings form to remount before restoring the originating control.
    requestAnimationFrame(() =>
      document.getElementById(trigger.current?.id ?? "")?.focus()
    );
  }, []);
  const screenTitle =
    activeField?.label ?? (showProperties ? properties.label : undefined);
  useLayoutEffect(() => {
    setChildView(
      screenTitle ? { title: screenTitle, back: goBack } : undefined
    );
    return () => setChildView(undefined);
  }, [screenTitle, goBack, setChildView]);
  if (activeField || showProperties) {
    return (
      <div className="grid min-w-0 gap-3" data-view-settings-screen={screen}>
        {activeField ? (
          <RadioGroup
            aria-label={activeField.label}
            className="gap-1"
            value={activeField.value}
            onValueChange={(value) => {
              activeField.onChange(String(value));
              goBack();
            }}
          >
            {activeField.options.map((option) => (
              <label
                htmlFor={`${id}-choice-${option.value}`}
                className="flex min-h-11 min-w-0 cursor-pointer items-center gap-3 rounded-md px-2 text-sm hover:bg-accent"
                key={option.value}
              >
                <RadioGroupItem
                  id={`${id}-choice-${option.value}`}
                  aria-label={option.label}
                  className="min-h-0! min-w-0!"
                  disabled={option.disabled}
                  value={option.value}
                />
                <span className="min-w-0 break-words">{option.label}</span>
              </label>
            ))}
          </RadioGroup>
        ) : null}
        {showProperties ? (
          <fieldset className="grid min-w-0 gap-1">
            <legend className="sr-only">{properties.label}</legend>
            {properties.options.map((option) => (
              <div
                className="flex min-h-9 min-w-0 cursor-pointer items-center gap-3 rounded-md px-2 text-sm hover:bg-accent max-md:min-h-11"
                key={option.value}
              >
                <Checkbox
                  aria-label={option.label}
                  id={`${id}-property-${option.value}`}
                  className="min-h-0! min-w-0!"
                  checked={properties.value.includes(option.value)}
                  onCheckedChange={(checked) =>
                    properties.onChange(
                      checked
                        ? [
                            ...properties.value.filter(
                              (value) => value !== option.value
                            ),
                            option.value,
                          ]
                        : properties.value.filter(
                            (value) => value !== option.value
                          )
                    )
                  }
                />
                <label
                  className="min-w-0 flex-1 cursor-pointer break-words py-2"
                  htmlFor={`${id}-property-${option.value}`}
                >
                  {option.label}
                </label>
              </div>
            ))}
            <div className="mt-2 flex min-h-11 cursor-pointer items-center gap-3 border-t px-2 pt-2 text-sm">
              <Checkbox
                aria-label={properties.showLabelsLabel}
                id={`${id}-labels`}
                className="min-h-0! min-w-0!"
                checked={properties.showLabels}
                onCheckedChange={properties.onShowLabelsChange}
              />
              <label
                className="flex-1 cursor-pointer py-2"
                htmlFor={`${id}-labels`}
              >
                {properties.showLabelsLabel}
              </label>
            </div>
          </fieldset>
        ) : null}
      </div>
    );
  }
  return (
    <div className="grid min-w-0 gap-3" data-view-settings>
      {intro}
      {fields.map((field) => (
        <SettingFieldRow
          controlId={`${id}-${field.id}`}
          field={field}
          key={field.id}
          mobile={mobile}
          onOpen={(button) => {
            trigger.current = button;
            setScreen(field.id);
          }}
        />
      ))}
      {properties ? (
        <Button
          aria-label={properties.label}
          className="w-full justify-start gap-2 font-normal"
          id={`${id}-properties`}
          variant="outline"
          onClick={(event) => {
            trigger.current = event.currentTarget;
            setScreen("properties");
          }}
        >
          <SlidersHorizontal aria-hidden="true" className="size-4" />
          <span className="min-w-0 flex-1 truncate text-left">
            {properties.label}
          </span>
          <ChevronRight aria-hidden="true" className="size-4" />
        </Button>
      ) : null}
      {children}
    </div>
  );
}
